force-app/main/default/objects/COGS_Set__c/COGS_Set__c.object-meta.xml
<CustomObject>
    <description>This object is a link between a product and COGS values.
Each Set has a quarter object connected that defines the validity period.
Next to that the COGS scenario is linked which was used to create the single values.</description>
    <label>COGS Set</label>
    <nameField>
        <label>COGS Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>COGS Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COGS_Set__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to product</description>
    <inlineHelpText>Linked Product</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>COGS Sets</relationshipLabel>
    <relationshipName>COGS_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Calculate_CogsBudget__c.field-meta.xml
<CustomField>
    <fullName>Calculate_CogsBudget__c</fullName>
    <formula>Update_Contribution__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculate COGS Budget</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Contribution__c.field-meta.xml
<CustomField>
    <fullName>Contribution__c</fullName>
    <description>The COGS (below) are now updated with Workflow:
( Product__r.COGS_1__c + 
CASE (text( Use_Restriction__c ),
&quot;2G M2M&quot;, Product__r.IPR_USD_M2M__c + Product__r.IPR_Pct_M2M__c,
&quot;3G M2M&quot;, Product__r.IPR_USD_M2M__c + Product__r.IPR_Pct_M2M__c,
&quot;4G M2M&quot;, Product__r.IPR_USD_M2M__c + Product__r.IPR_Pct_M2M__c,
...))</description>
    <formula>Contribution_Unweighted__c * Status_Factor__c * Opportunity__r.Probability</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>(Revenue Unweighted - Annual_Quantity__c * COGS__c) * Opportunity Probability
NOTE: 0 if Status is Alternative Product, Lost, Not Applicable</inlineHelpText>
    <label>Contribution</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Next_Year_COGS_Budget__c.field-meta.xml
<CustomField>
    <fullName>Next_Year_COGS_Budget__c</fullName>
    <description>Next Year budget calculated using Trigger . It populates value either from Product COGS1,2,3,4 or from Next year COGS SET Value from Product&apos;s &quot;Predicted COGS Info&quot; field.
Format will be - Q1:Q2:Q3:Q4</description>
    <label>Next Year COGS Budget</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <formula>text(Product__r.Product_Center__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Opp Products</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>case(text( Status__c ),
&quot;Won&quot;, 1,
&quot;Evaluation&quot;, 0.5,
&quot;Not applicable&quot;, 0,
0
) * Contribution__c</description>
    <formula>case(text( Status__c ),
&quot;Won&quot;, 1,
&quot;Evaluation&quot;, 0.5,
&quot;Not applicable&quot;, 0,
0
) * Revenue_With_Status_Factor__c / 10000</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ranking</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Reason_Same_As_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Reason_Same_As_Opportunity__c</fullName>
    <description>Added for Apex Class used to add lost Opp Products in Opportunity (SOQL query doesn&apos;t allow field-to-field comparison).</description>
    <formula>IF(TEXT(Loss_Reason__c)=TEXT(Opportunity__r.Reason__c), true, false)</formula>
    <label>Reason Same As Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>When multiple products are in evaluation, set the most probable one as “Evaluation”, all others as “Alternative product”. These will not count as revenue or contribution.</description>
    <inlineHelpText>When multiple products are in evaluation, set the most probable one as “Evaluation”, all others as “Alternative product”. These will not count as revenue or contribution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alternative Product</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
                <default>true</default>
                <label>Evaluation</label>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_1__c.field-meta.xml
<CustomField>
    <fullName>Product_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (1st in the related list).</inlineHelpText>
    <label>Product 1</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 1)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_2__c.field-meta.xml
<CustomField>
    <fullName>Product_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (2nd in the related list).</inlineHelpText>
    <label>Product 2</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 2)</relationshipLabel>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_3__c.field-meta.xml
<CustomField>
    <fullName>Product_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (3rd in the related list).</inlineHelpText>
    <label>Product 3</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 3)</relationshipLabel>
    <relationshipName>Opportunities5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_4__c.field-meta.xml
<CustomField>
    <fullName>Product_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (4th in the related list).</inlineHelpText>
    <label>Product 4</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 4)</relationshipLabel>
    <relationshipName>Opportunities6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_5__c.field-meta.xml
<CustomField>
    <fullName>Product_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (5th in the related list).</inlineHelpText>
    <label>Product 5</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 5)</relationshipLabel>
    <relationshipName>Opportunities7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Referred_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quotation referring to specific opportunity</description>
    <label>Referred Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>List of Quotations</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Services_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Services_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Services Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Tashang</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/oppProductTriggerHelper.cls
public with sharing class oppProductTriggerHelper {
    
    /**
* @description: get 5 products by Ranking and Last Modified date.
**/
    public static List<Opportunity> updateProductRankings(Map<Id, Opp_Product__c> oppProducts){
        
        List<Id> oppIds = new List<Id>();
        List<Opportunity> opps = new List<Opportunity>();
        Boolean isServiceProduct = FALSE;
        if (oppProducts == null) return null;
        
        // Get list of opportunitie ids.
        for (Opp_Product__c oppProduct : oppProducts.values()){
            oppIds.add(oppProduct.Opportunity__c);
        }
        if(oppIds.size() > 0){  opps = [SELECT Id, Product_1__c, Product_2__c, 
                                        Product_3__c, Product_4__c, Product_5__c,
                                        Services_Opportunity__c,Product_1__r.Product_Center__c,
                                        Product_2__r.Product_Center__c,Product_3__r.Product_Center__c
                                        FROM Opportunity  WHERE Id IN:oppIds];
                              
        }
        
        if (opps.size()==0) return null;
        
        
        // Get list of Opp Products for each opportunity - ranked.
        // 2015.09.09 khir: List only Opp Products in certain Status
        // 2016.01.20 khir: Lost Opp Product added only if Reason is the same as the Opportunity.
        List<Opp_Product__c> allOppProducts = [SELECT Id, 
                                                    Name, 
                                                    Ranking__c, 
                                                    Contribution__c, 
                                                    Product__c,
                                               		Product__r.product_center__c,
                                                    Opportunity__c, 
                                                    Opportunity__r.Name, 
                                                    LastModifiedDate, 
                                                    Product__r.Name, 
                                                    Status__c
                                               FROM Opp_Product__c 
                                               WHERE Opportunity__c IN :opps 
                                                    AND (Status__c IN ('Evaluation', 'Won') 
                                                    OR (Status__c = 'Lost' AND Reason_Same_As_Opportunity__c = true 
                                                    AND Opportunity__r.StageName='1 Lost' )
                                                    )                                                   
                                               ORDER BY Opportunity__c, Ranking__c DESC, LastModifiedDate DESC];
        
        List<Opportunity> OppToUpdate = new List <Opportunity>{}; // List of product which have changed
            // Loop through opportunity - get related products which should be ordered correctly.
            for (Opportunity opp : opps){
                Integer i=0;
                Boolean change =  false;  // remember if any change has happened.
                for (Opp_Product__c oppProduct : allOppProducts){
                    if (opp.Id == oppProduct.Opportunity__c){
                        // Only assign the Product_*__c if there is an actual change
                        // below three lines for Service Opportunity
                        if(oppProduct.Product__r.product_Center__c != 'Services' && !isServiceProduct){
                            isServiceProduct = TRUE;
                            opp.Services_Opportunity__c = FALSE;
                        }
                        if (i==0 && opp.Product_1__c != oppProduct.Product__c) {opp.Product_1__c = oppProduct.Product__c; change = true;}
                        if (i==1 && opp.Product_2__c != oppProduct.Product__c) {opp.Product_2__c = oppProduct.Product__c; change = true;}
                        if (i==2 && opp.Product_3__c != oppProduct.Product__c) {opp.Product_3__c = oppProduct.Product__c; change = true;}
                        if (i==3 && opp.Product_4__c != oppProduct.Product__c) {opp.Product_4__c = oppProduct.Product__c; change = true;}
                        if (i==4 && opp.Product_5__c != oppProduct.Product__c) {opp.Product_5__c = oppProduct.Product__c; change = true;}
                        i++;
                    } // if
                } // for
                for (Integer j = i; j < 5; j++) {
                    // Set the remainding Products to null if they are not null already
                    if (j==0 && opp.Product_1__c != null) {opp.Product_1__c = null; change = true;}
                    if (j==1 && opp.Product_2__c != null) {opp.Product_2__c = null; change = true;}
                    if (j==2 && opp.Product_3__c != null) {opp.Product_3__c = null; change = true;}
                    if (j==3 && opp.Product_4__c != null) {opp.Product_4__c = null; change = true;}
                    if (j==4 && opp.Product_5__c != null) {opp.Product_5__c = null; change = true;}
                } // for
                if(opp.Product_1__c == NULL && opp.Product_2__c == NULL && opp.Product_3__c == NULL){
                    opp.Services_Opportunity__c=false;
                }
                if (change) {
                    OppToUpdate.add(opp);
                } // if
            } // for
        return OppToUpdate; 
    }   
    
    /**To bind the Standard product value with Custom Product lookup**/
	
    // Commenting out this(updateProduct) method. It is for the removal of custom Product obj. By ufar, 12-6-22.
	/*    
    
    public static list<Opp_Product__c> updateProduct(Map<Id,Opp_Product__c> oppProducts){
        
        List<Opp_Product__c> oppProdList = new List<Opp_Product__c>();
        oppProdList = [select Id,Product__c,Products__c,Calculate_CogsBudget__c,Next_Year_COGS_Budget__c from Opp_Product__c where ID IN: oppProducts.keyset()];
        //List<Opp_Product__c> oppProdList1 = new List<Opp_Product__c>();
        Map<Id,Opp_Product__c> oppProdMap1 = new Map<Id,Opp_Product__c>();
        Map<Id,Id> standardProdId = new Map<Id,Id>();  
        List<Product__c> customProdList = new List<Product__c>();
        
        for(Opp_Product__c oppProd : oppProdList) {
            
            if(oppProd.Product__c != null) { 
                standardProdId.put(oppProd.Id,oppProd.Product__c);
            }
        }
        customProdList = [select Id,Name,Referred_Product__c from Product__c where Referred_Product__c IN: standardProdId.values()];
        for(Opp_Product__c oppProd : oppProdList){
            for(Product__c prod : customProdList){
                if(oppProd.Product__c == prod.Referred_Product__c){
                    oppProd.Products__c = prod.id;
                    //oppProdList1.add(oppProd);
                    oppProdMap1.put(oppProd.id,oppProd);
                }
            }
        }
        
        oppProdMap1 = updateBudgetCOGSVal(oppProducts,oppProdList,oppProdMap1,standardProdId);        
        return oppProdMap1.values();
    }
	*/

    public static boolean isFirstTime = true;
    
    public static Map<Id,Opp_Product__c> updateBudgetCOGSVal(Map<Id,Opp_Product__c> oppProducts,
        List<Opp_Product__c> oppProdList,Map<Id,Opp_Product__c> oppProdMap1,Map<Id,Id> standardProdId)
    {
        Map<Id,Id> prodCOGSSetMap = new Map<Id,Id>();
        
        Map<Id,Product2> stdProdMap = new Map<Id,Product2>([select Id,Name,Next_Year_COGS_Value__c,Valid_COGS_Info__c from Product2 where Id IN: standardProdId.values()]);
        
        for(Product2 prod : stdProdMap.values()){
            prodCOGSSetMap.put(prod.id,prod.Valid_COGS_Info__c);
        }
        List<COGS_Set_Value__c> cogsSetValList = [select Id,Name,COGS_Set__c,Value__c,Next_Year_Quarter__c from COGS_Set_Value__c where COGS_Set__c IN: prodCOGSSetMap.values() AND Next_Year_Quarter__c IN ('1','2','3','4')];
        Map<Id,Map<String,COGS_Set_Value__c>> COGSSetAndValueMap = new Map<Id,Map<String,COGS_Set_Value__c>>();
        for(COGS_Set_Value__c cogsValSet : cogsSetValList)
        {
            if(!COGSSetAndValueMap.containsKey(cogsValSet.COGS_Set__c)) {
                COGSSetAndValueMap.put(cogsValSet.COGS_Set__c,new Map<String,COGS_Set_Value__c>());
            }   
            COGSSetAndValueMap.get(cogsValSet.COGS_Set__c).put(cogsValSet.Next_Year_Quarter__c,cogsValSet);
        }
        Boolean considerCogs = false;
        Process_Settings__c pSetting = Process_Settings__c.getInstance();
        if(pSetting.Consider_Cogs_In_Next_Year_Budget__c == true)
        {
            considerCogs = pSetting.Consider_Cogs_In_Next_Year_Budget__c;
        }
        for(Opp_Product__c oppProd : oppProdList){
            if(oppProd.Calculate_CogsBudget__c == TRUE){
                Opp_Product__c tempOppProd = oppProdMap1.containsKey(oppProd.id)?oppProdMap1.get(oppProd.id):oppProd;
                
                string cogsSetId = prodCOGSSetMap.get(oppProd.Product__c);
                
                if(considerCogs && cogsSetId!=null && COGSSetAndValueMap.containsKey(cogsSetId))
                    tempOppProd.Next_Year_COGS_Budget__c = generateCOGSStringFromMap(COGSSetAndValueMap.get(cogsSetId));
                
                else{
                    List<String> cogsValList = splitNextValCOGSString(stdProdMap.get(oppProd.Product__c).Next_Year_COGS_Value__c,':');
                    String cogsValString =generateCOGSStringFromList(cogsValList);
                    tempOppProd.Next_Year_COGS_Budget__c = cogsValString; 
                }
				oppProdMap1.put(tempOppProd.id,tempOppProd);
            }            
        }
        return oppProdMap1;      
    }
    
    private static List<String> splitNextValCOGSString(String fText,String delimeter)
    {
        List<String> res = new List<String>();
        
        if(!String.isEmpty(fText)){ res = fText.split(delimeter);
            for(integer i=res.size();i<4;i++)  {
                res.add('');
            }
        }
        return res;
    }
    
    private static String generateCOGSStringFromList(List<String> cogsValList){
        String cogsValString ='';
        if(cogsValList.size() == 4) {
            cogsValString = generateCOGSString(cogsValList[0],cogsValList[1],cogsValList[2],cogsValList[3]);
        }
        return cogsValString;
    }
    
    private static String generateCOGSStringFromMap(Map<String,COGS_Set_Value__c> COGSSetAndValueMap){
        String cogsValString ='';
        if(COGSSetAndValueMap.size()>0) { 
            
            String q1Str = COGSSetAndValueMap.containsKey('1')?String.valueOf(COGSSetAndValueMap.get('1').Value__c):'';
            String q2Str= COGSSetAndValueMap.containsKey('2')?String.valueOf(COGSSetAndValueMap.get('2').Value__c):'';
            String q3Str= COGSSetAndValueMap.containsKey('3')?String.valueOf(COGSSetAndValueMap.get('3').Value__c):'';
            String q4Str= COGSSetAndValueMap.containsKey('4')?String.valueOf(COGSSetAndValueMap.get('4').Value__c):'';
            cogsValString = generateCOGSString(q1Str,q2Str,q3Str,q4Str);
        }
        return cogsValString;
    }
    
    private static string generateCOGSString(String q1,String q2,String q3,String q4)
    {
        String cogsQString ='1#'+q1+':2#'+q2+':3#'+q3+':4#'+q4;
        return cogsQString;
    }
}