force-app/main/default/objects/Campaign/fields/Email_Type__c.field-meta.xml
<CustomField>
    <fullName>Email_Type__c</fullName>
    <description>Required when Type=Email</description>
    <inlineHelpText>Required when Type=Email</inlineHelpText>
    <label>Email Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer email</fullName>
            </value>
            <value>
                <fullName>Event email</fullName>
            </value>
            <value>
                <fullName>Investor relation email</fullName>
            </value>
            <value>
                <fullName>Product notification</fullName>
            </value>
            <value>
                <fullName>Webinar email</fullName>
            </value>
            <value>
                <fullName>Marketing Communication</fullName>
            </value>
            <value>
                <fullName>Press release email</fullName>
                <isActive>false</isActive>
                <label>Press release email</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hard_Code_Ids__c/Hard_Code_Ids__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store recordIds used in Flows, validations rules and formulas.</description>
    <label>Hard Code Ids</label>
</CustomObject>

force-app/main/default/objects/Hard_Code_Ids__c/fields/Add_ae_cel__c.field-meta.xml
<CustomField>
    <fullName>Add_ae_cel__c</fullName>
    <description>Field is used in Flow { Campaign: After Create }</description>
    <label>Add ae-cel</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hard_Code_Ids__c/fields/Add_ae_pos__c.field-meta.xml
<CustomField>
    <fullName>Add_ae_pos__c</fullName>
    <description>Field is used in Flow { Campaign: After Create }</description>
    <label>Add ae-pos</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hard_Code_Ids__c/fields/Add_ae_sho__c.field-meta.xml
<CustomField>
    <fullName>Add_ae_sho__c</fullName>
    <description>Field is used in Flow { Campaign: After Create }</description>
    <label>Add ae-sho</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hard_Code_Ids__c/fields/Add_all_global__c.field-meta.xml
<CustomField>
    <fullName>Add_all_global__c</fullName>
    <description>Field is used in Flow { Campaign: After Create }</description>
    <label>Add_all_global</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hard_Code_Ids__c/fields/Add_ladm_team_americas__c.field-meta.xml
<CustomField>
    <fullName>Add_ladm_team_americas__c</fullName>
    <description>Field is used in Flow { Campaign: After Create }</description>
    <label>Add ladm-team-americas</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hard_Code_Ids__c/fields/Add_ms_team_global__c.field-meta.xml
<CustomField>
    <fullName>Add_ms_team_global__c</fullName>
    <description>Field is used in Flow { Campaign: After Create }</description>
    <label>Add ms-team-global</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hard_Code_Ids__c/fields/Add_ps_cel__c.field-meta.xml
<CustomField>
    <fullName>Add_ps_cel__c</fullName>
    <description>Field is used in Flow { Campaign: After Create }</description>
    <label>Add ps cel</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hard_Code_Ids__c/fields/Add_ps_pos__c.field-meta.xml
<CustomField>
    <fullName>Add_ps_pos__c</fullName>
    <description>Field is used in Flow { Campaign: After Create }</description>
    <label>Add ps pos</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hard_Code_Ids__c/fields/Add_ps_sho__c.field-meta.xml
<CustomField>
    <fullName>Add_ps_sho__c</fullName>
    <description>Field is used in Flow { Campaign: After Create }</description>
    <label>Add ps sho</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hard_Code_Ids__c/fields/Add_q_team_global__c.field-meta.xml
<CustomField>
    <fullName>Add_q_team_global__c</fullName>
    <description>Field is used in Flow { Campaign: After Create }</description>
    <label>Add q-team-global</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hard_Code_Ids__c/fields/Add_src_team_global__c.field-meta.xml
<CustomField>
    <fullName>Add_src_team_global__c</fullName>
    <description>Field is used in Flow { Campaign: After Create }</description>
    <label>Add src team global</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CampaignAfterFlowTest.cls
@isTest
public class CampaignAfterFlowTest {
    @isTest static void CustomerEmailTest() {

        CampaignTestDataFactory campaignFactory = new CampaignTestDataFactory();
        ContactTestDataFactory contactFactory = new ContactTestDataFactory();
        
        String campaignJSON = '[{"name": "Test Campaign1", "Email_Type__c": "Customer email", "Type": "Email"},{"name": "Test Campaign2", "Email_Type__c": "Marketing Communication", "Type": "Email"}]';
        
        Test.startTest();

        Contact cont = (Contact)contactFactory.createRecord();

        Hard_Code_Ids__c settings = Hard_Code_Ids__c.getOrgDefaults();
        settings.Add_all_global__c = cont.Id;
        upsert settings;
        
        Database.SaveResult[] campaignResultList = campaignFactory.createBulkRecordsfromJson(campaignJSON);
        
        List<Id> campIdsList = campaignFactory.getBulkRecordIds();
        
        List<CampaignMember> campMembList = new List<CampaignMember>([select id, CampaignId, ContactId, Status from CampaignMember where CampaignId IN :campIdsList]);

        System.assertEquals(campMembList.size(), campIdsList.size());
        
        // Customer email? created records
        for (campaign camp : (List<campaign>)campaignFactory.getRecordsList()) {
            for (CampaignMember member : campMembList) {
                if (member.campaignId == camp.id) {                    
                    System.assertEquals(member.status, 'Pending');
                }
            }
        }
        Test.stopTest();
    }

    @isTest static void ProductNotificationTest() {

        CampaignTestDataFactory campaignFactory = new CampaignTestDataFactory();
        ContactTestDataFactory contactFactory = new ContactTestDataFactory();
        String campaignJSON = '[{"name": "Test Campaign1", "Email_Type__c": "Product notification", "Type": "Email"},{"name": "Test Campaign2", "Email_Type__c": "Product notification", "Type": "Email"}]';
        
        Test.startTest();

        List<Contact> contactList = contactFactory.createBulkRecords();
        List<Id> contactIdsList = contactFactory.getBulkRecordIds();
        

        Hard_Code_Ids__c settings = Hard_Code_Ids__c.getOrgDefaults();
        settings.Add_ae_cel__c = contactList[0].Id;
        settings.Add_ae_pos__c = contactList[1].Id;
        settings.Add_ae_sho__c = contactList[2].Id;
        settings.Add_ladm_team_americas__c = contactList[3].Id;
        settings.Add_ms_team_global__c = contactList[4].Id;
        settings.Add_ps_cel__c = contactList[5].Id;
        settings.Add_ps_pos__c = contactList[6].Id;
        settings.Add_ps_sho__c = contactList[7].Id;
        settings.Add_q_team_global__c = contactList[8].Id;
        settings.Add_src_team_global__c = contactList[9].Id;
        upsert settings;
        
        Database.SaveResult[] campaignResultList = campaignFactory.createBulkRecordsfromJson(campaignJSON);
        
        List<Campaign> campList = (List<Campaign>)campaignFactory.getRecordsList();
        List<Id> campIdsList = campaignFactory.getBulkRecordIds();
        
        List<CampaignMember> campMembList = new List<CampaignMember>([select id, CampaignId, ContactId, Status from CampaignMember where CampaignId IN :campIdsList]);

        //every campaign creates 9 members
        System.assertEquals(9, campMembList.size()/campList.size());
        // Product notification created records
        for (campaign camp : campList) {
            for (CampaignMember member : campMembList) {
                if (member.campaignId == camp.id) {                    
                    System.assertEquals(member.status, 'Pending');

                }
            }
        }
        Test.stopTest();
    }

}