force-app/main/default/objects/Competitor_Product_Price__c/Competitor_Product_Price__c.object-meta.xml
<CustomObject>
    <label>Competitor Product Price</label>
    <nameField>
        <displayFormat>CPP-{000000}</displayFormat>
        <label>Competitor Product Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Product Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Product_Price__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Filled with Opportunity Account if the Competitor Product Price has been created from the Opp Product.</description>
    <inlineHelpText>Filled with Opportunity Account if the Competitor Product Price has been created from the Opp Product.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor Product Prices</relationshipLabel>
    <relationshipName>Competitor_Product_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Product_Price__c/fields/Opp_Product__c.field-meta.xml
<CustomField>
    <fullName>Opp_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Filled automatically when created from Opp Product</description>
    <inlineHelpText>Filled automatically when created from Opp Product</inlineHelpText>
    <label>Opp Product</label>
    <referenceTo>Opp_Product__c</referenceTo>
    <relationshipLabel>Competitor Product Prices</relationshipLabel>
    <relationshipName>Competitor_Product_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Product_Price__c/fields/Price_Information_Date__c.field-meta.xml
<CustomField>
    <fullName>Price_Information_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Populated automatically with modified date if left empty when Save.</description>
    <inlineHelpText>Populated automatically with modified date if left empty when Save.</inlineHelpText>
    <label>Price Information Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CompetitorProductPriceFlowTest.cls
/*
Test class for flow.
Obj: "Competitor_Product_Price__c"
Flow: "Competitor Product Price: After Create / Update"
*/

@isTest
public class CompetitorProductPriceFlowTest {

	@isTest
    static void TestHasOpportunity(){
        
        CompetitorProductPriceTestDataFactory cppTDF = new CompetitorProductPriceTestDataFactory();
        Competitor_Product_Price__c cpp = (Competitor_Product_Price__c)cppTDF.createRecord();

        AccountTestDataFactory accCpp = new AccountTestDataFactory();
        Account acc = (Account)accCpp.createRecord();
        
        test.startTest();
        if(cpp.Opp_Product__c != null){
            system.assertEquals(cpp.Account__c, acc.id);
        }
        test.stopTest();
        
    }
    
    @isTest
    static void TestPriceInfoDateTODAY(){
   		CompetitorProductPriceTestDataFactory cppTDF = new CompetitorProductPriceTestDataFactory();
        Competitor_Product_Price__c cpp = (Competitor_Product_Price__c)cppTDF.createRecord();
		        
		test.startTest();
        if(cpp.Price_Information_Date__c == null){
            System.assertEquals(Date.today(), cpp.Price_Information_Date__c);
        }
        test.stopTest();
        
    }



}