force-app/main/default/objects/Case/fields/Case_Initiator_Source__c.field-meta.xml
<CustomField>
    <fullName>Case_Initiator_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field if the case is opened for someone else (Case Initiator &lt;&gt; Created by)</inlineHelpText>
    <label>Case Initiator Source</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases_initiated</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>The technology of the product.</description>
    <label>Technology</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GNSS</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTestDataFactory.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@IsTest
public class CaseTestDataFactory extends TestDataFactory{
    public CaseTestDataFactory() {
        super('Case');
    }
    public override sObject initializeRecord(){ 
        Account caseAccount = (Account)new AccountTestDataFactory().createRecord();
        Id caseInitior = createUserWithProfile('Dirk Martin','Dirk.Martin@u-blox.com.invalid','EMEA','Service FAE').Id;       
        Case portalCase = new Case(
            Accountid = caseAccount.Id,
            OwnerId = caseInitior,
            Type = 'Technical Question',
            Origin = 'u-blox Portal',
            Status = 'New',
            Technology__c = 'Cellular',
            Case_Initiator_Source__c = caseInitior,
            RecordTypeId = Schema.sObjectType.Case.getRecordTypeInfosByName().get('Support Case').getRecordTypeId()
        );
        return portalCase;
    }

    public override sObject createRecord() {
        Case caseRec = (Case)initializeRecord();
        insert caseRec;
        return caseRec;
    }

    public override List<sObject> createBulkRecords() {
        for (Integer i = 0; i < numberOfRecords; i++) {
            recordsList.add((Case)initializeRecord());
        }
        Insert recordsList;
        return recordsList;
    }
}