force-app/main/default/objects/Case/fields/From_Address__c.field-meta.xml
<CustomField>
    <fullName>From_Address__c</fullName>
    <formula>IF(Account_uB_Office__c = &apos;EMEA&apos;, &apos;support@u-blox.com&apos;,
IF(Account_uB_Office__c = &apos;Americas&apos;,&apos;support_us@u-blox.com&apos;,
IF(Account_uB_Office__c = &apos;Australia&apos;,&apos;support_anz@u-blox.com&apos;,
IF(Account_uB_Office__c = &apos;Rest of APAC&apos;,&apos;support_ap@u-blox.com&apos;,
IF(Account_uB_Office__c = &apos;China&apos;,&apos;support_cn@u-blox.com&apos;,
IF(Account_uB_Office__c = &apos;India&apos;,&apos;support_in@u-blox.com&apos;,
IF(Account_uB_Office__c = &apos;Japan&apos;,&apos;support_jp@u-blox.com&apos;,
IF(Account_uB_Office__c = &apos;Korea&apos;,&apos;support_kr@u-blox.com&apos;,
IF(Account_uB_Office__c = &apos;Taiwan&apos;,&apos;support_tw@u-blox.com&apos;,&apos;support_eu@u-blox.com&apos;
)))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>From Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Macro_From_Address__mdt/Macro_From_Address__mdt.object-meta.xml
<CustomObject>
    <label>Macro From Address</label>
    <pluralLabel>Macro From Addresses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Spam_Email__mdt/Spam_Email__mdt.object-meta.xml
<CustomObject>
    <description>Spam Email Address</description>
    <label>Spam Email</label>
    <pluralLabel>Spam Emails</pluralLabel>
</CustomObject>

force-app/main/default/objects/Spam_Email__mdt/fields/Spam_Email__c.field-meta.xml
<CustomField>
    <fullName>Spam_Email__c</fullName>
    <label>Spam Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/SpamEmailCtrl.cls
global without sharing class SpamEmailCtrl {
    
    public List<String> toAddresses = new List<String>();
    
    public SpamEmailCtrl(ApexPages.StandardController controller) {
    }
    @RemoteAction
    global static Boolean spamCaseId(String CaseId){ 
        if(CaseId==null) return false;
        Case caseObj = [Select Id,Status, suppliedEmail from Case where Id=:CaseId];
      
        if(!String.isEmpty(caseObj.suppliedEmail) )
        sendEmail(caseObj.suppliedEmail);
        caseObj.Status = 'Closed';
        if(!Test.isRunningTest()){ 
            update caseObj;
        }
        return true;
    }
    public static void sendEmail(String suppliedEmail){
        
        Map<String, Macro_From_Address__mdt> mcs = Macro_From_Address__mdt.getAll();
        
        Map<String, Spam_Email__mdt> spamEmalToAddress = Spam_Email__mdt.getAll();
        if(spamEmalToAddress == NULL){
           return; 
        }
        String toAddress = spamEmalToAddress.get('Spam_Email_Address').Spam_Email__c;
        List<Messaging.SingleEmailMessage> messageList = new List<Messaging.SingleEmailMessage>();
        List<String> toAddresses = new List<String>();
        toAddresses.add(toAddress);
        
        for(Macro_From_Address__mdt FromAddressObj:  mcs.values()){
            Messaging.SingleEmailMessage messageObj = new Messaging.SingleEmailMessage();
            messageObj = SendEmail.setMessagingEmail(suppliedEmail,toAddresses, FromAddressObj.From_Address__c);

            messageList.add(messageObj);
        }
        Messaging.SendEmailResult[] r =Messaging.sendEmail(messageList);    
    }
}