force-app/main/default/objects/User_Group__c/User_Group__c.object-meta.xml
<CustomObject>
    <label>User Group</label>
    <nameField>
        <label>User Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Group_Item__c/User_Group_Item__c.object-meta.xml
<CustomObject>
    <label>User Group Item</label>
    <nameField>
        <displayFormat>UGI-{000000}</displayFormat>
        <label>User Group Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Group Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Group_Item__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e2p000001Prug</value>
        </filterItems>
        <infoMessage>Please select Community User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Group_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Group_Item__c/fields/User_Group__c.field-meta.xml
<CustomField>
    <fullName>User_Group__c</fullName>
    <label>User Group</label>
    <referenceTo>User_Group__c</referenceTo>
    <relationshipLabel>User Group Items</relationshipLabel>
    <relationshipName>User_Group_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UserGroupItemTriggerHandler.cls
public Class UserGroupItemTriggerHandler implements ITrigger
{
    
    // Process 1 Data : Associate UserFile with userGroupItem for selected user
    Map<String,User_Group_Item__c> userGroupItemMap = null;
    
    // Process 2 Data : share GroupItems file to specific with UserFile if inserted and also delete the link if Usergroup item is deleted
    Map<String,List<ID>> groupUserMap = null;
    Set<String> usersAdded = null;
                       
    
    // Prepare the data for catering to Before Trigger events
    public void prepareBefore(){
        //Process 1
        if(Trigger.isInsert)
        {
            userGroupItemMap = new Map<String,User_Group_Item__c>();
            for(User_Group_Item__c ugItem : (List<User_Group_Item__c>)Trigger.new)
            {
                userGroupItemMap.put(ugItem.User__c,ugItem);
            }
        }
        
        //Process 2
        if(Trigger.isDelete)
        {
            groupUserMap = new Map<String,List<ID>>();
            usersAdded = new Set<String>();
            for(User_Group_Item__c ugItem : (List<User_Group_Item__c>)Trigger.old)
            {
                if(!groupUserMap.containsKey(ugItem.User_Group__c))
                {
                    groupUserMap.put(ugItem.User_Group__c,new List<ID>());
                }
                groupUserMap.get(ugItem.User_Group__c).add(ugItem.User__c);
                usersAdded.add(ugItem.User__c);
            }  
            UserGroupItemObjectHelper.doUserGroupItemsChangeToUserFile(groupUserMap,usersAdded,Trigger.isInsert);        
            
        }
    }
    
    // Prepare the data for catering to After Trigger events 
    public void prepareAfter(){   
        //Process 2
        if(Trigger.isInsert)
        {
            groupUserMap = new Map<String,List<ID>>();
            usersAdded = new Set<String>();
            for(User_Group_Item__c ugItem : (List<User_Group_Item__c>)Trigger.new)
            {
                if(!groupUserMap.containsKey(ugItem.User_Group__c))
                {
                    groupUserMap.put(ugItem.User_Group__c,new List<ID>());
                }
                groupUserMap.get(ugItem.User_Group__c).add(ugItem.User__c);
                usersAdded.add(ugItem.User__c);
            }  
            UserGroupItemObjectHelper.doUserGroupItemsChangeToUserFile(groupUserMap,usersAdded,Trigger.isInsert);        
            
        }
             
    }
    
    // Process logic/functioanlities in other classes for before Insert event  
    public void beforeInsert(){
        //Process 1
        UserGroupItemObjectHelper.mapUserGroupItemToUserFile(userGroupItemMap);   
    }
    
    // Process logic/functioanlities in other classes for before Update  event
    public void beforeUpdate(){}
    
    // Process logic/functioanlities in other classes for before Delete event
    public void beforeDelete(){        
    }
    
    // Process logic/functioanlities in other classes for after Update  event
    public void afterInsert(){
    }
    
    // Process logic/functioanlities in other classes for after Update  event 
    public void afterUpdate(){        
    }
    
    // Process logic/functioanlities in other classes for after Delete  event
    public void afterDelete(){
    } 
    //Finally do operations to Commit 
    public void finish(){        
               
    }
    
    
}