force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <inlineHelpText>On creation, if empty copied from the master Opportunity after Save. Edit as needed.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <formula>text(Opportunity__r.New_Application_Type__c)</formula>
    <label>Application Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <description>Annual run rate of product. If</description>
    <inlineHelpText>Annual run rate. For single shot opportunities, use total quantity.
If Opportunity is converted from Lead, this is copied from Lead.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_design_house__c.field-meta.xml
<CustomField>
    <fullName>Area_design_house__c</fullName>
    <inlineHelpText>Area in which the design is made.</inlineHelpText>
    <label>uB Office Design House</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_Design_Win__c.field-meta.xml
<CustomField>
    <fullName>Area_Design_Win__c</fullName>
    <inlineHelpText>Area with the highest contribution to the design win. Field used for contribution split.</inlineHelpText>
    <label>uB Office Design-Win</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_manufacturing__c.field-meta.xml
<CustomField>
    <fullName>Area_manufacturing__c</fullName>
    <inlineHelpText>Select one or several areas, in which the product is manufactured.</inlineHelpText>
    <label>uB Office Manufacturing</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_opportunity_owner__c.field-meta.xml
<CustomField>
    <fullName>Area_opportunity_owner__c</fullName>
    <inlineHelpText>Area in which the opportunity owner resides</inlineHelpText>
    <label>uB Office Opp Owner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Values based on the global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Market__c.field-meta.xml
<CustomField>
    <fullName>New_Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Remark_Contribution__c.field-meta.xml
<CustomField>
    <fullName>Remark_Contribution__c</fullName>
    <inlineHelpText>Comment for contribution split</inlineHelpText>
    <label>Remark Contribution</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Partner_Role__c/Partner_Role__c.object-meta.xml
<CustomObject>
    <description>Link between two Accounts for a specific Opportunity</description>
    <label>Partner Role</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>P-Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Role__c/fields/Partner_Role__c.field-meta.xml
<CustomField>
    <fullName>Partner_Role__c</fullName>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 Partner Referral (commissions required)</fullName>
            </value>
            <value>
                <fullName>0 Partner Referral (no commissions)</fullName>
            </value>
            <value>
                <fullName>1 Opportunity owner</fullName>
            </value>
            <value>
                <fullName>2 Ref. design / platform dev.</fullName>
            </value>
            <value>
                <fullName>3 Design house</fullName>
            </value>
            <value>
                <fullName>3 ODM (Design and Manufacturing)</fullName>
            </value>
            <value>
                <fullName>3 Local Module Maker</fullName>
            </value>
            <value>
                <fullName>4 Consultant/Advisor</fullName>
            </value>
            <value>
                <fullName>4 Certification partner</fullName>
            </value>
            <value>
                <fullName>4 Technology partner</fullName>
            </value>
            <value>
                <fullName>4 MNO / MVNO</fullName>
            </value>
            <value>
                <fullName>5 Former contract manufacturer</fullName>
            </value>
            <value>
                <fullName>5 Actual contract manufacturer</fullName>
            </value>
            <value>
                <fullName>5 Potential contract manufacturer</fullName>
            </value>
            <value>
                <fullName>6 Sourcing / Negotiation entity</fullName>
            </value>
            <value>
                <fullName>6 Purchasing entity</fullName>
            </value>
            <value>
                <fullName>7 Distributor</fullName>
            </value>
            <value>
                <fullName>8 Sales representative</fullName>
            </value>
            <value>
                <fullName>8 Agent</fullName>
            </value>
            <value>
                <fullName>9 Customer of opp. owner</fullName>
            </value>
            <value>
                <fullName>9 Car brand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloneOpp.cls
//Created: 20.12.2021 - Umar Arshad - In order to convert clone Opp Javascript button on Opportunity to LWC
public with sharing class CloneOpp {

    public String opportunityId{get; set;}

    public CloneOpp(ApexPages.StandardController stdSetController) {
        opportunityId = (String)stdSetController.getRecord().Id;
    }

@AuraEnabled
public static String cloneOpportunity(String recordId){
String oppId;
String newOppId;
string AccountId;
List<Opp_Product__c> oppProductList = new List<Opp_Product__c>();
List<OpportunityContactRole> oppContactRoleList = new List<OpportunityContactRole>();
List<Partner_Role__c> partnerRoleList = new List<Partner_Role__c>();

if(!string.isEmpty(recordId)){

    oppId = recordId;
    List<Opportunity> oldOpp = [SELECT Id, Name, OwnerId,AccountId, CurrencyIsoCode, RecordTypeId, Annual_Quantity__c, New_Application_Type__c, New_Market__c, CloseDate, Description, Area_opportunity_owner__c, Area_design_house__c, Area_manufacturing__c, Area_Design_Win__c, Remark_Contribution__c,Team_members__c FROM Opportunity WHERE Id =:oppId ];
    AccountId = oldOpp[0].AccountId;
    //var records = result.getArray("records");
    
    //alert (records[0])
    
    //var QuotationCurrency = records[0].CurrencyIsoCode;
    
    // Creates cloned opportuntiy
    Opportunity OPP = new Opportunity();
    OPP.AccountId = AccountId;
    OPP.Opportunity_Account__c = AccountId;
    OPP.Name = oldOpp[0].Name + ' - New generation';
    OPP.OwnerId = oldOpp[0].OwnerId;
    OPP.CurrencyIsoCode = oldOpp[0].CurrencyIsoCode;
    OPP.RecordTypeId = '01220000000CqRn'; /*Record ID für Opportunity*/
    OPP.Annual_Quantity__c = oldOpp[0].Annual_Quantity__c;
    OPP.New_Application_Type__c = oldOpp[0].New_Application_Type__c;
    OPP.New_Market__c = oldOpp[0].New_Market__c;
    OPP.StageName = '3 Calling On';
    OPP.CloseDate = oldOpp[0].CloseDate;
    
    OPP.Description = oldOpp[0].Description;
    
    OPP.Area_opportunity_owner__c = oldOpp[0].Area_opportunity_owner__c;
    OPP.Area_design_house__c = oldOpp[0].Area_design_house__c;
    OPP.Area_manufacturing__c = oldOpp[0].Area_manufacturing__c;
    OPP.Area_Design_Win__c = oldOpp[0].Area_Design_Win__c;
    OPP.Remark_Contribution__c = oldOpp[0].Remark_Contribution__c;
    OPP.Team_members__c = oldOpp[0].Team_members__c;
    
    //var result = sforce.connection.create([OPP]);
    insert OPP;
    //alert (result[0])
    
    newOppId = OPP.id;
    
    // alert (ClonedOppId)
    
    
    //queries all opp products related to the original opportunity
    List<Opp_Product__c> oppProduct = [SELECT Id, Product__c, Annual_Quantity__c, Unit_Price__c, Use_Restriction__c, IPR_Coverage__c FROM Opp_Product__c WHERE Opportunity__c =: oppId];
    //var records = result.getArray("records");
    
    //alert (records[0])
    
    //Loop through the opp products in the records set
    If(oppProduct!= null){
    for(integer i=0;i<oppProduct.size();i++){
        
        
        
        //create an opp product item in the cloned opportuntiy for this opp product
        Opp_Product__c OPR = new Opp_Product__c();
        OPR.Opportunity__c = newOppId;
        OPR.Product__c = oppProduct[i].Product__c;
        OPR.Annual_Quantity__c = oppProduct[i].Annual_Quantity__c;
        OPR.Unit_Price__c = oppProduct[i].Unit_Price__c;
        OPR.Use_Restriction__c = oppProduct[i].Use_Restriction__c;
        OPR.IPR_Coverage__c = oppProduct[i].IPR_Coverage__c;
        
        oppProductList.add(OPR);
        
        //alert (result[0])
        
    }
}

    if(oppProductList != null)
    insert oppProductList;
}
    
    //queries all contact roles from the original opportunity
List<OpportunityContactRole> oppContactRole = [SELECT Id, ContactId, IsPrimary, Role FROM OpportunityContactRole WHERE OpportunityId =: oppId];
//var records = result.getArray("records");

/* alert (records[0]) */

//loop through the contact roles in the records set
if(oppContactRole!= null){

    for(integer i=0;i<oppContactRole.size();i++){
        
        //creates the same contact roles for the cloned opportunity
        OpportunityContactRole ROL = new OpportunityContactRole();
        ROL.ContactId = oppContactRole[i].ContactId;
        ROL.IsPrimary = oppContactRole[i].IsPrimary;
        ROL.Role = oppContactRole[i].Role;
        ROL.OpportunityId = newOppId;
        
        oppContactRoleList.add(ROL);
        
        /* alert (result[0]) */
        
    }

    if(oppContactRoleList!= null){
    insert oppContactRoleList;
    }
}
//queries the partner roles from the original opportunity
List<Partner_Role__c> partnerRole = [SELECT Id, Opportunity_Account__c, Partner_Account__c, Partner_Role__c FROM Partner_Role__c WHERE Opportunity__c =: oppId];

if(partnerRole!= null){
for(integer i=0;i<partnerRole.size();i++){

//creates the same partner roles for the cloned opportunity
Partner_Role__c PAR = new Partner_Role__c();
PAR.Opportunity__c = newOppId;
PAR.Opportunity_Account__c = partnerRole[i].Opportunity_Account__c;
PAR.Partner_Account__c = partnerRole[i].Partner_Account__c;
PAR.Partner_Role__c = partnerRole[i].Partner_Role__c;

partnerRoleList.add(PAR);

}
if(partnerRoleList != null){
    
    insert partnerRoleList;
}

//window.parent.location.href="/"+ ClonedOppId + "/e?retURL=%2F" + ClonedOppId;
}
return newOppId;
}

public pageReference classicCloneOpp()
    {
        String oppId =ApexPages.currentPage().getParameters().get('id');
        string cloneOppId = cloneOpportunity(opportunityId);
        pageReference pageRef = new pageReference('/' + cloneOppId);
        pageRef.SetRedirect(true);
        return pageRef;
    }
}