force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Referred_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quotation referring to specific opportunity</description>
    <label>Referred Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>List of Quotations</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Successor_Product__c.field-meta.xml
<CustomField>
    <fullName>Successor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Most recent product version used for opportunities and quotations.</inlineHelpText>
    <label>Successor Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Successor_Product__c.field-meta.xml
<CustomField>
    <fullName>Successor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Most recent product version used for opportunities and quotations.</inlineHelpText>
    <label>Successor Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Successor Product)</relationshipLabel>
    <relationshipName>Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/updateOppProductsWithSuccessorCtrl.cls
/*
*
* This controller class will update the Opp Products with Successor Product of Working Opportunites
* 
* **************************************************************************************
* 
* @author         Khurram Shahzad   <khurram.shahzad@u-blox.com>
* @created        18/11/2021
*
* *************************************************************************************
*
*/

public with sharing class updateOppProductsWithSuccessorCtrl {
    public updateOppProductsWithSuccessorCtrl(){}
    
    /* 
    *  Invoked from Lightning Component c:UpdateOppProductsWithSuccessor
    *  Querying the Successor of current Product
    *  Calling Async method to update Opp Products with Successor 
    *  Will throw an exception if no successfor found 
    */
    
    @AuraEnabled
    public static Id updateOppProductsWithSuccessor(Id productId){

        map<Id, Product2> successorProductMap = new map<Id, Product2>([Select Id, Successor_Product__c from Product2 where Id=: productId]);
        if(successorProductMap.size() > 0 && successorProductMap.get(productId).Successor_Product__c != null){
            updateOppProducts(productId,successorProductMap.get(productId).Successor_Product__c);
            return successorProductMap.get(productId).Successor_Product__c;                                
        }else throw new AuraHandledException('Successor Product is not added');
    }
    
    /* 
    *  Async method to update Opp Products with Successor
    *  Excluded Opp Products of Opportunities which are either closed lost or closed won
    */
    
    @future
    private static void updateOppProducts(Id productId, Id successorId){
        list<Opp_Product__c> oppProducts = new list<Opp_Product__c>();        
        for(Opp_Product__c oppProduct : [SELECT Id,Product__c FROM Opp_Product__c WHERE Product__c=: productId
                                            AND Opportunity__r.IsClosed = false 
                                            AND Opportunity__r.IsWon = false]){
            oppProducts.add(new Opp_Product__c(
                Id = oppProduct.Id,
                Product__c = successorId
            ));                
        }
        Database.update(oppProducts, false);
    }
}