force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <inlineHelpText>On creation, if empty copied from the master Opportunity after Save. Edit as needed.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NewCompetitorPriceCtrl.cls
public with sharing class NewCompetitorPriceCtrl {
    public Opp_Product__c oppProduct{get;set;} 
    public Id ids{get;set;}
    public NewCompetitorPriceCtrl(ApexPages.StandardSetController controller) {
        ids=ApexPages.currentPage().getParameters().get('id');
        if(ids!=null){
            oppProduct=[Select id,Annual_Quantity__c,Name from Opp_Product__c where id=:ids];
         }         
    }

}