force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <inlineHelpText>On creation, if empty copied from the master Opportunity after Save. Edit as needed.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Contribution__c.field-meta.xml
<CustomField>
    <fullName>Contribution__c</fullName>
    <description>The COGS (below) are now updated with Workflow:
( Product__r.COGS_1__c + 
CASE (text( Use_Restriction__c ),
&quot;2G M2M&quot;, Product__r.IPR_USD_M2M__c + Product__r.IPR_Pct_M2M__c,
&quot;3G M2M&quot;, Product__r.IPR_USD_M2M__c + Product__r.IPR_Pct_M2M__c,
&quot;4G M2M&quot;, Product__r.IPR_USD_M2M__c + Product__r.IPR_Pct_M2M__c,
...))</description>
    <formula>Contribution_Unweighted__c * Status_Factor__c * Opportunity__r.Probability</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>(Revenue Unweighted - Annual_Quantity__c * COGS__c) * Opportunity Probability
NOTE: 0 if Status is Alternative Product, Lost, Not Applicable</inlineHelpText>
    <label>Contribution</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Ordering_Code__c.field-meta.xml
<CustomField>
    <fullName>Ordering_Code__c</fullName>
    <formula>Product__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ordering Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <formula>text(Product__r.Product_Center__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>case(text( Status__c ),
&quot;Won&quot;, 1,
&quot;Evaluation&quot;, 0.5,
&quot;Not applicable&quot;, 0,
0
) * Contribution__c</description>
    <formula>case(text( Status__c ),
&quot;Won&quot;, 1,
&quot;Evaluation&quot;, 0.5,
&quot;Not applicable&quot;, 0,
0
) * Revenue_With_Status_Factor__c / 10000</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ranking</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <description>Annual Quantity * Unit Price * Opportunity Probability
NOTE: 0 if Status is Alternative Product, Lost, Not Applicable</description>
    <formula>Revenue_Unweighted__c * Status_Factor__c * Opportunity__r.Probability</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Annual Quantity * Unit Price * Opportunity Probability
NOTE: 0 if Status is Alternative Product, Lost, Not Applicable</inlineHelpText>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>When multiple products are in evaluation, set the most probable one as “Evaluation”, all others as “Alternative product”. These will not count as revenue or contribution.</description>
    <inlineHelpText>When multiple products are in evaluation, set the most probable one as “Evaluation”, all others as “Alternative product”. These will not count as revenue or contribution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alternative Product</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
                <default>true</default>
                <label>Evaluation</label>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Use_Restriction__c.field-meta.xml
<CustomField>
    <fullName>Use_Restriction__c</fullName>
    <label>Use Restriction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2G Consumer</fullName>
            </value>
            <value>
                <fullName>2G M2M</fullName>
            </value>
            <value>
                <fullName>2G Telematics</fullName>
            </value>
            <value>
                <fullName>2G Handset</fullName>
            </value>
            <value>
                <fullName>2G Laptop</fullName>
            </value>
            <value>
                <fullName>2G Other</fullName>
            </value>
            <value>
                <fullName>3G M2M</fullName>
            </value>
            <value>
                <fullName>3G Telematics</fullName>
            </value>
            <value>
                <fullName>3G Handset</fullName>
            </value>
            <value>
                <fullName>3G Laptop</fullName>
            </value>
            <value>
                <fullName>3G Other</fullName>
            </value>
            <value>
                <fullName>4G M2M</fullName>
            </value>
            <value>
                <fullName>4G Telematics</fullName>
            </value>
            <value>
                <fullName>4G Handset</fullName>
            </value>
            <value>
                <fullName>4G Laptop</fullName>
            </value>
            <value>
                <fullName>4G Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/recordTypes/Opp_Product_Tashang.recordType-meta.xml
<RecordType>
    <fullName>Opp_Product_Tashang</fullName>
    <active>true</active>
    <description>Tashang products can be selected in this record type.</description>
    <label>Opp Product Tashang</label>
</RecordType>

force-app/main/default/classes/Opportunity_Product_Controller.cls
public class Opportunity_Product_Controller {
    public Id oppId;
    public List<Opp_Product__c> oppProdList{get;set;}
    public Opportunity_Product_Controller(ApexPages.StandardController controller){
        oppId = ApexPages.currentPage().getParameters().get('id');
        system.debug('oppId: '+oppId);
        oppProdList = new List<Opp_Product__c>();
        Id recTypeId = Schema.SObjectType.Opp_Product__c.getRecordTypeInfosByDeveloperName().get('Opp_Product_Tashang').getRecordTypeId(); 
        oppProdList = [select Id,Name,Ordering_Code__c,Product_Center__c,Use_Restriction__c,Revenue__c,Contribution__c,Status__c,Ranking__c,
                       Unit_Price__c,Annual_Quantity__c from Opp_Product__c where Opportunity__c =: oppId and RecordTypeId =: recTypeId];
        
		system.debug('oppProdList:'+oppProdList);
    }

}