force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <description>Win or loss reason. Required when Status is Won or Lost.</description>
    <inlineHelpText>Win or loss reason. Required when Status is Won or Lost.</inlineHelpText>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alternative Product</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Features</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Incumbent</fullName>
            </value>
            <value>
                <fullName>Micro Opportunity</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Poor Opp Qualification</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Project Stopped</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Strategy/Tactics</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>T&amp;C</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Wrong strategy/tactics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Loss_Reason_Remark__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason_Remark__c</fullName>
    <description>Additional remark to Reason</description>
    <inlineHelpText>Additional remark to Reason</inlineHelpText>
    <label>Reason Remark</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/No_Opp_Update__c.field-meta.xml
<CustomField>
    <fullName>No_Opp_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to stop triggering updating parent opportunity to reorder opp products if opportunity is set to Lost. 
It is used in &apos;updateStatusOnOppProduct&apos; and &apos;oppProductTrigger&apos; trigger. If value is changed, then trigger from opp product won&apos;t update its parent Opportunity. If value is not change, then the trigger updates Opportunity record.</description>
    <label>No Opp Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Revenue_Unweighted__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Unweighted__c</fullName>
    <description>Annual Quantity * Unit Price</description>
    <formula>if( AND(RecordTypeId = &quot;0122p00000043gT&quot;, Opportunity_Lifetime_Year__c &gt; 1 ),
Annual_Quantity__c * Unit_Price__c * (Opportunity_Lifetime_Year__c - 1),
Annual_Quantity__c * Unit_Price__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Annual Quantity * Unit Price</inlineHelpText>
    <label>Revenue Unweighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>When multiple products are in evaluation, set the most probable one as “Evaluation”, all others as “Alternative product”. These will not count as revenue or contribution.</description>
    <inlineHelpText>When multiple products are in evaluation, set the most probable one as “Evaluation”, all others as “Alternative product”. These will not count as revenue or contribution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alternative Product</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
                <default>true</default>
                <label>Evaluation</label>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_1__c.field-meta.xml
<CustomField>
    <fullName>Product_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (1st in the related list).</inlineHelpText>
    <label>Product 1</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 1)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_2__c.field-meta.xml
<CustomField>
    <fullName>Product_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (2nd in the related list).</inlineHelpText>
    <label>Product 2</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 2)</relationshipLabel>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_3__c.field-meta.xml
<CustomField>
    <fullName>Product_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (3rd in the related list).</inlineHelpText>
    <label>Product 3</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 3)</relationshipLabel>
    <relationshipName>Opportunities5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_4__c.field-meta.xml
<CustomField>
    <fullName>Product_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (4th in the related list).</inlineHelpText>
    <label>Product 4</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 4)</relationshipLabel>
    <relationshipName>Opportunities6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_5__c.field-meta.xml
<CustomField>
    <fullName>Product_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (5th in the related list).</inlineHelpText>
    <label>Product 5</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 5)</relationshipLabel>
    <relationshipName>Opportunities7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Win or loss reason. Required when Stage is 1 Lost, 5 Design-in, 6 Prototypes, 7 Pre-Production, and 8 Production.</description>
    <inlineHelpText>Win or loss reason. Required when Stage is 1 Lost, 5 Design-in, 6 Prototypes, 7 Pre-Production, and 8 Production.</inlineHelpText>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Auto Closure</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Duplicate Entry</fullName>
            </value>
            <value>
                <fullName>Features</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Incumbent</fullName>
            </value>
            <value>
                <fullName>Micro Opportunity</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Poor Opp Qualification</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Project Stopped</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>T&amp;C</fullName>
            </value>
            <value>
                <fullName>No Follow-Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Referred_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quotation referring to specific opportunity</description>
    <label>Referred Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>List of Quotations</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Revenue_unweighted__c.field-meta.xml
<CustomField>
    <fullName>Revenue_unweighted__c</fullName>
    <description>Unweighted revenue independent of Opp status</description>
    <inlineHelpText>Unweighted revenue independent of Opp status</inlineHelpText>
    <label>Revenue unweighted</label>
    <summarizedField>Opp_Product__c.Pipeline_Revenue__c</summarizedField>
    <summaryForeignKey>Opp_Product__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Partner_Role__c/Partner_Role__c.object-meta.xml
<CustomObject>
    <description>Link between two Accounts for a specific Opportunity</description>
    <label>Partner Role</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>P-Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partner Roles</relationshipLabel>
    <relationshipName>R00N20000000pWzkEAE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OpportunityHelper.cls
public with sharing class OpportunityHelper {
    private static final string STAGE_LOST =  '1 Lost';
    private static final string EVALUATION =  'Evaluation';
    private static final string WON =  'Won';
    private static final string LOST =  'Lost';
    private static final string ALT_PRODUCT =  'Alternative Product';
    private static final string NA =  'Not applicable';
    private static final set<string> OPPORTUNITY_STAGES = new set<string>{        
        '5 Design-in',
        '6 Prototypes',
        '7 Pre-Production',
        '8 Production',
        '9 Closed EoL'        
    };

    public void updateOppProductStatus(map<Id, Opportunity> newMap, map<Id, Opportunity> oldMap) {
        set<Id> opportunityIdSet = new set<Id>();        

        for(Opportunity opp : newMap.values()){
            if(opp.StageName != oldMap.get(opp.Id).StageName){
                if(opp.StageName == STAGE_LOST || 
                    (OPPORTUNITY_STAGES.contains(opp.StageName) && !OPPORTUNITY_STAGES.contains(oldMap.get(opp.Id).StageName))){
                    opportunityIdSet.add(opp.Id);
                }
            }        
        }
        if(opportunityIdSet.size() > 0){
            map<Id,list<Opp_Product__c>> lostOppsAndOppProductsMap = new map<Id,list<Opp_Product__c>>();
            list<Opp_Product__c> OppProdToUpdate = new list<Opp_Product__c>();         
            
            for(Opp_Product__c OppProd:[SELECT Id,
                                                Product__c, 
                                                Opportunity__c, 
                                                Status__c, 
                                                Loss_Reason__c, 
                                                Opportunity__r.StageName, 
                                                Opportunity__r.Reason__c, 
                                                Loss_Reason_Remark__c, 
                                                No_Opp_Update__c
                                        FROM Opp_Product__c
                                        WHERE Opportunity__c IN :opportunityIdSet
                                        ORDER BY Revenue_Unweighted__c DESC]){
                
                if(OppProd.Opportunity__r.StageName == STAGE_LOST) {
                    OppProd.No_Opp_Update__c =  OppProd.No_Opp_Update__c ? false : true;
                    if(!lostOppsAndOppProductsMap.containsKey(OppProd.Opportunity__c)) {
                        lostOppsAndOppProductsMap.put(OppProd.Opportunity__c, new list<Opp_Product__c>());
                    }
                    lostOppsAndOppProductsMap.get(OppProd.Opportunity__c).add(OppProd);                
                    if(OppProd.Status__c == EVALUATION || OppProd.Status__c == WON){
                        setStatusLostAndPutRemarks(OppProd);
                        OppProd.Loss_Reason__c = OppProd.Opportunity__r.Reason__c;
                        OppProdToUpdate.add(OppProd);
                    }               
                }

                if(OppProd.Status__c == EVALUATION && OppProd.Opportunity__r.StageName != STAGE_LOST){               
                    OppProd.Status__c = WON;
                    OppProd.Loss_Reason__c = OppProd.Opportunity__r.Reason__c; 
                    OppProdToUpdate.add(OppProd); 
                
                }else if(OppProd.Status__c == ALT_PRODUCT || OppProd.Status__c == NA){                
                    setStatusLostAndPutRemarks(OppProd);
                    OppProd.Loss_Reason__c = ALT_PRODUCT;                                
                    OppProdToUpdate.add(OppProd);            
                }
            }
            list<Opportunity> oppsToUpdate = updateLostOpportunitiesProducts(lostOppsAndOppProductsMap);            
            database.update(OppProdToUpdate);        
            database.update(oppsToUpdate);
        }                            
    }

    private void setStatusLostAndPutRemarks(Opp_Product__c OppProd){
        OppProd.Status__c = LOST;        
        if(OppProd.Loss_Reason_Remark__c == null) {
            OppProd.Loss_Reason_Remark__c = '(Automatic update)';
        }        
    }

    private list<Opportunity> updateLostOpportunitiesProducts(map<Id,list<Opp_Product__c>> oppProductsMap){              
        map<Id, Opportunity> opportunityProductsUpdate = new map<Id, Opportunity>();
        if(oppProductsMap.size() > 0){             
            for(Opportunity opp : [SELECT Id, 
                                        Product_1__c, 
                                        Product_2__c, 
                                        Product_3__c, 
                                        Product_4__c, 
                                        Product_5__c 
                                    FROM Opportunity WHERE Id IN :oppProductsMap.keySet()]){            
                integer i=1;
                for(Opp_Product__c oppProd : oppProductsMap.get(opp.Id)){
                    if(i <= 5){
                        opp.put('Product_'+string.valueOf(i)+'__c',oppProd.Product__c);
                        opportunityProductsUpdate.put(opp.Id,opp);
                        i++;
                    }else break;                                
                }
            }            
        }
        return opportunityProductsUpdate.values();       
    }

    public list<Partner_Role__c> updatePartnerRole(set<Id> opportunityIdSet){
        list<Partner_Role__c> partnerRoleToUpdate = new list<Partner_Role__c>();
        
        for(Partner_Role__c pRole : [SELECT Id, 
                                            Opportunity_Account__c, 
                                            Opportunity__r.Opportunity_Account__c
                                    FROM Partner_Role__c
                                    WHERE Opp_Account_Mismatch__c = true
                                    AND Opportunity__c IN :opportunityIdSet]){

            pRole.Opportunity_Account__c = pRole.Opportunity__r.Opportunity_Account__c;
            PartnerRoleToUpdate.add(pRole);
        }       
        return partnerRoleToUpdate;
    }

    public void opportunityOwnerUpdate(list<Opportunity> opportunities){               
    
        for(Opportunity oppObj : opportunities){
            if(!String.isEmpty(oppObj.AccountOwnerID__c)){
                oppObj.Account_Owner__c = oppObj.AccountOwnerID__c;            
            }else{
                oppObj.Account_Owner__c = NULL;            
            }
            if(!String.isEmpty(oppObj.Account_Channel_Manager_Id__c)){
                oppObj.Account_Channel_Manager_Obj__c = oppObj.Account_Channel_Manager_Id__c;
            }else{
                oppObj.Account_Channel_Manager_Obj__c = NULL;
            }
        }
    }
}