force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <formula>text(Product__r.Product_Center__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F10</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M10</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
                <color>#B6E32E</color>
                <label>u-blox M9</label>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
                <color>#000099</color>
                <label>u-blox M8</label>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
                <color>#0B6FCE</color>
                <label>u-blox 7</label>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
                <color>#33CCFF</color>
                <label>u-blox 6</label>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
                <color>#6600CC</color>
                <label>u-blox 5</label>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
                <color>#CC66CC</color>
                <label>ANTARIS 4</label>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
                <color>#FF99FF</color>
                <label>Various</label>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
                <color>#999999</color>
                <default>true</default>
                <label>Not applicable</label>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Tashang</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALEX</fullName>
            </value>
            <value>
                <fullName>AMY</fullName>
            </value>
            <value>
                <fullName>ANN</fullName>
            </value>
            <value>
                <fullName>ANNA</fullName>
            </value>
            <value>
                <fullName>Blueprint</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>Boxed</fullName>
            </value>
            <value>
                <fullName>CAM</fullName>
            </value>
            <value>
                <fullName>CB15x22</fullName>
            </value>
            <value>
                <fullName>CB16x36</fullName>
            </value>
            <value>
                <fullName>CB23x36</fullName>
            </value>
            <value>
                <fullName>ELIN</fullName>
            </value>
            <value>
                <fullName>ELLA</fullName>
            </value>
            <value>
                <fullName>EMMY</fullName>
            </value>
            <value>
                <fullName>EVA</fullName>
            </value>
            <value>
                <fullName>Eval Kit</fullName>
            </value>
            <value>
                <fullName>FW75</fullName>
            </value>
            <value>
                <fullName>IC</fullName>
            </value>
            <value>
                <fullName>JODY</fullName>
            </value>
            <value>
                <fullName>LARA</fullName>
            </value>
            <value>
                <fullName>LCC09096</fullName>
            </value>
            <value>
                <fullName>LCC1316</fullName>
            </value>
            <value>
                <fullName>LCC1618</fullName>
            </value>
            <value>
                <fullName>LCC2626</fullName>
            </value>
            <value>
                <fullName>LEA</fullName>
            </value>
            <value>
                <fullName>LEON</fullName>
            </value>
            <value>
                <fullName>LILY</fullName>
            </value>
            <value>
                <fullName>LISA</fullName>
            </value>
            <value>
                <fullName>LUCY</fullName>
            </value>
            <value>
                <fullName>LUKA</fullName>
            </value>
            <value>
                <fullName>PCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ApprovalProSchedulableTest.cls
@isTest
private class ApprovalProSchedulableTest {


    public static String CRON_EXP = '0 0 0 15 3 ? 2030';

    static testmethod void testprocessApprovalrecord(){
        
    Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        
    // Commenting out Product__c prod. It is for the removal of custom Product obj. By ufar, 12-6-22.
    /*
        Product__c prod = new Product__c();
        prod.Name = 'TEst Product';
        prod.Type_No__c = 'MPCI-L280-03S-03';
    prod.Packaging_Size__c = 150;
        prod.Product_Family__c = 'PCI';
        prod.Positioning_Engine__c = 'Not applicable';
        prod.CurrencyIsoCode = 'USD';
        insert prod;
	*/
    Product2 prodForRanked1 = new Product2(Name='testProd1', Type_No__c='testTypeNum1', Product_Center__C='Positioning');  // khir: Added Product Canter
        insert prodForRanked1;

        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Name = 'Test opportunity';
        opp.StageName = '6 Prototypes';
        opp.CloseDate = Date.newInstance(2030, 12, 9);
        insert opp;

    Opp_Product__c oppProd = new Opp_Product__c(); 
        oppProd.Opportunity__c = opp.Id;
    oppProd.CurrencyIsoCode = 'USD';
        oppProd.Status__c = 'Not applicable';
        oppProd.Flag_Approval_Status__c = 'Pending';
        oppProd.Flagged_Item__c = False;
        oppProd.Product__c = prodForRanked1.Id;
        insert oppProd;
    
    List<Approval.ProcessWorkitemRequest> requests = new List<Approval.ProcessWorkitemRequest>();

    Test.startTest();
        
    Approval.ProcessWorkitemRequest apwir = new approval.ProcessWorkitemRequest();
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
    app.setObjectId(oppProd.Id);
        Approval.ProcessResult resu = Approval.process(app);
    String jobId = System.schedule('ScheduledApexTest', CRON_EXP, new ApprovalProSchedulable());
    ApprovalProcessAutomation approclass = new ApprovalProcessAutomation();
        approclass.processApprovalrecord();
        apwir.setAction('Approve');
        
        Test.stopTest();
    }   
}