force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <inlineHelpText>On creation, if empty copied from the master Opportunity after Save. Edit as needed.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/IPR_Coverage__c.field-meta.xml
<CustomField>
    <fullName>IPR_Coverage__c</fullName>
    <label>IPR Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Premium coverage</fullName>
            </value>
            <value>
                <fullName>Prime coverage</fullName>
            </value>
            <value>
                <fullName>Premium except Qualcomm</fullName>
            </value>
            <value>
                <fullName>Prime except Qualcomm</fullName>
            </value>
            <value>
                <fullName>No coverage</fullName>
            </value>
            <value>
                <fullName>Full coverage</fullName>
            </value>
            <value>
                <fullName>All except Qualcomm</fullName>
            </value>
            <value>
                <fullName>All except Interdigital</fullName>
            </value>
            <value>
                <fullName>All except QCOM and IDC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>When multiple products are in evaluation, set the most probable one as “Evaluation”, all others as “Alternative product”. These will not count as revenue or contribution.</description>
    <inlineHelpText>When multiple products are in evaluation, set the most probable one as “Evaluation”, all others as “Alternative product”. These will not count as revenue or contribution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alternative Product</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
                <default>true</default>
                <label>Evaluation</label>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Use_Restriction__c.field-meta.xml
<CustomField>
    <fullName>Use_Restriction__c</fullName>
    <label>Use Restriction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2G Consumer</fullName>
            </value>
            <value>
                <fullName>2G M2M</fullName>
            </value>
            <value>
                <fullName>2G Telematics</fullName>
            </value>
            <value>
                <fullName>2G Handset</fullName>
            </value>
            <value>
                <fullName>2G Laptop</fullName>
            </value>
            <value>
                <fullName>2G Other</fullName>
            </value>
            <value>
                <fullName>3G M2M</fullName>
            </value>
            <value>
                <fullName>3G Telematics</fullName>
            </value>
            <value>
                <fullName>3G Handset</fullName>
            </value>
            <value>
                <fullName>3G Laptop</fullName>
            </value>
            <value>
                <fullName>3G Other</fullName>
            </value>
            <value>
                <fullName>4G M2M</fullName>
            </value>
            <value>
                <fullName>4G Telematics</fullName>
            </value>
            <value>
                <fullName>4G Handset</fullName>
            </value>
            <value>
                <fullName>4G Laptop</fullName>
            </value>
            <value>
                <fullName>4G Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <description>Annual run rate of product. If</description>
    <inlineHelpText>Annual run rate. For single shot opportunities, use total quantity.
If Opportunity is converted from Lead, this is copied from Lead.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/OppProductTestDataFactory.cls
@isTest
public with sharing class OppProductTestDataFactory extends TestDataFactory{


    public OppProductTestDataFactory() {
        super('Opp_Product__c');
    }

    public override sObject initializeRecord(){
        Opp_Product__c OPR = new Opp_Product__c();
        // OPR.Opportunity__c = opp.Id;
        // OPR.Product__c = product.Id;
        OPR.Annual_Quantity__c = 500;
        OPR.Unit_Price__c = 30;
        OPR.Use_Restriction__c = '2G Consumer';
        OPR.IPR_Coverage__c = 'Full coverage';
        OPR.Status__c = 'Evaluation';

        return (Opp_Product__c)OPR;
    }

    public override sObject createRecord() {
        Opp_Product__c o = (Opp_Product__c)initializeRecord();
        Insert o;
        return o;
    }



    public Opp_Product__c createRecord(string oppId, string productId) {

        Opp_Product__c OPR = new Opp_Product__c();
        OPR.Opportunity__c = oppId;
        OPR.Product__c = productId;
        OPR.Annual_Quantity__c = 500;
        OPR.Unit_Price__c = 30;
        // OPR.Use_Restriction__c = '4G M2M';
        // OPR.IPR_Coverage__c = 'Premium coverage';
        OPR.Status__c = 'Evaluation';

        Insert OPR;
        return OPR;
    }

    public sObject updateRecord(Opp_Product__c record) {
        update record;
        return record;
    }

    public override List<sObject> createBulkRecords() {
        for (Integer i = 0; i < numberOfRecords; i++) {
            // Opp_Product__c cont = new Opp_Product__c();
            // cont.Name = 'Test Opportunity'+i;
            // recordsList.add(cont);
        }
        Insert recordsList;
        return recordsList;
    }
}