force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Flag_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Flag_Approval_Status__c</fullName>
    <description>Set through the Approval Process</description>
    <inlineHelpText>Set through the Approval Process</inlineHelpText>
    <label>Flag Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Flagged_Item__c.field-meta.xml
<CustomField>
    <fullName>Flagged_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, you can edit the manual forecast in the report opened with &quot;Measure Report&quot; button.</description>
    <inlineHelpText>If checked, you can edit the manual forecast in the report opened with &quot;Measure Report&quot; button. Press &quot;Submit for Approval&quot; button to check or uncheck.</inlineHelpText>
    <label>Flagged Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ApprovalProcessAutomation.cls
/*
	This class contains business logic for automatic approval of approval process for Opp Product
	Created date: 10/15/2021
	Created by:
*/

public class ApprovalProcessAutomation {
    public void processApprovalrecord(){ 

		String username = userinfo.getUserName();
            List<Opp_Product__c> ListOppProds = [Select Id From Opp_Product__c Where Flag_Approval_Status__c ='Pending' AND  Flagged_Item__c=False];
            List<Approval.ProcessWorkitemRequest> requests = new List<Approval.ProcessWorkitemRequest>();

        	For(ProcessInstanceWorkitem workItems: [SELECT Id, ProcessInstanceId FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId =:ListOppProds]){
                
                Approval.ProcessWorkitemRequest apwir = new approval.ProcessWorkitemRequest();
                apwir.setWorkitemId(workItems.Id);
                apwir.setAction('Approve');
                requests.add(apwir);
			}
			Approval.process(requests);
	}
}