force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <inlineHelpText>On creation, if empty copied from the master Opportunity after Save. Edit as needed.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <formula>text(Opportunity__r.New_Application_Type__c)</formula>
    <label>Application Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <formula>Opportunity__r.Account.Name</formula>
    <label>Opportunity Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <description>Annual run rate of product. If</description>
    <inlineHelpText>Annual run rate. For single shot opportunities, use total quantity.
If Opportunity is converted from Lead, this is copied from Lead.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_design_house__c.field-meta.xml
<CustomField>
    <fullName>Area_design_house__c</fullName>
    <inlineHelpText>Area in which the design is made.</inlineHelpText>
    <label>uB Office Design House</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_Design_Win__c.field-meta.xml
<CustomField>
    <fullName>Area_Design_Win__c</fullName>
    <inlineHelpText>Area with the highest contribution to the design win. Field used for contribution split.</inlineHelpText>
    <label>uB Office Design-Win</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_manufacturing__c.field-meta.xml
<CustomField>
    <fullName>Area_manufacturing__c</fullName>
    <inlineHelpText>Select one or several areas, in which the product is manufactured.</inlineHelpText>
    <label>uB Office Manufacturing</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_opportunity_owner__c.field-meta.xml
<CustomField>
    <fullName>Area_opportunity_owner__c</fullName>
    <inlineHelpText>Area in which the opportunity owner resides</inlineHelpText>
    <label>uB Office Opp Owner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Values based on the global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Market__c.field-meta.xml
<CustomField>
    <fullName>New_Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is quotation, than it is blank.</description>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Remark_Contribution__c.field-meta.xml
<CustomField>
    <fullName>Remark_Contribution__c</fullName>
    <inlineHelpText>Comment for contribution split</inlineHelpText>
    <label>Remark Contribution</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Team_members__c.field-meta.xml
<CustomField>
    <fullName>Team_members__c</fullName>
    <description>Sales persons involved in the opportunity</description>
    <inlineHelpText>Select the sales persons involved in the opportunity. If they are in a different area, grant access by adding them to the account team.</inlineHelpText>
    <label>Team Members</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adam Andres</fullName>
            </value>
            <value>
                <fullName>Adam Strout</fullName>
            </value>
            <value>
                <fullName>Adrian Tan</fullName>
            </value>
            <value>
                <fullName>Amitesh Bajaj</fullName>
            </value>
            <value>
                <fullName>Anthony Protopsaltis</fullName>
            </value>
            <value>
                <fullName>Armin Böshenz</fullName>
            </value>
            <value>
                <fullName>Brad Sherrard</fullName>
            </value>
            <value>
                <fullName>Bruce Wu</fullName>
            </value>
            <value>
                <fullName>Carine Loo</fullName>
            </value>
            <value>
                <fullName>Carlos Dias</fullName>
            </value>
            <value>
                <fullName>Daniel Jungo</fullName>
            </value>
            <value>
                <fullName>David Sel</fullName>
            </value>
            <value>
                <fullName>Derek Wang</fullName>
            </value>
            <value>
                <fullName>Dylan Huang</fullName>
            </value>
            <value>
                <fullName>Ellen Huang</fullName>
            </value>
            <value>
                <fullName>Federico Dal Ferro</fullName>
            </value>
            <value>
                <fullName>Frederic Duhem</fullName>
            </value>
            <value>
                <fullName>Fredrik Borgstrom</fullName>
            </value>
            <value>
                <fullName>Henry You</fullName>
            </value>
            <value>
                <fullName>Hiroshi Yoshimura</fullName>
            </value>
            <value>
                <fullName>Jan Reisen</fullName>
            </value>
            <value>
                <fullName>Jason Meilhon</fullName>
            </value>
            <value>
                <fullName>Jean-Marie Dubois</fullName>
            </value>
            <value>
                <fullName>JeeHoon Kim</fullName>
            </value>
            <value>
                <fullName>Jennifer Nkire</fullName>
            </value>
            <value>
                <fullName>Jim Neff</fullName>
            </value>
            <value>
                <fullName>Jochen Steinhauer</fullName>
            </value>
            <value>
                <fullName>John Demirali</fullName>
            </value>
            <value>
                <fullName>Krystal Li</fullName>
            </value>
            <value>
                <fullName>Leo DeRosa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Partner_Role__c/Partner_Role__c.object-meta.xml
<CustomObject>
    <description>Link between two Accounts for a specific Opportunity</description>
    <label>Partner Role</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>P-Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Role__c/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Roles (As Opportunity Account)</relationshipLabel>
    <relationshipName>R00N200000018BaOEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CloneOppCtrl.cls
public class CloneOppCtrl {     
    @AuraEnabled
     public static String cloneOppMethod(String recordId){
        //ID AccountId;
       String ClonedOppId;
       if(!string.isEmpty(recordId)){  
        ID OpportunityId=(Id)recordId;
        List<Opportunity> oppObjLst=[SELECT Id, Name,AccountId,Opportunity_Account__c, OwnerId, CurrencyIsoCode, RecordTypeId, Annual_Quantity__c, New_Application_Type__c, New_Market__c, CloseDate, Description, Area_opportunity_owner__c, Area_design_house__c, Area_manufacturing__c, Area_Design_Win__c, Remark_Contribution__c,Team_members__c FROM Opportunity WHERE Id = :OpportunityId];
        String QuotationCurrency = oppObjLst[0].CurrencyIsoCode;
         // Creates cloned opportuntiy
        Opportunity oppObj= new Opportunity();        
        oppObj.AccountId = oppObjLst[0].Opportunity_Account__c;
        oppObj.Opportunity_Account__c = oppObjLst[0].Opportunity_Account__c;
        oppObj.Name = oppObjLst[0].Name + ' - New generation';
        oppObj.OwnerId = oppObjLst[0].OwnerId;
        oppObj.CurrencyIsoCode = oppObjLst[0].CurrencyIsoCode; 
        oppObj.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Opportunity').getRecordTypeId();    /*Record ID für Opportunity*/
        oppObj.Annual_Quantity__c = oppObjLst[0].Annual_Quantity__c;
        oppObj.New_Application_Type__c = oppObjLst[0].New_Application_Type__c;
        oppObj.New_Market__c = oppObjLst[0].New_Market__c;
        oppObj.StageName ='3 Calling On';
        oppObj.CloseDate = oppObjLst[0].CloseDate;    
        oppObj.Description = oppObjLst[0].Description;    
        oppObj.Area_opportunity_owner__c = oppObjLst[0].Area_opportunity_owner__c;
        oppObj.Area_design_house__c = oppObjLst[0].Area_design_house__c;
        oppObj.Area_manufacturing__c = oppObjLst[0].Area_manufacturing__c;
        oppObj.Area_Design_Win__c = oppObjLst[0].Area_Design_Win__c;
        oppObj.Remark_Contribution__c = oppObjLst[0].Remark_Contribution__c;
        oppObj.Team_members__c = oppObjLst[0].Team_members__c;
        insert oppObj;
        ClonedOppId=oppObj.id;        
        //queries all opp products related to the original opportunity
        List<Opp_Product__c> oppProObjLst = [SELECT Id, Product__c, Annual_Quantity__c, Unit_Price__c, Use_Restriction__c, IPR_Coverage__c FROM Opp_Product__c WHERE Opportunity__c =: OpportunityId];
        //Loop through the opp products in the records set
        list<Opp_Product__c> oppProlsts=new  list<Opp_Product__c>();
        for(Opp_Product__c OppPro:oppProObjLst){
            Opp_Product__c tempOppPro =new Opp_Product__c();  tempOppPro.Opportunity__c = ClonedOppId;   tempOppPro.Product__c = OppPro.Product__c;  tempOppPro.Annual_Quantity__c = OppPro.Annual_Quantity__c; tempOppPro.Unit_Price__c = OppPro.Unit_Price__c; tempOppPro.Use_Restriction__c = OppPro.Use_Restriction__c; tempOppPro.IPR_Coverage__c = OppPro.IPR_Coverage__c; 
            oppProlsts.add(tempOppPro);                                                                                            
          }  
           if(!oppProlsts.isEmpty()){
               insert oppProlsts;
           }
         //queries all contact roles from the original opportunity
         list<OpportunityContactRole> oppConcRoleLst=[SELECT Id, ContactId, IsPrimary, Role FROM OpportunityContactRole WHERE OpportunityId =:OpportunityId];              
        //loop through the contact roles in the records set
         list<OpportunityContactRole> oconrolelst=new list<OpportunityContactRole>();
          for(OpportunityContactRole oppConcRole: oppConcRoleLst){
           //creates the same contact roles for the cloned opportunity   
           OpportunityContactRole tempOppConRole =new OpportunityContactRole();       
            tempOppConRole.ContactId = oppConcRole.ContactId;
            tempOppConRole.IsPrimary = oppConcRole.IsPrimary;
            tempOppConRole.Role = oppConcRole.Role;
            tempOppConRole.OpportunityId = ClonedOppId;    
            oconrolelst.add(tempOppConRole);  
            //insert tempOppConRole;
          }  
           if(!oconrolelst.isEmpty()){
               insert oconrolelst;
           }
        //queries the partner roles from the original opportunity
       list<Partner_Role__c> parRoleLst=[SELECT Id, Opportunity_Account__c, Partner_Account__c, Partner_Role__c FROM Partner_Role__c WHERE Opportunity__c = :OpportunityId];              
        //loop through the partner roles in the records set
       list<Partner_Role__c> parlst=new list<Partner_Role__c>();
       for(Partner_Role__c parRoleObj:parRoleLst){
        //creates the same partner roles for the cloned opportunity      
        Partner_Role__c tempParRoleObj=new Partner_Role__c();   
        tempParRoleObj.Opportunity__c = ClonedOppId;
        tempParRoleObj.Opportunity_Account__c = parRoleObj.Opportunity_Account__c;
        tempParRoleObj.Partner_Account__c = parRoleObj.Partner_Account__c;
        tempParRoleObj.Partner_Role__c = parRoleObj.Partner_Role__c;
        parlst.add(tempParRoleObj);                  
        } 
        if(!parlst.isEmpty()){
               insert parlst;
           }   
      } 
       return ClonedOppId;    
    }    
    //window.parent.location.href="/"+ ClonedOppId + "/e?retURL=%2F" + ClonedOppId;*/  
   
    
}