force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Calculate_CogsBudget__c.field-meta.xml
<CustomField>
    <fullName>Calculate_CogsBudget__c</fullName>
    <formula>Update_Contribution__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculate COGS Budget</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/No_Opp_Update__c.field-meta.xml
<CustomField>
    <fullName>No_Opp_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to stop triggering updating parent opportunity to reorder opp products if opportunity is set to Lost. 
It is used in &apos;updateStatusOnOppProduct&apos; and &apos;oppProductTrigger&apos; trigger. If value is changed, then trigger from opp product won&apos;t update its parent Opportunity. If value is not change, then the trigger updates Opportunity record.</description>
    <label>No Opp Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>case(text( Status__c ),
&quot;Won&quot;, 1,
&quot;Evaluation&quot;, 0.5,
&quot;Not applicable&quot;, 0,
0
) * Contribution__c</description>
    <formula>case(text( Status__c ),
&quot;Won&quot;, 1,
&quot;Evaluation&quot;, 0.5,
&quot;Not applicable&quot;, 0,
0
) * Revenue_With_Status_Factor__c / 10000</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ranking</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/OppProductTriggerHandler.cls
public without sharing class OppProductTriggerHandler implements ITrigger{
     
    list<Opportunity> OpportunityToUpdate = new list<Opportunity>();
    // Commenting out this oppProductsToUpdate list. It is for the removal of custom Product obj. By ufar, 12-6-22.
	/*
    list<Opp_Product__c> oppProductsToUpdate = new list<Opp_Product__c>();
	*/
    // Prepare the data for catering to Before Trigger events
     public void prepareBefore(){}
    

     public void prepareAfter(){}
     
     // Process logic/functioanlities in other classes for before Insert event  
     public void beforeInsert(){}
 
     // Process logic/functioanlities in other classes for after Update  event
     public void afterInsert(){
    // Commenting out this(updateProduct) method call. It is for the removal of custom Product obj. By ufar, 12-6-22.
	/*    
        oppProductsToUpdate = oppProductTriggerHelper.updateProduct((map<Id,Opp_Product__c>)Trigger.newMap);
	*/
        OpportunityToUpdate = oppProductTriggerHelper.updateProductRankings((map<Id,Opp_Product__c>)Trigger.newMap);
     }
 
     // Process logic/functioanlities in other classes for before Update  event
     public void beforeUpdate(){}
     
     // Process logic/functioanlities in other classes for after Update  event
     public void afterUpdate(){
 
        map<Id, Opp_Product__c> changedMap = new  map<Id, Opp_Product__c>();
        map<Id, Opp_Product__c> changedProdMap = new  map<Id, Opp_Product__c>();
            
        // Look only for products which have changed there Ranking__c
        List<Opp_Product__c> obj = (List<Opp_Product__c>)Trigger.new;
        for(Opp_Product__c n: obj){
            Opp_Product__c o = (Opp_Product__c)Trigger.oldMap.get(n.Id);
            
            // compare new ranking and product in i with old ranking and product from the oldMap.
            // check whether No_Opp_Update__c is not changed. If not, its Opportunity will be updated. 
            // This was created to prevent updating Opportunity after Opportunity was set to Lost.
            
            if(n.No_Opp_Update__c == o.No_Opp_Update__c 
                && (n.Ranking__c != o.Ranking__c || n.Product__c != o.Product__c)){ 
                // updating parent Opportunity 
                changedMap.put(n.Id, n);                
            } 
            if(((n.Product__c != o.Product__c) && n.Product__c != null)){
                changedProdMap.put(n.Id,n);
            }              
            if(n.Calculate_CogsBudget__c){
                changedProdMap.put(n.Id,n);
            }            
        }                 
        if (!changedMap.isEmpty()){
            OpportunityToUpdate = oppProductTriggerHelper.updateProductRankings(changedMap);
        } 
        if (!changedProdMap.isEmpty() && oppProductTriggerHelper.isFirstTime) {
            oppProductTriggerHelper.isFirstTime = false;
    	// Commenting out this(updateProduct) method call. It is for the removal of custom Product obj. By ufar, 12-6-22.
		/* 
            oppProductsToUpdate = oppProductTriggerHelper.updateProduct(changedProdMap);
		*/    
		}
     }
     // Process logic/functioanlities in other classes for before Delete event
     public void beforeDelete(){}    
     
     // Process logic/functioanlities in other classes for after Delete  event
     public void afterDelete(){
         OpportunityToUpdate = oppProductTriggerHelper.updateProductRankings((map<Id,Opp_Product__c>)Trigger.oldMap);
     }
 
     //Finally do operations to Commit
     public void finish(){
         update OpportunityToUpdate;
    // Commenting out this(oppProductsToUpdate) update list. It is for the removal of custom Product obj. By ufar, 12-6-22.
	/* 
         update oppProductsToUpdate;
	*/
     }
}