force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Partner_Role__c/Partner_Role__c.object-meta.xml
<CustomObject>
    <description>Link between two Accounts for a specific Opportunity</description>
    <label>Partner Role</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>P-Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Role__c/fields/Partner_Role__c.field-meta.xml
<CustomField>
    <fullName>Partner_Role__c</fullName>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 Partner Referral (commissions required)</fullName>
            </value>
            <value>
                <fullName>0 Partner Referral (no commissions)</fullName>
            </value>
            <value>
                <fullName>1 Opportunity owner</fullName>
            </value>
            <value>
                <fullName>2 Ref. design / platform dev.</fullName>
            </value>
            <value>
                <fullName>3 Design house</fullName>
            </value>
            <value>
                <fullName>3 ODM (Design and Manufacturing)</fullName>
            </value>
            <value>
                <fullName>3 Local Module Maker</fullName>
            </value>
            <value>
                <fullName>4 Consultant/Advisor</fullName>
            </value>
            <value>
                <fullName>4 Certification partner</fullName>
            </value>
            <value>
                <fullName>4 Technology partner</fullName>
            </value>
            <value>
                <fullName>4 MNO / MVNO</fullName>
            </value>
            <value>
                <fullName>5 Former contract manufacturer</fullName>
            </value>
            <value>
                <fullName>5 Actual contract manufacturer</fullName>
            </value>
            <value>
                <fullName>5 Potential contract manufacturer</fullName>
            </value>
            <value>
                <fullName>6 Sourcing / Negotiation entity</fullName>
            </value>
            <value>
                <fullName>6 Purchasing entity</fullName>
            </value>
            <value>
                <fullName>7 Distributor</fullName>
            </value>
            <value>
                <fullName>8 Sales representative</fullName>
            </value>
            <value>
                <fullName>8 Agent</fullName>
            </value>
            <value>
                <fullName>9 Customer of opp. owner</fullName>
            </value>
            <value>
                <fullName>9 Car brand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloneOppTest.cls
@isTest
public with sharing class CloneOppTest {

    public CloneOppTest() {
        
    }

    @isTest
    static void cloneOpportunityTest(){
        Opportunity opp = new Opportunity();
        Product2 product = new Product2();
        OpportunityContactRole oppContactRole = new OpportunityContactRole();
        Opp_Product__c oppProduct = new Opp_Product__c();
        Partner_Role__c partnerRole = new Partner_Role__c();
        string oppId;
        string productId;

        OpportunityTestDataFactory oppTestFactory = new OpportunityTestDataFactory();
        Product2TestDataFactory productTestFactory = new Product2TestDataFactory();
        PartnerRoleTestDataFactory partnerRoleTestFactory = new PartnerRoleTestDataFactory();
        OppProductTestDataFactory oppProductTestFactory = new OppProductTestDataFactory();
        OpportunityContactRoleTestDataFactory oppContactRoleTestFactory = new OpportunityContactRoleTestDataFactory();

        opp = oppTestFactory.oppForOppProduct();
        product = (Product2)productTestFactory.createRecord();
        oppId = opp.Id;
        productId = product.Id;
        oppContactRole = oppContactRoleTestFactory.createRecord(oppId);
        oppProduct = oppProductTestFactory.createRecord(oppId,productId);
        partnerRole = partnerRoleTestFactory.createRecord(opp);

        string newOppId = CloneOpp.cloneOpportunity(oppId);

    }
}