force-app/main/default/objects/User_File__c/User_File__c.object-meta.xml
<CustomObject>
    <label>User File</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Group__c/User_Group__c.object-meta.xml
<CustomObject>
    <label>User Group</label>
    <nameField>
        <label>User Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Group_Item__c/User_Group_Item__c.object-meta.xml
<CustomObject>
    <label>User Group Item</label>
    <nameField>
        <displayFormat>UGI-{000000}</displayFormat>
        <label>User Group Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Group Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Group_Item__c/fields/User_File__c.field-meta.xml
<CustomField>
    <fullName>User_File__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User File</label>
    <referenceTo>User_File__c</referenceTo>
    <relationshipLabel>User Group Items</relationshipLabel>
    <relationshipName>User_Group_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Group_Item__c/fields/User_Group__c.field-meta.xml
<CustomField>
    <fullName>User_Group__c</fullName>
    <label>User Group</label>
    <referenceTo>User_Group__c</referenceTo>
    <relationshipLabel>User Group Items</relationshipLabel>
    <relationshipName>User_Group_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkTest.cls
@isTest
Class ContentDocumentLinkTest{
     
    @isTest
    static void associateFileToUserGroup()
    {
        User commUser = DocumentLibCommonTest.createCommunityUser();        
        ContentVersion cVer = DocumentLibCommonTest.createTestDocumentVersion();
        //Create UserFile
        User_File__c uFile = DocumentLibCommonTest.createUserFile(commUser.contactId,commUser.Id);
        
        //Create Group
        User_Group__c uGroup = DocumentLibCommonTest.createUserGroup('TestGroup1');        
        User_Group_Item__c uGroupItem = DocumentLibCommonTest.createUserGroupItem(uGroup.Id,commUser.Id);
        
        // Associate document to User Group
        ContentDocument cDoc = DocumentLibCommonTest.getContentDocumentFromContentVersion(cVer.Id);
        DocumentLibCommonTest.createConDocLink(cDoc.id,uGroup.id);
        List<ContentDocumentLink> cdLinkObjList = [select id,ContentDocumentId,LinkedEntityId from ContentDocumentLink where LinkedEntityId =: uFile.id];
        System.assert(cdLinkObjList.size() == 1,'There is an issue associating file using Groups.');
    }
    
    @isTest
    static void associateFileToUserFile()
    {
        User commUser = DocumentLibCommonTest.createCommunityUser();        
        ContentVersion cVer = DocumentLibCommonTest.createTestDocumentVersion();
        //Create UserFile
        User_File__c uFile = DocumentLibCommonTest.createUserFile(commUser.contactId,commUser.Id);
        
        ContentDocument cDoc = DocumentLibCommonTest.getContentDocumentFromContentVersion(cVer.Id);
        
        // Associate document to User Group
        DocumentLibCommonTest.createConDocLink(cDoc.id,uFile.id);
        List<ContentDocumentLink> cdLinkObjList = [select id,ContentDocumentId,LinkedEntityId from ContentDocumentLink where LinkedEntityId =: uFile.id];
        System.assert(cdLinkObjList.size() == 1,'There is an issue associating file to UserFile.');
    }
    
    @isTest
    static void associateFileToUserFileByCommUser()
    {
        User commUser = DocumentLibCommonTest.createCommunityUser();        
        
        //Create UserFile
        User_File__c uFile = DocumentLibCommonTest.createUserFile(commUser.contactId,commUser.Id);
        
        System.runAs(commUser) {
            ContentVersion cVer = DocumentLibCommonTest.createTestDocumentVersionInComm(commUser.Id);
            
            ContentDocument cDoc = DocumentLibCommonTest.getContentDocumentFromContentVersion(cVer.Id);
            
            // Associate document to UserFile
            
            // try catch is used as this always give validation error
            try{
                DocumentLibCommonTest.createConDocLink(cDoc.id,uFile.id);
            }catch(Exception ex){}
        }
        List<ContentDocumentLink> cdLinkObjList = [select id,ContentDocumentId,LinkedEntityId from ContentDocumentLink where LinkedEntityId =: uFile.id];
        System.assert(cdLinkObjList.size() == 0,'There is an issue associating file to UserFile.');
    }
    
    @isTest
    static void removeFileAssociatedToUserFile()
    {
        User commUser = DocumentLibCommonTest.createCommunityUser();        
        ContentVersion cVer = DocumentLibCommonTest.createTestDocumentVersion();
        //Create UserFile
        User_File__c uFile = DocumentLibCommonTest.createUserFile(commUser.contactId,commUser.Id);
        
        //Create Group
        User_Group__c uGroup = DocumentLibCommonTest.createUserGroup('TestGroup1');        
        User_Group_Item__c uGroupItem = DocumentLibCommonTest.createUserGroupItem(uGroup.Id,commUser.Id);
        
        // Associate document to UserFile
        ContentDocument cDoc = DocumentLibCommonTest.getContentDocumentFromContentVersion(cVer.Id);
        ContentDocumentLink cdl = DocumentLibCommonTest.createConDocLink(cDoc.id,uFile.id);
        
        delete cdl;
        
        List<ContentDocumentLink> cdLinkObjList = [select id,ContentDocumentId,LinkedEntityId from ContentDocumentLink where LinkedEntityId =: uFile.id];
        System.assert(cdLinkObjList.size() == 0,'There is an issue deleting file from UserFile.');
    }
    
    @isTest
    static void removeFileAssociatedToUserFileWithGroup()
    {
        User commUser = DocumentLibCommonTest.createCommunityUser();        
        ContentVersion cVer = DocumentLibCommonTest.createTestDocumentVersion();
        //Create UserFile
        User_File__c uFile = DocumentLibCommonTest.createUserFile(commUser.contactId,commUser.Id);
        
        //Create Group
        User_Group__c uGroup = DocumentLibCommonTest.createUserGroup('TestGroup1');        
        User_Group_Item__c uGroupItem = DocumentLibCommonTest.createUserGroupItem(uGroup.Id,commUser.Id);
        
        ContentDocument cDoc = DocumentLibCommonTest.getContentDocumentFromContentVersion(cVer.Id);
        
        // Associate document to UserFile
        ContentDocumentLink cdl = DocumentLibCommonTest.createConDocLink(cDoc.id,uFile.id);
        ContentDocumentLink cdlGroup = DocumentLibCommonTest.createConDocLink(cDoc.id,uGroup.id);
        // try catch is used as this always give validation error
        try{
            delete cdl;
        }catch(Exception ex){}
        List<ContentDocumentLink> cdLinkObjList = [select id,ContentDocumentId,LinkedEntityId from ContentDocumentLink where LinkedEntityId =: uFile.id];
        System.assert(cdLinkObjList.size() == 1,'There is an issue deleting file from UserFile.');
    }
    @isTest
    public static void callTriggerHandler()
    {
        ContentDocumentLinkTriggerHandler cHandler = new ContentDocumentLinkTriggerHandler();
        cHandler.beforeUpdate();
        cHandler.afterDelete();
        cHandler.afterUpdate();
        cHandler.finish();
        
    }
}