force-app/main/default/objects/Account/recordTypes/Legal.recordType-meta.xml
<RecordType>
    <fullName>Legal</fullName>
    <active>true</active>
    <description>Used exclusively for Accounts handled by Legal</description>
    <label>Legal</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Applicability__c.field-meta.xml
<CustomField>
    <fullName>Applicability__c</fullName>
    <description>Defines whether contract applies on local of group level</description>
    <inlineHelpText>Defines whether contract applies on local of group level</inlineHelpText>
    <label>Applicability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Category__c.field-meta.xml
<CustomField>
    <fullName>Contract_Category__c</fullName>
    <description>Classifies Contract by type of agreement</description>
    <label>Contract Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2022 NCNR agreement</fullName>
            </value>
            <value>
                <fullName>Agency Agreement</fullName>
            </value>
            <value>
                <fullName>Branding Agreement</fullName>
            </value>
            <value>
                <fullName>Commission Agreement</fullName>
            </value>
            <value>
                <fullName>Distribution Agreement</fullName>
            </value>
            <value>
                <fullName>End Use Statement</fullName>
            </value>
            <value>
                <fullName>License Agreement</fullName>
            </value>
            <value>
                <fullName>MoU, LoI, MoA</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>PRA</fullName>
            </value>
            <value>
                <fullName>Quality Agreement</fullName>
            </value>
            <value>
                <fullName>Reseller Agreement</fullName>
            </value>
            <value>
                <fullName>RIL Software Agreement</fullName>
            </value>
            <value>
                <fullName>Risk Waiver Agreement</fullName>
            </value>
            <value>
                <fullName>Sales Agreement</fullName>
            </value>
            <value>
                <fullName>Service Agreement</fullName>
            </value>
            <value>
                <fullName>Special Agreement</fullName>
            </value>
            <value>
                <fullName>Design Partner Program Agreement</fullName>
            </value>
            <value>
                <fullName>Solution Partner Program Agreement</fullName>
            </value>
            <value>
                <fullName>Service Referral Commission Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Survival_Period_Years__c.field-meta.xml
<CustomField>
    <fullName>Contract_Survival_Period_Years__c</fullName>
    <description>Duration the confidentiality of NDA&apos;s</description>
    <label>Confidentiality Survival Period (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Source Case from that the Contract has been created. Used for e-NDA (web-to-case).</description>
    <inlineHelpText>Source Case from that the Contract has been created. Used for e-NDA (web-to-case).</inlineHelpText>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/u_blox_Entity__c.field-meta.xml
<CustomField>
    <fullName>u_blox_Entity__c</fullName>
    <description>Defines for what u-blox entity have contract entered</description>
    <label>u-blox Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox AG</fullName>
            </value>
            <value>
                <fullName>u-blox America Inc.</fullName>
            </value>
            <value>
                <fullName>u-blox Italy SpA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewContractCtrl.cls
global with sharing class NewContractCtrl {

    public NewContractCtrl(ApexPages.StandardController controller) {

    }

    @RemoteAction
    global static Boolean execute(String CaseId){

        if(CaseId==null) return false;
        
        Case cl = [SELECT Id, AccountId, Account.Name, Account.OwnerId, Account.Owner.Profile.Name, CreatedDate, Type FROM Case WHERE Id =: CaseId];
        
        String AccountName = cl.Account.Name;
                
        if (AccountName.length() > 64) {
          AccountName = AccountName.substring(0,64);
        }
        String ContractOwnerProfile = cl.Account.Owner.Profile.Name;
        String ContractOwnerId = cl.Account.OwnerId;
        
        List<String> profilesToRestrict = CommonUtils.getRestrictedProfilesForContract();
        Set<String> restrictedProfiles = new Set<String>();
        
        restrictedProfiles.addAll(profilesToRestrict);
        if (restrictedProfiles.contains(ContractOwnerProfile)) {
            ContractOwnerId = UserInfo.getUserId();
        }
        
        
        String CaseCreatedDate = string.valueOf(cl.CreatedDate);
        String CaseType = cl.Type;
        String ContractName = '';
        
        Contract c = new Contract();
            
        if (CaseType == 'Legal (e-NDA)') {
          ContractName  = AccountName + ' - NDA - ' + CaseCreatedDate.substring(0, 4);
          c.Contract_Category__c = 'NDA';
          c.u_blox_Entity__c = 'u-blox AG';
        } else if (CaseType == 'Legal (e-NDA Americas)') {
          ContractName  = AccountName + ' - NDA - ' + CaseCreatedDate.substring(0, 4);
          c.Contract_Category__c = 'NDA';
          c.u_blox_Entity__c = 'u-blox America Inc.';
        } else if (CaseType == 'Legal (e-LULA-M)') {
          ContractName  = AccountName + ' - LULA-M - ' + CaseCreatedDate.substring(0, 4);
          c.Contract_Category__c = 'License Agreement';
          c.u_blox_Entity__c = 'u-blox AG';
        } else if (CaseType == 'Legal (e-LULA-N)') {
          ContractName  = AccountName + ' - LULA-N - ' + CaseCreatedDate.substring(0, 4);
          c.Contract_Category__c = 'License Agreement';
          c.u_blox_Entity__c = 'u-blox AG';
        }else if(CaseType == 'End Use Statement'){
          ContractName  = AccountName + ' - EUS - ' + CaseCreatedDate.substring(0, 4);
          c.Contract_Category__c = 'End Use Statement';
          c.u_blox_Entity__c = 'u-blox AG';
        }
        
        c.Name = ContractName;
        c.OwnerId = ContractOwnerId;
        c.AccountId = cl.AccountId; 
        c.Applicability__c = 'Group';
        c.StartDate = cl.CreatedDate.date();
        c.Contract_Survival_Period_Years__c = 5;
        c.Related_Case__c = CaseId;
        
        insert c;
        return true;
    }
}