force-app/main/default/objects/Case_Assignment_Settings__mdt/Case_Assignment_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Email Case Assignment Setting</label>
    <pluralLabel>Case Assignment Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Assignment_Settings__mdt/fields/FAE_Email__c.field-meta.xml
<CustomField>
    <fullName>FAE_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>FAE Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Assignment_Settings__mdt/fields/FAE_User_Id__c.field-meta.xml
<CustomField>
    <fullName>FAE_User_Id__c</fullName>
    <label>FAE User Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailToCaseAssignment.cls
public class EmailToCaseAssignment {
    
    @InvocableMethod
    public static void AssignCaseToFAEOfSuppliedEmail(list<Id> caseIds){       
        map<string, Id> FAEEmailToIdMap = new map<string, Id>();
        list<Case> assignCasesToFAE = new list<Case>();
        string emailAdress;
        
        for(Case_Assignment_Settings__mdt setting : [Select FAE_Email__c, 
                                                        FAE_User_Id__c 
                                                        from Case_Assignment_Settings__mdt]){
            FAEEmailToIdMap.put(setting.FAE_Email__c, setting.FAE_User_Id__c);                                                    
        }
        
        for(Case c : [Select Id, OwnerId, SuppliedEmail,Contact.Email from Case where Id IN:caseIds]){            
            emailAdress = c.SuppliedEmail == null ? c.Contact.Email : c.SuppliedEmail;
            
            if(FAEEmailToIdMap.get(emailAdress) != null){
                assignCasesToFAE.add(new Case(
                    Id = c.Id,
                    OwnerId = FAEEmailToIdMap.get(emailAdress)                    
                ));
            }
        }
        
        if(assignCasesToFAE.size() > 0){
            database.update(assignCasesToFAE, false);
        }        
    }
}