force-app/main/default/objects/Product2/fields/Abacus_Konditionsnummer_101__c.field-meta.xml
<CustomField>
    <fullName>Abacus_Konditionsnummer_101__c</fullName>
    <label>Abacus Konditionsnummer 101</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Abacus_Konditionsnummer_102__c.field-meta.xml
<CustomField>
    <fullName>Abacus_Konditionsnummer_102__c</fullName>
    <label>Abacus Konditionsnummer 102</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Abacus_Konditionsnummer_103__c.field-meta.xml
<CustomField>
    <fullName>Abacus_Konditionsnummer_103__c</fullName>
    <label>Abacus Konditionsnummer 103</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MAP_pricing__c.field-meta.xml
<CustomField>
    <fullName>MAP_pricing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if this product should be part of the MAP Export</description>
    <inlineHelpText>Check if this product should be part of the MAP Export</inlineHelpText>
    <label>MAP Pricing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/max_MAP_pricing__c.field-meta.xml
<CustomField>
    <fullName>max_MAP_pricing__c</fullName>
    <description>The maximum amount of units to include in the Abacus pricelist export</description>
    <inlineHelpText>The maximum amount of units to include in the Abacus pricelist export</inlineHelpText>
    <label>Max MAP Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>250</fullName>
            </value>
            <value>
                <fullName>500</fullName>
            </value>
            <value>
                <fullName>1000</fullName>
            </value>
            <value>
                <fullName>2500</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductPricesUpdateProductTest.cls
@isTest
public class ProductPricesUpdateProductTest {

	// updateProducts should update the testProduct
	@isTest static void testUpdateProducts1() { 
 		Product2 testProduct = ProductPricesTestDataFactory.createProduct()[0];
        
     	ProductPricesUpdateProduct a = new ProductPricesUpdateProduct();
        a.updateProducts();
        
        Product2 updatedTestProduct = ProductPricesAbacusCtrl.getProductByProductId(testProduct.id);
        System.assertNotEquals(null, updatedTestProduct); 

        System.assertEquals(3115, updatedTestProduct.Abacus_Konditionsnummer_101__c);
        System.assertEquals(3035, updatedTestProduct.Abacus_Konditionsnummer_102__c);
        System.assertEquals(3195, updatedTestProduct.Abacus_Konditionsnummer_103__c);
	}
    
    // updateProductsSetMapPricingField should update the testProduct
	@isTest static void testUpdateProductsSetMapPricingField() {
        //Init
 		Product2 testProduct = ProductPricesTestDataFactory.createProductMapPricingFalse()[0];
        ProductPricesTestDataFactory.createProductPrice();
        
        //check before
        System.assertEquals(FALSE, testProduct.MAP_pricing__c);
        
        // run update 
     	ProductPricesUpdateProduct a = new ProductPricesUpdateProduct();
        a.updateProductsSetMapPricingFieldStartEnd(0,200);
        
        // Check after
        Product2 updatedTestProduct = ProductPricesAbacusCtrl.getProductByProductId(testProduct.id);
        System.assertNotEquals(null, updatedTestProduct); 

        System.assertEquals(TRUE, updatedTestProduct.MAP_pricing__c);
	}
    
    // updateProductsSetMapPricingField should update the testProduct
	@isTest static void testUpdateProductsSetMapPricingField2() {
        //Init
 		List<Product2> testProducts = ProductPricesTestDataFactory.createProductsWithMapPricingFalseWithoutMaxMapPricing();
        ProductPricesTestDataFactory.createProductPricesMax();
        
        //check before
        for (Product2 currentProduct :testProducts) 
        {
            System.assertEquals(FALSE, currentProduct.MAP_pricing__c);
            System.assertEquals(null, currentProduct.max_MAP_pricing__c);
        }
        
        // run update 
     	ProductPricesUpdateProduct a = new ProductPricesUpdateProduct();
        a.updateProductsSetMapPricingFieldStartEnd(0,200);
        
        // Check after
 		for (Product2 currentProduct :testProducts) 
        {        
            Product2 updatedTestProduct = ProductPricesAbacusCtrl.getProductByProductId(currentProduct.id);
            System.assertNotEquals(null, updatedTestProduct); 
    
            System.assertEquals(TRUE, updatedTestProduct.MAP_pricing__c);
            //System.assertNotEquals(null, updatedTestProduct.max_MAP_pricing__c);
        }
        System.assertEquals(5, testProducts.size());
	}
    
}