force-app/main/default/objects/Product2/fields/Automotive_Product__c.field-meta.xml
<CustomField>
    <fullName>Automotive_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Forecast for automotive products made based on type no</inlineHelpText>
    <label>Automotive Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tashang</fullName>
            </value>
            <value>
                <fullName>u-blox</fullName>
                <default>true</default>
                <label>u-blox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ES_Under_Allocation__c.field-meta.xml
<CustomField>
    <fullName>ES_Under_Allocation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag set until product reach IP or if enough ES available (e.g. in case IP delayed)</description>
    <inlineHelpText>Flag set until product reach IP or if enough ES available (e.g. in case IP delayed)</inlineHelpText>
    <label>ES Under Allocation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/FOTA__c.field-meta.xml
<CustomField>
    <fullName>FOTA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(From Abacus)</description>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>FOTA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/From_Abacus__c.field-meta.xml
<CustomField>
    <fullName>From_Abacus__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>From Abacus</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Checked__c.field-meta.xml
<CustomField>
    <fullName>IPR_Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be checked by Product Owner once confirmed that IPR Class and IPR Cost fields are correct.</description>
    <inlineHelpText>To be checked by Product Owner once confirmed that IPR Class and IPR Cost fields are correct.</inlineHelpText>
    <label>IPR Checked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Technology_Changed__c.field-meta.xml
<CustomField>
    <fullName>IPR_Technology_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag when IPR Technology picklist changed to update IPR cost fields (trigger the workflow)</description>
    <inlineHelpText>Flag when IPR Technology picklist changed to update IPR cost fields (trigger the workflow)</inlineHelpText>
    <label>IPR Technology Changed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MEID__c.field-meta.xml
<CustomField>
    <fullName>MEID__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(From Abacus)</description>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>MEID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MFi_License_Required__c.field-meta.xml
<CustomField>
    <fullName>MFi_License_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Product requiring MFi License., can be ordered only by &quot;MFi Licensee&quot; Account</description>
    <inlineHelpText>Product requiring MFi License., can be ordered only by &quot;MFi Licensee&quot; Account</inlineHelpText>
    <label>MFi License Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/RoT__c.field-meta.xml
<CustomField>
    <fullName>RoT__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is maintained in Abacus</description>
    <inlineHelpText>(From Abacus) Checked if the product contains a secure Root Of Trust</inlineHelpText>
    <label>RoT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Shop_Active__c.field-meta.xml
<CustomField>
    <fullName>Shop_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Inported from Abacus (inverted &quot;Inaktiv&quot; in Produktstamm)</description>
    <inlineHelpText>(From Abacus) Activated for Online Shop. The product may not be visible (e.g. only visible in Americas or not placed in any locations).</inlineHelpText>
    <label>Shop Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Time_Based_WF_Flag__c.field-meta.xml
<CustomField>
    <fullName>Time_Based_WF_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used only to &quot;touch&quot; record to put it in the time-based WF queue.</description>
    <inlineHelpText>Used only to &quot;touch&quot; record to put it in the time-based WF queue.</inlineHelpText>
    <label>Time-Based WF Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Use_Abacus_Cost__c.field-meta.xml
<CustomField>
    <fullName>Use_Abacus_Cost__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checked, use the cost from Abacus to calculate the contribution.</inlineHelpText>
    <label>Use Abacus Cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Visible_In_Masterschedule__c.field-meta.xml
<CustomField>
    <fullName>Visible_In_Masterschedule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if the product needs to be visible in Masterschedule dashboard and report</description>
    <inlineHelpText>Check if the product needs to be visible in Masterschedule dashboard and report</inlineHelpText>
    <label>Visible In Masterschedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Visible_To_Partner__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the product will be included in the Masterschedule visible to the partner.</description>
    <inlineHelpText>When checked, the product will be included in the Masterschedule visible to the partner.</inlineHelpText>
    <label>Visible To Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProductObjectTriggerHandlerTest.cls
@isTest
public class ProductObjectTriggerHandlerTest {
	@isTest
    public static  void insertCustomProductTest(){
        
        Map<Id,Product2> prodMap = new Map<Id,Product2>();
        Product2 prod1 = new Product2(Name='testProd1', Type_No__c='testTypeNum1',
                                      Product_Center__C='Positioning',
                                      Automotive_Product__c = true,
                                      ES_Under_Allocation__c = true,
                                      FOTA__c = false,
                                      ProductCode = '123',
                                      Description = 'test description',
                                      IsActive = true,
                                      From_Abacus__c =true,
                                      IPR_Checked__c = false,
                                      IPR_Technology_Changed__c = true,
                                      MEID__c =false,
                                      RoT__c = false,
                                      Shop_Active__c = false,
                                      Time_Based_WF_Flag__c = true,
                                      Use_Abacus_Cost__c = true,
                                      Visible_In_Masterschedule__c	= false,
                                      Visible_To_Partner__c = true,
                                      MFi_License_Required__c = false,
                                      BusinessUnit__c ='Tashang');  
        insert prod1;
        prodMap.put(prod1.id,prod1);
        
        product2 prod2 = new product2();
        prod2 = prod1.clone(false,true);
        prod2.Type_No__c = 'testTypeNum12';
        prod2.Product_Center__C = 'Short Range';
        List<product2> prodList = new List<Product2>();
        prodList.add(prod2);
        insert prodList;
        
        Test.startTest();
        ProductObjectTriggerHandler.checkProductClone(prodList);
    // Commenting out this(updateProduct) method. It is for the removal of custom Product obj. By ufar, 12-6-22.
	/*  
        BeforeUpdateAbacusProduct.upsertCustomProduct(prodMap);
	*/
        system.assertEquals(2, [select count() from Product2 ]) ;
        Test.stopTest();
        
    }
    
    public static testmethod void testCustomProductTest(){
        List<Product2> oldlistProduct=new List<Product2>();
        List<Product2> newlistProduct=new List<Product2>();
        
        oldlistProduct.add(new Product2(Name='Test123', Type_No__c='type', From_Abacus__c = true));
      
        
        newlistProduct.add(new Product2(Name='Test', Type_No__c='type123', From_Abacus__c = true));
        
        //update oldListProduct;
        system.debug('oldListProduct: '+oldListProduct);
        system.debug('newlistProduct: '+newlistProduct);
        
        User u = TestUtils.createUserWithProfile('LName','Partner Base Quotation');
        test.startTest();
        
        system.runAs(u){
            insert oldListProduct;
              oldListProduct[0].Name = 'update Name';
            
                oldListProduct[0].ProductCode = 'update Product';
            //oldListProduct.
            
            try{
                update oldListProduct;
            }        
            catch (exception ex){
                system.debug('ex Test: '+ex);
                Boolean expectedExceptionThrown =  ex.getMessage().contains('Product linked to Abacus. Name, Ordering No, Type No, Status, and Product Text are not modifiable.') ? true : false;
			System.assertEquals(expectedExceptionThrown, true);
            }
        }
        test.stopTest();        
        system.debug('User id-->>' + u);
    }
    
    public static testmethod void testcheckProductClone(){
        
    }
        
       
}