force-app/main/default/objects/Product2/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tashang</fullName>
            </value>
            <value>
                <fullName>u-blox</fullName>
                <default>true</default>
                <label>u-blox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/From_Abacus__c.field-meta.xml
<CustomField>
    <fullName>From_Abacus__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>From Abacus</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <inlineHelpText>(From Abacus) To be maintained here in Salesforce if not Linked to Abacus. NOTE: Considered and In Definition are not in Abacus.</inlineHelpText>
    <label>Product Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Considered</fullName>
            </value>
            <value>
                <fullName>In Definition</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
                <default>true</default>
                <label>In Development</label>
            </value>
            <value>
                <fullName>Prototypes</fullName>
            </value>
            <value>
                <fullName>Engineering Samples</fullName>
            </value>
            <value>
                <fullName>Production Ready</fullName>
            </value>
            <value>
                <fullName>Initial Production</fullName>
            </value>
            <value>
                <fullName>Mass Production</fullName>
            </value>
            <value>
                <fullName>End of Life</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Text_1__c.field-meta.xml
<CustomField>
    <fullName>Product_Text_1__c</fullName>
    <description>First line of Abacus product description</description>
    <inlineHelpText>(From Abacus) First line of Abacus product description</inlineHelpText>
    <label>Product Text 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Text_2__c.field-meta.xml
<CustomField>
    <fullName>Product_Text_2__c</fullName>
    <description>Second line of Abacus product description</description>
    <inlineHelpText>(From Abacus) Second line of Abacus product description</inlineHelpText>
    <label>Product Text 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tashang</fullName>
            </value>
            <value>
                <fullName>u-blox</fullName>
                <default>true</default>
                <label>u-blox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/From_Abacus__c.field-meta.xml
<CustomField>
    <fullName>From_Abacus__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>From Abacus</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALEX</fullName>
            </value>
            <value>
                <fullName>AMY</fullName>
            </value>
            <value>
                <fullName>ANN</fullName>
            </value>
            <value>
                <fullName>ANNA</fullName>
            </value>
            <value>
                <fullName>Blueprint</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>Boxed</fullName>
            </value>
            <value>
                <fullName>CAM</fullName>
            </value>
            <value>
                <fullName>CB15x22</fullName>
            </value>
            <value>
                <fullName>CB16x36</fullName>
            </value>
            <value>
                <fullName>CB23x36</fullName>
            </value>
            <value>
                <fullName>ELIN</fullName>
            </value>
            <value>
                <fullName>ELLA</fullName>
            </value>
            <value>
                <fullName>EMMY</fullName>
            </value>
            <value>
                <fullName>EVA</fullName>
            </value>
            <value>
                <fullName>Eval Kit</fullName>
            </value>
            <value>
                <fullName>FW75</fullName>
            </value>
            <value>
                <fullName>IC</fullName>
            </value>
            <value>
                <fullName>JODY</fullName>
            </value>
            <value>
                <fullName>LARA</fullName>
            </value>
            <value>
                <fullName>LCC09096</fullName>
            </value>
            <value>
                <fullName>LCC1316</fullName>
            </value>
            <value>
                <fullName>LCC1618</fullName>
            </value>
            <value>
                <fullName>LCC2626</fullName>
            </value>
            <value>
                <fullName>LEA</fullName>
            </value>
            <value>
                <fullName>LEON</fullName>
            </value>
            <value>
                <fullName>LILY</fullName>
            </value>
            <value>
                <fullName>LISA</fullName>
            </value>
            <value>
                <fullName>LUCY</fullName>
            </value>
            <value>
                <fullName>LUKA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <label>Product Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Considered</fullName>
            </value>
            <value>
                <fullName>In Definition</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>Prototypes</fullName>
            </value>
            <value>
                <fullName>Engineering Samples</fullName>
            </value>
            <value>
                <fullName>Production Ready</fullName>
            </value>
            <value>
                <fullName>Initial Production</fullName>
            </value>
            <value>
                <fullName>Mass Production</fullName>
            </value>
            <value>
                <fullName>End of Life</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Text_1__c.field-meta.xml
<CustomField>
    <fullName>Product_Text_1__c</fullName>
    <description>First line of Abacus product description</description>
    <inlineHelpText>(From Abacus) First line of Abacus product description</inlineHelpText>
    <label>Product Text 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Text_2__c.field-meta.xml
<CustomField>
    <fullName>Product_Text_2__c</fullName>
    <description>Second line of Abacus product description</description>
    <inlineHelpText>(From Abacus) Second line of Abacus product description</inlineHelpText>
    <label>Product Text 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Referred_Product__c.field-meta.xml
<CustomField>
    <fullName>Referred_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Product)</relationshipLabel>
    <relationshipName>Products3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProductObjectTriggerHandler.cls
public class ProductObjectTriggerHandler {
    public static final String ERROR_MESSAGE = 'Product linked to Abacus. Name, Ordering No, Type No, Status, and Product Text are not modifiable.';
    
    public static void preventUpdateAbacusProduct(map<Id, Product2> ProdMap){
        for(product2  newProd : ProdMap.values()){
            product2 oldProd = (product2) trigger.oldMap.get(newProd.Id);
            if(newProd.From_Abacus__c){
                
                if(newProd.Name!=oldProd.Name){
                    newProd.Name.addError(ERROR_MESSAGE);
                }
                if(newProd.ProductCode!=oldProd.ProductCode){
                    newProd.ProductCode.addError(ERROR_MESSAGE);
                }
                if(newProd.Type_No__c!=oldProd.Type_No__c){
                    newProd.Type_No__c.addError(ERROR_MESSAGE);
                }
                if(newProd.Product_Status__c!=oldProd.Product_Status__c){
                    newProd.Product_Status__c.addError(ERROR_MESSAGE);
                }
                if(newProd.Product_Text_1__c!=oldProd.Product_Text_1__c){
                    newProd.Product_Text_1__c.addError(ERROR_MESSAGE);
                }
                if(newProd.Product_Text_2__c!=oldProd.Product_Text_2__c){
                    newProd.Product_Text_2__c.addError(ERROR_MESSAGE);
                }
            }
        }
    }
    
    // Commenting out this(upsertCustomProduct) method. It is for the removal of custom Product obj. By ufar, 12-6-22.
    /*
    public static List<product__c> upsertCustomProduct(Map<Id,product2> standardProdMap){
        
        //Retrieve All the Fields from the Product Object
        Schema.DescribeSObjectResult prodFields =   Product2.sObjectType.getDescribe();
        Map<String, Schema.SObjectField> prodFieldsMap =   prodFields.fields.getMap();
        
        //Retrieve All the Fields from Product__c Object
        Schema.DescribeSObjectResult cprodFields =   Product__c.sObjectType.getDescribe();
        Map<String, Schema.SObjectField> cprodFieldsMap =   cprodFields.fields.getMap();
        
        List<Product__c> prodList = new List<Product__c>(); // To add the products in Custom Product
        List<Product__c> cProdList = new List<Product__c> ();
        
        List<string> cProdFieldList = new List<string>();
        List<string> prodFieldsList = new List<string>(); // To retrieve all the fields
        
        //Update Changes
        Map<Id,Id> updateCustomProduct = new Map<Id,Id>();
        
        if(!standardProdMap.isEmpty()){
            cProdList = [select Id, Referred_Product__c from Product__c where Id != ''  AND Referred_Product__c =: standardProdMap.keySet() ];
        }
        
        for(Schema.SObjectField checkFieldType : cprodFieldsMap.values()){
            if(!cprodFieldsMap.get(string.valueof(checkFieldType)).getDescribe().isCalculated()){
                cProdFieldList.add(string.valueOf(checkFieldType).toLowerCase());
            }
        }
        
        if(!cProdList.isEmpty()){
            for(Product__c cProd:cProdList){
                updateCustomProduct.put(cProd.Referred_Product__c,cProd.Id);  
            }
        }
        
        for(Schema.SObjectField checkFieldType : prodFieldsMap.values()){
            if(!prodFieldsMap.get(string.valueof(checkFieldType)).getDescribe().isCalculated()){
                prodFieldsList.add((string.valueOf(checkFieldType)).toLowerCase());                    
            }            
        }
        for(Product2 prod:standardProdMap.values()){
            if(prod.BusinessUnit__c == 'Tashang'){
                Product__c prodClone = new Product__c();
                
                for(String fieldNames : prodFieldsList){
                    if(  cProdFieldList.contains(fieldNames.toLowerCase())   ){
                        
                        if(fieldNames.contains('__c')){
                            prodClone.put(fieldNames,prod.get(fieldNames));
                            
                        }else{
                            if(fieldNames == 'ProductCode'){
                                prodClone.put('ProductCode__c',prod.ProductCode);
                            }else if(fieldNames == 'CurrencyIsoCode' ){
                                prodClone.put('CurrencyIsoCode',prod.CurrencyIsoCode);
                            }else if(fieldNames == 'Description'){
                                prodClone.put('Product_Description__c',prod.Description);
                            }else if(fieldNames == 'Family'){
                                prodClone.put('Product_Family__c',prod.Family);
                            }else if(fieldNames == 'Name'){
                                prodClone.put('Name',prod.Name);
                            }else if(fieldNames == 'IsActive'){
                                prodClone.put('IsActive__c',prod.IsActive);
                            }else if(updateCustomProduct.containsKey(prod.Id)){
                                prodClone.Id = updateCustomProduct.get(prod.Id);
                            }
                        }
                        prodClone.Referred_Product__c = prod.Id;
                    }
                }
                prodList.add(prodClone);
            }
        }        
        return prodList;
    }
	
	*/

    //Function check if the product is being clone from existing product record or being newly created.
    @InvocableMethod(Label = 'Product2: After Created/Updated')
    public static List<Boolean> checkProductClone(list<product2> prodRecords){
        List<Boolean> isCloned = new List<Boolean>();
        for(Product2 tempProd : prodRecords){
            if(!String.isEmpty(tempProd.getCloneSourceId()) ){
                isCloned.add(true);
            }
        }
        return isCloned;
    }
}