force-app/main/default/objects/Product2/fields/Cellular_Technology__c.field-meta.xml
<CustomField>
    <fullName>Cellular_Technology__c</fullName>
    <inlineHelpText>Select the most advanced technology supported by the product</inlineHelpText>
    <label>Cellular Technology</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GPRS</fullName>
            </value>
            <value>
                <fullName>EDGE</fullName>
            </value>
            <value>
                <fullName>HSDPA</fullName>
            </value>
            <value>
                <fullName>HSUPA</fullName>
            </value>
            <value>
                <fullName>HSPA+</fullName>
            </value>
            <value>
                <fullName>CDMA 1xRTT</fullName>
            </value>
            <value>
                <fullName>CDMA EV-DO</fullName>
            </value>
            <value>
                <fullName>LTE-only</fullName>
            </value>
            <value>
                <fullName>LTE-multi</fullName>
            </value>
            <value>
                <fullName>CIoT</fullName>
            </value>
            <value>
                <fullName>RPMA</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
                <default>true</default>
                <label>Not applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comment on update of product schedule.</description>
    <inlineHelpText>Comment on update of product schedule.</inlineHelpText>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Comment_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>Comment_Updated_Date__c</fullName>
    <label>Comment Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Checked__c.field-meta.xml
<CustomField>
    <fullName>IPR_Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be checked by Product Owner once confirmed that IPR Class and IPR Cost fields are correct.</description>
    <inlineHelpText>To be checked by Product Owner once confirmed that IPR Class and IPR Cost fields are correct.</inlineHelpText>
    <label>IPR Checked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Checked_Date__c.field-meta.xml
<CustomField>
    <fullName>IPR_Checked_Date__c</fullName>
    <description>Date when IPR Checked has been checked (automatically updated).</description>
    <inlineHelpText>Date when IPR Checked has been checked (automatically updated).</inlineHelpText>
    <label>IPR Checked Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Cost__c.field-meta.xml
<CustomField>
    <fullName>IPR_Cost__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>IPR cost in detail, used to update IPR USD xxx and IPR Pct xxx fields. Populated when IPR Technology picklist field is changed (using Process and Workflow)</description>
    <inlineHelpText>IPR cost in detail, used to update IPR USD xxx and IPR Pct xxx fields. Populated when IPR Technology picklist field is changed</inlineHelpText>
    <label>IPR Cost</label>
    <referenceTo>IPR_Cost__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Technology__c.field-meta.xml
<CustomField>
    <fullName>IPR_Technology__c</fullName>
    <inlineHelpText>Technology related to Cellular Technology</inlineHelpText>
    <label>IPR Technology</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cellular_Technology__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>EV-DO</fullName>
            </value>
            <value>
                <fullName>1xRTT</fullName>
            </value>
            <value>
                <fullName>GSM</fullName>
            </value>
            <value>
                <fullName>Rel 5/6</fullName>
            </value>
            <value>
                <fullName>Rel 7+</fullName>
            </value>
            <value>
                <fullName>Rel 9&amp;10 single</fullName>
            </value>
            <value>
                <fullName>Rel 9&amp;10 multi</fullName>
            </value>
            <value>
                <fullName>Cat 1 single-mode</fullName>
            </value>
            <value>
                <fullName>Cat 1 multi-mode</fullName>
            </value>
            <value>
                <fullName>Cat 1 multi-mode NO 3G</fullName>
            </value>
            <value>
                <fullName>Cat 3 single-mode</fullName>
            </value>
            <value>
                <fullName>Cat 3 multi-mode</fullName>
            </value>
            <value>
                <fullName>Cat 4 single-mode</fullName>
            </value>
            <value>
                <fullName>Cat 4 multi-mode</fullName>
            </value>
            <value>
                <fullName>Cat 6 single-mode</fullName>
            </value>
            <value>
                <fullName>Cat 6 multi-mode</fullName>
            </value>
            <value>
                <fullName>Cat M single-mode</fullName>
            </value>
            <value>
                <fullName>Cat M multi-mode</fullName>
            </value>
            <value>
                <fullName>Cat M multi-mode NO 3G</fullName>
            </value>
            <value>
                <fullName>NB-IoT</fullName>
            </value>
            <value>
                <fullName>NB-IoT CN</fullName>
            </value>
            <value>
                <fullName>RPMA</fullName>
            </value>
            <value>
                <fullName>not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Technology_Changed__c.field-meta.xml
<CustomField>
    <fullName>IPR_Technology_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag when IPR Technology picklist changed to update IPR cost fields (trigger the workflow)</description>
    <inlineHelpText>Flag when IPR Technology picklist changed to update IPR cost fields (trigger the workflow)</inlineHelpText>
    <label>IPR Technology Changed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F10</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M10</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
                <color>#B6E32E</color>
                <label>u-blox M9</label>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
                <color>#000099</color>
                <label>u-blox M8</label>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
                <color>#0B6FCE</color>
                <label>u-blox 7</label>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
                <color>#33CCFF</color>
                <label>u-blox 6</label>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
                <color>#6600CC</color>
                <label>u-blox 5</label>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
                <color>#CC66CC</color>
                <label>ANTARIS 4</label>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
                <color>#FF99FF</color>
                <label>Various</label>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
                <color>#999999</color>
                <default>true</default>
                <label>Not applicable</label>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <inlineHelpText>(From Abacus) To be maintained here in Salesforce if not Linked to Abacus. NOTE: Considered and In Definition are not in Abacus.</inlineHelpText>
    <label>Product Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Considered</fullName>
            </value>
            <value>
                <fullName>In Definition</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
                <default>true</default>
                <label>In Development</label>
            </value>
            <value>
                <fullName>Prototypes</fullName>
            </value>
            <value>
                <fullName>Engineering Samples</fullName>
            </value>
            <value>
                <fullName>Production Ready</fullName>
            </value>
            <value>
                <fullName>Initial Production</fullName>
            </value>
            <value>
                <fullName>Mass Production</fullName>
            </value>
            <value>
                <fullName>End of Life</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Text_1__c.field-meta.xml
<CustomField>
    <fullName>Product_Text_1__c</fullName>
    <description>First line of Abacus product description</description>
    <inlineHelpText>(From Abacus) First line of Abacus product description</inlineHelpText>
    <label>Product Text 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Text_2__c.field-meta.xml
<CustomField>
    <fullName>Product_Text_2__c</fullName>
    <description>Second line of Abacus product description</description>
    <inlineHelpText>(From Abacus) Second line of Abacus product description</inlineHelpText>
    <label>Product Text 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Text_3__c.field-meta.xml
<CustomField>
    <fullName>Product_Text_3__c</fullName>
    <inlineHelpText>(From Abacus) Product Text, line 3</inlineHelpText>
    <label>Product Text 3</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Thingstream_Id__c.field-meta.xml
<CustomField>
    <fullName>Thingstream_Id__c</fullName>
    <label>Thingstream Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Visible_In_Masterschedule__c.field-meta.xml
<CustomField>
    <fullName>Visible_In_Masterschedule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if the product needs to be visible in Masterschedule dashboard and report</description>
    <inlineHelpText>Check if the product needs to be visible in Masterschedule dashboard and report</inlineHelpText>
    <label>Visible In Masterschedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Visible_To_Partner__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the product will be included in the Masterschedule visible to the partner.</description>
    <inlineHelpText>When checked, the product will be included in the Masterschedule visible to the partner.</inlineHelpText>
    <label>Visible To Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Product2TestDataFactory.cls
@isTest
public with sharing class Product2TestDataFactory extends TestDataFactory {
    public Product2TestDataFactory() {
        super('Product2');
    }

    public override sObject initializeRecord(){
        Product2 testProduct = createMinimalProduct();
        return testProduct;
    }

    public override sObject createRecord(){
        Product2 testProduct = (Product2)initializeRecord();
        insert testProduct;
        return testProduct;
    }

    public override List<sObject> createBulkRecords(){

        Integer [] maxValues =new Integer[]{1,9,20,49,230,265,560,1022};

        for (Integer i = 0; i < maxValues.size(); i++) {
            Product2 prod = createProductForMaxPrice(maxValues[i]);
            recordsList.add(prod);
        }
        Insert recordsList;
        return recordsList;
    }

    public static Product2 createMinimalProduct() {
        //List<Product2> testProducts = new List<Product2>();
        Product2 testProduct = new Product2(
            Name = 'NEO-M8P',
            Type_No__c= 'NEO-M8P-2-11',
            ProductCode= 'NEO-M8P-2',
            Family = 'ALEX',
            Positioning_Engine__c = 'Not applicable',
            Product_Center__c = 'Positioning',
            Packaging_Size__c = 1000
            //CurrencyIsoCode = 'USD - U.S. Dollar'
            );
        //testProducts.add(testProduct);
        
        return testProduct;
    }

    public static Product2 iprClassProduct() {
        //List<Product2> testProducts = new List<Product2>();
        Product2 testProduct = new Product2(
            Name = 'NEO-M8P',
            Type_No__c= 'NEO-M8P-2-11',
            ProductCode= 'NEO-M8P-2',
            Family = 'ALEX',
            Positioning_Engine__c = 'Not applicable',
            Product_Center__c = 'Positioning',
            Packaging_Size__c = 1000
            //CurrencyIsoCode = 'USD - U.S. Dollar'
            );
        //testProducts.add(testProduct);
        
        return testProduct;
    }

    public Product2 iprTechnologyChanged(Product2 iprTestProduct){
        iprTestProduct.Cellular_Technology__c = 'GPRS';
        iprTestProduct.IPR_Technology__c = 'GSM';
        
        insert iprTestProduct;
        return iprTestProduct;
    }

    public Product2 thing_Stream_Condition(Product2 thingStreamProduct){
        thingStreamProduct.Thingstream_Id__c = 'GPRS';
        
        insert thingStreamProduct;
        return thingStreamProduct;
    }

    public Product2 should_Product_Description_Be_Updated(Product2 descriptionTestProduct){
        descriptionTestProduct.Thingstream_Id__c = 'GPRS';
        descriptionTestProduct.Product_Text_1__c = 'one';
        descriptionTestProduct.Product_Text_2__c = 'two';
        descriptionTestProduct.Product_Text_3__c = 'three';
        
        insert descriptionTestProduct;
        return descriptionTestProduct;
    }

    public Product2 should_Product_Description_Be_Updated2(Product2 descriptionTestProduct){
        descriptionTestProduct.Thingstream_Id__c = 'GPRS';
        descriptionTestProduct.Product_Text_1__c = 'one';
        descriptionTestProduct.Product_Text_2__c = 'two';
        
        insert descriptionTestProduct;
        return descriptionTestProduct;
    }

    public Product2 should_Product_Description_Be_Updated3(Product2 descriptionTestProduct){
        descriptionTestProduct.Thingstream_Id__c = 'GPRS';
        descriptionTestProduct.Product_Text_1__c = 'one';
        descriptionTestProduct.Product_Text_3__c = 'two';
        
        insert descriptionTestProduct;
        return descriptionTestProduct;
    }

    public Product2 product_Decision_Ipr_CostChanged(Product2 changedDecisionProduct){
        IPR_Cost__c iprCost = makeIprCost();

        changedDecisionProduct.Cellular_Technology__c = 'GPRS';
        //changedDecisionProduct.IPR_Technology__c = 'GSM';
        changedDecisionProduct.IPR_Cost__c = iprCost.Id;
        
        insert changedDecisionProduct;
        return changedDecisionProduct;
    }

    public Product2 update_Product_Decision_Ipr_CostChanged(Product2 changedDecisionProduct){
        changedDecisionProduct.IPR_Technology_Changed__c = true;

        update changedDecisionProduct;
        return changedDecisionProduct;
    }

    public Product2 update_Product_Active_Status(Product2 activatedProduct, boolean active){
        activatedProduct.IsActive = active;

        update activatedProduct;
        return activatedProduct;
    }

    public Product2 update_Product_Status(Product2 prodToBeUpdated){
        prodToBeUpdated.Product_Status__c = 'Obsolete';
        prodToBeUpdated.Visible_In_Masterschedule__c = true;
        prodToBeUpdated.Visible_To_Partner__c = true;

        update prodToBeUpdated;
        return prodToBeUpdated;
    }

    public Product2 update_IPR_Checked_Flag(Product2 prodToBeUpdated){
        prodToBeUpdated.IPR_Checked__c = true;
        prodToBeUpdated.IPR_Checked_Date__c = Date.newInstance(2019, 2, 17);

        update prodToBeUpdated;
        return prodToBeUpdated;
    }

    public Product2 update_Comment(Product2 prodToBeUpdated){
        prodToBeUpdated.Comment__c = 'These are the comments for testing';
        prodToBeUpdated.Comment_Updated_Date__c = Date.newInstance(2019, 2, 17);

        update prodToBeUpdated;
        return prodToBeUpdated;
    }

    public Product2 unchecked_Ipr_Checked(Product2 changeIPR){
        IPR_Cost__c iprCost = makeIprCost2();
        changeIPR.IPR_Cost__c = iprCost.Id;

        update changeIPR;
        return changeIPR;
    }

    public static Product2 createProductForMaxPrice(Integer packagingSize) {
        //List<Product2> testProducts = new List<Product2>();
        Product2 testProduct = new Product2(
            Name = 'NEO-M8P',
            Type_No__c= 'NEO-M8P-'+packagingSize+'-11',
            ProductCode= 'NEO-M8P-'+ packagingSize,
            Family = 'ALEX',
            Positioning_Engine__c = 'Not applicable',
            Product_Center__c = 'Positioning',
            Product_Category__c = 'Antennas',
            Packaging_Size__c = packagingSize
            //CurrencyIsoCode = 'USD - U.S. Dollar'
            );
        //testProducts.add(testProduct);
        
        return testProduct;
    }

    public static IPR_Cost__c makeIprCost(){

        IPR_Cost__c iprTestProduct = new IPR_Cost__c();
        
        iprTestProduct.Name = 'IPR Cost';
        iprTestProduct.Consumer_USD__c = 15;
        iprTestProduct.Handset_USD__c = 50;
        iprTestProduct.Other_USD__c = 500;
    
        insert iprTestProduct;
    
        return iprTestProduct;
        
    }

    public static IPR_Cost__c makeIprCost2(){

        IPR_Cost__c iprTestProduct = new IPR_Cost__c();
        
        iprTestProduct.Name = 'IPR Cost 2';
        iprTestProduct.Consumer_USD__c = 20;
        iprTestProduct.Handset_USD__c = 10;
        iprTestProduct.Other_USD__c = 40;
    
        insert iprTestProduct;
    
        return iprTestProduct;
        
    }
}