force-app/main/default/objects/Account/fields/a4a_Region__c.field-meta.xml
<CustomField>
    <fullName>a4a_Region__c</fullName>
    <formula>BLANKVALUE(TEXT(uB_Office__c),&quot;Other&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>a4a Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/a4a_Measure_Filter__c.field-meta.xml
<CustomField>
    <fullName>a4a_Measure_Filter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>a4a Measure Filter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/a4a_Measure_Filter_Formula__c.field-meta.xml
<CustomField>
    <fullName>a4a_Measure_Filter_Formula__c</fullName>
    <formula>NOT(Frame_Order__c) 
&amp;&amp; 
(Order_Status__c = &quot;Closed&quot; || (Order_Status__c = &quot;Open&quot; &amp;&amp; a4a_Date__c &gt;= TODAY()))
&amp;&amp; 
Total_Value_CHF__c &lt;&gt; 0
&amp;&amp;
a4a_Date__c &gt;= DATE(YEAR(TODAY())-2,01,01)

/* added 11.11.2019 */
&amp;&amp;
a4a_Date__c &lt;= TODAY() + ($Setup.a4x__app4forecast__c.a4x__Forecast_Periods__c + 2) * 30


/* temporarly added */
&amp;&amp;
NOT(a4a_Manual_Forecast__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>a4a Measure Filter Formula</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/a4a_Region__c.field-meta.xml
<CustomField>
    <fullName>a4a_Region__c</fullName>
    <formula>BLANKVALUE( a4a_Region_To_Consolidate__c ,BLANKVALUE(TEXT(Project_Owner_Account__r.uB_Office__c),&quot;Other&quot;))

/* previous version until 22.5.2021
BLANKVALUE(TEXT(Project_Owner_Account__r.uB_Office__c),&quot;Other&quot;)
*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>a4a Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Salesforce Account. Conneced via field &quot;Customer No&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <inlineHelpText>(From Abacus) Date of delivery. Used to calculate delivery reliability</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/End_Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The end customer is the company buying from the Account that buys from us. Typically this is the customer of our distributor or direct CM.</inlineHelpText>
    <label>End Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (End Customer Account)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated with Billing</description>
    <inlineHelpText>Product associated with Billing</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Link to Account in Salesforce</inlineHelpText>
    <label>Project Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Project Owner Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Qty_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Qty_Ordered__c</fullName>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Qty Ordered</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Total_Value_CHF__c.field-meta.xml
<CustomField>
    <fullName>Total_Value_CHF__c</fullName>
    <inlineHelpText>(From Abacus) Billing value in CHF. Imported from Abacus with correct exchange rate</inlineHelpText>
    <label>Total Value CHF</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OrderTriggerTest.cls
@isTest
public class OrderTriggerTest {
    @isTest
    static void orderInputUpdateDeleteTest() {
        
        a4x__app4forecast__c orgDefaults = a4x__app4forecast__c.getOrgDefaults();
        orgDefaults.a4x__Measure_Events_Active__c = True;
        
        Account acc001 = new Account();
        acc001.Name = 'Test ACC 001';
        insert acc001;
        
        Account acc002 = new Account();
        acc002.Name = 'Test ACC 002';
        insert acc002;
        
        Account eca001 = new Account();
        eca001.Name = 'Test ECA 001';
        insert eca001;
        
        Account eca002 = new Account();
        eca002.Name = 'Test ECA 002';
        insert eca002;
        
        Account poa001 = new Account();
        poa001.Name = 'Test POA 001';
        poa001.uB_Office__c = 'EMEA';
        insert poa001;
        
        Account poa002 = new Account();
        poa002.Name = 'Test POA 002';
        insert poa002;
        
        Product2 prod011 = new Product2();
        prod011.Name = 'TEST-P001';
        prod011.ProductCode = 'TEST-P001-0';
        prod011.Type_No__c = 'TEST-P001-0-01';
        insert prod011;
        
        Product2 prod012 = new Product2();
        prod012.Name = 'TEST-P001';
        prod012.ProductCode = 'TEST-P001-0';
        prod012.Type_No__c = 'TEST-P001-0-02';
        insert prod012;
        
        // Insert
        Billings__c o = new Billings__c();
        o.Account__c = acc001.Id;
        o.End_Customer_Account__c = eca001.Id;
        o.Project_Owner_Account__c = poa001.Id;
        o.Product__c = prod011.Id;
        o.Product__c = prod011.Id;
        o.Delivery_Date__c = Date.today().addMonths(+1);
        o.Qty_Ordered__c = 100;
        o.Total_Value_CHF__c = 1000;
        insert o;
        
        List<Billings__c> orders = [SELECT Id, a4a_Measure_Filter__c, a4a_Measure_Filter_Formula__c, a4a_Region__c From Billings__c];
        system.assertEquals(1, orders.size());
        system.assertEquals(orders[0].a4a_Measure_Filter_Formula__c, orders[0].a4a_Measure_Filter__c);
        
        // Filter Off due to change of the Delivery Date into the past
        o.Delivery_Date__c = Date.today().addMonths(-1);
        update o;
        
        orders = [SELECT Id, a4a_Measure_Filter__c, a4a_Measure_Filter_Formula__c, a4a_Region__c From Billings__c];
        system.assertEquals(1, orders.size());
        system.assertEquals(orders[0].a4a_Measure_Filter_Formula__c, orders[0].a4a_Measure_Filter__c);
        
        // Filter On due to change of the Delivery Date into the future
        o.Delivery_Date__c = Date.today().addMonths(+3);
        update o;
        
        orders = [SELECT Id, a4a_Measure_Filter__c, a4a_Measure_Filter_Formula__c, a4a_Region__c From Billings__c];
        system.assertEquals(1, orders.size());
        system.assertEquals(orders[0].a4a_Measure_Filter_Formula__c, orders[0].a4a_Measure_Filter__c);
        
        
        // Order Dimensions Changed - leading to a new Key
        o.Project_Owner_Account__c = poa002.Id;
        update o;
        
        orders = [SELECT Id, a4a_Measure_Filter__c, a4a_Measure_Filter_Formula__c, a4a_Region__c From Billings__c];
        system.assertEquals(1,orders.size());
        system.assertEquals(orders[0].a4a_Measure_Filter_Formula__c, orders[0].a4a_Measure_Filter__c);
        
        // Updates With Unchanged Dimensions
        o.Qty_Ordered__c = 500;
        update o;
        
        orders = [SELECT Id, a4a_Measure_Filter__c, a4a_Measure_Filter_Formula__c From Billings__c];
        system.assertEquals(1, orders.size());
        system.assertEquals(orders[0].a4a_Measure_Filter_Formula__c, orders[0].a4a_Measure_Filter__c);
        
        // Delete
        delete o;
        orders = [SELECT Id, a4a_Measure_Filter__c, a4a_Measure_Filter_Formula__c From Billings__c];
        system.assertEquals(0, orders.size());        
        
    }
}