force-app/main/default/objects/Account/fields/Abacus_Payterms__c.field-meta.xml
<CustomField>
    <fullName>Abacus_Payterms__c</fullName>
    <inlineHelpText>(From Abacus) Payment terms</inlineHelpText>
    <label>Abacus Payterms</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Delivery_Terms__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Terms__c</fullName>
    <description>(From Abacus)</description>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Delivery Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>DAP TEST</fullName>
            </value>
            <value>
                <fullName>DDP</fullName>
            </value>
            <value>
                <fullName>DDU</fullName>
            </value>
            <value>
                <fullName>EXW</fullName>
            </value>
            <value>
                <fullName>EXW Althofen (AT)</fullName>
            </value>
            <value>
                <fullName>EXW Thalwil (CH)</fullName>
            </value>
            <value>
                <fullName>Ex Works Reston, VA (USA)</fullName>
            </value>
            <value>
                <fullName>FCA Amkor ATP3 Binan PH</fullName>
            </value>
            <value>
                <fullName>FCA Flextronics Althofen AT</fullName>
            </value>
            <value>
                <fullName>Lieferkondition</fullName>
            </value>
            <value>
                <fullName>FCA Thalwil (CH)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OppCloseDate__c.field-meta.xml
<CustomField>
    <fullName>OppCloseDate__c</fullName>
    <formula>TODAY() + 180</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OppCloseDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Competitor_Product_Price__c/Competitor_Product_Price__c.object-meta.xml
<CustomObject>
    <label>Competitor Product Price</label>
    <nameField>
        <displayFormat>CPP-{000000}</displayFormat>
        <label>Competitor Product Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Product Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Product_Price__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Filled with Opportunity Account if the Competitor Product Price has been created from the Opp Product.</description>
    <inlineHelpText>Filled with Opportunity Account if the Competitor Product Price has been created from the Opp Product.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor Product Prices</relationshipLabel>
    <relationshipName>Competitor_Product_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Product_Price__c/fields/Opp_Product__c.field-meta.xml
<CustomField>
    <fullName>Opp_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Filled automatically when created from Opp Product</description>
    <inlineHelpText>Filled automatically when created from Opp Product</inlineHelpText>
    <label>Opp Product</label>
    <referenceTo>Opp_Product__c</referenceTo>
    <relationshipLabel>Competitor Product Prices</relationshipLabel>
    <relationshipName>Competitor_Product_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Product_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product in related Opp Product</description>
    <formula>Opp_Product__r.Product__r.Name</formula>
    <inlineHelpText>Product in related Opp Product</inlineHelpText>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash in advance</fullName>
            </value>
            <value>
                <fullName>Cash on delivery</fullName>
            </value>
            <value>
                <fullName>30 days end of month net</fullName>
            </value>
            <value>
                <fullName>30 days net</fullName>
            </value>
            <value>
                <fullName>30 days upon approved credit</fullName>
            </value>
            <value>
                <fullName>60 days net</fullName>
            </value>
            <value>
                <fullName>L/C irrevocable and confirmed</fullName>
            </value>
            <value>
                <fullName>Pre-Payment</fullName>
            </value>
            <value>
                <fullName>T/T in advance</fullName>
            </value>
            <value>
                <fullName>-</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Special_Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Special_Price_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Related Special Price Request (if exists, for PPP mandatory)</inlineHelpText>
    <label>Special Price Request</label>
    <referenceTo>Special_Price_Request__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Special_Price_Request__c/Special_Price_Request__c.object-meta.xml
<CustomObject>
    <description>Request for TPD, MSP, PPP that needs approvals</description>
    <label>Special Price Request</label>
    <nameField>
        <displayFormat>SPR-{000000}</displayFormat>
        <label>Special Price Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Price_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Opportunity Account if there is Opportunity</description>
    <inlineHelpText>Opportunity Account if there is Opportunity</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Special Price Requests</relationshipLabel>
    <relationshipName>Project_Price_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Comment_by_Requestor__c.field-meta.xml
<CustomField>
    <fullName>Comment_by_Requestor__c</fullName>
    <label>Comment by Requestor</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <inlineHelpText>Imported to Quotation (with New Quotation button)</inlineHelpText>
    <label>Delivery</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FCA Flextronics Althofen (AT)</fullName>
            </value>
            <value>
                <fullName>FCA Amkor ATP3 Binan (PH)</fullName>
            </value>
            <value>
                <fullName>FCA Thalwil (CH)</fullName>
            </value>
            <value>
                <fullName>FCA Reston (USA)</fullName>
            </value>
            <value>
                <fullName>EXW Reston (USA)</fullName>
            </value>
            <value>
                <fullName>DAP + add Place and Country manually, e.g. Shenzhen (CN)</fullName>
            </value>
            <value>
                <fullName>DDP + add Place and Country manually, e.g. Shenzhen (CN)</fullName>
            </value>
            <value>
                <fullName>EXW Althofen, Austria (Incoterms 2000)</fullName>
            </value>
            <value>
                <fullName>EXW Thalwil, Switzerland (Incoterms 2000) for samples, EXW Althofen, Austria (Incoterms 2000) for complete packing units</fullName>
            </value>
            <value>
                <fullName>EXW Biñan, Philippines (Incoterms 2000)</fullName>
            </value>
            <value>
                <fullName>EXW Thalwil, Switzerland (Incoterms 2000) for samples, EXW Biñan, Philippines (Incoterms 2000) for complete packing units</fullName>
            </value>
            <value>
                <fullName>EXW Thalwil, Switzerland (Incoterms 2000)</fullName>
            </value>
            <value>
                <fullName>EXW Reston VA, Unites States (Incoterms 2000)</fullName>
            </value>
            <value>
                <fullName>DDU</fullName>
            </value>
            <value>
                <fullName>DDP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.Opportunity_Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Special Price Requests</relationshipLabel>
    <relationshipName>Project_Price_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <inlineHelpText>Imported to Quotation (with New Quotation button). Leave empty if it should be from the Account.</inlineHelpText>
    <label>Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>30 days end of month net</fullName>
            </value>
            <value>
                <fullName>30 days net</fullName>
            </value>
            <value>
                <fullName>30 days upon approved credit</fullName>
            </value>
            <value>
                <fullName>60 days net</fullName>
            </value>
            <value>
                <fullName>L/C irrevocable and confirmed</fullName>
            </value>
            <value>
                <fullName>Pre-Payment</fullName>
            </value>
            <value>
                <fullName>T/T in advance</fullName>
            </value>
            <value>
                <fullName>-</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Price_Level__c.field-meta.xml
<CustomField>
    <fullName>Price_Level__c</fullName>
    <description>Price level
RSP: Price = RSP
TPD: RSP &gt; Price &gt;= TPD
MSP: TPD &gt; Price &gt;= MSP
PPP: MSP &gt; Price</description>
    <inlineHelpText>Price level
RSP: Price = RSP
TPD: RSP &gt; Price &gt;= TPD
MSP: TPD &gt; Price &gt;= MSP
PPP: MSP &gt; Price
NOTE: No Approval Process required for TPD</inlineHelpText>
    <label>Price Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PPP (Project Price Plan)</fullName>
            </value>
            <value>
                <fullName>MSP (Minimum Sales Price)</fullName>
            </value>
            <value>
                <fullName>TPD (Transfer Price for Distributor)</fullName>
            </value>
            <value>
                <fullName>RSP (Recommended Sales Price)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Prices_Valid_Until__c.field-meta.xml
<CustomField>
    <fullName>Prices_Valid_Until__c</fullName>
    <description>If it is empty, it will be Date Approved By CEO + 120 days</description>
    <inlineHelpText>If it is empty, it will be Date Approved By CEO + 120 days</inlineHelpText>
    <label>Prices Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request_Product__c/Special_Price_Request_Product__c.object-meta.xml
<CustomObject>
    <description>Product price plans for Special Price Request</description>
    <label>Special Price Request Product</label>
    <nameField>
        <displayFormat>SPRP-{000000}</displayFormat>
        <label>Special Price Request Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Price_Request_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Special_Price_Request__r.Account__r.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Special_Price_Request__r.Opportunity__r.Name</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request_Product__c/fields/Special_Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Special_Price_Request__c</fullName>
    <label>Special Price Request</label>
    <referenceTo>Special_Price_Request__c</referenceTo>
    <relationshipLabel>Special Price Request Products</relationshipLabel>
    <relationshipName>Special_Price_Request_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NewSPRCtrl.cls
public Without Sharing class  NewSPRCtrl {

    @AuraEnabled
    public static Map<String, String> getIds(Id recordId){
        Map<String, String> mapping = new Map<String, String>{};
        mapping.put('AccountId', recordId);
        mapping.put('OpportunityId', '');

        Opportunity[] o = [Select AccountId from Opportunity where Id = :recordId];   
        if(!o.isEmpty()) {
            mapping.put('AccountId', o[0].AccountId);
            mapping.put('OpportunityId', recordId);
        }

        return mapping;
    }
    
    @AuraEnabled
    public static String save(Special_Price_Request__c sp){
        String rId = ''; 
        
        Account a = [Select Id, Name, OppCloseDate__c, Delivery_Terms__c, Abacus_Payterms__c, CurrencyIsoCode from Account Where Id = :sp.Account__c];
        String AccountId = sp.Account__c;
        Date OppCloseDate = a.OppCloseDate__c;
        String PayTerms = a.Abacus_Payterms__c;
        String DelTerms = a.Delivery_Terms__c;
        String SPRCurrency = a.CurrencyIsoCode;
        Id OpportunityId = sp.Opportunity__c;
        
        if(OpportunityId!=null) {
            Opportunity o = [SELECT Name, CurrencyIsoCode, OwnerId, CloseDate FROM Opportunity WHERE Id = :OpportunityId];
        	SPRCurrency = o.CurrencyIsoCode;
        	OppCloseDate = o.CloseDate;
        }


        Special_Price_Request__c spr = new Special_Price_Request__c(
            Account__c = AccountId,
            CurrencyIsoCode = SPRCurrency,
            Payment__c = PayTerms,
            Delivery__c = DelTerms,
            Price_Level__c = sp.Price_Level__c,
            Comment_by_Requestor__c = sp.Comment_by_Requestor__c,
            Prices_Valid_Until__c = sp.Prices_Valid_Until__c
        );
        if(OpportunityId!=null) spr.Opportunity__c = OpportunityId;
        insert spr;
        
        if(OpportunityId!=null && spr.Id != null) {
            Map<Id,Id> maps = new Map<Id,Id>(); 
            
            //Loop through the Opp Products in the records set
            for(Opp_Product__c op: [SELECT Id, Product__c, Annual_Quantity__c, Unit_Price__c, Use_Restriction__c, IPR_Coverage__c, CurrencyIsoCode FROM Opp_Product__c WHERE Opportunity__c = :OpportunityId AND Status__c != 'Lost']){
                
                Special_Price_Request_Product__c sprp =new Special_Price_Request_Product__c();    
                sprp.Special_Price_Request__c = spr.Id;
                sprp.Product__c = op.Product__c;
                sprp.Year_P1__c = OppCloseDate;
                sprp.Quantity_P1__c = op.Annual_Quantity__c;
                sprp.Unit_Price_P1__c = op.Unit_Price__c;
                sprp.Use_Restriction__c = op.Use_Restriction__c;
                sprp.IPR_Coverage__c = op.IPR_Coverage__c;
                sprp.CurrencyIsoCode = op.CurrencyIsoCode;
                insert sprp; 
                
                if(sprp.Id != null) {
                    // map of opp products and sprp to use in Competitor_Product_Price__c 
                    maps.put(op.Id,sprp.Id);
                }
            }     
            
            if(!maps.isEmpty()) {
                List<Competitor_Product_Price__c> lstCP = new list<Competitor_Product_Price__c>();
                
            	for(Competitor_Product_Price__c  cp: [SELECT Id, Opp_Product__c, Special_Price_Request_Product__c FROM Competitor_Product_Price__c WHERE Opp_Product__c IN :maps.keySet()]) {
                	Competitor_Product_Price__c cps = new Competitor_Product_Price__c(); 
                    cps.Id = cp.Id;
                    cps.Special_Price_Request_Product__c = maps.get(cp.Opp_Product__c);
                    
                    lstCP.add(cps);
                }
                                                      
                if(!lstCP.isEmpty()) {
                    update(lstCP);
                }                                         
            }
        }
    
        rId = spr.Id; 
        return rId;
    }
        
}