force-app/main/default/objects/Account/fields/Abacus_Payterms__c.field-meta.xml
<CustomField>
    <fullName>Abacus_Payterms__c</fullName>
    <inlineHelpText>(From Abacus) Payment terms</inlineHelpText>
    <label>Abacus Payterms</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Jobs__c.field-meta.xml
<CustomField>
    <fullName>Customer_Jobs__c</fullName>
    <description>Added on request OpenIssues52917</description>
    <inlineHelpText>What jobs are required to accomplish tasks and problems of the customer?</inlineHelpText>
    <label>Customer Jobs</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Added on request OpenIssues52917</description>
    <inlineHelpText>Describe the type of customer and his style</inlineHelpText>
    <label>Customer Type</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gain_Creators__c.field-meta.xml
<CustomField>
    <fullName>Gain_Creators__c</fullName>
    <description>Added on request OpenIssues52917</description>
    <inlineHelpText>What new or additional benefits does our solution offer?</inlineHelpText>
    <label>Gain Creators</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gains__c.field-meta.xml
<CustomField>
    <fullName>Gains__c</fullName>
    <description>Added on request OpenIssues52917</description>
    <inlineHelpText>Describe the desired outcome and benefits when job is done correctly
[Required, expected, desired, unexpected]</inlineHelpText>
    <label>Gains</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pain_Relievers__c.field-meta.xml
<CustomField>
    <fullName>Pain_Relievers__c</fullName>
    <description>Added on request OpenIssues52917</description>
    <inlineHelpText>How does our solution alleviate problems, obstacles and risk our customer encounters?</inlineHelpText>
    <label>Pain Relievers</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pains__c.field-meta.xml
<CustomField>
    <fullName>Pains__c</fullName>
    <description>Added on request OpenIssues52917</description>
    <inlineHelpText>Describe problems, challenges, obstacles and risks the customer is encountering</inlineHelpText>
    <label>Pains</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash in advance</fullName>
            </value>
            <value>
                <fullName>Cash on delivery</fullName>
            </value>
            <value>
                <fullName>30 days end of month net</fullName>
            </value>
            <value>
                <fullName>30 days net</fullName>
            </value>
            <value>
                <fullName>30 days upon approved credit</fullName>
            </value>
            <value>
                <fullName>60 days net</fullName>
            </value>
            <value>
                <fullName>L/C irrevocable and confirmed</fullName>
            </value>
            <value>
                <fullName>Pre-Payment</fullName>
            </value>
            <value>
                <fullName>T/T in advance</fullName>
            </value>
            <value>
                <fullName>-</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Special_Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Special_Price_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Related Special Price Request (if exists, for PPP mandatory)</inlineHelpText>
    <label>Special Price Request</label>
    <referenceTo>Special_Price_Request__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Value_Proposition__c.field-meta.xml
<CustomField>
    <fullName>Value_Proposition__c</fullName>
    <description>Added on request OpenIssues52917</description>
    <inlineHelpText>What does the product help the customer to accomplish his jobs?
[Create, raise, reduce, eliminate]</inlineHelpText>
    <label>Value Proposition</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Special_Price_Request__c/Special_Price_Request__c.object-meta.xml
<CustomObject>
    <description>Request for TPD, MSP, PPP that needs approvals</description>
    <label>Special Price Request</label>
    <nameField>
        <displayFormat>SPR-{000000}</displayFormat>
        <label>Special Price Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Price_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Opportunity Account if there is Opportunity</description>
    <inlineHelpText>Opportunity Account if there is Opportunity</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Special Price Requests</relationshipLabel>
    <relationshipName>Project_Price_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Approved_By_Regional_Head__c.field-meta.xml
<CustomField>
    <fullName>Approved_By_Regional_Head__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved By Regional Head</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <inlineHelpText>Imported to Quotation (with New Quotation button)</inlineHelpText>
    <label>Delivery</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FCA Flextronics Althofen (AT)</fullName>
            </value>
            <value>
                <fullName>FCA Amkor ATP3 Binan (PH)</fullName>
            </value>
            <value>
                <fullName>FCA Thalwil (CH)</fullName>
            </value>
            <value>
                <fullName>FCA Reston (USA)</fullName>
            </value>
            <value>
                <fullName>EXW Reston (USA)</fullName>
            </value>
            <value>
                <fullName>DAP + add Place and Country manually, e.g. Shenzhen (CN)</fullName>
            </value>
            <value>
                <fullName>DDP + add Place and Country manually, e.g. Shenzhen (CN)</fullName>
            </value>
            <value>
                <fullName>EXW Althofen, Austria (Incoterms 2000)</fullName>
            </value>
            <value>
                <fullName>EXW Thalwil, Switzerland (Incoterms 2000) for samples, EXW Althofen, Austria (Incoterms 2000) for complete packing units</fullName>
            </value>
            <value>
                <fullName>EXW Biñan, Philippines (Incoterms 2000)</fullName>
            </value>
            <value>
                <fullName>EXW Thalwil, Switzerland (Incoterms 2000) for samples, EXW Biñan, Philippines (Incoterms 2000) for complete packing units</fullName>
            </value>
            <value>
                <fullName>EXW Thalwil, Switzerland (Incoterms 2000)</fullName>
            </value>
            <value>
                <fullName>EXW Reston VA, Unites States (Incoterms 2000)</fullName>
            </value>
            <value>
                <fullName>DDU</fullName>
            </value>
            <value>
                <fullName>DDP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <inlineHelpText>Imported to Quotation (with New Quotation button). Leave empty if it should be from the Account.</inlineHelpText>
    <label>Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>30 days end of month net</fullName>
            </value>
            <value>
                <fullName>30 days net</fullName>
            </value>
            <value>
                <fullName>30 days upon approved credit</fullName>
            </value>
            <value>
                <fullName>60 days net</fullName>
            </value>
            <value>
                <fullName>L/C irrevocable and confirmed</fullName>
            </value>
            <value>
                <fullName>Pre-Payment</fullName>
            </value>
            <value>
                <fullName>T/T in advance</fullName>
            </value>
            <value>
                <fullName>-</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Price_Level__c.field-meta.xml
<CustomField>
    <fullName>Price_Level__c</fullName>
    <description>Price level
RSP: Price = RSP
TPD: RSP &gt; Price &gt;= TPD
MSP: TPD &gt; Price &gt;= MSP
PPP: MSP &gt; Price</description>
    <inlineHelpText>Price level
RSP: Price = RSP
TPD: RSP &gt; Price &gt;= TPD
MSP: TPD &gt; Price &gt;= MSP
PPP: MSP &gt; Price
NOTE: No Approval Process required for TPD</inlineHelpText>
    <label>Price Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PPP (Project Price Plan)</fullName>
            </value>
            <value>
                <fullName>MSP (Minimum Sales Price)</fullName>
            </value>
            <value>
                <fullName>TPD (Transfer Price for Distributor)</fullName>
            </value>
            <value>
                <fullName>RSP (Recommended Sales Price)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Approved: Only when the final approval has been made.
Rejected: Any time the request has been rejected.</description>
    <inlineHelpText>Approved: Only when the final approval has been made.
Rejected: Any time the request has been rejected.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Price_Request_Product__c/Special_Price_Request_Product__c.object-meta.xml
<CustomObject>
    <description>Product price plans for Special Price Request</description>
    <label>Special Price Request Product</label>
    <nameField>
        <displayFormat>SPRP-{000000}</displayFormat>
        <label>Special Price Request Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Price_Request_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Special_Price_Request__r.Account__r.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request_Product__c/fields/Special_Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Special_Price_Request__c</fullName>
    <label>Special Price Request</label>
    <referenceTo>Special_Price_Request__c</referenceTo>
    <relationshipLabel>Special Price Request Products</relationshipLabel>
    <relationshipName>Special_Price_Request_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NewQuotationSPRCtrlTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@IsTest
private class NewQuotationSPRCtrlTest {
    static testMethod void TestNewSPRQuotation() {
        Account acc = new Account();
        acc.uB_Office__c = 'Corporate';
        acc.Name = 'test class name';           
        acc.Abacus_Payterms__c = 'test payment abacus'; 
        acc.CurrencyIsoCode = 'USD';
        insert acc;

        Opportunity quotOpp = new Opportunity();
        quotOpp.Name = 'Test Opportunity';        
        quotOpp.CloseDate = Date.newInstance(2016, 12, 9);
        quotOpp.AccountId = acc.Id;
        quotOpp.StageName = '5 Design-in';
        quotOpp.Value_Proposition__c = 'test value proposition';
        quotOpp.Gain_Creators__c = 'test';
        quotOpp.Pain_Relievers__c='text area';
        quotOpp.Customer_Type__c='test';
        quotOpp.Gains__c = 'ere';
        quotOpp.Pains__c='pains';
        quotOpp.Customer_Jobs__c = 'customer jobs';
        insert quotOpp;
            
        Contact cont = new Contact();
        cont.LastName = 'Test contact name';
        cont.AccountId = acc.Id;
        insert cont;
            
        Special_Price_Request__c spr = new Special_Price_Request__c();
        spr.Price_Level__c = 'PPP (Project Price Plan)';
        spr.Account__c = acc.Id;
        spr.CurrencyIsoCode = 'USD';
        spr.Account__c = acc.Id;
        spr.Delivery__c = 'FCA Thalwil (CH)';
        
        spr.Payment__c = '30 days end of month net';
        spr.Status__c = 'Approved';
        spr.Approved_By_Regional_Head__c = true;
        spr.Opportunity__c = quotOpp.Id;
        spr.Contact__c = cont.Id;
        insert spr;

        Product2 prod = new Product2();
        //Product__c prod = new Product__c();
        prod.Name = 'Test product';
        prod.Type_No__c = 'Test 123654789 type';
        prod.Packaging_Size__c = 123456;
        //prod.Product_Family__c = 'ALEX';
        prod.Positioning_Engine__c = 'u-blox D9';
        prod.CurrencyIsoCode = spr.CurrencyIsoCode;
        insert prod;
        
        
        Special_Price_Request_Product__c sprp = new Special_Price_Request_Product__c();
        sprp.Special_Price_Request__c = spr.Id;
        sprp.Product__c = prod.Id;
        sprp.CurrencyIsoCode = spr.CurrencyIsoCode;
        sprp.Year_P1__c = Date.newInstance(2016, 12, 9);
        sprp.Unit_Price_P1__c = 15;
        sprp.Quantity_P1__c = 1500;
        sprp.Quantity_P2__c = 15;
        sprp.Quantity_P3__c = 20;
        sprp.Quantity_P4__c = 20;
        sprp.Quantity_P5__c = 20; 
        insert sprp;
        
        Special_Price_Request_Product__c sprp2 = new Special_Price_Request_Product__c();
        sprp2.Special_Price_Request__c = spr.Id;
        sprp2.Product__c = prod.Id;
        sprp2.CurrencyIsoCode = spr.CurrencyIsoCode;
        sprp2.Year_P1__c = Date.newInstance(2016, 12, 9);
        sprp2.Unit_Price_P1__c = 15;
        sprp2.Quantity_P1__c = 1500;
        insert sprp2;
        
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = prod.Id,
            CurrencyIsoCode = 'USD',
            UnitPrice = 10.5,
            IsActive = true,
            UseStandardPrice = false
        );
        insert pbe;
       
        NewQuotationSPRCtrl.getSPRid(spr.Id); 
          
            
    }
}