force-app/main/default/objects/Account/fields/Abacus_Payterms__c.field-meta.xml
<CustomField>
    <fullName>Abacus_Payterms__c</fullName>
    <inlineHelpText>(From Abacus) Payment terms</inlineHelpText>
    <label>Abacus Payterms</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OppCloseDate__c.field-meta.xml
<CustomField>
    <fullName>OppCloseDate__c</fullName>
    <formula>TODAY() + 180</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OppCloseDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <formula>text(Product__r.Product_Center__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OppAutoNumber__c.field-meta.xml
<CustomField>
    <fullName>OppAutoNumber__c</fullName>
    <description>To be used for Quotation_Reference_Number__c</description>
    <displayFormat>{YY}{000000}</displayFormat>
    <label>OppAutoNumber</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash in advance</fullName>
            </value>
            <value>
                <fullName>Cash on delivery</fullName>
            </value>
            <value>
                <fullName>30 days end of month net</fullName>
            </value>
            <value>
                <fullName>30 days net</fullName>
            </value>
            <value>
                <fullName>30 days upon approved credit</fullName>
            </value>
            <value>
                <fullName>60 days net</fullName>
            </value>
            <value>
                <fullName>L/C irrevocable and confirmed</fullName>
            </value>
            <value>
                <fullName>Pre-Payment</fullName>
            </value>
            <value>
                <fullName>T/T in advance</fullName>
            </value>
            <value>
                <fullName>-</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quotation_Account__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is opportunity, than it is blank.</description>
    <label>Quotation Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Referred_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quotation referring to specific opportunity</description>
    <label>Referred Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>List of Quotations</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Referred_Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Quotation appears in this Account under Partner Quotations.</description>
    <inlineHelpText>This Quotation appears in this Account under Partner Quotations.</inlineHelpText>
    <label>Referred Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Quotations</relationshipLabel>
    <relationshipName>ReferredOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Quotation.recordType-meta.xml
<RecordType>
    <fullName>Quotation</fullName>
    <active>true</active>
    <businessProcess>Quotation</businessProcess>
    <label>Quotation</label>
</RecordType>

force-app/main/default/objects/Product2/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tashang</fullName>
            </value>
            <value>
                <fullName>u-blox</fullName>
                <default>true</default>
                <label>u-blox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityQuotationPageController.cls
/*
 * Apex Controller for New Quotation button in Account object in Lightning
 * 
 * Date: 2019/11/06
 * Author: PARX-ogu
 * */
public class OpportunityQuotationPageController {
    
    public Opportunity currentRecord {get;set;}    //Current Opporutnity
    public Opportunity QuotationTemplate {get;set;} //Template Oppportunity for Quotation
    public Opportunity TashangQuotationTemplate {get;set;} // Tashang Template Opportunity 
    public List<Opp_Product__c> oppProdList{get;set;}
    public Boolean checkTashang{get;set;}
    public Boolean checkUblox{get;set;}
    public OpportunityQuotationPageController(apexPages.StandardController sc)
    {
        //Fetch current record's information
        Id currentRecordId = sc.getRecord().Id;
        oppProdList = new List<Opp_Product__c>();
        checkTashang = false;
        checkUblox = false;
        currentRecord = [SELECT Id, 
                         Name,
                         OppAutoNumber__c ,
                         CurrencyIsoCode,
                         AccountId,
                         CloseDate,
                         Account.OppCloseDate__c,
                         Account.Abacus_Payterms__c
                         FROM Opportunity
                         WHERE Id =:currentRecordId];
        oppProdList = [Select Id,Product_Center__c,Product__r.BusinessUnit__c from Opp_Product__c where Opportunity__c =: currentRecordId];
        
        for(Opp_Product__c oppProd : oppProdList){
            if(oppProd.Product__r.BusinessUnit__c == 'Tashang')checkTashang = true;
            
            if(oppProd.Product__r.BusinessUnit__c == 'u-blox') checkUblox = true;
            
        }
        system.debug('currentRecord: '+currentRecord.CurrencyIsoCode);
        //Initialize template quotation from current Opportunity
        QuotationTemplate = new Opportunity(
            CurrencyIsoCode          = currentRecord.CurrencyIsoCode,
            Name               = currentRecord.Name,
            Quotation_Account__c       = currentRecord.AccountId,
            Referred_Opportunity_Account__c = currentRecord.AccountId,
            AccountId             = currentRecord.AccountId,
            Referred_Opportunity__c     = currentRecord.Id,
            CloseDate             = currentRecord.Account.OppCloseDate__c,
            RecordTypeId           = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Quotation').getRecordTypeId(),
            Payment__c             = currentRecord.Account.Abacus_Payterms__c,
            StageName             = '3 Calling on'
        );
        
        // Initialize Template Quotation for Tashang from Current Opportunity
        if(checkTashang){
             TashangQuotationTemplate = new Opportunity(
                CurrencyIsoCode          = currentRecord.CurrencyIsoCode,
                Name               = currentRecord.Name,
                Quotation_Account__c       = currentRecord.AccountId,
                Referred_Opportunity_Account__c = currentRecord.AccountId,
                AccountId             = currentRecord.AccountId,
                Referred_Opportunity__c     = currentRecord.Id,
                CloseDate             = currentRecord.Account.OppCloseDate__c,
                RecordTypeId           = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Quotation').getRecordTypeId(),
                Payment__c             = currentRecord.Account.Abacus_Payterms__c,
                StageName             = '3 Calling on'
            );
      }
    }
    
    //Return to previous opportunity
    public pageReference doCancel()
    {
        pageReference pageRef = new pageReference('/' + currentRecord.Id);
        pageRef.SetRedirect(true);
        return pageRef;
    }
    
    //Save and return
    public pageReference doSave()
    {
        try{
            Id newQuotationId = NewQuotationCtrl.save(QuotationTemplate,TashangQuotationTemplate,'Opportunity');
            pageReference pageRef = new pageReference('/' + (newQuotationId != null ? newQuotationId : currentRecord.Id));
            pageRef.SetRedirect(true);
            return pageRef;
        }catch(DMLException ex){
            for(Integer i=0;i<ex.getNumDml();i++){           
                ApexPages.addmessage(new ApexPages.message(ApexPages.SEVERITY.FATAL, ex.getDmlMessage(i)));
            }
        }
        return null;
    }
}