force-app/main/default/objects/Account/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <inlineHelpText>Select the application where u-blox realize the largest part of the revenues. Used for statistical analysis.</inlineHelpText>
    <label>Old Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADAS</fullName>
            </value>
            <value>
                <fullName>Asset tracking</fullName>
            </value>
            <value>
                <fullName>ATM, POS, vending</fullName>
            </value>
            <value>
                <fullName>Aviation &amp; UAV</fullName>
            </value>
            <value>
                <fullName>Base station</fullName>
            </value>
            <value>
                <fullName>Car connectivity</fullName>
            </value>
            <value>
                <fullName>Digital camera</fullName>
            </value>
            <value>
                <fullName>Driving recorder</fullName>
            </value>
            <value>
                <fullName>Emergency call</fullName>
            </value>
            <value>
                <fullName>Femtocell</fullName>
            </value>
            <value>
                <fullName>GPS mouse</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Home entertainment</fullName>
            </value>
            <value>
                <fullName>In-car navigation</fullName>
            </value>
            <value>
                <fullName>Industrial terminal</fullName>
            </value>
            <value>
                <fullName>Insurance box</fullName>
            </value>
            <value>
                <fullName>Machine control</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Metering</fullName>
            </value>
            <value>
                <fullName>Military &amp; government</fullName>
            </value>
            <value>
                <fullName>Mobile gaming</fullName>
            </value>
            <value>
                <fullName>Mobile hotspot and router</fullName>
            </value>
            <value>
                <fullName>Mobile phone</fullName>
            </value>
            <value>
                <fullName>Monitoring &amp; control</fullName>
            </value>
            <value>
                <fullName>Notebook, tablet</fullName>
            </value>
            <value>
                <fullName>PDA</fullName>
            </value>
            <value>
                <fullName>People &amp; animal tracking</fullName>
            </value>
            <value>
                <fullName>PND</fullName>
            </value>
            <value>
                <fullName>Radar detector</fullName>
            </value>
            <value>
                <fullName>Recreation &amp; sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <inlineHelpText>Market where largest share of u-blox revenues are generated. Choose &quot;not applicable&quot; for distributors, sales reps, competitors.</inlineHelpText>
    <label>Market (OLD)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <inlineHelpText>On creation, if empty copied from the master Opportunity after Save. Edit as needed.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <formula>text(Opportunity__r.Application_type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Old Application Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <description>Annual run rate of product. If</description>
    <inlineHelpText>Annual run rate. For single shot opportunities, use total quantity.
If Opportunity is converted from Lead, this is copied from Lead.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_type__c.field-meta.xml
<CustomField>
    <fullName>Application_type__c</fullName>
    <label>Old Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADAS</fullName>
            </value>
            <value>
                <fullName>Asset tracking</fullName>
            </value>
            <value>
                <fullName>ATM, POS, vending</fullName>
            </value>
            <value>
                <fullName>Aviation &amp; UAV</fullName>
            </value>
            <value>
                <fullName>Base station</fullName>
            </value>
            <value>
                <fullName>Car connectivity</fullName>
            </value>
            <value>
                <fullName>Digital camera</fullName>
            </value>
            <value>
                <fullName>Driving recorder</fullName>
            </value>
            <value>
                <fullName>Emergency call</fullName>
            </value>
            <value>
                <fullName>Femtocell</fullName>
            </value>
            <value>
                <fullName>GPS mouse</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Home entertainment</fullName>
            </value>
            <value>
                <fullName>In-car navigation</fullName>
            </value>
            <value>
                <fullName>Industrial terminal</fullName>
            </value>
            <value>
                <fullName>Insurance box</fullName>
            </value>
            <value>
                <fullName>Machine control</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Metering</fullName>
            </value>
            <value>
                <fullName>Military &amp; government</fullName>
            </value>
            <value>
                <fullName>Mobile gaming</fullName>
            </value>
            <value>
                <fullName>Mobile hotspot and router</fullName>
            </value>
            <value>
                <fullName>Mobile phone</fullName>
            </value>
            <value>
                <fullName>Monitoring &amp; control</fullName>
            </value>
            <value>
                <fullName>Notebook, tablet</fullName>
            </value>
            <value>
                <fullName>PDA</fullName>
            </value>
            <value>
                <fullName>People &amp; animal tracking</fullName>
            </value>
            <value>
                <fullName>PND</fullName>
            </value>
            <value>
                <fullName>Radar detector</fullName>
            </value>
            <value>
                <fullName>Recreation &amp; sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <inlineHelpText>Select market by quality grade.</inlineHelpText>
    <label>Market (OLD)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/TestSendOppReminderController.cls
@isTest
private class TestSendOppReminderController{
    
static testMethod void oppReminderEmail() {


        
      
        Account a = new Account();
        a.Name = 'Test Account'; 
        a.BillingCity = 'Hartland'; 
        a.BillingState = 'WI'; 
        a.BillingCountry = 'US'; 
        a.BillingPostalCode = '55009'; 
        a.BillingStreet = '1234 First St.';
        insert a;
        
        
        Contact c = new Contact();
        c.FirstName = 'Unit'; 
        c.LastName = 'Test'; 
        c.Email = 'non@non.com'; 
        c.AccountId = a.Id;
        insert c;

              
       
        Opportunity o = new Opportunity();
        o.AccountId = a.Id; 
        o.Name = 'Test Opp'; 
        o.CurrencyIsoCode = 'EUR'; 
        o.Annual_Quantity__c = 10; 
        o.StageName = '8 Production'; 
        o.Application_Type__c = 'Mobile phone'; 
        o.Market__c = 'Industrial'; 
        o.CloseDate = System.today();
        insert o;


        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = c.Id;
        ocr.OpportunityId = o.Id;
        ocr.IsPrimary = TRUE;
        ocr.Role = 'Decision Maker';
        insert ocr;

        List<OrgWideEmailAddress> owea = [Select DisplayName, Address From OrgWideEmailAddress Where DisplayName='none' limit 1];
        if(owea.isEmpty()){
            owea = [Select DisplayName, Address From OrgWideEmailAddress limit 1];
        }
        /*owea.DisplayName = 'info';
        owea.address = 'info@info.com';
        insert owea;*/


        List<OpportunityContactRole> OppConRoles = [Select ContactId, OpportunityId, IsPrimary, Role From OpportunityContactRole Where Role='Decision Maker'];
        List<Opp_Product__c> OppProds = new List<Opp_Product__c>(); 
        System.assertEquals(1, OppConRoles.size());

      
      
        String templateLang = '';
        Boolean emailValidity = false;

        
        // Go to our page
        PageReference pageRef = Page.Opp_reminder;
        
        // Create the controller
        SendOppReminderController controller = new SendOppReminderController(new ApexPages.StandardController(o));
   
        
        // call the template
        pageRef = controller.populateTemplate(); 


        //validate email
        emailValidity = controller.validateEmail('non@non.com');


        //fetch OppProds
        controller.fetchOppProds();

        //set language
        templateLang = controller.setLanguage();

        // send the email
        pageRef = controller.send();

               
        // cancel it
        pageRef = controller.cancel();

        //refresh it
        pageRef = controller.refresh();

    }

    
}