force-app/main/default/objects/Account/fields/Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Manager__c</fullName>
    <inlineHelpText>If the Account is owned by a distribution partner, this field indicates the channel manager. Else it is the same as the Owner. Copied from User settings.</inlineHelpText>
    <label>Old Channel Manager</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <description>See Worksflow for RMA.</description>
    <inlineHelpText>Name of distributor will be copied to the field with the same name of all RMAs connected to this account. The sharing rule will ensure access to these RMAs</inlineHelpText>
    <label>Distributor Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Email_Account_Owner__c</fullName>
    <inlineHelpText>Email address of the Account owner. Copied from User settings.</inlineHelpText>
    <label>Email Account Owner</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>Email_Channel_Manager__c</fullName>
    <inlineHelpText>Email address of the channel manager. Copied from User settings.</inlineHelpText>
    <label>Email Channel Manager</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/accountHelper.cls
public class accountHelper {

	public static void createUpdateAccountAction(set<Id> accountIds){
		List<Account> passedAccounts = [select Id, OwnerId, Distributor_Name__c, Channel_Manager__c, Email_Channel_Manager__c, Email_Account_Owner__c from Account where Id in : accountIds];
		Map<Id,List<Account>> ownerAccountMap = new Map<Id,List<Account>>();
	
		for(Account acc : passedAccounts){
			if(acc.OwnerId != null){
				if(ownerAccountMap.containsKey(acc.OwnerId)){
					List<Account> accounts = ownerAccountMap.get(acc.OwnerId);
					accounts.add(acc);
					ownerAccountMap.put(acc.OwnerId,accounts);
				}else{
					List<Account> accounts = new List<Account>();
					accounts.add(acc);
					ownerAccountMap.put(acc.OwnerId,accounts);
				}
			}
		}
		
		List<User> userList = [select Id, Name, Distributor_Name__c, Channel_Manager__c, Email_Channel_Manager__c, Email from User where Id in : ownerAccountMap.keySet()];
		List<Account> accountsToUpdate = new List<Account>();
		
		for(User owner : userList){
			for(Account acc : ownerAccountMap.get(owner.Id)){
				acc.Distributor_Name__c = owner.Distributor_Name__c;
				acc.Channel_Manager__c = owner.Channel_Manager__c; 
				acc.Email_Channel_Manager__c = owner.Email_Channel_Manager__c; 
				acc.Email_Account_Owner__c = owner.Email;
				accountsToUpdate.add(acc);
			}
		}
		
		if(accountsToUpdate.size() > 0){
			update accountsToUpdate;
		}
	}

}