force-app/main/default/objects/Account/fields/Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Manager__c</fullName>
    <inlineHelpText>If the Account is owned by a distribution partner, this field indicates the channel manager. Else it is the same as the Owner. Copied from User settings.</inlineHelpText>
    <label>Old Channel Manager</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>Email_Channel_Manager__c</fullName>
    <inlineHelpText>Email address of the channel manager. Copied from User settings.</inlineHelpText>
    <label>Email Channel Manager</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Manager__c</fullName>
    <formula>Account.New_Channel_Manager__r.FirstName&amp;&quot; &quot;&amp;Account.New_Channel_Manager__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Copied from Account</inlineHelpText>
    <label>Channel Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserTestDataFactory.cls
@isTest
public class UserTestDataFactory  extends TestDataFactory {
    public UserTestDataFactory() {
        super('user');
    }

    public override sObject initializeRecord(){
         Profile prof = [SELECT Id FROM Profile WHERE Name='Management'];
        User u_user = new User();
                        u_user.Alias = 'atan';
                        u_user.Email='newuser@testorg.com'; 
                        u_user.EmailEncodingKey='UTF-8'; 
                        u_user.LastName='Testing';
                        u_user.LanguageLocaleKey='en_US';
                        u_user.LocaleSidKey='en_US';
                        u_user.ProfileId = prof.Id;
                        u_user.TimeZoneSidKey='America/Los_Angeles';
                        u_user.UserName='u_user@testorg.com';
                        u_user.IsActive = true;
        return u_user;
    }

    public override sObject createRecord() {
        User u = (User)initializeRecord();
        Insert u;
        return u;
    }

    public sObject createRecord(sObject record) {
        Insert record;
        return record;
    }

    public override List<sObject> createBulkRecords() {
        for (Integer i = 0; i < numberOfRecords; i++) {
            recordsList.add((User)initializeRecord());
        }
        Insert recordsList;
        return recordsList;
    }

    public User updateRecords(User toupdate) {
        update toupdate;
        return toupdate;
    }

    public User createTestUser(String fName, String lName)
    {
        Id profId = '00e200000015GYr'; // chatter free user
        
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        
       
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        
        Id roleID = '00E20000000urlW'; //Corporate
        
        
        User tuser = new User(  firstname = fName,
                                lastName = lName,
                                email = uniqueName + 'test@u-blox.com',
                                Username = uniqueName + 'test@u-blox.com',
                                EmailEncodingKey = 'ISO-8859-1',
                                Alias = uniqueName.substring(18, 23),
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US',
                                IsActive = true,
                                ProfileId = profId
                                );
        insert tuser;
        
        return tuser;
    }

    public User createPortalUser(string userLName, string userEmail, string uBOffice, string profileName){
        User testUser = null;
        list<Profile> profList = [select id,Name from Profile where Name =: profileName];
        AccountTestDataFactory accountTestDataFactory = new AccountTestDataFactory();
        ContactTestDataFactory contactTestDataFactory = new ContactTestDataFactory();
        Contact contact = (Contact)contactTestDataFactory.createRecord();
        Account account = (Account)accountTestDataFactory.createRecord();
        contact.accountid = account.id;
        update contact;
        if(profList.size() > 0){
            
            testUser = new User(
                Alias = 'standt', 
                Email = (userEmail == NULL)? 'apex-test@u-blox.com' : userEmail, 
                EmailEncodingKey = 'UTF-8', 
                LastName = (userLName == NULL)? 'Mukul Bandodkar' : userLName, 
                LanguageLocaleKey = 'en_US', 
                LocaleSidKey = 'en_US', 
                ProfileId = profList[0].Id,
                ContactId = contact.Id,
                Channel_Manager__c = 'Test Manager',
                Email_Channel_Manager__c = 'apex-test-manager@u-blox.com',
                TimeZoneSidKey = 'America/Los_Angeles', 
                UserName = (userEmail == NULL)? 'apex-test'+(integer)Math.floor((Math.random()*5000))+ '@u-blox.com' : userEmail + (integer)Math.floor((Math.random()*5000)),
                uB_Office__c = (uBOffice == NULL)? 'EMEA' : uBOffice
            );           
            insert testUser; 
        }        
        return testUser;
    }
}