force-app/main/default/objects/Account/fields/Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Manager__c</fullName>
    <inlineHelpText>If the Account is owned by a distribution partner, this field indicates the channel manager. Else it is the same as the Owner. Copied from User settings.</inlineHelpText>
    <label>Old Channel Manager</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <description>See Worksflow for RMA.</description>
    <inlineHelpText>Name of distributor will be copied to the field with the same name of all RMAs connected to this account. The sharing rule will ensure access to these RMAs</inlineHelpText>
    <label>Distributor Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>Email_Channel_Manager__c</fullName>
    <inlineHelpText>Email address of the channel manager. Copied from User settings.</inlineHelpText>
    <label>Email Channel Manager</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Manager__c</fullName>
    <formula>Account.New_Channel_Manager__r.FirstName&amp;&quot; &quot;&amp;Account.New_Channel_Manager__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Copied from Account</inlineHelpText>
    <label>Channel Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

force-app/main/default/classes/updateContactOwnerTest.cls
/*
    Name         : updateContactOwnerTest
    Author       : ldra
    Date         : 2019-02-04
    Description  : This class covers updateContactOwner class.
*/
@isTest
public class updateContactOwnerTest{
    
    @testSetup static void setup() {

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1]; 
        
        // Create new User
        User u = new User(Alias = 'standt', Email='apex-test@u-blox.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', UserName='apex-test@u-blox.com',
                         uB_Office__c='EMEA', Channel_Manager__c='Apex Test', Email_Channel_Manager__c='apex-test2@u-blox.com', Distributor_Name__c='Internal'
                         );
        insert u;
        
        // Create new Account
        Account a = new Account(name= 'Test updateContactOwnerTest', ShippingCity = 'Zurich', ShippingPostalCode = '8000', ShippingStreet = 'Hauptstrasse 1', OwnerId = u.Id);
        insert a;
    }
    
    @isTest static void testExecute() {
        Account a = [SELECT Id, OwnerId FROM Account WHERE Name = 'Test updateContactOwnerTest'];
        System.debug('account: '+a);
        
        // Create a new Contact
        Contact c = new Contact(LastName = 'Last', FirstName = 'First', Email = 'apex-test@u-blox.com', AccountId = a.Id);
        insert c;   

        Contact cs = [SELECT OwnerId FROM Contact WHERE Id =: c.Id];
        System.debug('contact: '+cs);
        
        System.assertEquals(a.OwnerId, cs.OwnerId);                                                
    } 
}