force-app/main/default/objects/Account/fields/Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Manager__c</fullName>
    <inlineHelpText>If the Account is owned by a distribution partner, this field indicates the channel manager. Else it is the same as the Owner. Copied from User settings.</inlineHelpText>
    <label>Old Channel Manager</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>(From Abacus) Abacus customer number</inlineHelpText>
    <label>Customer No</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <description>See Worksflow for RMA.</description>
    <inlineHelpText>Name of distributor will be copied to the field with the same name of all RMAs connected to this account. The sharing rule will ensure access to these RMAs</inlineHelpText>
    <label>Distributor Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Email_Account_Owner__c</fullName>
    <inlineHelpText>Email address of the Account owner. Copied from User settings.</inlineHelpText>
    <label>Email Account Owner</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>Email_Channel_Manager__c</fullName>
    <inlineHelpText>Email address of the channel manager. Copied from User settings.</inlineHelpText>
    <label>Email Channel Manager</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Global_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Global_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of User that coordinates all activities with such a Global Account and its subsidiaries</description>
    <inlineHelpText>to be decided by regional sales heads

Coordination Tasks
- Strategic and tactic planning and guidance
- Information and action planning on all actual and potential projects.
- Quotations definition and approval
- Contact guidance
- Closing of deal</inlineHelpText>
    <label>Global Account Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Potential_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Potential_Competitor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to filter Accounts from the mailing list. Automatically ticked if you create a new Account with Name including Competitor Name (from Competitor object). Clear the check if it isn&apos;t.</description>
    <inlineHelpText>Used to filter Accounts from the mailing list. Automatically ticked if you create a new Account with Name including Competitor Name (from Competitor object). Clear the check if it isn&apos;t.</inlineHelpText>
    <label>Potential Competitor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Visiting_Address_changed__c.field-meta.xml
<CustomField>
    <fullName>Visiting_Address_changed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag is triggered by changes in the visiting (billing) address of the account, requiring a change in the related contacts. It is set by a workflow in the account record. An APEX Trigger/Class sets the Visiting Address changed flag in the related Contact records.</description>
    <label>Visiting Address changed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Object to capture general data about competitors</description>
    <label>Competitor</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Manager__c</fullName>
    <formula>Account.New_Channel_Manager__r.FirstName&amp;&quot; &quot;&amp;Account.New_Channel_Manager__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Copied from Account</inlineHelpText>
    <label>Channel Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Visiting_Address_changed__c.field-meta.xml
<CustomField>
    <fullName>Visiting_Address_changed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>set by an APEX Class to trigger an update of the Contact address fields</description>
    <label>Visiting Address changed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of all countries and mapping to sales people. Used to automatically assign Accounts when created by OnDemand Service (ISA).</description>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <label>ISO Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <label>uB Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountObjectHelper.cls
Public Class AccountObjectHelper{
    
    public static List<Contract> getContractsForOwnerWithRestriction(Map<Id,List<Id>> accMapWithOwnerChange,Map<ID,sObject> oldAccountMap)
    {    
        List<Contract> conList = new List<Contract>();
        
        // Get the profile name list from custom setting
        List<string> profilesToRestrict = CommonUtils.getRestrictedProfilesForContract();        
        
        if(accMapWithOwnerChange!=null && accMapWithOwnerChange.size()>0)
        {
            List<ID> accIds = new List<ID>();
            Set<ID> userIds = new Set<ID>();
            
            // Query all user from accMapWithOwnerChange to get profile Name to filter list of accounts 
            for(User userObj :[select id,profileid,profile.name from user where id in: accMapWithOwnerChange.keySet() AND profile.Name in: profilesToRestrict ] )
            {
                if(accMapWithOwnerChange.get(userObj.id)!=null)
                {
                    accIds.addAll(accMapWithOwnerChange.get(userObj.id));
                    userIds.add(userObj.id);
                }        
            }
            
            
            if(accIds.size()>0 && userIds.size()>0)
            {
                // Get all the contracts for selected accounts + Owners and change the OwnerId to older ones
                for(Contract con : [select id,OwnerId,accountId from Contract where accountid in: accIds AND OwnerId in:userIds AND status ='Draft'])
                {
                    con.OwnerId = ((Account) oldAccountMap.get(con.accountId)).OwnerId;
                    conList.add(con);
                }              
            }    
        }
        
        return conList;
    }    
    /*getAccTeamRec method to get Account team record for new global Account Manager for insert purpose.
* Wiki Ticket # 58278
* Date 6/May/2020
*/
    public static List<AccountTeamMember> getAccTeamRec(map<Id,Id> accMap, Boolean isInsert){
        if(isInsert != NULL && !isInsert) {
            // searching accMap in Account Team Member (then we even more shrink the map to have only data we need)           
            for(AccountTeamMember accTM : [Select id, teamMemberRole, account.Global_Account_Manager__c from AccountTeamMember where accountId =: accMap.keySet() and userId =: accMap.values() and TeamMemberRole != 'Global Account Manager']){
                // removing account from the map if user already added
                if( accTM.UserId == accMap.get(accTM.AccountId) ){
                    accMap.remove(accTM.AccountId);
                }
            }
        }
        
        List<AccountTeamMember> insertAccMember = new List<AccountTeamMember>();
        
        // loop through through prepared clean accMap
        for (Id atm_AccountId : accMap.keySet()) {
            Id atm_UserId = accMap.get(atm_AccountId);
            AccountTeamMember accTeamMember = new AccountTeamMember();
            accTeamMember.AccountId = atm_AccountId;
            accTeamMember.UserId = atm_UserId;
            accTeamMember.TeamMemberRole = 'Global Account Manager';
            accTeamMember.AccountAccessLevel = 'Read';
            accTeamMember.CaseAccessLevel = 'Read';
            accTeamMember.OpportunityAccessLevel = 'Read';
            insertAccMember.add(accTeamMember);
        }
        return insertAccMember;
    }
    /*getAccTeamForDel method to get Account team record for ex global Account Manager to delete the record.
* Wiki Ticket # 58278
* Date 6/May/2020
*/
    public static List<AccountTeamMember> getAccTeamForDel(map<Id,Id> accMap){
        List<AccountTeamMember> accTeams = new List<AccountTeamMember>();
        if(accMap != NULL){
            accTeams = [Select id from AccountTeamMember where AccountId =:accMap.keySet() and UserId =:accMap.values() and TeamMemberRole = 'Global Account Manager' ];
        }
        return accTeams;
    }
    
    /*isAccFromDiffrenetRegions method to check either the merging account are from same regions or from different regions.
* 
* Date 5/June/2020
*/
    public static Boolean isAccFromDiffrenetRegions(Map<String,Id> accRegionIdMap){
        Boolean isAccFromDiffRegion = False;
        
        for(Account tempAccount : [SELECT Ub_Office__c FROM Account WHERE Id IN : accRegionIdMap.values()]){
            for(String oldAccRegion : accRegionIdMap.keySet()){
                if(oldAccRegion != tempAccount.uB_Office__c){
                    isAccFromDiffRegion = True;
                }
            }
        }
        return isAccFromDiffRegion;
    }
    
    public static List<Account> updateOwnerEmailFields ( Map<Id,Id> accUserIdMap){
        
        map<Id,String> userIdOwnerEmail = new map<Id,String>();
        map<Id,String> userIdChannelManager = new map<Id,String>();
        map<Id,String> userIdDistributor = new map<Id,String>();
        map<Id,String> userIdEmailChannelManager = new map<Id,String>();
        List<Account> accountsToUpdate = new List<Account>();
        
        List<Account> accList = new List<Account>();
        if(!accUserIdMap.isEmpty()){
            
            
            accList = [SELECT Id, OwnerId, Distributor_Name__c, Channel_Manager__c, Email_Channel_Manager__c, Email_Account_Owner__c FROM Account where Id IN :accUserIdMap.keySet()];
            
            system.debug('in method');
            
            for(User userObj : [SELECT Id,Channel_Manager__c,Distributor_Name__c,Email_Channel_Manager__c,Email from user where ID IN :accUserIdMap.values()]){
                userIdOwnerEmail.put(userObj.Id, userObj.Email);
                userIdChannelManager.put(userObj.Id, userObj.Channel_Manager__c);
                userIdDistributor.put(userObj.Id, userObj.Distributor_Name__c);
                userIdEmailChannelManager.put(userObj.Id, userObj.Email_Channel_Manager__c);
            }
        }
        system.debug('userIdOwnerEmail-->>'+userIdOwnerEmail);
        for(Account accTemp : accList){//
            if( userIdOwnerEmail.containsKey(accTemp.OwnerId) ){
                
                accTemp.Distributor_Name__c = userIdDistributor.get(accTemp.OwnerId);
                accTemp.Channel_Manager__c = userIdChannelManager.get(accTemp.OwnerId);
                accTemp.Email_Channel_Manager__c = userIdEmailChannelManager.get(accTemp.OwnerId);
                accTemp.Email_Account_Owner__c = userIdOwnerEmail.get(accTemp.OwnerId);
                accountsToUpdate.add(accTemp);
            }
        }
        return accountsToUpdate;
    }
    
    Public static void updateAccOwnerCountryBase (List<Account> accLst, List<String> countryList,List<String> setStateCode){
        
        map<String,String> countryMap = new Map<String,String>();
        map<String,String> stateCodeMap = new Map<String,String>();
        
        Map<String,String> UbOfficeStateMap=new Map<String,String>();
        Map<String,String> UbOfficeCountryMap=new Map<String,String>();
        
        if(!CountryList.isEmpty() ||  !setStateCode.isEmpty()){
            
            
            for(Country__c tempCont : [SELECT Id,ISO_Code__c,ub_Office__c,OwnerId,state__c,state_Code__c from Country__c where ISO_Code__c IN :CountryList  OR state_Code__c IN :setStateCode]){
                //country can repeat, but code will not repeat, so set as state code
                if(!String.isEmpty(tempCont.state_Code__c)){
                    
                    stateCodeMap.put(tempCont.state_Code__c,tempCont.OwnerId);
                    //Dealing with Ub Office            
                    UbOfficeStateMap.put(tempCont.state_Code__c,tempCont.uB_Office__c);
                }else
                {
                    countryMap.put(tempCont.ISO_Code__c, tempCont.OwnerId);
                    UbOfficeCountryMap.put(tempCont.ISO_Code__c,tempCont.uB_Office__c);
                }
                
            }
        }
        for(Account acc : accLst )
        {
            if( !String.isEmpty( stateCodeMap.get(acc.shippingState )) ){
                
                acc.OwnerId = stateCodeMap.get(acc.shippingState);
            } else if(!String.isEmpty( countryMap.get(acc.ShippingCountry))){
                
                acc.OwnerId = countryMap.get(acc.ShippingCountry);
            }
            if(!String.isEmpty(UbOfficeStateMap.get(acc.ShippingState)) ){
                acc.uB_Office__c=UbOfficeStateMap.get(acc.ShippingState);   
            }else if(!String.isEmpty(UbOfficeCountryMap.get(acc.ShippingCountry))){
                acc.uB_Office__c=UbOfficeCountryMap.get(acc.ShippingCountry);   
            }
            system.debug('acc.OwnerId--->>>'+acc.OwnerId);
            system.debug('acc.uB_Office__c-->>'+acc.uB_Office__c);
        }
    }
    
    public static List<Contact> updateVisitingAddressCheckBox(Set<Id> accIds ){
        List<Contact> accContacts = new List<Contact>();
        if(!accIds.isEmpty()){
            
            
            for(Contact tempCon : [SELECT Visiting_Address_changed__c from Contact where AccountId IN :accIds]){
                tempCon.Visiting_Address_changed__c = true;
                accContacts.add(tempCon);
            }
        }
        return accContacts;
    }
    
    
    public static void checkCompetitor(List<Account> accLst, Set<String> compName,Set<String> compNameSub,Set<String> compNameExt ){
        
        
        List<String> Nam = new List<String>();
        if(!compName.isEmpty() || !compNameSub.isEmpty() || !compNameExt.isEmpty() ){
            for(Competitor__c tempComp : [SELECT Id,Name from Competitor__c where Name = :compName OR Name LIKE :compNameExt OR Name LIKE :compNameSub]){
                Nam.add(tempComp.Name);
            }
            
            String compNameStr = String.valueOf(Nam);
            for(Account tempAcc : accLst){
                
                String accNameSubString = tempAcc.Name.split(' ')[0];
                
                if(compNameStr.containsIgnoreCase(accNameSubString)  ||  compNameStr.containsIgnoreCase(tempAcc.Name)){
                    tempAcc.Potential_Competitor__c = true;
                    system.debug('tempAcc.Potential_Competitor__c00>>'+tempAcc.Potential_Competitor__c);
                }
            }
        }
        
    }
    
    
    public static void preventUpdateAbacusAccount(List<Account> accLst){
        list<User> currentUser=[select isUserSpecial__c, Profile.Name from user where Id=:UserInfo.getUserId()];
        Set<String> setProfile = new Set<String>{'system administrator','automatic process'};
        for(Account acc : accLst )
        {
            Account accOld = (Account) Trigger.oldMap.get(acc.id);
            if(currentUser != null && accOld != null){
                if( !BeforeUpdateAbacusAccount.fromAbacus 
                    && !currentUser[0].isUserSpecial__c 
                    && !setProfile.contains(currentUser[0].profile.Name.toLowerCase()) 
                    && (!String.isBlank(accOld.ShippingStreet) 
                        || !String.isBlank(accOld.ShippingState) 
                        || !String.isBlank(accOld.ShippingCity) 
                        || !String.isBlank(accOld.ShippingPostalCode) 
                        || !String.isBlank(accOld.ShippingCountry))){
                    // address condition can be discussed
                    if(acc.Name!=accOld.Name ){
                        acc.Name.addError(AccountTriggerHandler.errorMessage);
                    }
                    if(acc.Phone!=accOld.Phone ){
                        acc.Phone.addError(AccountTriggerHandler.errorMessage);
                    }
                    if(acc.Fax!=accOld.Fax ){
                        acc.Fax.addError(AccountTriggerHandler.errorMessage);
                    }
                    if(acc.Customer_No__c!=accOld.Customer_No__c ){
                        acc.Customer_No__c.addError(AccountTriggerHandler.errorMessage);
                    }
                }
            }            
        }
    }   
    
}