force-app/main/default/objects/Account/fields/Current_User_Internal__c.field-meta.xml
<CustomField>
    <fullName>Current_User_Internal__c</fullName>
    <description>Used to flag the current user is an internal user, made for Process Builder to enable Chatter post.
OLD
NOT(OR(
$User.ProfileId = &quot;00eD000000160IL&quot;, /* Distributor Limited FAE */
$User.ProfileId = &quot;00eD00000015ehS&quot;, /* Distributor team */
$User.ProfileId = &quot;00eD00000015Trl&quot;, /* Gold Partner User */
$User.ProfileId = &quot;00eD00000015UEf&quot;, /* Distributor Standard */
$User.ProfileId = &quot;00eD000000160Nk&quot;, /* Distributor Standard FAE */
$User.ProfileId = &quot;00e57000001AvLY&quot;, /* Distributor RFD */
$User.ProfileId = &quot;00eD00000016DpY&quot;, /* Distributor team extended */
$User.ProfileId = &quot;00e57000001AvOm&quot;, /* Distributor RFD FAE */
$User.ProfileId = &quot;00e57000001tRer&quot;, /* Distributor SE FAE */
$User.ProfileId = &quot;00e57000001J6wk&quot;, /* Partner Community Distributor Standard */
$User.ProfileId = &quot;00e57000001J73W&quot; /* Partner Community Distributor team extended */
))</description>
    <formula>AND(
  ISPICKVAL($User.UserType,&quot;Standard&quot;),
  $User.ProfileId &lt;&gt; &quot;00e2p000001opLR&quot;, /* Partner Base */
  $User.ProfileId &lt;&gt; &quot;00e2p000001opYk&quot;, /* Partner Base Quotation */
  $UserRole.Id &lt;&gt; &quot;00E57000001DHfr&quot; /* RF Design (distributor) */
)</formula>
    <inlineHelpText>Used to flag the current user is an internal user, made for Process Builder to enable Chatter post.</inlineHelpText>
    <label>Current User Internal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/FAE__c.field-meta.xml
<CustomField>
    <fullName>FAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>u-blox FAE responsible for this Account</description>
    <inlineHelpText>u-blox FAE responsible for this Account</inlineHelpText>
    <label>FAE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Initiator_Source__c.field-meta.xml
<CustomField>
    <fullName>Case_Initiator_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field if the case is opened for someone else (Case Initiator &lt;&gt; Created by)</inlineHelpText>
    <label>Case Initiator Source</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases_initiated</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Created_By_Partner__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be updated through workflow</description>
    <inlineHelpText>Checked if the Case is created by our partner users (distributors), updated through workflow.</inlineHelpText>
    <label>Created By Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Current_User_Internal__c.field-meta.xml
<CustomField>
    <fullName>Current_User_Internal__c</fullName>
    <description>Used to flag the current user is an internal user, made for Process Builder to enable Chatter post.
OLD
NOT(OR(
$User.ProfileId = &quot;00eD000000160IL&quot;, /* Distributor Limited FAE */
$User.ProfileId = &quot;00eD00000015ehS&quot;, /* Distributor team */
$User.ProfileId = &quot;00eD00000015Trl&quot;, /* Gold Partner User */
$User.ProfileId = &quot;00eD00000015UEf&quot;, /* Distributor Standard */
$User.ProfileId = &quot;00eD000000160Nk&quot;, /* Distributor Standard FAE */
$User.ProfileId = &quot;00e57000001AvLY&quot;, /* Distributor RFD */
$User.ProfileId = &quot;00eD00000016DpY&quot;, /* Distributor team extended */
$User.ProfileId = &quot;00e57000001AvOm&quot;, /* Distributor RFD FAE */
$User.ProfileId = &quot;00e57000001tRer&quot; /* Distributor SE FAE */
))</description>
    <formula>AND(
  ISPICKVAL($User.UserType,&quot;Standard&quot;),
  $User.ProfileId &lt;&gt; &quot;00e2p000001opLR&quot;, /* Partner Base */
  $User.ProfileId &lt;&gt; &quot;00e2p000001opYk&quot;, /* Partner Base Quotation */
  $UserRole.Id &lt;&gt; &quot;00E57000001DHfr&quot; /* RF Design (distributor) */
)</formula>
    <inlineHelpText>Used to flag the current user is an internal user, made for Process Builder to enable Chatter post.</inlineHelpText>
    <label>Current User Internal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_Escalated_by_AE_APAC__c.field-meta.xml
<CustomField>
    <fullName>Date_Escalated_by_AE_APAC__c</fullName>
    <label>Date Escalated by AE APAC</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_Escalated_by_FAE__c.field-meta.xml
<CustomField>
    <fullName>Date_Escalated_by_FAE__c</fullName>
    <label>Date Escalated by FAE</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_Escalated_by_FAE_Leader__c.field-meta.xml
<CustomField>
    <fullName>Date_Escalated_by_FAE_Leader__c</fullName>
    <label>Date Escalated by FAE Leader</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_Escalated_by_TM__c.field-meta.xml
<CustomField>
    <fullName>Date_Escalated_by_TM__c</fullName>
    <label>Date Escalated by TM</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Escalation_Source__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Source__c</fullName>
    <formula>IF(OR($User.ProfileId=&quot;00e200000015FVB&quot;,$User.ProfileId=&quot;00e2p000001BMJg&quot;),&quot;TM&quot;,
  IF(ISPICKVAL($User.uB_Office__c,&quot;Rest of APAC&quot;),&quot;AE APAC&quot;,
    IF($User.Team_Leader__c,&quot;FAE Leader&quot;,&quot;FAE&quot;)
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Escalation Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FAE__c.field-meta.xml
<CustomField>
    <fullName>FAE__c</fullName>
    <description>FAE of the Account</description>
    <formula>Account.FAE__r.Alias</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>FAE of the Account</inlineHelpText>
    <label>FAE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/is_Escalated_to_L2__c.field-meta.xml
<CustomField>
    <fullName>is_Escalated_to_L2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Escalated to L2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Send_Notification_Mail__c.field-meta.xml
<CustomField>
    <fullName>Send_Notification_Mail__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked by buttons when Case has been escalated or returned. This triggers a notification mail to be sent to the new owner.</inlineHelpText>
    <label>Send Notification Mail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>The technology of the product.</description>
    <label>Technology</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GNSS</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Type__mdt/Case_Type__mdt.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <pluralLabel>Case Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Type__mdt/fields/category__c.field-meta.xml
<CustomField>
    <fullName>category__c</fullName>
    <label>category</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Support__mdt/Channel_Support__mdt.object-meta.xml
<CustomObject>
    <label>Channel Level Support</label>
    <pluralLabel>Channel Support</pluralLabel>
</CustomObject>

force-app/main/default/objects/External_FAE__mdt/External_FAE__mdt.object-meta.xml
<CustomObject>
    <label>External FAE</label>
    <pluralLabel>External FAEs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Partners_with_case_access__mdt/Partners_with_case_access__mdt.object-meta.xml
<CustomObject>
    <label>Partners with case access</label>
    <pluralLabel>Partners with case access</pluralLabel>
</CustomObject>

force-app/main/default/objects/Partners_with_case_access__mdt/fields/ub_Office__c.field-meta.xml
<CustomField>
    <fullName>ub_Office__c</fullName>
    <label>ub Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Support_Level2__mdt/Support_Level2__mdt.object-meta.xml
<CustomObject>
    <label>Level 2 Support</label>
    <pluralLabel>Level 2 Support</pluralLabel>
</CustomObject>

force-app/main/default/objects/Support_Level2__mdt/fields/Queue__c.field-meta.xml
<CustomField>
    <fullName>Queue__c</fullName>
    <label>Queue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceCloud_EscalationHandler.cls
public virtual class ServiceCloud_EscalationHandler {
    private Case supportCase = new Case();
    private User currentUser = new User();
    private static final set<string> PARTNERS_FAE = new set<string>();
    private static final map<string, string> CHANNEL_SUPPORT = new map<string, string>();
    private static final map<string, string> SUPPORT_L2 = new map<string, string>();
    private static final set<string> EXTERNAL_FAE = new set<string>();
    private static final map<string, set<string>> CASE_TYPE = new map<string, set<string>>();
    private static final map<string,Id> QUEUE_MAP = new map<string,Id>();
    private static final set<Id> CHANNEL_FAE = new set<Id>();
        
    public void setCaseToEscalate(Case c){
        supportCase = c;
    }

    public void setContextUser(User u){
        currentUser = u;
    }

    public ServiceCloud_EscalationHandler(){
        if(CHANNEL_SUPPORT.isEmpty()){
            for(Channel_Support__mdt ch : [Select Label,Queue__c from Channel_Support__mdt]){
                CHANNEL_SUPPORT.put(ch.Label, ch.Queue__c);
            }
        }
        if(CHANNEL_FAE.isEmpty()){
            for(GroupMember cFAE: [SELECT UserOrGroupId FROM GroupMember where Group.Name LIKE '%Channel']){
                CHANNEL_FAE.add(cFAE.UserOrGroupId);
            }
        }
        if(SUPPORT_L2.isEmpty()){
            for(Support_Level2__mdt TM : [Select Label,Queue__c from Support_Level2__mdt]){
                SUPPORT_L2.put(TM.Label, TM.Queue__c);
            }
        }
        if(EXTERNAL_FAE.isEmpty()){
            for(External_FAE__mdt eFAE : [Select Label from External_FAE__mdt]){
                EXTERNAL_FAE.add(eFAE.Label); 
            }
        }
        if(PARTNERS_FAE.isEmpty()){
            for(Partners_with_case_access__mdt partner: [Select Label from Partners_with_case_access__mdt]){
                PARTNERS_FAE.add(partner.Label);                        
            }
        }
        if(CASE_TYPE.isEmpty()){
            for(Case_Type__mdt cType: [Select Label,category__c from Case_Type__mdt]){
                if(CASE_TYPE.get(cType.category__c) == null)            
                    CASE_TYPE.put(cType.category__c, new set<string>());
                CASE_TYPE.get(cType.category__c).add(cType.Label);            
            }
        }
        if(QUEUE_MAP.isEmpty()){
            for(QueueSobject Q: [SELECT QueueId, Queue.Name FROM QueueSobject where SobjectType = 'Case' limit 1000]){
                QUEUE_MAP.put(Q.Queue.Name,Q.QueueId);
            }
        }        
    }

    public virtual Case escalateCase(){
        this.validateUserAndCaseInputs();
        if(this.caseTypeQuality() 
            && currentUser.uB_Office__c == ServiceCloud_Constants.CASE_REGION_EMEA
            && currentUser.ProfileId != ServiceCloud_Constants.PARTNER_PORTAL_PROFILE
            && currentUser.ProfileId != ServiceCloud_Constants.PARTNER_BASE_PROFILE){
            this.assignToQualityQueue();
        }else{
            if(currentUser.ProfileId == ServiceCloud_Constants.PARTNER_PORTAL_PROFILE 
                || currentUser.ProfileId == ServiceCloud_Constants.PARTNER_BASE_PROFILE){
                this.escalateToChannelSupport();            
            }else if(ServiceCloud_Constants.EXTERNAL_USER_ROLE.contains(currentUser.UserRole.Name)
                && (EXTERNAL_FAE.contains(supportCase.owner.Name) 
                    || EXTERNAL_FAE.contains(supportCase.Account.FAE__r.Name))){
                this.escalateToSupportQueue();
            }else if(ServiceCloud_Constants.FAE_PROFILE.contains(currentUser.Profile.Name) && !supportCase.is_Escalated_to_L2__c){
                supportCase.is_Escalated_to_L2__c = true;
                this.escalateToLevel2Support();
            }else this.escalateToLevel3Support();
        }
        this.finish();
        return supportCase;
    }

    protected void escalateToChannelSupport(){
        supportCase.OwnerId = QUEUE_MAP.get(CHANNEL_SUPPORT.get(currentUser.uB_Office__c));
    }

    protected void escalateToLevel2Support(){
        if(currentUser.uB_Office__c == ServiceCloud_Constants.CASE_REGION_EMEA){            
            this.assignToAEQueue();
            /*if(CHANNEL_FAE.contains(currentUser.Id) 
                || CHANNEL_FAE.contains(supportCase.ownerId) 
                || CHANNEL_FAE.contains(supportCase.Account.FAE__c)){
                supportCase.OwnerId = QUEUE_MAP.get(SUPPORT_L2.get(currentUser.uB_Office__c));
            }else this.assignToAEQueue();*/              
        }else supportCase.OwnerId = QUEUE_MAP.get(SUPPORT_L2.get(currentUser.uB_Office__c));        
    }

    protected void escalateToSupportQueue(){
        supportCase.OwnerId = QUEUE_MAP.get(ServiceCloud_Constants.QUEUE_SUPPORT_EMEA);
    }

    protected void escalateToLevel3Support(){        
        if(this.caseTypeQuality()){
            this.assignToQualityQueue();
        }else this.assignToAEQueue(); 
    }

    protected void assignToAEQueue(){
        this.validateCaseTechnology();
        supportCase.OwnerId = QUEUE_MAP.get(ServiceCloud_Constants.TECH_QUEUE_MAP.get(supportCase.Technology__c));               
    }

    protected void assignToQualityQueue(){ 
        supportCase.OwnerId = QUEUE_MAP.get(ServiceCloud_Constants.QUALITY);        
    }

    public virtual void finish(){
        if(supportCase.Case_Initiator_Source__c == null){ 
            supportCase.Case_Initiator_Source__c = supportCase.CreatedById; 
        }        
        if(supportCase.Escalation_Source__c == ServiceCloud_Constants.ESCALATION_SRC_TM){ 
            supportCase.Date_Escalated_by_TM__c = system.now();
        }else if (supportCase.Escalation_Source__c == ServiceCloud_Constants.ESCALATION_SRC_FAE_LEAD){ 
            supportCase.Date_Escalated_by_FAE_Leader__c = system.now();
        }else if (supportCase.Escalation_Source__c == ServiceCloud_Constants.ESCALATION_SRC_AE_APAC){ 
            supportCase.Date_Escalated_by_AE_APAC__c = system.now();
        }else if (ServiceCloud_Constants.FAE_PROFILE.contains(supportCase.Escalation_Source__c)){ 
            if(supportCase.Created_By_Partner__c && supportCase.Current_User_Internal__c){ 
                supportCase.Date_Escalated_by_TM__c = system.now();                
            }else supportCase.Date_Escalated_by_FAE__c = system.now();
        }
        supportCase.Send_Notification_Mail__c = true;
        supportCase.IsEscalated = true;
        supportCase.Status = ServiceCloud_Constants.ESCALATED;                
    }

    private void validateCaseTechnology(){
        if(supportCase.Technology__c == null){
            throw new ApexException(Label.Case_Technology); 
        }else if(supportCase.Technology__c == ServiceCloud_Constants.CASE_TECH_OTHER){
            throw new ApexException(Label.Case_Other_Technology);
        }
    }

    private void validateUserAndCaseInputs(){
        if(supportCase == NULL || currentUser == NULL){ 
            throw new ApexException('Case and user properties must be set to escalate the case');            
        }
        if(currentUser.uB_Office__c == NULL){
            throw new ApexException('u-blox office not mentioned in your user record');
        }
    }

    private boolean caseTypeQuality(){
        if(CASE_TYPE.get(ServiceCloud_Constants.QUALITY).contains(supportCase.Type)){
            return true;
        }
        return false;
    }
}