force-app/main/default/objects/Account/fields/Current_User_Internal__c.field-meta.xml
<CustomField>
    <fullName>Current_User_Internal__c</fullName>
    <description>Used to flag the current user is an internal user, made for Process Builder to enable Chatter post.
OLD
NOT(OR(
$User.ProfileId = &quot;00eD000000160IL&quot;, /* Distributor Limited FAE */
$User.ProfileId = &quot;00eD00000015ehS&quot;, /* Distributor team */
$User.ProfileId = &quot;00eD00000015Trl&quot;, /* Gold Partner User */
$User.ProfileId = &quot;00eD00000015UEf&quot;, /* Distributor Standard */
$User.ProfileId = &quot;00eD000000160Nk&quot;, /* Distributor Standard FAE */
$User.ProfileId = &quot;00e57000001AvLY&quot;, /* Distributor RFD */
$User.ProfileId = &quot;00eD00000016DpY&quot;, /* Distributor team extended */
$User.ProfileId = &quot;00e57000001AvOm&quot;, /* Distributor RFD FAE */
$User.ProfileId = &quot;00e57000001tRer&quot;, /* Distributor SE FAE */
$User.ProfileId = &quot;00e57000001J6wk&quot;, /* Partner Community Distributor Standard */
$User.ProfileId = &quot;00e57000001J73W&quot; /* Partner Community Distributor team extended */
))</description>
    <formula>AND(
  ISPICKVAL($User.UserType,&quot;Standard&quot;),
  $User.ProfileId &lt;&gt; &quot;00e2p000001opLR&quot;, /* Partner Base */
  $User.ProfileId &lt;&gt; &quot;00e2p000001opYk&quot;, /* Partner Base Quotation */
  $UserRole.Id &lt;&gt; &quot;00E57000001DHfr&quot; /* RF Design (distributor) */
)</formula>
    <inlineHelpText>Used to flag the current user is an internal user, made for Process Builder to enable Chatter post.</inlineHelpText>
    <label>Current User Internal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/FAE__c.field-meta.xml
<CustomField>
    <fullName>FAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>u-blox FAE responsible for this Account</description>
    <inlineHelpText>u-blox FAE responsible for this Account</inlineHelpText>
    <label>FAE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Initiator_Source__c.field-meta.xml
<CustomField>
    <fullName>Case_Initiator_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field if the case is opened for someone else (Case Initiator &lt;&gt; Created by)</inlineHelpText>
    <label>Case Initiator Source</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases_initiated</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Created_By_Partner__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be updated through workflow</description>
    <inlineHelpText>Checked if the Case is created by our partner users (distributors), updated through workflow.</inlineHelpText>
    <label>Created By Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Current_User_Internal__c.field-meta.xml
<CustomField>
    <fullName>Current_User_Internal__c</fullName>
    <description>Used to flag the current user is an internal user, made for Process Builder to enable Chatter post.
OLD
NOT(OR(
$User.ProfileId = &quot;00eD000000160IL&quot;, /* Distributor Limited FAE */
$User.ProfileId = &quot;00eD00000015ehS&quot;, /* Distributor team */
$User.ProfileId = &quot;00eD00000015Trl&quot;, /* Gold Partner User */
$User.ProfileId = &quot;00eD00000015UEf&quot;, /* Distributor Standard */
$User.ProfileId = &quot;00eD000000160Nk&quot;, /* Distributor Standard FAE */
$User.ProfileId = &quot;00e57000001AvLY&quot;, /* Distributor RFD */
$User.ProfileId = &quot;00eD00000016DpY&quot;, /* Distributor team extended */
$User.ProfileId = &quot;00e57000001AvOm&quot;, /* Distributor RFD FAE */
$User.ProfileId = &quot;00e57000001tRer&quot; /* Distributor SE FAE */
))</description>
    <formula>AND(
  ISPICKVAL($User.UserType,&quot;Standard&quot;),
  $User.ProfileId &lt;&gt; &quot;00e2p000001opLR&quot;, /* Partner Base */
  $User.ProfileId &lt;&gt; &quot;00e2p000001opYk&quot;, /* Partner Base Quotation */
  $UserRole.Id &lt;&gt; &quot;00E57000001DHfr&quot; /* RF Design (distributor) */
)</formula>
    <inlineHelpText>Used to flag the current user is an internal user, made for Process Builder to enable Chatter post.</inlineHelpText>
    <label>Current User Internal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Escalation_Source__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Source__c</fullName>
    <formula>IF(OR($User.ProfileId=&quot;00e200000015FVB&quot;,$User.ProfileId=&quot;00e2p000001BMJg&quot;),&quot;TM&quot;,
  IF(ISPICKVAL($User.uB_Office__c,&quot;Rest of APAC&quot;),&quot;AE APAC&quot;,
    IF($User.Team_Leader__c,&quot;FAE Leader&quot;,&quot;FAE&quot;)
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Escalation Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FAE__c.field-meta.xml
<CustomField>
    <fullName>FAE__c</fullName>
    <description>FAE of the Account</description>
    <formula>Account.FAE__r.Alias</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>FAE of the Account</inlineHelpText>
    <label>FAE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/is_Escalated_to_L2__c.field-meta.xml
<CustomField>
    <fullName>is_Escalated_to_L2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Escalated to L2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/isDirect__c.field-meta.xml
<CustomField>
    <fullName>isDirect__c</fullName>
    <formula>AND(NOT(ISBLANK(Account.Distributor__c)), CONTAINS(UPPER(Account.Distributor__c),&apos;DIRECT&apos;))</formula>
    <label>Direct Case Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>The technology of the product.</description>
    <label>Technology</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GNSS</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/TransferOwnerId__c.field-meta.xml
<CustomField>
    <fullName>TransferOwnerId__c</fullName>
    <formula>/* If Type=Audit, assign to Queue &quot;Quality&quot; */
IF(ISPICKVAL(Type,&quot;Audit&quot;),&quot;00G20000001Lsn7&quot;,
  /* If created by the partner user and the current user is FAE Partner or Partner Base, assign to the Manager. */
  IF(AND(Created_By_Partner__c,OR($Profile.Id=&quot;00e57000001YbiK&quot;,$Profile.Id=&quot;00e2p000001opLR&quot;,ISPICKVAL($User.UserType,&quot;Partner&quot;))),$User.ManagerId,
    /* If created by the partner user and the current user is FAE in EMEA, assign to Quality or the corresponding AE. */
    IF(AND(Created_By_Partner__c,$UserRole.Id=&quot;00E20000000uqdP&quot;,$Profile.Id=&quot;00e20000000zSSg&quot;),
      CASE(TEXT(Technology__c),
        &quot;Cellular&quot;,&quot;00G20000001Lsac&quot;,
        &quot;Short Range&quot;,&quot;00GD0000003uWXg&quot;,
        &quot;00G20000001LsZy&quot;
      ),
      /* The Case assignment is defined by the field in User object. */
      CASE(TEXT(Technology__c),
        &quot;Cellular&quot;,$User.CaseNextOwnerIDCEL__c,
        &quot;Short Range&quot;,$User.CaseNextOwnerIDSHO__c,
        $User.CaseNextOwnerIDPOS__c
      )
    )
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TransferOwnerId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EscalateCtrl.cls
global without sharing class EscalateCtrl {
    private static ServiceCloud_EscalationHandler eHandler = null;
    
    public EscalateCtrl(ApexPages.StandardController controller) {
        
    }
    
    @RemoteAction
    global static Boolean escalateCaseId(String CaseId){ 
        if(CaseId==null) return false;         
        
        Case c = [Select Id,
                    Account.uB_Office__c,                    
                    Account.FAE__r.Name,
                    Account.owner.Name,
                    isDirect__c,
                    OwnerId, 
                    Owner.Name, 
                    Type,
                    Status, 
                    TransferOwnerId__c, 
                    Escalation_Source__c, 
                    Case_Initiator_Source__c, 
                    CreatedById, 
                    Created_By_Partner__c, 
                    Technology__c, 
                    Current_User_Internal__c,
                    is_Escalated_to_L2__c,
                    lastModifiedDate,
                    lastModifiedById
                    from Case where Id=:CaseId];
        
        User u = [Select Id,
                    Name,
                    uB_Office__c, 
                    UserType, 
                    ManagerId, 
                    CaseNextOwnerIDSER__c, 
                    CaseNextOwnerIDCEL__c, 
                    CaseNextOwnerIDSHO__c, 
                    CaseNextOwnerIDPOS__c, 
                    ProfileId,
                    Profile.Name,
                    UserRoleId,
                    UserRole.Name
                    from User where Id=:userinfo.getuserId()];        
        
        //String UserId = UserInfo.getUserId();
        String OwnerId = c.OwnerId;
        string givenTimeDiff = Label.Case_Escalation_Time_Difference_in_Seonds;
        givenTimeDiff = givenTimeDiff == null? '5' : givenTimeDiff;
        Integer requiredTimeDifference = Integer.valueOf(givenTimeDiff);

        Long diffInSeconds = utility.getTimeDifferenceInSeconds(DateTime.now(), c.lastModifiedDate);                
        // Case can not be escalated again in less than 30 seconds for same user
        if(c.Status == 'Escalated' && c.lastModifiedById == u.Id && diffInSeconds < requiredTimeDifference){            
            throw new ApexException(Label.Case_Double_Escalation_Message);
        }
        
        // if member is user add to team member (user-005,queue-00G)
        if( OwnerId.startsWith('005')) {
            // create a CaseTeamMember record for the actual owner of the case        
            Boolean memberExists = [Select COUNT() from CaseTeamMember where ParentId=:CaseId and MemberId=:OwnerId LIMIT 1] > 0;
            if(memberExists == false){ 
                CaseTeamMember ctm =new CaseTeamMember(
                    ParentId = c.Id,
                    MemberId = OwnerId,
                    TeamRoleId = '0B7D0000000CanX' // standard team role (first and only available) 
                );
                insert ctm;
            }
        }
        
        if(eHandler == null){
            eHandler =  new ServiceCloud_EscalationHandler();
        }
        eHandler.setCaseToEscalate(c);
        eHandler.setContextUser(u);
        c = eHandler.escalateCase();        
        if(!Test.isRunningTest()){ 
            update c;
        }
        return true;
    }
}