force-app/main/default/objects/Account/fields/Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>(From Abacus) Abacus customer number</inlineHelpText>
    <label>Customer No</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Global_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Global_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of User that coordinates all activities with such a Global Account and its subsidiaries</description>
    <inlineHelpText>to be decided by regional sales heads

Coordination Tasks
- Strategic and tactic planning and guidance
- Information and action planning on all actual and potential projects.
- Quotations definition and approval
- Contact guidance
- Closing of deal</inlineHelpText>
    <label>Global Account Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Salesforce Account. Conneced via field &quot;Customer No&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Contribution_Share__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Share__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contribution share that defines the split of the contribution for this order</inlineHelpText>
    <label>Contribution Share</label>
    <referenceTo>Contribution_Share__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_No__c</fullName>
    <description>ABACUS Customer Number</description>
    <inlineHelpText>(From Abacus) Abacus customer number</inlineHelpText>
    <label>Customer No</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <inlineHelpText>(From Abacus) End customer of this order item.</inlineHelpText>
    <label>End Customer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated with Billing</description>
    <inlineHelpText>Product associated with Billing</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Link to Account in Salesforce</inlineHelpText>
    <label>Project Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Project Owner Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Product for which the case is opened.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases (Product Name)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/Contribution_Share__c.object-meta.xml
<CustomObject>
    <description>Object that defines the share of contribution that is assigned for a certain Project Owner in an order.</description>
    <label>Contribution Share</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Contribution Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Shares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contribution_Share__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Buying Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contribution Share</relationshipLabel>
    <relationshipName>Contribution_Share</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer of buying account. Only used for clarification, it is not used for contribution split.</inlineHelpText>
    <label>End Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contribution Shares (End Customer)</relationshipLabel>
    <relationshipName>Contribution_Shares1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product to be used for matching Orders</description>
    <inlineHelpText>Product to be used for matching Orders</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contribution Shares</relationshipLabel>
    <relationshipName>Contribution_Shares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Product_Filter_Field__c.field-meta.xml
<CustomField>
    <fullName>Product_Filter_Field__c</fullName>
    <inlineHelpText>Product field which is used in the matching logic of the Contribution Share process.</inlineHelpText>
    <label>Product Filter Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Family</fullName>
                <label>Product Family</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Product_Filter_Value__c.field-meta.xml
<CustomField>
    <fullName>Product_Filter_Value__c</fullName>
    <inlineHelpText>Product field value which is used in the matching logic of the Contribution Share process. Product Filter Field must be selected.</inlineHelpText>
    <label>Product Filter Value</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Project_Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Account for which this contribution share applies</inlineHelpText>
    <label>Project Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contribution Shares (Project Owner Account)</relationshipLabel>
    <relationshipName>Contribution_Shares</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of all countries and mapping to sales people. Used to automatically assign Accounts when created by OnDemand Service (ISA).</description>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <label>ISO Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <label>uB Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Settings__c/fields/Account_Allowed_Profiles_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>Account_Allowed_Profiles_To_Delete__c</fullName>
    <description>Profiles able to delete accounts in any criteria.</description>
    <inlineHelpText>Profiles able to delete accounts in any criteria.</inlineHelpText>
    <label>Account: Allowed Profiles To Delete</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Process_Settings__c/fields/Account_Allowed_Profiles_To_Merge__c.field-meta.xml
<CustomField>
    <fullName>Account_Allowed_Profiles_To_Merge__c</fullName>
    <description>Profiles which are allowed to merge accounts in different regions.</description>
    <inlineHelpText>Profiles which are allowed to merge accounts in different regions.</inlineHelpText>
    <label>Account: Allowed Profiles To Merge</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Process_Settings__c/fields/Restricted_Profiles_For_Contract__c.field-meta.xml
<CustomField>
    <fullName>Restricted_Profiles_For_Contract__c</fullName>
    <description>Restricted Profiles for users which cannot be Owner of Contracts</description>
    <label>Restricted Profiles For Contract</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestUtils.cls
Public Class TestUtils
{
    public static Account createAccount()
    {
        Account acc = new Account();
        acc.name = 'Test Account';
        insert acc;
        return acc;
    }
    
    public static Account createAccountWithOwner(ID ownerId)
    {
        Account acc = new Account();
        acc.name = 'Test Account';
        acc.OwnerId = ownerId;
        insert acc;
        return acc;
    }

    public static Account createAccountWithGAM()
    {
        Account acc = new Account();
        acc.name = 'Test Account';
        
        User u= createUserWithProfile('Jhon','System Administrator');
        acc.Global_Account_Manager__c = u.Id;
        insert acc;
        return acc;
    }
    //create Abacus Account
    public static Account createAbacusAccount()
    {
        Account acc = new Account();
        acc.name = 'Test Account';
        acc.Customer_No__c = '123Test';
        acc.uB_Office__c = 'Americas';
        User u= createUserWithProfile('Jhon','System Administrator');
        acc.Global_Account_Manager__c = u.Id;
        insert acc;
        return acc;
    }
    //create Non-Abacus Account
    public static Account createNonAbacusAccount()
    {
        Account acc = new Account();
        acc.name = 'Test Account';
        //acc.Customer_No__c = '123Test';
        User u= createUserWithProfile('Jhon','System Administrator');
        acc.uB_Office__c = 'Americas';
        acc.Global_Account_Manager__c = u.Id;
        insert acc;
        return acc;
    }
    
    //create account with country
    public static Account createAccountWithCountry()
    {
        Account acc = new Account();
        acc.name = 'Test Account';
        acc.ShippingCountry='US';
        acc.ShippingState='AR';
        User u= createUserWithProfile('Jhon','System Administrator');
        acc.Global_Account_Manager__c = u.Id;
        insert acc;
        return acc;
    }
    
    public static Contract createContractWithAccount(ID accid)
    {
        Contract cont = new Contract();
        cont.accountId = accid;
        insert cont;
        return cont;
    }
    
    public static Contract createContractWithAccount(Id accId, String status)
    {
        Contract cont = new Contract();
        cont.accountId = accid;
        cont.Status = status;
        insert cont;
        return cont;
    }
    
    public static Contract createContractWithOwner(ID accid,ID ownerId)
    {
        Contract cont = new Contract();
        cont.ownerId = ownerId;
        cont.accountId = accid;
        insert cont;
        return cont;
    }
    
    public static Process_Settings__c createProcessSettingRecord()
    {
        String profileId = userinfo.getProfileId();
            
        Process_Settings__c pSetting = Process_Settings__c.getInstance();
        pSetting.Restricted_Profiles_For_Contract__c = 'Partner Base Quotation;';
        pSetting.Account_Allowed_Profiles_To_Merge__c = profileId;
        pSetting.Account_Allowed_Profiles_To_Delete__c = profileId;
        
        upsert pSetting;
        return pSetting;
    }
    public static User createUserWithProfile(String lName,String profileName)
    {
        User u = null;
        
        List<Profile> profList = [select id,Name from Profile where Name =: profileName];
        
        if(profList.size()>0)
        {
            u = new User(Alias = 'testabc', Email='testabc_'+DateTime.now().getTime()+'@u-blox-test.com', 
            EmailEncodingKey='UTF-8', LastName=lName, LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = profList[0].id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testabc_'+DateTime.now().getTime()+'@u-blox-test.com');
            
            insert u; 
        }    
        
        return u;
    }

    public static Case createCaseForAccount(Id accountId)
    {
        Case cse = new Case();
        cse.Status = 'New';
        cse.AccountId = accountId;
        insert cse;
        return cse;
    }
    
    public static Opportunity createOpportunityForAccount(Id accountId)
    {
        Opportunity opp = new Opportunity(Name='TestOpp', StageName='3 Calling on',CloseDate=Date.today(),Description='test description',AccountId=accountId);
        insert opp;
        return opp;
    }
    
    public static Process_Settings__c createAccCustomSetting()
    {
        Process_Settings__c psetting = new Process_Settings__c();
        psetting.Name = 'Test Setting';
        pSetting.Account_Allowed_Profiles_To_Merge__c='00e20000000ki5l';
        psetting.Account_Allowed_Profiles_To_Delete__c ='00e20000000ki5l';
        insert psetting;
        return psetting;
    }
    
    public static Country__c createCountry()
    {
        Country__c countryObj = new country__c();        
        countryObj.ISO_Code__c='US';
        countryObj.State__c='001';
        insert countryObj;
        return countryObj;
    }
    
        public static product2 createProduct(String name, String productCode, String family, String typeNo)
    {
        product2 prodObj = new product2();        
        prodObj.Name = name;
        prodObj.ProductCode = productCode;
        prodObj.Family = family;
        prodObj.Type_No__c = typeNo;
        
        insert prodObj;
        return prodObj;
    }
    
    public static Contribution_Share__c createCS(String acId, String ecAccId, String poAccId, String prodId, String oppId,String prodField, String prodValue)
    {
        Contribution_Share__c CSObj = new Contribution_Share__c();        
        CSObj.Account__c = acId;
        CSObj.End_Customer__c = ecAccId;
        CSObj.Project_Owner_Account__c = poAccId;
        CSObj.Product__c = prodId;
        if(!String.isBlank(prodField)  && !String.isBlank(prodValue) ){
            CSObj.Product_Filter_Field__c = prodField;
            CSObj.Product_Filter_Value__c = prodValue;
            
        }
        CSObj.Status__c = 'Activated';
        CSObj.Opportunity__c = oppId;
        CSObj.CurrencyIsoCode ='USD' ;
        
        insert CSObj;
        return CSObj;
    }

public static Billings__c createOrder(String acId, String ecAccId, String poAccId, String prodId)
    {
        Billings__c o = new Billings__c();
        o.Account__c = acId;
        o.End_Customer_Account__c = acId;
        o.Project_Owner_Account__c = acId;
        o.Product__c = prodId;
        o.Delivery_Date__c = Date.today().addMonths(+1);
        o.Qty_Ordered__c = 100;
        o.Total_Value_CHF__c = 1000;
        o.Update_CS__c = true;
        insert o;
        return o;
    }
    
    
    
    
        
      
}