force-app/main/default/objects/Account/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <description>See Worksflow for RMA.</description>
    <inlineHelpText>Name of distributor will be copied to the field with the same name of all RMAs connected to this account. The sharing rule will ensure access to these RMAs</inlineHelpText>
    <label>Distributor Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Email_Account_Owner__c</fullName>
    <inlineHelpText>Email address of the Account owner. Copied from User settings.</inlineHelpText>
    <label>Email Account Owner</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <inlineHelpText>Distributor name of Account owner. Used to grant access for portal users</inlineHelpText>
    <label>Distributor Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Email_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Email_Account_Owner__c</fullName>
    <description>Used for workflows.</description>
    <inlineHelpText>Email address of the account owner related to this Case.</inlineHelpText>
    <label>Email Account Owner</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RMA__c/RMA__c.object-meta.xml
<CustomObject>
    <description>Return Material Handling</description>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA{0000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RMA__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>Account to which the RMA relates</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RMAs</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RMA__c/fields/Approval_available__c.field-meta.xml
<CustomField>
    <fullName>Approval_available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the Commercial RMA has been approved in written form by the ASM or Regional VP Sales, according to the Signing Rules in TWiki</description>
    <inlineHelpText>Check if the Commercial RMA has been approved in written form by the ASM or Regional VP Sales according to the Signing Rules.
If not checked, the Commercial RMA is not authorized.</inlineHelpText>
    <label>Approval available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RMA__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <description>Value copied from user.distributor_name__c with APEX code.</description>
    <inlineHelpText>Used to grant access to external partners via sharing rules.</inlineHelpText>
    <label>Distributor Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMA__c/fields/Email_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Email_Account_Owner__c</fullName>
    <inlineHelpText>Email address of the account owner.</inlineHelpText>
    <label>Email Account Owner</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/UpdateDistributorNameTester.cls
@isTest
public with sharing class UpdateDistributorNameTester {

    public static testMethod void testUpdateRMADistributorName(){
        List<Profile> profList = [select id,Name from Profile where Name ='System Administrator'];
        string profId = profList[0].id;  
    
        List<User> usersList = [select Id, Email, Distributor_Name__c from User where profileId = : profId AND IsActive = true];
        User testOwner = usersList[0];
        testOwner.Distributor_Name__c = 'DistributorName1';
        testOwner.Email = 'test@test.com';
        update testOwner;
        
        Account testAccount = new Account(Name = 'TestAccount', OwnerId = testOwner.Id);
        insert testAccount;
        
        RMA__c testRMA = new RMA__c(Account_Name__c=testAccount.Id,/*OwnerId = testOwner.Id,*/ Email_Account_Owner__c = 'test@test.com', Distributor_Name__c = 'DistributorName0', Approval_available__c = true);
        insert testRMA;
    }
    
    public static testMethod void testUpdateCaseDistributorName(){
        List<Profile> profList = [select id,Name from Profile where Name ='System Administrator'];
        string profId = profList[0].id;  
    
        List<User> usersList = [select Id, Email, Distributor_Name__c from User where profileId = : profId AND IsActive = true];
        User testOwner = usersList[0];
        testOwner.Distributor_Name__c = 'DistributorName1';
        testOwner.Email = 'test@test.com';
        update testOwner;
        
        Case testCase = new Case(/*OwnerId = testOwner.Id,*/ Email_Account_Owner__c = 'test@test.com', Distributor_Name__c = 'DistributorName0');
        insert testCase;
    }
    
    public static testMethod void testUpdateRMAandCaseDistributorName(){
        List<Profile> profList = [select id,Name from Profile where Name ='System Administrator'];
        string profId = profList[0].id;  
    
        List<User> usersList = [select Id, Email, Distributor_Name__c from User where profileId = : profId AND IsActive = true];
        User testOwner = usersList[0];
        testOwner.Distributor_Name__c = 'DistributorName1';
        testOwner.Email = 'test@test.com';
        update testOwner;
        
        User testOwner2 = usersList[1];
        testOwner2.Distributor_Name__c = 'DistributorName2';
        testOwner2.Email = 'test@test.com';
        update testOwner2;

        Account testAccount = new Account(Name = 'TestAccount', OwnerId = testOwner.Id);
        insert testAccount;
        
        RMA__c testRMA = new RMA__c( Email_Account_Owner__c = 'test@test.com', Distributor_Name__c = 'DistributorName0', Account_Name__c = testAccount.Id, Approval_available__c = true );
        insert testRMA;
        
        Case testCase = new Case(OwnerId = testOwner.Id, Email_Account_Owner__c = 'test@test.com', Distributor_Name__c = 'DistributorName0', AccountId = testAccount.Id );
        insert testCase;
        
        testAccount.OwnerId = testOwner2.Id;
        update testAccount;
    }
    
}