force-app/main/default/objects/Account/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <description>See Worksflow for RMA.</description>
    <inlineHelpText>Name of distributor will be copied to the field with the same name of all RMAs connected to this account. The sharing rule will ensure access to these RMAs</inlineHelpText>
    <label>Distributor Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/New_Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>New_Channel_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If left empty, it will be populated if Account Owner is
- u-blox (except Inside Sales US): Account Owner
- u-blox (Inside Sales US) and distributor: Manager of the Account Owner</description>
    <inlineHelpText>If left empty, it will be populated if Account Owner is
- u-blox (except Inside Sales US): Account Owner
- u-blox (Inside Sales US) and distributor: Manager of the Account Owner</inlineHelpText>
    <label>Channel Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Owner_Partner_Account_Map__c/Account_Owner_Partner_Account_Map__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Account Owner Partner Account Map</label>
</CustomObject>

force-app/main/default/objects/Account_Owner_Partner_Account_Map__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Partner Account Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountOwnerUpdateWithChannelManagerTest.cls
@isTest
public class AccountOwnerUpdateWithChannelManagerTest {
    public static User InitializeUserWithProfile(String lName,String profileName)
    {
        User u = null;
        
        List<Profile> profList = [select id,Name from Profile where Name =: profileName];
        
        if(profList.size()>0)
        {
            u = new User(Alias = 'testabc', Email='testabc_'+DateTime.now().getTime()+'@u-blox-test.com', 
            EmailEncodingKey='UTF-8', LastName=lName, LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = profList[0].id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testabc_'+DateTime.now().getTime()+'@u-blox-test.com');
        }    
        return u;
    }
    
    static testMethod void testMethod1() 
    {
        List<User> userList = new List<User>();
        
        User u = InitializeUserWithProfile('Alpha Micro','Partner Base');
        u.Distributor_Name__c = 'Alpha Micro';
        userList.add(u);
        
        User u2 = InitializeUserWithProfile('Test User','System Administrator');
        u2.Distributor_Name__c = 'Internals';
        userList.add(u2);
        insert userList;    
        
        Account accountObj1 = new Account();
        accountObj1.Name ='Alpha Micro Customer Account';
        accountObj1.OwnerId = userList[0].Id;
        accountObj1.New_Channel_Manager__c =userList[1].Id ;
        
        Account accountObj2 = new Account();
        accountObj2.Name ='Alpha Micro Customer Account';
        accountObj2.OwnerId = userList[0].Id;
        //accountObj1.New_Channel_Manager__c =userList[1].Id ;
        
        List<Account> accList = new List<account>();
        accList.add(accountObj1);
        accList.add(accountObj2);
        insert accList;
        //insert accountObj;
        
        Account_Owner_Partner_Account_Map__c customSettingsoObj = new Account_Owner_Partner_Account_Map__c();
        customSettingsoObj.Name = u.Id;
        customSettingsoObj.value__c =accList[0].Id;
        insert customSettingsoObj;
        
        
        
        Test.startTest();
        
        AccountOwnerUpdateWithChannelManager obj = new AccountOwnerUpdateWithChannelManager();
        obj.accountIdforAttachment = accList[0].Id;
        DataBase.executeBatch(obj); 
        Test.stopTest();
    }
}