force-app/main/default/objects/Account/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <description>See Worksflow for RMA.</description>
    <inlineHelpText>Name of distributor will be copied to the field with the same name of all RMAs connected to this account. The sharing rule will ensure access to these RMAs</inlineHelpText>
    <label>Distributor Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Email_Account_Owner__c</fullName>
    <inlineHelpText>Email address of the Account owner. Copied from User settings.</inlineHelpText>
    <label>Email Account Owner</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <inlineHelpText>Distributor name of Account owner. Used to grant access for portal users</inlineHelpText>
    <label>Distributor Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Email_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Email_Account_Owner__c</fullName>
    <description>Used for workflows.</description>
    <inlineHelpText>Email address of the account owner related to this Case.</inlineHelpText>
    <label>Email Account Owner</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Design_Review__c/Design_Review__c.object-meta.xml
<CustomObject>
    <description>shows the Design Reviews done by u-blox Technical Support.</description>
    <label>Design Review</label>
    <nameField>
        <displayFormat>CDR-{0000}</displayFormat>
        <label>Design Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Design_Review__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Design Reviews</relationshipLabel>
    <relationshipName>Design_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Design_Review__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <description>Value copied from user.distributor_name__c of Account Owner with APEX code</description>
    <inlineHelpText>Used to grant access to external partners via sharing rules.</inlineHelpText>
    <label>Distributor Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Design_Review__c/fields/Email_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Email_Account_Owner__c</fullName>
    <inlineHelpText>Email address of the account owner related to this Design Review.</inlineHelpText>
    <label>Email Account Owner</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RMA__c/RMA__c.object-meta.xml
<CustomObject>
    <description>Return Material Handling</description>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA{0000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RMA__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>Account to which the RMA relates</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RMAs</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RMA__c/fields/Approval_available__c.field-meta.xml
<CustomField>
    <fullName>Approval_available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the Commercial RMA has been approved in written form by the ASM or Regional VP Sales, according to the Signing Rules in TWiki</description>
    <inlineHelpText>Check if the Commercial RMA has been approved in written form by the ASM or Regional VP Sales according to the Signing Rules.
If not checked, the Commercial RMA is not authorized.</inlineHelpText>
    <label>Approval available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RMA__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <description>Value copied from user.distributor_name__c with APEX code.</description>
    <inlineHelpText>Used to grant access to external partners via sharing rules.</inlineHelpText>
    <label>Distributor Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMA__c/fields/Email_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Email_Account_Owner__c</fullName>
    <inlineHelpText>Email address of the account owner.</inlineHelpText>
    <label>Email Account Owner</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/TestTriggers.cls
@isTest
public with sharing class TestTriggers {

	public static testMethod void testTriggers(){
		Account testAcc = new Account();
		testAcc.Name = 'test';
		insert testAcc;
		
		testAcc.Name = 'test2';
		update testAcc;
		
		Design_Review__c testDr = new Design_Review__c();
		testDr.Distributor_Name__c = '';
		testDr.Email_Account_Owner__c = '';
		testDr.Account_Name__c = testAcc.Id;
		insert testDr;
		
		RMA__c testRMA = new RMA__c();
		testRMA.Distributor_Name__c = '';
		testRMA.Email_Account_Owner__c = '';
		testRMA.Approval_available__c = true;
		testRMA.Account_Name__c = testAcc.Id;
		insert testRMA;
		
		Case testCase = new Case();
		testCase.Distributor_Name__c = '';
		testCase.Email_Account_Owner__c = '';
		insert testCase;
	}

}