force-app/main/default/objects/Account/fields/FAE__c.field-meta.xml
<CustomField>
    <fullName>FAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>u-blox FAE responsible for this Account</description>
    <inlineHelpText>u-blox FAE responsible for this Account</inlineHelpText>
    <label>FAE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Global_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Global_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of User that coordinates all activities with such a Global Account and its subsidiaries</description>
    <inlineHelpText>to be decided by regional sales heads

Coordination Tasks
- Strategic and tactic planning and guidance
- Information and action planning on all actual and potential projects.
- Quotations definition and approval
- Contact guidance
- Closing of deal</inlineHelpText>
    <label>Global Account Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Previous_Owner__c.field-meta.xml
<CustomField>
    <fullName>Previous_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Made to be used for transfer</description>
    <inlineHelpText>Made to be used for transfer</inlineHelpText>
    <label>Previous Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RAE__c.field-meta.xml
<CustomField>
    <fullName>RAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Delegated FAE</description>
    <inlineHelpText>Delegated FAE in the absence of FAE</inlineHelpText>
    <label>RAE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Admin__c.field-meta.xml
<CustomField>
    <fullName>Sales_Admin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>u-blox Sales Admin responsible for this Account</description>
    <inlineHelpText>u-blox Sales Admin responsible for this Account</inlineHelpText>
    <label>Sales Operations</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Service_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>IN_SF_MTC-476</description>
    <inlineHelpText>Sales Manager who supports the customer with Services products</inlineHelpText>
    <label>Service Sales Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Initiator_Source__c.field-meta.xml
<CustomField>
    <fullName>Case_Initiator_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field if the case is opened for someone else (Case Initiator &lt;&gt; Created by)</inlineHelpText>
    <label>Case Initiator Source</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases_initiated</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FAE__c.field-meta.xml
<CustomField>
    <fullName>FAE__c</fullName>
    <description>FAE of the Account</description>
    <formula>Account.FAE__r.Alias</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>FAE of the Account</inlineHelpText>
    <label>FAE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Comment_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Comment_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Added for returning the Case to person who made the last Comment</description>
    <inlineHelpText>Added for returning the Case to person who made the last Comment</inlineHelpText>
    <label>Last Comment By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Return_To__c.field-meta.xml
<CustomField>
    <fullName>Return_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Made to return the Case to the person who added the last comment.</description>
    <inlineHelpText>Made to return the Case to the person who added the last comment.</inlineHelpText>
    <label>Return To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Product_Price__c/Competitor_Product_Price__c.object-meta.xml
<CustomObject>
    <label>Competitor Product Price</label>
    <nameField>
        <displayFormat>CPP-{000000}</displayFormat>
        <label>Competitor Product Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Product Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Lead_Source_Person_User__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Person_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person (Salesforce User) who introduced this Lead. Transferred to Opportunity.</description>
    <inlineHelpText>Person (Salesforce User) who introduced this Lead. Transferred to Opportunity.</inlineHelpText>
    <label>Lead Source Person (User)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Channel_Manager_Obj__c.field-meta.xml
<CustomField>
    <fullName>Account_Channel_Manager_Obj__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Channel Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitieChannelManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FAE__c.field-meta.xml
<CustomField>
    <fullName>FAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FAE for the opportunity. The value is populated from Account on Insert and can be changed.</description>
    <inlineHelpText>FAE for the opportunity. The value is populated from Account and can be updated any time.</inlineHelpText>
    <label>FAE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Source_Person_User__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Person_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>From Lead</inlineHelpText>
    <label>Lead Source Person (User)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_CEL__c.field-meta.xml
<CustomField>
    <fullName>Owner_CEL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Responsible from PS-CEL for this Strategic Business Opportunity</description>
    <inlineHelpText>Responsible from PS-CEL for this Strategic Business Opportunity</inlineHelpText>
    <label>Owner CEL</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesCEL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_PC_SER__c.field-meta.xml
<CustomField>
    <fullName>Owner_PC_SER__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Responsible from PS-SER for this Strategic Business Opportunity</description>
    <inlineHelpText>Responsible from PS-SER for this Strategic Business Opportunity</inlineHelpText>
    <label>Owner SER</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_POS__c.field-meta.xml
<CustomField>
    <fullName>Owner_POS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Responsible from PS-POS for this Strategic Business Opportunity</description>
    <inlineHelpText>Responsible from PS-POS for this Strategic Business Opportunity</inlineHelpText>
    <label>Owner POS</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesPOS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_SHO__c.field-meta.xml
<CustomField>
    <fullName>Owner_SHO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Responsible from PS-SHO for this Strategic Business Opportunity</description>
    <inlineHelpText>Responsible from PS-SHO for this Strategic Business Opportunity</inlineHelpText>
    <label>Owner SHO</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesSHO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Variable__c/Variable__c.object-meta.xml
<CustomObject>
    <label>Variable</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DataMigration.cls
public class DataMigration {
    public Map<Id, Id> usersIdMap = new Map<Id, Id> ();
    public Id acc; //Id of the dummy account to which results will be stored
    public Id batchInstanceId1;
    public Id batchInstanceId2;
    public Map<String, List<String>> objectFieldMapping = new Map<String, List<String>>();
	public Map<String, String> objectWhereMapping = new Map<String, String>();
	public Map<String, String> manualSharingQueries = new Map<String, String>();
    public Map<String, List<String>> fieldstoUpdateMapping = new Map<String, List<String>>();
	
    public void EXECUTE() {        
        changeOwner();
        changeManualSharing();
    }
	
	public void ExecuteWithConfig() { 
		populateChangeOwnerConfig();
		populateManualSharingConfig();
        changeOwner();
        changeManualSharing();
    }
	//Call this function before execute
	public void populateChangeOwnerConfig()
	{
		objectFieldMapping.put('Account', new List<String>{'FAE__c', 'Global_Account_Manager__c', 'Previous_Owner__c', 'RAE__c', 'Sales_Admin__c', 'Service_Sales_Manager__c'});
        
        objectFieldMapping.put('Contact',  new List<String>{'OwnerId'});
        
        objectFieldMapping.put('Lead',  new List<String>{'OwnerId', 'Lead_Source_Person_User__c'});
        objectWhereMapping.put('Lead', 'AND IsConverted = False');
        
        objectFieldMapping.put('Case',  new List<String>{'OwnerId', 'Case_Initiator_Source__c', 'Last_Comment_By__c', 'Return_To__c'});
        
        objectFieldMapping.put('Opportunity',  new List<String>{'OwnerId', 'Account_Channel_Manager_Obj__c', 'Account_Owner__c', 'FAE__c', 'Lead_Source_Person_User__c', 'Owner_CEL__c', 'Owner_POS__c', 'Owner_PC_SER__c', 'Owner_SHO__c'});
        
        objectFieldMapping.put('Variable__c',  new List<String>{'OwnerId'});
        objectFieldMapping.put('Competitor_Product_Price__c',  new List<String>{'OwnerId'});
        objectFieldMapping.put('Task',  new List<String>{'OwnerId'});
        
        objectFieldMapping.put('note',  new List<String>{'OwnerId'});
        objectFieldMapping.put('Attachment',  new List<String>{'OwnerId'});
	}
	// parent id in the case team member
    // run in chain
	//Call this function before execute
	public void populateManualSharingConfig()
	{
		// Manaul sharing Job
        String conditions = ' and (RowCause != \'Owner\' and RowCause != \'ImplicitParent\' and RowCause != \'ImplicitChild\')';
        String conditionAccount = ' and (RowCause != \'Owner\' and RowCause != \'ImplicitChild\')';
        String accountShare = 'Select Id, AccountAccessLevel, AccountId, CaseAccessLevel, ContactAccessLevel, OpportunityAccessLevel, RowCause, UserOrGroupId from AccountShare  Where UserorGroupId IN :oldUserIds '+conditionAccount;
        String contactShare = 'Select Id, ContactId, ContactAccessLevel, IsDeleted, RowCause, UserOrGroupId from ContactShare Where UserorGroupId IN :oldUserIds '+conditions;
        String leadShare = 'Select Id, IsDeleted, LeadAccessLevel, LeadId, RowCause, UserOrGroupId from LeadShare Where UserorGroupId IN :oldUserIds '+conditions;
        String caseShare = 'Select Id, CaseAccessLevel, CaseId, IsDeleted, UserOrGroupId from CaseShare Where UserorGroupId IN :oldUserIds '+conditions;
        String opportunityShare = 'Select Id, IsDeleted, OpportunityAccessLevel, OpportunityId, RowCause, UserOrGroupId from OpportunityShare Where UserorGroupId IN :oldUserIds '+conditions;
        String caseTeamMember = 'Select Id, MemberId, ParentId, TeamRoleId, TeamTemplateId, TeamTemplateMemberId from CaseTeamMember Where MemberId IN :oldUserIds';
        String accountTeamMember = 'Select Id, AccountAccessLevel, AccountId, CaseAccessLevel, ContactAccessLevel, CurrencyIsoCode, IsDeleted, OpportunityAccessLevel, PhotoURL, TeamMemberRole, Title, UserId from AccountTeamMember Where UserId IN :oldUserIds';
        
        manualSharingQueries.put('AccountShare', accountShare);
        fieldstoUpdateMapping.put('AccountShare', new List<String>{'UserorGroupId'});
        
        manualSharingQueries.put('ContactShare', contactShare);
        fieldstoUpdateMapping.put('ContactShare', new List<String>{'UserorGroupId'});
        
        manualSharingQueries.put('OpportunityShare', opportunityShare);
        fieldstoUpdateMapping.put('OpportunityShare', new List<String>{'UserorGroupId'});
        
        manualSharingQueries.put('LeadShare', leadShare);
        fieldstoUpdateMapping.put('LeadShare', new List<String>{'UserorGroupId'});
        
        manualSharingQueries.put('CaseShare', caseShare);
        fieldstoUpdateMapping.put('CaseShare', new List<String>{'UserorGroupId'});
        
        manualSharingQueries.put('CaseTeamMember', caseTeamMember);
        fieldstoUpdateMapping.put('CaseTeamMember', new List<String>{'MemberId'});
        
        manualSharingQueries.put('AccountTeamMember', accountTeamMember);
        fieldstoUpdateMapping.put('AccountTeamMember', new List<String>{'UserId'});        
	}
	
    public void changeOwner() {
        for (String e : objectFieldMapping.keySet()) {
            String w = objectWhereMapping.get(e) != null ? objectWhereMapping.get(e) : '';
            batchInstanceId1 = Database.executeBatch(new BatchOwnerUpdater(e,objectFieldMapping.get(e),w,acc, usersIdMap));
        }
    }

    // clone record with new user ids
    public void changeManualSharing() {
        for (String e : manualSharingQueries.keySet()) {
            List<String> fieldstoUpdate = fieldstoUpdateMapping.get(e) != null ? fieldstoUpdateMapping.get(e) : new List<String>();
            batchInstanceId2 = Database.executeBatch(new BatchManualSharingUpdater(e,manualSharingQueries.get(e),acc, usersIdMap, fieldstoUpdate));
        }
    }
}