force-app/main/default/objects/Account/fields/FAE__c.field-meta.xml
<CustomField>
    <fullName>FAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>u-blox FAE responsible for this Account</description>
    <inlineHelpText>u-blox FAE responsible for this Account</inlineHelpText>
    <label>FAE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/New_Market__c.field-meta.xml
<CustomField>
    <fullName>New_Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>New_Application_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FAE__c.field-meta.xml
<CustomField>
    <fullName>FAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FAE for the opportunity. The value is populated from Account on Insert and can be changed.</description>
    <inlineHelpText>FAE for the opportunity. The value is populated from Account and can be updated any time.</inlineHelpText>
    <label>FAE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard,PowerPartner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Values based on the global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Market__c.field-meta.xml
<CustomField>
    <fullName>New_Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is quotation, than it is blank.</description>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/populateOpportunityAccount.cls
public with sharing class populateOpportunityAccount {
    
    /*
    Created by: Ben Mansfield
    Created Date: 29th July 2009
    
    Version: 1.0
    Last Modified Date: 31st July 2009 
    */
/*
2016.04.07 khir: Added Description of new Opportunity creation for update of updateStatusOnOppProduct.apxt
*/
    
    public static void execute(List<Opportunity> opps)
    {
        // Get Opportunity record type
        List<RecordType> recordTypes = [Select Id, Name From RecordType Where SObjectType = 'Opportunity' and Name = 'Opportunity' Limit 1];
        
        // If we cannot find the correct record type, exit function
        if (recordTypes.size() != 1) return;
        RecordType rt = recordTypes.get(0);
        
        Set<Id> accountIds = new Set<Id>();
        // Loop through all new opportunities
        for (Opportunity o : opps)
        {
            // For every opportunity with an account id
            if (o.AccountId != null)
            {
                // Add the account id to set
                accountIds.add(o.AccountId);
            }
        }
        
        // Query all accounts associated with the new opportunities
        Map<Id, Account> associatedAccounts = new Map<Id, Account>([Select Id, FAE__c, Name, 
                                                New_Application_Type__c, New_Market__c 
                                                From Account Where Id in :accountIds]);
        
        // Loop through all opportunities again
        for (Opportunity o : opps)
        {
            // If the opportunity account field is empty and this opportunity
            // is associated with an account
            if (o.RecordTypeId == rt.Id && associatedAccounts.containsKey(o.AccountId))
            {
                // Get the account
                Account a = associatedAccounts.get(o.AccountId);
                
                // Update other account fields
                if(o.Opportunity_Account__c == null) o.Opportunity_Account__c = a.Id;
                if(o.FAE__c == null) o.FAE__c = a.FAE__c;
                if(o.New_Application_Type__c == null) o.New_Application_Type__c = a.New_Application_Type__c;
                if(o.New_Market__c == null) o.New_Market__c = a.New_Market__c;	

            }
            system.debug(o.FAE__c);
        }
    }
}