force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <inlineHelpText>Market where largest share of u-blox revenues are generated. Choose &quot;not applicable&quot; for distributors, sales reps, competitors.</inlineHelpText>
    <label>Market (OLD)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this account.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market_Classification__c/Market_Classification__c.object-meta.xml
<CustomObject>
    <description>Market Classification object is created to store market and market segments for different objects like Account, Lead, and Opportunities. It&apos;s an improvement on an existing way of storing the application and application type on account, lead and opportunities.</description>
    <label>Market Classification</label>
    <nameField>
        <label>Market Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Classification__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Classification__c/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/MarketClassificationTriggerHelperTest.cls
@isTest
public class MarketClassificationTriggerHelperTest {

    @isTest
    public static void marketclassificationDeactivate(){
        market_classification__c marketObj = new Market_classification__c();
        marketObj.isActive__c = true;
        marketObj.Name = 'C-Asset tracking and management';
        marketObj.Description__c = 'Battery-powered tracking devices for trailers, containers, pallets, parcels, luggage, livestock, pets, power tools';
        marketObj.Market__c = 'Consumer';
        marketObj.Market_Segment__c = 'Asset tracking and management';
        insert marketObj;
        
        Account accObj = new Account();
        accObj.Name = 'test Account';
        insert accObj;

        List<market_classification__c> marketClassificationList = new List<market_classification__c>();
        List<Account> accList = new List<Account>();
        marketClassificationList=[SELECT Id, isActive__c from Market_Classification__c ];//where name = 'C-Asset tracking and management' LIMIT 1
        
        accList = [SELECT Id from Account where name = 'test Account'];
        accList[0].Market_Classification__c = marketClassificationList[0].Id;
        update accList;
        marketClassificationList[0].isActive__c = false;
        
        list<Database.SaveResult> results = Database.update(marketClassificationList, false);
       
    }
    @isTest
    public static void marketClassificationDeleteScenario1(){
        
        market_classification__c marketObj = new Market_classification__c();
        marketObj.isActive__c = true;
        marketObj.Name = 'C-Asset tracking and management';
        marketObj.Description__c = 'Battery-powered tracking devices for trailers, containers, pallets, parcels, luggage, livestock, pets, power tools';
        marketObj.Market__c = 'Consumer';
        marketObj.Market_Segment__c = 'Asset tracking and management';
        insert marketObj;
        delete marketObj;
    }
}