force-app/main/default/objects/Account/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this account.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/New_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>New_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New Opportunity added to this Account. Updated with Process. To be used for Chatter post.</description>
    <inlineHelpText>New Opportunity added to this Account. Updated with Process. To be used for Chatter post.</inlineHelpText>
    <label>New Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Private_Major_Shareholder__c.field-meta.xml
<CustomField>
    <fullName>Private_Major_Shareholder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Show Organization which holds share of 3rd party</inlineHelpText>
    <label>Private Major Shareholder</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Finance</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Source_Account__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that introduced this Lead. Add if Lead Source is Partner.
Transferred to Opportunity and Partner Role.</description>
    <inlineHelpText>Account that introduced this Lead. Add if Lead Source is Partner.
Transferred to Opportunity and Partner Role.</inlineHelpText>
    <label>Lead Source Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this lead.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market_Classification__c/Market_Classification__c.object-meta.xml
<CustomObject>
    <description>Market Classification object is created to store market and market segments for different objects like Account, Lead, and Opportunities. It&apos;s an improvement on an existing way of storing the application and application type on account, lead and opportunities.</description>
    <label>Market Classification</label>
    <nameField>
        <label>Market Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this opportunity.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is quotation, than it is blank.</description>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MarketClassificationTriggerHelper.cls
public class MarketClassificationTriggerHelper {
    
    /*
     * check if there are any associated accounts/leads/opportunites and prevent deactivating the record if there are any.
     */
    public static void isMarketClassificationReferenced(List<Id> marketClassificationIds, List<Market_Classification__c> marketClassificationList){
        
        List<Market_Classification__c> marketClassificationLst = new List<Market_Classification__c>();
        if(marketClassificationIds.size() > 0){
            try{
                marketClassificationLst = [SELECT Id ,(SELECT Id from Opportunities__r),(SELECT Id from accounts__r), (SELECT Id from Leads__r) from Market_classification__c where id =: marketClassificationIds];
            }catch(QueryException e){
                system.debug('An error has occurred'+e.getMessage());
            }
        }
        map<Id,Boolean> marketClassIdMap = new map<Id,Boolean>();
        
        for(Market_Classification__c tempMarketClassificationObj :  marketClassificationLst){
            
            if(tempMarketClassificationObj.opportunities__r.size()>0 || tempMarketClassificationObj.Accounts__r.size()>0 || tempMarketClassificationObj.Leads__r.size()>0 ){
                marketClassIdMap.put(tempMarketClassificationObj.Id, true);
            }
        }
        for(Market_Classification__c tempMarketClassificationObj :  marketClassificationList){
            if(marketClassIdMap.containsKey(tempMarketClassificationObj.Id)){
                tempMarketClassificationObj.AddError(Label.Market_Classification_Message);
            }
        }
    }
    
}