force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <inlineHelpText>Market where largest share of u-blox revenues are generated. Choose &quot;not applicable&quot; for distributors, sales reps, competitors.</inlineHelpText>
    <label>Market (OLD)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this account.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Distributor account which handles account.</description>
    <inlineHelpText>Distributor account which handles account.</inlineHelpText>
    <label>Partner Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Partner Account)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Source_Account__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that introduced this Lead. Add if Lead Source is Partner.
Transferred to Opportunity and Partner Role.</description>
    <inlineHelpText>Account that introduced this Lead. Add if Lead Source is Partner.
Transferred to Opportunity and Partner Role.</inlineHelpText>
    <label>Lead Source Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this lead.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Based on the values of global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Classification__c/Market_Classification__c.object-meta.xml
<CustomObject>
    <description>Market Classification object is created to store market and market segments for different objects like Account, Lead, and Opportunities. It&apos;s an improvement on an existing way of storing the application and application type on account, lead and opportunities.</description>
    <label>Market Classification</label>
    <nameField>
        <label>Market Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Classification__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Classification__c/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Role__c/Partner_Role__c.object-meta.xml
<CustomObject>
    <description>Link between two Accounts for a specific Opportunity</description>
    <label>Partner Role</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>P-Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partner Roles</relationshipLabel>
    <relationshipName>R00N20000000pWzkEAE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Role__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Roles (As Partner Account)</relationshipLabel>
    <relationshipName>R00N20000000pWzvEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Role__c/fields/Partner_Role__c.field-meta.xml
<CustomField>
    <fullName>Partner_Role__c</fullName>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 Partner Referral (commissions required)</fullName>
            </value>
            <value>
                <fullName>0 Partner Referral (no commissions)</fullName>
            </value>
            <value>
                <fullName>1 Opportunity owner</fullName>
            </value>
            <value>
                <fullName>2 Ref. design / platform dev.</fullName>
            </value>
            <value>
                <fullName>3 Design house</fullName>
            </value>
            <value>
                <fullName>3 ODM (Design and Manufacturing)</fullName>
            </value>
            <value>
                <fullName>3 Local Module Maker</fullName>
            </value>
            <value>
                <fullName>4 Consultant/Advisor</fullName>
            </value>
            <value>
                <fullName>4 Certification partner</fullName>
            </value>
            <value>
                <fullName>4 Technology partner</fullName>
            </value>
            <value>
                <fullName>4 MNO / MVNO</fullName>
            </value>
            <value>
                <fullName>5 Former contract manufacturer</fullName>
            </value>
            <value>
                <fullName>5 Actual contract manufacturer</fullName>
            </value>
            <value>
                <fullName>5 Potential contract manufacturer</fullName>
            </value>
            <value>
                <fullName>6 Sourcing / Negotiation entity</fullName>
            </value>
            <value>
                <fullName>6 Purchasing entity</fullName>
            </value>
            <value>
                <fullName>7 Distributor</fullName>
            </value>
            <value>
                <fullName>8 Sales representative</fullName>
            </value>
            <value>
                <fullName>8 Agent</fullName>
            </value>
            <value>
                <fullName>9 Customer of opp. owner</fullName>
            </value>
            <value>
                <fullName>9 Car brand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/createPartnerRoleOnConversionTest.cls
@isTest
public class createPartnerRoleOnConversionTest {
        public static testMethod void testcreatePartnerRoleOnConversionTest()
        {
//      System.debug(Logginglevel.INFO, '+ alignOppAccOnPartnerRoleTest.alignOppAccOnPartnerRole');
            Market_Classification__c classification = new Market_Classification__c(
                    IsActive__c = true,
                    Market__c = 'Automotive',
                    Market_Segment__c = 'Autonomous driving');
            Database.insert(classification);

            // Create Account and Lead records to be used for test
            Account a = new Account(Name='test account', BillingCountry='CH',Market_Classification__c = classification.id);
            insert a;
            Lead l = new Lead(LastName='testname', Company='testcompany', Lead_Source_Account__c=a.Id, Country='CH', Market_Classification__c = classification.Id, New_Application_Type__c = 'Autonomous driving');
            insert l;
            Lead l2 = new Lead(LastName='testname2', Company='testcompany2', Country='CH', Market_Classification__c = classification.Id, New_Application_Type__c = 'Autonomous driving');
            insert l2;
            
            
            // Lead conversion and check if the conversion is successful
            Database.LeadConvert lc = new Database.LeadConvert();
            lc.setLeadId(l.id);
            LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
            lc.setConvertedStatus(convertStatus.MasterLabel);
            Database.LeadConvertResult lcr = Database.convertLead(lc);
            System.assert(lcr.isSuccess());
            
            Database.LeadConvert lc2 = new Database.LeadConvert();
            lc2.setLeadId(l2.id);
            LeadStatus convertStatus2 = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
            lc2.setConvertedStatus(convertStatus2.MasterLabel);
            Database.LeadConvertResult lcr2 = Database.convertLead(lc2);
            System.assert(lcr2.isSuccess());
            
            // Retrieve field values of the converted Lead and created Partner Role
            Lead convertedLead = [SELECT Id, ConvertedAccountId, ConvertedOpportunityId FROM Lead WHERE id = :l.id];
            
            Lead convertedLead2 = [SELECT Id, ConvertedAccountId, ConvertedOpportunityId FROM Lead WHERE id = :l2.id];
            List<Partner_Role__c> createdPRList = [SELECT Partner_Account__r.Id FROM Partner_Role__c WHERE Opportunity__c = :lcr2.getOpportunityId()];

            // Check if the created Partner Role has correct Account or Partner Role is not created (expected, actual)
            System.assertEquals(0, createdPRList.size());
        
            // If the trigger needs to be deactivated, comment all the above and include only below.
//                    System.assertEquals(1, 1);

//      System.debug(Logginglevel.INFO, '- alignOppAccOnPartnerRoleTest.alignOppAccOnPartnerRole'); 
        } 

}