force-app/main/default/objects/Account/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this account.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this lead.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market_Classification__c/Market_Classification__c.object-meta.xml
<CustomObject>
    <description>Market Classification object is created to store market and market segments for different objects like Account, Lead, and Opportunities. It&apos;s an improvement on an existing way of storing the application and application type on account, lead and opportunities.</description>
    <label>Market Classification</label>
    <nameField>
        <label>Market Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this opportunity.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/MarketClassificationTriggerHandler.cls
/****
Process 1 : prevent user from deactivating records that are being referenced in Account/lead/opportunity objects.
***/
public Class MarketClassificationTriggerHandler implements ITrigger
{
    
    static List<Id> marketClassificationIds = new List<Id>();
    // Prepare the data for catering to Before Trigger events
    public void prepareBefore(){
        if(!trigger.isInsert){
            List<Market_Classification__c> marketClassObjOld = (list<Market_Classification__c>)Trigger.old;
            
            for(Market_Classification__c tempMarketClassificationObj : MarketClassObjOld){
                if(Trigger.isUpdate){
                    Market_Classification__c marketClassObjNew = (Market_Classification__c)Trigger.newMap.get(tempMarketClassificationObj.Id);
                    if(marketClassObjNew.IsActive__c != tempMarketClassificationObj.IsActive__c && !marketClassObjNew.IsActive__c){
                        marketClassificationIds.add(tempMarketClassificationObj.Id);
                    }
                }
                if(Trigger.isDelete){
                    if(tempMarketClassificationObj.isActive__c){
                        marketClassificationIds.add(tempMarketClassificationObj.Id);
                    }
                }
            }
        }
    }
    
    // Prepare the data for catering to After Trigger events 
    public void prepareAfter(){
    }
    
    // Process logic/functioanlities in other classes for before Insert event  
    public void beforeInsert(){
    }
    
    // Process logic/functioanlities in other classes for before Update  event
    public void beforeUpdate(){
        List<Market_Classification__c> MarketClassObjLst = (list<Market_Classification__c>)Trigger.New;
        MarketClassificationTriggerHelper.isMarketClassificationReferenced(marketClassificationIds,MarketClassObjLst);
        
    }
    // Process logic/functioanlities in other classes for before Delete event
    public void beforeDelete(){
        List<Market_Classification__c> MarketClassObjLst = (list<Market_Classification__c>)Trigger.old;
        MarketClassificationTriggerHelper.isMarketClassificationReferenced(marketClassificationIds,MarketClassObjLst);
    }
    
    // Process logic/functioanlities in other classes for after Update  event
    public void afterInsert(){
    }
    
    // Process logic/functioanlities in other classes for after Update  event 
    public void afterUpdate(){
    }
    
    // Process logic/functioanlities in other classes for after Delete  event
    public void afterDelete(){
    } 
    //Finally do operations to Commit 
    public void finish(){
        
    }
}