force-app/main/default/objects/Account/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this account.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/New_Market__c.field-meta.xml
<CustomField>
    <fullName>New_Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>New_Application_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OppCloseDate__c.field-meta.xml
<CustomField>
    <fullName>OppCloseDate__c</fullName>
    <formula>TODAY() + 180</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OppCloseDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Market_Classification__c/Market_Classification__c.object-meta.xml
<CustomObject>
    <description>Market Classification object is created to store market and market segments for different objects like Account, Lead, and Opportunities. It&apos;s an improvement on an existing way of storing the application and application type on account, lead and opportunities.</description>
    <label>Market Classification</label>
    <nameField>
        <label>Market Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this opportunity.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Values based on the global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Market__c.field-meta.xml
<CustomField>
    <fullName>New_Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is quotation, than it is blank.</description>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/NewOpportunityCtrl.cls
/*
 * Apex Controller for New Opportunity button in Account object in Lightning
 * Author: ldra
 * Date: 27/09/2019
 * */

public class NewOpportunityCtrl {

     @AuraEnabled
     public static Account getAccount(String recordId){
         if(!string.isEmpty(recordId)){
             Account a = [Select Id, CurrencyIsoCode, OwnerId, OppCloseDate__c,Market_Classification__c, New_Application_Type__c, New_Market__c from Account Where id=:recordId];
             return a;
         }
         return null;
     }

     @AuraEnabled
     public static Id save(Opportunity o){
         // Owner is changed in trigger updateOpportunityOwner
         // o.OwnerId = [Select OwnerId from Account Where id=:o.Opportunity_Account__c].OwnerId;
         o.AccountId = o.Opportunity_Account__c;
         upsert o;
         return o.Id;
     }

}