force-app/main/default/objects/Account/fields/NDA_Available__c.field-meta.xml
<CustomField>
    <fullName>NDA_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated with Apex Trigger</description>
    <inlineHelpText>Checked if there is an active NDA (stored under Contracts).</inlineHelpText>
    <label>NDA Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Category__c.field-meta.xml
<CustomField>
    <fullName>Contract_Category__c</fullName>
    <description>Classifies Contract by type of agreement</description>
    <label>Contract Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2022 NCNR agreement</fullName>
            </value>
            <value>
                <fullName>Agency Agreement</fullName>
            </value>
            <value>
                <fullName>Branding Agreement</fullName>
            </value>
            <value>
                <fullName>Commission Agreement</fullName>
            </value>
            <value>
                <fullName>Distribution Agreement</fullName>
            </value>
            <value>
                <fullName>End Use Statement</fullName>
            </value>
            <value>
                <fullName>License Agreement</fullName>
            </value>
            <value>
                <fullName>MoU, LoI, MoA</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>PRA</fullName>
            </value>
            <value>
                <fullName>Quality Agreement</fullName>
            </value>
            <value>
                <fullName>Reseller Agreement</fullName>
            </value>
            <value>
                <fullName>RIL Software Agreement</fullName>
            </value>
            <value>
                <fullName>Risk Waiver Agreement</fullName>
            </value>
            <value>
                <fullName>Sales Agreement</fullName>
            </value>
            <value>
                <fullName>Service Agreement</fullName>
            </value>
            <value>
                <fullName>Special Agreement</fullName>
            </value>
            <value>
                <fullName>Design Partner Program Agreement</fullName>
            </value>
            <value>
                <fullName>Solution Partner Program Agreement</fullName>
            </value>
            <value>
                <fullName>Service Referral Commission Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractTriggerTest.cls
/*
 * Title: ContractTriggerTest
 * Description: Test class for ContractTrigger
 * Author:  ldra
 * Created:  2019-11-14
 */

@isTest
public class ContractTriggerTest {

    @isTest 
    static void execute() {

        Account a = new Account(Name='Test Acc',uB_Office__c='Corporate');
        insert a;
        
        List<Contract> contracts = new List<Contract>();
        Contract c1 =new Contract();  
        c1.Name='Contract1 NDA';
        c1.AccountId=a.Id;
        c1.Contract_Category__c='NDA';
        // Activated status is not allowed for import;
        c1.Status = 'Draft';
        contracts.add(c1);
        
        Contract c2 =new Contract();  
        c2.Name='Contract2 NDA';
        c2.AccountId=a.Id;
        c2.Contract_Category__c='NDA';
        // Activated status is not allowed for import;
        c2.Status = 'Draft';
        contracts.add(c2);
        
        insert contracts;
        
        Contract c = [SELECT Id FROM Contract WHERE AccountId = :a.Id and Name='Contract1 NDA'];
		c.Status = 'Activated'; 
        update c;
        
        a = [SELECT Id, NDA_Available__c FROM Account WHERE Id = :a.Id];
        System.assertEquals(true, a.NDA_Available__c);

        delete c;
        
        a = [SELECT Id, NDA_Available__c FROM Account WHERE Id = :a.Id];
        System.assertEquals(false, a.NDA_Available__c);  

    }

    
}