force-app/main/default/objects/Account/fields/New_Market__c.field-meta.xml
<CustomField>
    <fullName>New_Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>New_Application_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <inlineHelpText>On creation, if empty copied from the master Opportunity after Save. Edit as needed.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <formula>text(Opportunity__r.New_Application_Type__c)</formula>
    <label>Application Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <formula>TEXT( Opportunity__r.Account.uB_Office__c )</formula>
    <label>uB Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <description>Annual run rate of product. If</description>
    <inlineHelpText>Annual run rate. For single shot opportunities, use total quantity.
If Opportunity is converted from Lead, this is copied from Lead.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Values based on the global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Market__c.field-meta.xml
<CustomField>
    <fullName>New_Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Product2/fields/COGS_1__c.field-meta.xml
<CustomField>
    <fullName>COGS_1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cost of goods sold in USD</description>
    <inlineHelpText>Cost of goods sold in USD</inlineHelpText>
    <label>COGS 1</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COGS_Pct__c.field-meta.xml
<CustomField>
    <fullName>COGS_Pct__c</fullName>
    <inlineHelpText>Cost of goods sold as a percentage of the sales price. Added to COGS.</inlineHelpText>
    <label>COGS Pct</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F10</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M10</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
                <color>#B6E32E</color>
                <label>u-blox M9</label>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
                <color>#000099</color>
                <label>u-blox M8</label>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
                <color>#0B6FCE</color>
                <label>u-blox 7</label>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
                <color>#33CCFF</color>
                <label>u-blox 6</label>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
                <color>#6600CC</color>
                <label>u-blox 5</label>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
                <color>#CC66CC</color>
                <label>ANTARIS 4</label>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
                <color>#FF99FF</color>
                <label>Various</label>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
                <color>#999999</color>
                <default>true</default>
                <label>Not applicable</label>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/COGS_1__c.field-meta.xml
<CustomField>
    <fullName>COGS_1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cost of goods sold in USD</description>
    <inlineHelpText>Cost of goods sold in USD</inlineHelpText>
    <label>COGS 1</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/COGS_Pct__c.field-meta.xml
<CustomField>
    <fullName>COGS_Pct__c</fullName>
    <label>COGS Pct</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/updateStatusOnOppProductTestStage3to1.cls
@isTest
public class updateStatusOnOppProductTestStage3to1 {

    private static Product2 createProduct (String Name, String Type)
    {
    return new Product2(
        Name=Name,
        Type_No__C=Type,
        Packaging_Size__c=1,
        Family='Other',
        Positioning_Engine__c='Not applicable',
        CurrencyIsoCode='USD',
        COGS_1__c=20,
        COGS_Pct__c=0);
    }

    private static Opportunity createOpportunity (String Name)
    {
        Account a = new Account(Name='Test Acc',uB_Office__c='Corporate');
        insert a;
        return new Opportunity(
            Name=Name,
            Annual_Quantity__c=10,
            New_Application_Type__c='Asset tracking and management', 
            New_Market__c='Industrial',
            CurrencyIsoCode='USD',
            StageName='3 Calling on',
            Description='test description',
            AccountId=a.Id,
            CloseDate=Date.today());
    }

    private static Opp_Product__c createOppProduct (String ProductID, String OpportunityID, String Status, String Reason)
    {
    return new Opp_Product__c(
        RecordTypeID='012D0000000BaPZ',
        Product__c = ProductID,
        Opportunity__c = OpportunityID,
        CurrencyIsoCode='USD',
        Unit_Price__c=30,
        Status__c=Status,
        Loss_Reason__c=Reason);
    }
    
    public static testMethod void testOppProdStatusReason()
    {
        // Create new Product with mandatory fields (Product Center undefined)
        List<Product2> ProdToInsert = new List <Product2>{};
        Product2 p1 = createProduct ('Test Product 1', 'Test_Type_Number_1');
        ProdToInsert.add(p1);
        Product2 p2 = createProduct ('Test Product 2', 'Test_Type_Number_2');
        ProdToInsert.add(p2);
        Product2 p3 = createProduct ('Test Product 3', 'Test_Type_Number_3');
        ProdToInsert.add(p3);
        Product2 p4 = createProduct ('Test Product 4', 'Test_Type_Number_4');
        ProdToInsert.add(p4);
        Product2 p5 = createProduct ('Test Product 5', 'Test_Type_Number_5');
        ProdToInsert.add(p5);
        insert ProdToInsert;

        // Create new Opportunities with mandatory fields
        // o1: Opportunity Stage from 3 Calling on to 5 Design-in
        // o2: Opportunity Stage from 3 Calling on to 1 Lost
        List<Opportunity> OppToInsert = new List <Opportunity>{};
        Opportunity o1 = createOpportunity ('TestOpp_3_to_5');
        OppToInsert.add(o1);
        insert OppToInsert;

        // Create new Opp Product (Record Type=Positioning)
        // op1: For o1 to test Evaluation to Won
        // op2: For o1 to test Lost (unchanged)
        // op3: For o1 to test Alternative Product to Lost
        // op4: For o2 to test Evaluation to Lost
        // op5: For o2 to test Lost (unchanged)
        // op6: For o2 to test Alternative Product to Lost
        List<Opp_Product__c> OppProdToInsert = new List <Opp_Product__c>{};
        Opp_Product__c op1 = createOppProduct(p1.Id,o1.Id,'Evaluation','');
        OppProdToInsert.add(op1);
        Opp_Product__c op2 = createOppProduct(p2.Id,o1.Id,'Won','Performance');
        OppProdToInsert.add(op2);
        Opp_Product__c op3 = createOppProduct(p3.Id,o1.Id,'Lost','Price');
        OppProdToInsert.add(op3);
        Opp_Product__c op4 = createOppProduct(p4.Id,o1.Id,'Alternative Product','');
        OppProdToInsert.add(op4);
        Opp_Product__c op5 = createOppProduct(p5.Id,o1.Id,'Not applicable','');
        OppProdToInsert.add(op5);

        insert OppProdToInsert;

        // Change Currency in Forecast Unit
        o1.StageName = '1 Lost';
        o1.Reason__c = 'Project Stopped';
        update OppToInsert;

        // Verify that the Status and Reason (Loss_Reason__c) of Opp Products have been changed as expected
        // Stage: 3 Evaluation > 1 Lost
        // Opp Product with Status=Evaluation: Should become Lost, Reason should be from the Opportunity
        Opp_Product__c op1_updated = [SELECT Status__c, Opportunity__r.Reason__c, Loss_Reason__c FROM Opp_Product__c WHERE Product__c = :p1.Id];
        System.assertEquals('Lost', op1_updated.Status__c);
        System.assertEquals(op1_updated.Opportunity__r.Reason__c, op1_updated.Loss_Reason__c);
        Opp_Product__c op2_updated = [SELECT Status__c, Opportunity__r.Reason__c, Loss_Reason__c FROM Opp_Product__c WHERE Product__c = :p2.Id];
        System.assertEquals('Lost', op2_updated.Status__c);
        System.assertEquals(op2_updated.Opportunity__r.Reason__c, op2_updated.Loss_Reason__c);
        Opp_Product__c op3_updated = [SELECT Status__c, Opportunity__r.Reason__c, Loss_Reason__c FROM Opp_Product__c WHERE Product__c = :p3.Id];
        System.assertEquals('Lost', op3_updated.Status__c);
        System.assertEquals('Price', op3_updated.Loss_Reason__c);
        Opp_Product__c op4_updated = [SELECT Status__c, Opportunity__r.Reason__c, Loss_Reason__c FROM Opp_Product__c WHERE Product__c = :p4.Id];
        System.assertEquals('Lost', op4_updated.Status__c);
        System.assertEquals('Alternative Product', op4_updated.Loss_Reason__c);
        Opp_Product__c op5_updated = [SELECT Status__c, Opportunity__r.Reason__c, Loss_Reason__c FROM Opp_Product__c WHERE Product__c = :p5.Id];
        System.assertEquals('Lost', op5_updated.Status__c);
        System.assertEquals('Alternative Product', op5_updated.Loss_Reason__c);

    }
}