force-app/main/default/objects/Account/fields/New_Market__c.field-meta.xml
<CustomField>
    <fullName>New_Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>New_Application_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Values based on the global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Market__c.field-meta.xml
<CustomField>
    <fullName>New_Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is quotation, than it is blank.</description>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/populateOpportunityAccountTest.cls
@isTest
public with sharing class populateOpportunityAccountTest {
    public populateOpportunityAccountTest() {

    }

    
    public static TestMethod void test()
    {
        Account a = new Account();
        a.Name = 'Test Acc';
        a.New_Application_Type__c = 'Mobile robotics';
        insert a;
        
        RecordType rt = [Select Id, Name From RecordType Where SObjectType = 'Opportunity' and Name = 'Opportunity' Limit 1][0];
        
        Opportunity o = new Opportunity();
        o.RecordTypeId = rt.Id;
        o.Name = 'Test Opp';
        o.StageName = 'Prospecting';
        o.CloseDate = System.Today();
        o.AccountId = a.Id;
        // 2016.04.07 khir: Added Description of new Opportunity creation for update of updateStatusOnOppProduct.apxt
        o.Description='test description';
        
        Test.startTest();
            insert o;
        Test.stopTest();
        
        Opportunity updatedOpp = [Select Id, Name, StageName, New_Application_Type__c, New_Market__c, CloseDate, AccountId, Opportunity_Account__c From Opportunity Where Id = :o.Id Limit 1][0];
        
        System.assertEquals(a.Id, updatedOpp.Opportunity_Account__c);
        
        System.assertEquals(a.New_Application_Type__c, updatedOpp.New_Application_Type__c);
        System.assertEquals(a.New_Market__c, updatedOpp.New_Market__c);
    }
}