force-app/main/default/objects/Account/fields/OppCloseDate__c.field-meta.xml
<CustomField>
    <fullName>OppCloseDate__c</fullName>
    <formula>TODAY() + 180</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OppCloseDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is quotation, than it is blank.</description>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Quotation.recordType-meta.xml
<RecordType>
    <fullName>Quotation</fullName>
    <active>true</active>
    <businessProcess>Quotation</businessProcess>
    <label>Quotation</label>
</RecordType>

force-app/main/default/classes/NewOpportunityCtrlTest.cls
@IsTest
private class NewOpportunityCtrlTest{
    public static TestMethod void test(){      
        Account accObj=new Account();
        accObj.Name='Sumit';    
        insert accObj; 
        String accId=accObj.id;
        Account a = NewOpportunityCtrl.getAccount(accId);
        system.assertNotEquals(null, a);
        
        Opportunity o = new Opportunity();
        o.OwnerId = a.OwnerId;
        o.CurrencyIsoCode = a.CurrencyIsoCode;
        o.StageName = '3 Calling On';
        o.CloseDate = a.OppCloseDate__c;
        o.Opportunity_Account__c = a.Id;
        o.Name='Quotation'; 
        Id oId = NewOpportunityCtrl.save(o);
        system.assertNotEquals(null, oId);
    }
}