force-app/main/default/objects/Account/fields/OppCloseDate__c.field-meta.xml
<CustomField>
    <fullName>OppCloseDate__c</fullName>
    <formula>TODAY() + 180</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OppCloseDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <inlineHelpText>On creation, if empty copied from the master Opportunity after Save. Edit as needed.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/IPR_Coverage__c.field-meta.xml
<CustomField>
    <fullName>IPR_Coverage__c</fullName>
    <label>IPR Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Premium coverage</fullName>
            </value>
            <value>
                <fullName>Prime coverage</fullName>
            </value>
            <value>
                <fullName>Premium except Qualcomm</fullName>
            </value>
            <value>
                <fullName>Prime except Qualcomm</fullName>
            </value>
            <value>
                <fullName>No coverage</fullName>
            </value>
            <value>
                <fullName>Full coverage</fullName>
            </value>
            <value>
                <fullName>All except Qualcomm</fullName>
            </value>
            <value>
                <fullName>All except Interdigital</fullName>
            </value>
            <value>
                <fullName>All except QCOM and IDC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <formula>Opportunity__r.Account.Name</formula>
    <label>Opportunity Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <formula>TEXT( Opportunity__r.Account.uB_Office__c )</formula>
    <label>uB Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Use_Restriction__c.field-meta.xml
<CustomField>
    <fullName>Use_Restriction__c</fullName>
    <label>Use Restriction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2G Consumer</fullName>
            </value>
            <value>
                <fullName>2G M2M</fullName>
            </value>
            <value>
                <fullName>2G Telematics</fullName>
            </value>
            <value>
                <fullName>2G Handset</fullName>
            </value>
            <value>
                <fullName>2G Laptop</fullName>
            </value>
            <value>
                <fullName>2G Other</fullName>
            </value>
            <value>
                <fullName>3G M2M</fullName>
            </value>
            <value>
                <fullName>3G Telematics</fullName>
            </value>
            <value>
                <fullName>3G Handset</fullName>
            </value>
            <value>
                <fullName>3G Laptop</fullName>
            </value>
            <value>
                <fullName>3G Other</fullName>
            </value>
            <value>
                <fullName>4G M2M</fullName>
            </value>
            <value>
                <fullName>4G Telematics</fullName>
            </value>
            <value>
                <fullName>4G Handset</fullName>
            </value>
            <value>
                <fullName>4G Laptop</fullName>
            </value>
            <value>
                <fullName>4G Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <description>Annual run rate of product. If</description>
    <inlineHelpText>Annual run rate. For single shot opportunities, use total quantity.
If Opportunity is converted from Lead, this is copied from Lead.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is quotation, than it is blank.</description>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quotation_Account__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is opportunity, than it is blank.</description>
    <label>Quotation Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Referred_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quotation referring to specific opportunity</description>
    <label>Referred Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>List of Quotations</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Referred_Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Quotation appears in this Account under Partner Quotations.</description>
    <inlineHelpText>This Quotation appears in this Account under Partner Quotations.</inlineHelpText>
    <label>Referred Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Quotations</relationshipLabel>
    <relationshipName>ReferredOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Quotation.recordType-meta.xml
<RecordType>
    <fullName>Quotation</fullName>
    <active>true</active>
    <businessProcess>Quotation</businessProcess>
    <label>Quotation</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/NewQuotationCtrlTest.cls
@IsTest
private class NewQuotationCtrlTest{
    public static TestMethod void test(){
        // 2017.11.27 khir: Added Account creation to solve the error for Flow "EMEA_Sales_Stage_8" (made by Process Builder)
        Account acc = new Account(Name='Test Acc 3',uB_Office__c='APAC');
        insert acc;

        Account a = NewQuotationCtrl.getAccount(acc.Id);
        system.debug('0');
        
        Opportunity o = new Opportunity();
        o.OwnerId = [Select Id, Username from User where Username like 'salesforce@u-blox.com%'].Id;
        o.StageName = '3 Calling On';
        o.CloseDate = a.OppCloseDate__c;
        o.Opportunity_Account__c = a.Id;
        o.AccountId = a.Id;
        o.Name='Opportunity'; 
        insert o;
        system.debug('1');
        
        Product2 p = new Product2();
        p.Name = 'Product';
        p.Type_No__c = 'Product-01';
        insert p;
        
        Opp_Product__c op = new Opp_Product__c();
        op.Product__c = p.Id;
        op.Annual_Quantity__c = 200;
        op.Unit_Price__c = 1.2;
        //op.Use_Restriction__c = ;
        //op.IPR_Coverage__c = ;
        op.Opportunity__c = o.Id;
        insert op;
        system.debug('11');
        
        // PricebookEntry pbe = new PricebookEntry();
        // pbe.UnitPrice = 10;
        // pbe.Product2Id = p.Id;
        // pbe.Pricebook2Id = ?;
        // pbe.CurrencyIsoCode = o.CurrencyIsoCode;
        // insert pbe;
        
        Contact c=new Contact();
        c.LastName='sumit singh';
        insert c;
        system.debug('2');
        
        AccountContactRole acr= new AccountContactRole();
        acr.AccountId=a.Id;
        acr.ContactId=c.id;
        acr.IsPrimary = true;
        acr.Role = 'Contact Commercial';
        insert acr;       
     	system.debug('3');
        
        OpportunityContactRole ocr= new OpportunityContactRole();
        ocr.OpportunityId=o.id;
        ocr.ContactId=c.id;
        ocr.Role = 'Contact Quotation';
        insert ocr;       
     	system.debug('33');
        
        Opportunity q = new Opportunity();
        q.OwnerId = o.OwnerId;
        q.CurrencyIsoCode = o.CurrencyIsoCode;
        q.StageName = '3 Calling On';
        q.Quotation_Account__c = a.Id;
        q.Name='Quotation 1'; 
        q.RecordTypeId = '01220000000CqRdAAK';
        q.CloseDate = a.OppCloseDate__c;
        q.Referred_Opportunity__c = o.Id;
        q.Referred_Opportunity_Account__c = o.AccountId;
		system.debug('4');
        
        Id oId1 = NewQuotationCtrl.save(q,'Opportunity');
        system.assertNotEquals(null, oId1);
        
        a = NewQuotationCtrl.getAccount(o.Id);
        
        q = new Opportunity();
        q.OwnerId = o.OwnerId;
        q.CurrencyIsoCode = o.CurrencyIsoCode;
        q.StageName = '3 Calling On';
        q.Quotation_Account__c = a.Id;
        q.Name='Quotation 2'; 
        q.RecordTypeId = '01220000000CqRdAAK';
        q.CloseDate = a.OppCloseDate__c;
		system.debug('4');
        
        Id oId2 = NewQuotationCtrl.save(q,'Account');
        //system.assertNotEquals(null, oId2);
        


    }
}