force-app/main/default/objects/Account/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Distributor account which handles account.</description>
    <inlineHelpText>Distributor account which handles account.</inlineHelpText>
    <label>Partner Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Partner Account)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is quotation, than it is blank.</description>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Partner_Role__c/Partner_Role__c.object-meta.xml
<CustomObject>
    <description>Link between two Accounts for a specific Opportunity</description>
    <label>Partner Role</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>P-Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partner Roles</relationshipLabel>
    <relationshipName>R00N20000000pWzkEAE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Role__c/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Roles (As Opportunity Account)</relationshipLabel>
    <relationshipName>R00N200000018BaOEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Role__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Roles (As Partner Account)</relationshipLabel>
    <relationshipName>R00N20000000pWzvEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Role__c/fields/Partner_Role__c.field-meta.xml
<CustomField>
    <fullName>Partner_Role__c</fullName>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 Partner Referral (commissions required)</fullName>
            </value>
            <value>
                <fullName>0 Partner Referral (no commissions)</fullName>
            </value>
            <value>
                <fullName>1 Opportunity owner</fullName>
            </value>
            <value>
                <fullName>2 Ref. design / platform dev.</fullName>
            </value>
            <value>
                <fullName>3 Design house</fullName>
            </value>
            <value>
                <fullName>3 ODM (Design and Manufacturing)</fullName>
            </value>
            <value>
                <fullName>3 Local Module Maker</fullName>
            </value>
            <value>
                <fullName>4 Consultant/Advisor</fullName>
            </value>
            <value>
                <fullName>4 Certification partner</fullName>
            </value>
            <value>
                <fullName>4 Technology partner</fullName>
            </value>
            <value>
                <fullName>4 MNO / MVNO</fullName>
            </value>
            <value>
                <fullName>5 Former contract manufacturer</fullName>
            </value>
            <value>
                <fullName>5 Actual contract manufacturer</fullName>
            </value>
            <value>
                <fullName>5 Potential contract manufacturer</fullName>
            </value>
            <value>
                <fullName>6 Sourcing / Negotiation entity</fullName>
            </value>
            <value>
                <fullName>6 Purchasing entity</fullName>
            </value>
            <value>
                <fullName>7 Distributor</fullName>
            </value>
            <value>
                <fullName>8 Sales representative</fullName>
            </value>
            <value>
                <fullName>8 Agent</fullName>
            </value>
            <value>
                <fullName>9 Customer of opp. owner</fullName>
            </value>
            <value>
                <fullName>9 Car brand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variable__c/Variable__c.object-meta.xml
<CustomObject>
    <label>Variable</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Variable__c/fields/LastOppID__c.field-meta.xml
<CustomField>
    <fullName>LastOppID__c</fullName>
    <label>LastOppID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Variable__c/fields/LastPartnerRoleID__c.field-meta.xml
<CustomField>
    <fullName>LastPartnerRoleID__c</fullName>
    <label>LastPartnerRoleID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NewPartnerRoleCtrlTest.cls
@IsTest
private class NewPartnerRoleCtrlTest {    
    public static TestMethod void test(){
        
        // 2017.11.27 khir: Added Account creation to solve the error for Flow "EMEA_Sales_Stage_8" (made by Process Builder)
        Account acc = new Account(Name='Test Acc',uB_Office__c='Corporate');
        insert acc;
        
        Opportunity oppObj = new Opportunity();
        oppObj.Name='test'; 
        oppObj.StageName='3 Calling on'; 
        oppObj.CloseDate=System.today();
        oppObj.AccountId=acc.Id; // 2017.11.27 khir
        insert oppObj;      
        
        Opportunity o = NewPartnerRoleCtrl.getRecord(oppObj.Id);
        system.assertNotEquals(null, o);
        
        Partner_Role__c pr1 = new Partner_Role__c();
        pr1.Partner_Role__c = '3 Design house';
        pr1.Opportunity__c = oppObj.Id;
        pr1.CurrencyIsoCode = oppObj.CurrencyIsoCode;
        insert pr1;
        
        Variable__c var =new Variable__c();
        var.Name =UserInfo.getUserId();
        var.LastOppID__c= oppObj.Id;
        var.LastPartnerRoleID__c=pr1.Id; 
        insert var;  
        
        Partner_Role__c pr = new Partner_Role__c();
        pr.Partner_Role__c = '3 Design house';
        pr.Partner_Account__c = acc.Id;
        pr.Opportunity__c = oppObj.Id;
        pr.Opportunity_Account__c = acc.Id;
        pr.CurrencyIsoCode = oppObj.CurrencyIsoCode;
        
        Id prid = NewPartnerRoleCtrl.save(pr);
        system.assertNotEquals(null, prid);
    }
    
    //Test 2
    @isTest
    public static void testingCustomController(){
        
        Account acc = new Account(Name='Test Acc',uB_Office__c='Corporate');
        insert acc;
        
        Opportunity oppObj = new Opportunity();
        oppObj.Name='test'; 
        oppObj.StageName='3 Calling on'; 
        oppObj.CloseDate=System.today();
        oppObj.AccountId=acc.Id;
        insert oppObj;      
        
        Opportunity o = NewPartnerRoleCtrl.getRecord(oppObj.Id);
        system.assertNotEquals(null, o);
        Test.StartTest();
        PageReference pageRef = Page.NewPartnerRolePage; 
        pageRef.getParameters().put('id',oppObj.Id );
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(oppObj);
        NewPartnerRoleCtrl NewPartnerRoleCtrlObj = new NewPartnerRoleCtrl(sc);
        NewPartnerRoleCtrlObj.doSave();
        NewPartnerRoleCtrlObj.doCancel();
        Test.StopTest();
    }
    
}