force-app/main/default/objects/Account/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Distributor account which handles account.</description>
    <inlineHelpText>Distributor account which handles account.</inlineHelpText>
    <label>Partner Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Partner Account)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <description>Annual run rate of product. If</description>
    <inlineHelpText>Annual run rate. For single shot opportunities, use total quantity.
If Opportunity is converted from Lead, this is copied from Lead.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Values based on the global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is quotation, than it is blank.</description>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Partner_Role__c/Partner_Role__c.object-meta.xml
<CustomObject>
    <description>Link between two Accounts for a specific Opportunity</description>
    <label>Partner Role</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>P-Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partner Roles</relationshipLabel>
    <relationshipName>R00N20000000pWzkEAE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Role__c/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Roles (As Opportunity Account)</relationshipLabel>
    <relationshipName>R00N200000018BaOEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Role__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Roles (As Partner Account)</relationshipLabel>
    <relationshipName>R00N20000000pWzvEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Role__c/fields/Partner_Role__c.field-meta.xml
<CustomField>
    <fullName>Partner_Role__c</fullName>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 Partner Referral (commissions required)</fullName>
            </value>
            <value>
                <fullName>0 Partner Referral (no commissions)</fullName>
            </value>
            <value>
                <fullName>1 Opportunity owner</fullName>
            </value>
            <value>
                <fullName>2 Ref. design / platform dev.</fullName>
            </value>
            <value>
                <fullName>3 Design house</fullName>
            </value>
            <value>
                <fullName>3 ODM (Design and Manufacturing)</fullName>
            </value>
            <value>
                <fullName>3 Local Module Maker</fullName>
            </value>
            <value>
                <fullName>4 Consultant/Advisor</fullName>
            </value>
            <value>
                <fullName>4 Certification partner</fullName>
            </value>
            <value>
                <fullName>4 Technology partner</fullName>
            </value>
            <value>
                <fullName>4 MNO / MVNO</fullName>
            </value>
            <value>
                <fullName>5 Former contract manufacturer</fullName>
            </value>
            <value>
                <fullName>5 Actual contract manufacturer</fullName>
            </value>
            <value>
                <fullName>5 Potential contract manufacturer</fullName>
            </value>
            <value>
                <fullName>6 Sourcing / Negotiation entity</fullName>
            </value>
            <value>
                <fullName>6 Purchasing entity</fullName>
            </value>
            <value>
                <fullName>7 Distributor</fullName>
            </value>
            <value>
                <fullName>8 Sales representative</fullName>
            </value>
            <value>
                <fullName>8 Agent</fullName>
            </value>
            <value>
                <fullName>9 Customer of opp. owner</fullName>
            </value>
            <value>
                <fullName>9 Car brand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/alignOppAccOnPartnerRoleTest.cls
@isTest
public class alignOppAccOnPartnerRoleTest {
/*
2016.04.07 khir: Added Description of new Opportunity creation for update of updateStatusOnOppProduct.apxt
*/
        public static testMethod void testOppAccOnPartnerRole()
        {
// 	    System.debug(Logginglevel.INFO, '+ alignOppAccOnPartnerRoleTest.alignOppAccOnPartnerRole'); 

        // Create new Accounts to use for test
        Account a1 = new Account(Name='TestAcc1', BillingCountry='CH', uB_Office__c='Corporate', CurrencyIsoCode='USD');
        insert a1;
        Account a2 = new Account(Name='TestAcc2', BillingCountry='CH', uB_Office__c='Corporate', CurrencyIsoCode='USD');
        insert a2;
        Account a3 = new Account(Name='TestAcc2', BillingCountry='CH', uB_Office__c='Corporate', CurrencyIsoCode='USD');
        insert a3;

        // Create new Opportunity
        // 2016.04.07 khir: Added Description of new Opportunity creation for update of updateStatusOnOppProduct.apxt
        Opportunity o = new Opportunity(Name='TestOpp', Annual_Quantity__c=10, New_Application_Type__c='Asset tracking and management', CurrencyIsoCode='USD', StageName='3 Calling on',CloseDate=Date.today(), Opportunity_Account__c=a1.Id, AccountId=a1.Id, Description='test description');
        insert o;

        // Create new Partner Role
        Partner_Role__c p = new Partner_Role__c(Opportunity__c = o.Id, CurrencyIsoCode='USD', Opportunity_Account__c=a1.Id, Partner_Account__c=a2.Id);
        insert p;
                    
        // Change Opportunity Account in the Opportunity
        o.Opportunity_Account__c = a3.Id;
        o.AccountId=a3.Id;
        update o;
                                                      
        // Verify that the inserted FUP has the same Currency as the related FU                    
        Partner_Role__c updatedPR = [SELECT Opportunity_Account__c FROM Partner_Role__c WHERE Opportunity__c = :o.Id];
        System.assertEquals(o.Opportunity_Account__c, updatedPR.Opportunity_Account__c);
            
            // If the trigger needs to be deactivated, comment all the above and include only below.
//                    System.assertEquals(1, 1);

// 	    System.debug(Logginglevel.INFO, '- alignOppAccOnPartnerRoleTest.alignOppAccOnPartnerRole'); 
        } 
}