force-app/main/default/objects/Account/fields/Potential_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Potential_Competitor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to filter Accounts from the mailing list. Automatically ticked if you create a new Account with Name including Competitor Name (from Competitor object). Clear the check if it isn&apos;t.</description>
    <inlineHelpText>Used to filter Accounts from the mailing list. Automatically ticked if you create a new Account with Name including Competitor Name (from Competitor object). Clear the check if it isn&apos;t.</inlineHelpText>
    <label>Potential Competitor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Object to capture general data about competitors</description>
    <label>Competitor</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CheckCompetitorTestClass.cls
/**
 * @description Test class for checkCompetitor trigger
 *
 * @author ldra
 */

@isTest
private class CheckCompetitorTestClass
{

    @testSetup static void setupData()
    {
       // Adding Competitor
       Competitor__c c = new Competitor__c(Name='Trump Tower');
       insert c;
    }

    @isTest static void testData() 
    {
        ApexTrigger checkCompetitor = [Select Id, Status from ApexTrigger where name='checkCompetitor'];
        if(checkCompetitor.Status == 'Inactive'){
            return;  
        }

        // Adding Account
        Account a = new Account(Name='Trump',uB_Office__c='Americas');
        insert a;

        // Selecting Type from Account
        Account t1 = [select Potential_Competitor__c FROM Account WHERE Id = :a.Id];
            
        // Testing whether the trigger works ok
        System.assertEquals(true, t1.Potential_Competitor__c);

        // Adding Account
        Account p = new Account(Name='Putin',uB_Office__c='EMEA');
        insert p;

        // Selecting Type from Account
        Account t2 = [select Potential_Competitor__c FROM Account WHERE Id = :p.Id];
            
        // Testing whether the trigger works ok
        System.assertEquals(false, t2.Potential_Competitor__c); 
    }
}