force-app/main/default/objects/Account/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>A: annual contribution &gt;$800k
B: annual contribution &gt;$175k
C: business expected but not high $$
Z: no business expected
X: unqualified (should have no X accounts - if you find any change to any of the other priorities)</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>X</fullName>
                <default>true</default>
                <label>X</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Expected_Contribution_CHF__c.field-meta.xml
<CustomField>
    <fullName>Expected_Contribution_CHF__c</fullName>
    <description>Orig:
if ( Order_Status__c = &quot;Open&quot;,
Total_Value_CHF__c 
/* Subtract total COGS and COGS in Pct */
- Qty_Ordered__c  *  Product__r.COGS_CHF__c 
- Total_Value_CHF__c  *  Product__r.COGS_Pct__c ,
0)</description>
    <formula>if ( Order_Status__c = &quot;Open&quot;,
Total_Value_CHF__c 
/* Subtract total COGS and COGS in Pct */
- Qty_Ordered__c  * IF(ISBLANK(Product__r.COGS_CHF__c),0,Product__r.COGS_CHF__c) 
- Total_Value_CHF__c  *  IF(ISBLANK(Product__r.COGS_Pct__c),0,Product__r.COGS_Pct__c) ,
0)</formula>
    <inlineHelpText>Expected contribution of this open order. Empty if Order status &lt;&gt; Open</inlineHelpText>
    <label>Expected Contribution CHF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Frame_Order__c.field-meta.xml
<CustomField>
    <fullName>Frame_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <description>1 if true, 0 else</description>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Frame Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>Date of invoice (valuta). Relevant for reporting</description>
    <inlineHelpText>(From Abacus) Date of invoice (valuta). Relevant for reporting</inlineHelpText>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <formula>IF ( Product_ID__c = &quot;VIA-CB-C&quot;, &quot;Ignore&quot;,
IF( (Qty_Invoiced__c=0)  &amp;&amp; (Total_Value_CHF__c=0) &amp;&amp; ( Qty_Ordered__c = 0), &quot;Ignore&quot;,
IF(Position_Replaced__c=false,
                    IF( ISNULL(Invoice_Date__c)  ||   Qty_Invoiced__c =0 || ISNULL( Invoice_Number__c ) || Invoice_Number__c =&quot;0&quot;, &quot;Open&quot;, &quot;Closed&quot;),
                    &quot;Position Replaced&quot; )
))</formula>
    <inlineHelpText>Values:
- Billing
- Open Order
- Position Replaced
- Ignore</inlineHelpText>
    <label>Order Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Link to Account in Salesforce</inlineHelpText>
    <label>Project Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Project Owner Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Total_Contribution_CHF__c.field-meta.xml
<CustomField>
    <fullName>Total_Contribution_CHF__c</fullName>
    <formula>if ( Order_Status__c != &quot;Closed&quot;, 0, 
Total_Value_CHF__c - Total_COGS_CHF__c 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total contribution of this order.</inlineHelpText>
    <label>Total Contribution CHF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Total_Value_CHF__c.field-meta.xml
<CustomField>
    <fullName>Total_Value_CHF__c</fullName>
    <inlineHelpText>(From Abacus) Billing value in CHF. Imported from Abacus with correct exchange rate</inlineHelpText>
    <label>Total Value CHF</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SalesCloud_ProjectOwnerAccountSummary.cls
public virtual class SalesCloud_ProjectOwnerAccountSummary {
    public SalesCloud_ProjectOwnerAccountSummary() {

    }
    
    public virtual ProjectOwnerAccountSummaryWrapper BillingAndRevenue(Id projectOwnerAccountId){
        ProjectOwnerAccountSummaryWrapper summary = new ProjectOwnerAccountSummaryWrapper();
        if(projectOwnerAccountId != null){            
            /* Booking Contribution calculations of all time in CHF */
            AggregateResult[] results = [Select SUM(Expected_Contribution_CHF__c)AMBookingsContribution                
                                                    from Billings__c 
                                                    where Project_Owner_Account__c =:projectOwnerAccountId
                                                    AND Order_Status__c = 'Open'
                                                    AND Frame_Order__c = false];
            double AMBookingsContributionChf = (double)results[0].get('AMBookingsContribution');
            AMBookingsContributionChf = AMBookingsContributionChf > 0 ? AMBookingsContributionChf : 0;

            /* Booking Revenue calculations of all time in CHF */
            AggregateResult[] results1 = [Select SUM(Total_Value_CHF__c)AMBookingsRevenue                
                                                    from Billings__c 
                                                    where Project_Owner_Account__c =:projectOwnerAccountId
                                                    AND Order_Status__c = 'Open'
                                                    AND Frame_Order__c = false];
            double AMBookingsRevenueChf = (double)results1[0].get('AMBookingsRevenue');
            AMBookingsRevenueChf = AMBookingsRevenueChf > 0 ? AMBookingsRevenueChf : 0;

            /* Billing Contribution calculations of last 365 days */
            AggregateResult[] results2 = [Select SUM(Total_Contribution_CHF__c)AMBillingsContributionTmt                
                                                    from Billings__c 
                                                    where Project_Owner_Account__c =:projectOwnerAccountId
                                                    AND Order_Status__c = 'Closed'
                                                    AND Invoice_Date__c >= LAST_N_DAYS:365];
            double AMBillingsContributionTmtChf = (double)results2[0].get('AMBillingsContributionTmt');
            AMBillingsContributionTmtChf = AMBillingsContributionTmtChf > 0 ? AMBillingsContributionTmtChf : 0;

            /* Billing Revenue calculations of last last 365 days */
            AggregateResult[] results3 = [Select SUM(Total_Value_CHF__c)AMBillingsRevenueTmt                
                                                    from Billings__c 
                                                    where Project_Owner_Account__c =:projectOwnerAccountId
                                                    AND Order_Status__c = 'Closed'
                                                    AND Invoice_Date__c >= LAST_N_DAYS:365];
            double AMBillingsRevenueTmtChf = (double)results3[0].get('AMBillingsRevenueTmt');
            AMBillingsRevenueTmtChf = AMBillingsRevenueTmtChf > 0 ? AMBillingsRevenueTmtChf : 0;

            /* AM Billing Contribution calculations of current fiscal year */
            AggregateResult[] results4 = [Select SUM(Total_Contribution_CHF__c)AMBillingsContributionYtd                
                                                    from Billings__c 
                                                    where Project_Owner_Account__c =:projectOwnerAccountId
                                                    AND Order_Status__c = 'Closed'
                                                    AND Invoice_Date__c >= THIS_FISCAL_YEAR];
            double AMBillingsContributionYtdChf = (double)results4[0].get('AMBillingsContributionYtd');
            AMBillingsContributionYtdChf = AMBillingsContributionYtdChf > 0 ? AMBillingsContributionYtdChf : 0;

            /* AM Billing Revenue calculations of current fiscal year */
            AggregateResult[] results5 = [Select SUM(Total_Value_CHF__c)AMBillingsRevenueYtd                
                                                    from Billings__c 
                                                    where Project_Owner_Account__c =:projectOwnerAccountId
                                                    AND Order_Status__c = 'Closed'
                                                    AND Invoice_Date__c >= THIS_FISCAL_YEAR];
            double AMBillingsRevenueYtdChf = (double)results5[0].get('AMBillingsRevenueYtd');
            AMBillingsRevenueYtdChf = AMBillingsRevenueYtdChf > 0 ? AMBillingsRevenueYtdChf : 0;

            /* AM Billing Contribution calculations of last fiscal year */
            AggregateResult[] results6 = [Select SUM(Total_Contribution_CHF__c)AMBillingsContributionPrevYr                
                                                    from Billings__c 
                                                    where Project_Owner_Account__c =:projectOwnerAccountId
                                                    AND Order_Status__c = 'Closed'
                                                    AND Invoice_Date__c >= LAST_FISCAL_YEAR];
            double AMBillingsContributionPrevYrChf = (double)results6[0].get('AMBillingsContributionPrevYr');
            AMBillingsContributionPrevYrChf = AMBillingsContributionPrevYrChf > 0 ? AMBillingsContributionPrevYrChf : 0;

            /* AM Billing Revenue calculations of last fiscal year */
            AggregateResult[] results7 = [Select SUM(Total_Value_CHF__c)AMBillingsRevenuePrevYr                
                                                    from Billings__c 
                                                    where Project_Owner_Account__c =:projectOwnerAccountId
                                                    AND Order_Status__c = 'Closed'
                                                    AND Invoice_Date__c >= LAST_FISCAL_YEAR];
            double AMBillingsRevenuePrevYrChf = (double)results7[0].get('AMBillingsRevenuePrevYr');
            AMBillingsRevenuePrevYrChf = AMBillingsRevenuePrevYrChf > 0 ? AMBillingsRevenuePrevYrChf : 0;

            list<Account> projectOwnerAccount = [Select Priority__c 
                                                    from Account 
                                                    where Id =: projectOwnerAccountId];
            
            string Priority;
            if(projectOwnerAccount[0].Priority__c != 'A'
                    && AMBillingsContributionTmtChf >= 800000){
                    Priority = 'A';
            }else if(projectOwnerAccount[0].Priority__c != 'B'
                    && AMBillingsContributionTmtChf < 800000
                    && AMBillingsContributionTmtChf >= 175000){
                    Priority = 'B';
            }else if((projectOwnerAccount[0].Priority__c == 'A' 
                    || projectOwnerAccount[0].Priority__c == 'B')
                    && AMBillingsContributionTmtChf < 175000){
                    Priority = 'CXZ';
            }else Priority = projectOwnerAccount[0].Priority__c;        
            
            summary.AMBookingsContributionChf = AMBookingsContributionChf;
            summary.AMBookingsRevenueChf = AMBookingsRevenueChf;
            summary.AMBillingsContributionTmtChf = AMBillingsContributionTmtChf;
            summary.AMBillingsRevenueTmtChf = AMBillingsRevenueTmtChf;
            summary.AMBillingsContributionYtdChf = AMBillingsContributionYtdChf;
            summary.AMBillingsRevenueYtdChf = AMBillingsRevenueYtdChf;
            summary.AMBillingsContributionPrevYrChf = AMBillingsContributionPrevYrChf;
            summary.AMBillingsRevenuePrevYrChf = AMBillingsRevenuePrevYrChf;
            summary.AMPrioChangeProposed = Priority;
        }
        return summary;
    }
    
    public class ProjectOwnerAccountSummaryWrapper {
        @AuraEnabled public double AMBookingsContributionChf {get; set;}
        @AuraEnabled public double AMBookingsRevenueChf {get; set;}
        @AuraEnabled public double AMBillingsContributionTmtChf {get; set;}
        @AuraEnabled public double AMBillingsRevenueTmtChf {get; set;}
        @AuraEnabled public double AMBillingsContributionYtdChf {get; set;}
        @AuraEnabled public double AMBillingsRevenueYtdChf {get; set;}
        @AuraEnabled public double AMBillingsContributionPrevYrChf {get; set;}
        @AuraEnabled public double AMBillingsRevenuePrevYrChf {get; set;}
        @AuraEnabled public string AMPrioChangeProposed {get; set;}        
    }
}