force-app/main/default/objects/Account/fields/Reporting_Region__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Region__c</fullName>
    <inlineHelpText>(From Abacus) Region for which sales are reported by default. Can be adapted in Abacus for each Order.</inlineHelpText>
    <label>Reporting Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <inlineHelpText>(From Abacus) Date of delivery. Used to calculate delivery reliability</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Frame_Order__c.field-meta.xml
<CustomField>
    <fullName>Frame_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <description>1 if true, 0 else</description>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Frame Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <inlineHelpText>(From Abacus) Date of order intake.</inlineHelpText>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Order_No__c.field-meta.xml
<CustomField>
    <fullName>Order_No__c</fullName>
    <description>Order Number</description>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Order No</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <formula>Product__r.Packaging_Size__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Packaging Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/PO_No_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>PO_No_Line_Item__c</fullName>
    <description>From Abacus</description>
    <inlineHelpText>From Abacus</inlineHelpText>
    <label>PO No Line Item</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Price_per_unit__c.field-meta.xml
<CustomField>
    <fullName>Price_per_unit__c</fullName>
    <inlineHelpText>(From Abacus) Price per unit in local currency</inlineHelpText>
    <label>Price per unit</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <formula>text(Product__r.Product_Center__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Product Center: copied from product property</inlineHelpText>
    <label>Product Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <description>Product identification</description>
    <inlineHelpText>(From Abacus) Product identification. Used to match with field &quot;Type No&quot; in Salesforce products.</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Qty_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Qty_Ordered__c</fullName>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Qty Ordered</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <inlineHelpText>(From Abacus) Customer reference. Used to indicate shop orders</inlineHelpText>
    <label>Reference</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Reporting_Region__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Region__c</fullName>
    <inlineHelpText>(From Abacus) Reporting region</inlineHelpText>
    <label>Reporting Region</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <inlineHelpText>(From Abacus) Date of request delivery</inlineHelpText>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Total_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Value__c</fullName>
    <inlineHelpText>(From Abacus) Total Value of order in local currency</inlineHelpText>
    <label>Total Value</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/USDtoCHF__c.field-meta.xml
<CustomField>
    <fullName>USDtoCHF__c</fullName>
    <inlineHelpText>Exchange rate USD to CHF at the date of invoicing</inlineHelpText>
    <label>USDtoCHF</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F10</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M10</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
                <color>#B6E32E</color>
                <label>u-blox M9</label>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
                <color>#000099</color>
                <label>u-blox M8</label>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
                <color>#0B6FCE</color>
                <label>u-blox 7</label>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
                <color>#33CCFF</color>
                <label>u-blox 6</label>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
                <color>#6600CC</color>
                <label>u-blox 5</label>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
                <color>#CC66CC</color>
                <label>ANTARIS 4</label>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
                <color>#FF99FF</color>
                <label>Various</label>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
                <color>#999999</color>
                <default>true</default>
                <label>Not applicable</label>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <formula>Id</formula>
    <label>Product Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Tashang</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ShowOrdersListTest.cls
@IsTest
public class ShowOrdersListTest {

	@isTest
    static void TestgetOrders(){
        AccountTestDataFactory account = new AccountTestDataFactory();
        SObject accountRecord = account.createRecord();
        system.debug('accountRecord  ufar >>>> '+accountRecord);
		
        Product2 product2 = new Product2(Name = 'EVK-M101', Type_No__c= 'EVK-M101-00-00', ProductCode= 'EVK-M101-00', Family = 'Eval Kit', Positioning_Engine__c = 'Not applicable', Product_Center__c = 'Positioning', Packaging_Size__c = 1000);
        insert product2;
        system.debug('product2 ufar >>>> '+product2);
        // Date.newInstance(2022, 10, 10)
       	Billings__c mybillings = new Billings__c(Name = 'Test Billings', Total_Value__c = 5000 , Price_per_unit__c = 5, Qty_Ordered__c = 400, Delivery_Date__c = Date.today(), Request_Date__c = Date.today(), Order_Date__c = Date.today(), Frame_Order__c = false, Product_ID__c = 'EVK-M101-00-00', Reporting_Region__c = 'AMERICAS', Reference__c = 'test reference', Order_No__c = 123456, PO_No_Line_Item__c = 'test line number' , USDtoCHF__c = 5,  Invoice_Number__c = 'abc0123', Total_Value_CHF__c = 10, Total_COGS_CHF__c = 2, Invoice_Date__c =Date.today(), Product__c = product2.id,Account__c = accountRecord.id , End_Customer_Account__c= accountRecord.id, Project_Owner_Account__c = accountRecord.id);
        insert mybillings;
        system.debug('mybillings ufar >>>> '+mybillings);
        
        Opportunity opp = new Opportunity(Name = 'Test Opportunity1', product_1__c = product2.id , StageName = '3 Calling on', CloseDate = Date.today(), AccountId = accountRecord.id);
		insert opp;
        system.debug('opp ufar  >>>> '+opp);
        
        test.startTest();
         
        List<Account> acc = [SELECT SF_Account_Number__c FROM Account WHERE id=:accountRecord.id];
       	List<Billings__c> listBillngAccount = ShowOrderslist.getOrders(accountRecord.id);
		List<Billings__c> listBillngOpportunity = ShowOrderslist.getOrders(opp.id);
                
        system.assert(listBillngAccount.size() >0);
        system.assert(listBillngOpportunity.size() >0);

        test.stopTest();
    }
}


/*
@IsTest
public class ShowOrdersListTest {

	@isTest
    static void TestgetOrders(){
        AccountTestDataFactory account = new AccountTestDataFactory();
        BillingsTestDataFactory billings = new BillingsTestDataFactory();
        OpportunityTestDataFactory opportunity = new OpportunityTestDataFactory();
        SObject accountRecord = account.createRecord();
        SObject billingsRecord = billings.createRecord();
        SObject oppRecord = opportunity.createRecord();
        
        test.startTest();
         
       	ShowOrderslist.getOrders(accountRecord.id);
       	ShowOrderslist.getOrders(oppRecord.id);
        //system.debug('acc ---- '+acc);
        //system.debug('billingsRecord ---- '+billingsRecord);
        //system.debug('accountRecord ---- '+accountRecord);
		//system.debug('reportOrdersList ---- '+reportOrdersList);
        test.stopTest();
    }
}
*/