force-app/main/default/objects/Account/fields/SF_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SF_Account_Number__c</fullName>
    <displayFormat>{0}</displayFormat>
    <inlineHelpText>Automatically generated number that is used to identify end customers in Abacus</inlineHelpText>
    <label>SF Account Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Salesforce Account. Conneced via field &quot;Customer No&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>Date of invoice (valuta). Relevant for reporting</description>
    <inlineHelpText>(From Abacus) Date of invoice (valuta). Relevant for reporting</inlineHelpText>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <formula>IF ( Product_ID__c = &quot;VIA-CB-C&quot;, &quot;Ignore&quot;,
IF( (Qty_Invoiced__c=0)  &amp;&amp; (Total_Value_CHF__c=0) &amp;&amp; ( Qty_Ordered__c = 0), &quot;Ignore&quot;,
IF(Position_Replaced__c=false,
                    IF( ISNULL(Invoice_Date__c)  ||   Qty_Invoiced__c =0 || ISNULL( Invoice_Number__c ) || Invoice_Number__c =&quot;0&quot;, &quot;Open&quot;, &quot;Closed&quot;),
                    &quot;Position Replaced&quot; )
))</formula>
    <inlineHelpText>Values:
- Billing
- Open Order
- Position Replaced
- Ignore</inlineHelpText>
    <label>Order Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated with Billing</description>
    <inlineHelpText>Product associated with Billing</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <formula>text(Product__r.Product_Center__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Product Center: copied from product property</inlineHelpText>
    <label>Product Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_SF_Acc_No__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_SF_Acc_No__c</fullName>
    <formula>Project_Owner_Account__r.SF_Account_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Copy of &quot;Project Owner Account Number&quot; that allows filtering of orders (used in Custom Button &quot;Show Orders&quot; on Account level)</inlineHelpText>
    <label>Project Owner SF Acc No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Qty_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Qty_Invoiced__c</fullName>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Qty Invoiced</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/SF_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SF_Account_Number__c</fullName>
    <inlineHelpText>(From Abacus) Account number of end customer.</inlineHelpText>
    <label>End Customer SF Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Total_Contribution_USD__c.field-meta.xml
<CustomField>
    <fullName>Total_Contribution_USD__c</fullName>
    <formula>if ( USDtoCHF__c = 0, 0,  Total_Contribution_CHF__c / USDtoCHF__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Contribution in USD, calculated with ex rate of the month.</inlineHelpText>
    <label>Total Contribution USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Total_Value_USD__c.field-meta.xml
<CustomField>
    <fullName>Total_Value_USD__c</fullName>
    <formula>if ( USDtoCHF__c = 0, Total_Value_CHF__c /  $User.USDtoCHF__c ,  Total_Value_CHF__c / USDtoCHF__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Value of order in USD, calculated with value in field USDtoCHF (ex rate of invoice date), if this field is empty then ex rate of the month is used</inlineHelpText>
    <label>Total Value USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BillingHistoryList.cls
public class BillingHistoryList {
    private static final string ACCOUNTOBJ = 'Account';
    private static final string OPEN = 'Open';
    private static final string CLOSED = 'Closed';
    public BillingHistoryList(){
    }
	@AuraEnabled
    public static Map<string, Map<Integer,BillingHistoryWrapper>> bHistoryOrders(Id recordId){
        Map<string, Map<Integer,BillingHistoryWrapper>> resmap = new Map<string, Map<Integer,BillingHistoryWrapper>>();
        if(recordId != null){       
            String sobjectType = recordId.getSObjectType().getDescribe().getName();
            if(sobjectType == ACCOUNTOBJ){
                List<Account> acc = [SELECT SF_Account_Number__c FROM Account WHERE id=:recordId Limit 1];            
                List<AggregateResult> aggriRes = [ SELECT SUM(Qty_Invoiced__c)QtyInvoiced, 
                                                  SUM(Total_Contribution_USD__c)TotalContributionUSD, 
                                                  SUM(Total_Value_USD__c)TotalValueUSD, 
                                                  CALENDAR_YEAR(Invoice_Date__c)InvoiceDate, 
                                                  Product__r.Product_Center__c 
                                                  From Billings__c 
                                                  Where
                                                  Invoice_Date__c >= LAST_N_YEARS:4 
                                                  AND ( Account__r.SF_Account_Number__c=:acc[0].SF_Account_Number__c OR SF_Account_Number__c=:acc[0].SF_Account_Number__c OR Project_Owner_SF_Acc_No__c =:acc[0].SF_Account_Number__c)
                                                  AND (Order_Status__c =:OPEN OR Order_Status__c =:CLOSED ) 
                                                  GROUP BY CALENDAR_YEAR(Invoice_Date__c), Product__r.Product_Center__c ];
                If( aggriRes.size() > 0 ) 
                {                   
                        set<string> pCenterSet = new set<string>();
                        set<integer> iDate = new set<integer>();
                        for(AggregateResult res: aggriRes ){
                            String productCenter =(String) res.get('Product_Center__c');
                            pCenterSet.add(productCenter);
                                if (!resmap.containsKey(productCenter)){
                                    resmap.put(productCenter, New Map<Integer,BillingHistoryWrapper>());
                                }
                            Map<Integer,BillingHistoryWrapper> currentProdMap = resmap.get(productCenter);
                                Integer invoiceDate =(Integer) res.get('InvoiceDate');
                                iDate.add(invoiceDate);                               
                                currentProdMap.put(invoiceDate, New BillingHistoryWrapper((Double)res.get('QtyInvoiced'),(Double)res.get('TotalContributionUSD'), (Double)res.get('TotalValueUSD')));
                                resmap.put(productCenter,currentProdMap);   
                        }
                        for(string c : pCenterSet){
                            for(integer i : iDate){
                                if(!resmap.get(c).containsKey(i)){
                                    Map<Integer,BillingHistoryWrapper> currentProdMap = resmap.get(c);
                                    currentProdMap.put(i,New BillingHistoryWrapper(0,0,0));
                                    resmap.put(c,currentProdMap);                                
                                }
                            }
                        }
                    }
                }
        }
            return resmap;

    }
    public class BillingHistoryWrapper {
        public  BillingHistoryWrapper(Double QtyInvo, Double TotCon, Double TotValUSD) {
          	this.QtyInvoiced = QtyInvo;
            this.TotalContributionUSDList = TotCon;
            this.TotalValueUSDList = TotValUSD;
       	}
	    @AuraEnabled
        public  Double QtyInvoiced {get; set;}
        @AuraEnabled
        public  Double TotalContributionUSDList {get; set;}
        @AuraEnabled
        public  Double TotalValueUSDList {get; set;}
        @AuraEnabled
        public  Double totalValues {get; set;}
      
	}
    /*
    public class ProductCenter {
        @AuraEnabled
        public string productCenter {get; set;}
        @AuraEnabled
        public list<Years> Years	{get; set;}
        @AuraEnabled
        public Double totalByProductCenter	{get; set;}
    }
    public class Years {
        @AuraEnabled
        public string Year	{get; set;}
        @AuraEnabled
        public BillingHistoryWrapper billing{get; set;}
    }
		*/
}