force-app/main/default/objects/Account/fields/SF_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SF_Account_Number__c</fullName>
    <displayFormat>{0}</displayFormat>
    <inlineHelpText>Automatically generated number that is used to identify end customers in Abacus</inlineHelpText>
    <label>SF Account Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Salesforce Account. Conneced via field &quot;Customer No&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <inlineHelpText>(From Abacus) Date of delivery. Used to calculate delivery reliability</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/End_Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The end customer is the company buying from the Account that buys from us. Typically this is the customer of our distributor or direct CM.</inlineHelpText>
    <label>End Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (End Customer Account)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/End_Customer_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account_ID__c</fullName>
    <description>Field used in &quot;Show Orders&quot; report under Account.</description>
    <formula>End_Customer_Account__r.Id</formula>
    <label>End Customer Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/End_Customer_Account_SF_Number__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account_SF_Number__c</fullName>
    <description>Copy of Salesforce Account number that allows filtering of orders (used in Custom Button &quot;Show Orders&quot; on Account level)</description>
    <formula>End_Customer_Account__r.SF_Account_Number__c</formula>
    <label>End Customer Account SF Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Frame_Order__c.field-meta.xml
<CustomField>
    <fullName>Frame_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <description>1 if true, 0 else</description>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Frame Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <description>This field is used to determine that a shipment has actually been made. In cases of pre-payment, the invoice quantity and invoice date might be set in order to print a pro-forma invoice, but the shipment awaits the payment.</description>
    <inlineHelpText>(From Abacus) Identification number of the invoice sent to customer.</inlineHelpText>
    <label>Invoice Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <inlineHelpText>(From Abacus) Date of order intake.</inlineHelpText>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Order_No__c.field-meta.xml
<CustomField>
    <fullName>Order_No__c</fullName>
    <description>Order Number</description>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Order No</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <formula>IF ( Product_ID__c = &quot;VIA-CB-C&quot;, &quot;Ignore&quot;,
IF( (Qty_Invoiced__c=0)  &amp;&amp; (Total_Value_CHF__c=0) &amp;&amp; ( Qty_Ordered__c = 0), &quot;Ignore&quot;,
IF(Position_Replaced__c=false,
                    IF( ISNULL(Invoice_Date__c)  ||   Qty_Invoiced__c =0 || ISNULL( Invoice_Number__c ) || Invoice_Number__c =&quot;0&quot;, &quot;Open&quot;, &quot;Closed&quot;),
                    &quot;Position Replaced&quot; )
))</formula>
    <inlineHelpText>Values:
- Billing
- Open Order
- Position Replaced
- Ignore</inlineHelpText>
    <label>Order Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/PO_No_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>PO_No_Line_Item__c</fullName>
    <description>From Abacus</description>
    <inlineHelpText>From Abacus</inlineHelpText>
    <label>PO No Line Item</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Price_per_unit__c.field-meta.xml
<CustomField>
    <fullName>Price_per_unit__c</fullName>
    <inlineHelpText>(From Abacus) Price per unit in local currency</inlineHelpText>
    <label>Price per unit</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated with Billing</description>
    <inlineHelpText>Product associated with Billing</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <description>Product identification</description>
    <inlineHelpText>(From Abacus) Product identification. Used to match with field &quot;Type No&quot; in Salesforce products.</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Link to Account in Salesforce</inlineHelpText>
    <label>Project Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Project Owner Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_Account_ID__c</fullName>
    <formula>Project_Owner_Account__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Owner Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_SF_Acc_No__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_SF_Acc_No__c</fullName>
    <formula>Project_Owner_Account__r.SF_Account_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Copy of &quot;Project Owner Account Number&quot; that allows filtering of orders (used in Custom Button &quot;Show Orders&quot; on Account level)</inlineHelpText>
    <label>Project Owner SF Acc No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Qty_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Qty_Invoiced__c</fullName>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Qty Invoiced</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Qty_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Qty_Ordered__c</fullName>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Qty Ordered</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <inlineHelpText>(From Abacus) Customer reference. Used to indicate shop orders</inlineHelpText>
    <label>Reference</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Reporting_uB_Office__c.field-meta.xml
<CustomField>
    <fullName>Reporting_uB_Office__c</fullName>
    <formula>Case (Reporting_Area__c,
&quot;AU&quot;,&quot;Australia&quot;,
&quot;IN&quot;,&quot;India&quot;,
&quot;MY&quot;,&quot;Rest of APAC&quot;,
&quot;NZ&quot;,&quot;Australia&quot;,
&quot;PH&quot;,&quot;Rest of APAC&quot;,
&quot;SG&quot;,&quot;Rest of APAC&quot;,
&quot;TH&quot;,&quot;Rest of APAC&quot;,
&quot;VN&quot;,&quot;Rest of APAC&quot;,
&quot;JP&quot;,&quot;Japan&quot;,
&quot;CN&quot;,&quot;China&quot;,
&quot;HK&quot;,&quot;China&quot;,
&quot;TW&quot;,&quot;Taiwan&quot;,
&quot;KR&quot;,&quot;Korea&quot;,
&quot;Rest of APAC&quot;,&quot;Rest of APAC&quot;,

    Case(Reporting_Region__c ,
    &quot;EMEA&quot;,&quot;EMEA&quot;,
    &quot;AMERICAS&quot;, &quot;Americas&quot;,
    &quot;UBX Corporate&quot;)
)</formula>
    <inlineHelpText>uB Office for reporting, derived from Reporting Area.</inlineHelpText>
    <label>Reporting uB Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <inlineHelpText>(From Abacus) Date of request delivery</inlineHelpText>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/SF_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SF_Account_Number__c</fullName>
    <inlineHelpText>(From Abacus) Account number of end customer.</inlineHelpText>
    <label>End Customer SF Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Total_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Value__c</fullName>
    <inlineHelpText>(From Abacus) Total Value of order in local currency</inlineHelpText>
    <label>Total Value</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End Customer Account)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_1__c.field-meta.xml
<CustomField>
    <fullName>Product_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (1st in the related list).</inlineHelpText>
    <label>Product 1</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 1)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_2__c.field-meta.xml
<CustomField>
    <fullName>Product_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (2nd in the related list).</inlineHelpText>
    <label>Product 2</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 2)</relationshipLabel>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_3__c.field-meta.xml
<CustomField>
    <fullName>Product_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (3rd in the related list).</inlineHelpText>
    <label>Product 3</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 3)</relationshipLabel>
    <relationshipName>Opportunities5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_4__c.field-meta.xml
<CustomField>
    <fullName>Product_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (4th in the related list).</inlineHelpText>
    <label>Product 4</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 4)</relationshipLabel>
    <relationshipName>Opportunities6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_5__c.field-meta.xml
<CustomField>
    <fullName>Product_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled automatically with the added Opp Product (5th in the related list).</inlineHelpText>
    <label>Product 5</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Product 5)</relationshipLabel>
    <relationshipName>Opportunities7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SF_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SF_Account_Number__c</fullName>
    <formula>Account.SF_Account_Number__c</formula>
    <inlineHelpText>SF Account Number of the Opportunity Account</inlineHelpText>
    <label>SF Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <formula>Id</formula>
    <label>Product Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ShowOrderslist.cls
public class ShowOrderslist {

    private static final string ACCOUNTOBJ = 'Account';
    private static final string OPPRTUNITYOBJ = 'Opportunity';
    private static final string OPEN = 'Open';
    private static final string CLOSED = 'Closed';
    @AuraEnabled
    public static List<Billings__c> getOrders(Id recordId){
        Date deliverDateRange = Date.newInstance(2021,01,01);
        List<Billings__c> reportOrdersList = new List<Billings__c>();
        String sobjectType = recordId.getSObjectType().getDescribe().getName();

        // IF Record is Account
        if(sobjectType == ACCOUNTOBJ){
                    List<Account> acc = [SELECT SF_Account_Number__c FROM Account WHERE id=:recordId Limit 1];
            try{
                    reportOrdersList = [Select id, Name, 
                              Order_No__c, PO_No_Line_Item__c, Invoice_Number__c, 
                              Reference__c, Account__c,
                              Account__r.Name, Reporting_uB_Office__c, 
                              Order_Status__c, Product_ID__c, 
                              Frame_Order__c, Order_Date__c, 
                              Request_Date__c, Delivery_Date__c, 
                              Qty_Ordered__c, Qty_Invoiced__c, 
                              Price_per_unit__c, Total_Value__c, 
                              End_Customer_Account__c,End_Customer_Account__r.Name, Project_Owner_Account__c,Project_Owner_Account__r.Name,
                              End_Customer_Account_SF_Number__c, Project_Owner_SF_Acc_No__c
                              From Billings__c
                              Where Delivery_Date__c >=:deliverDateRange 
                              AND (Account__r.SF_Account_Number__c=:acc[0].SF_Account_Number__c OR 
                                   End_Customer_Account_SF_Number__c =:acc[0].SF_Account_Number__c OR 
                                   Project_Owner_SF_Acc_No__c =:acc[0].SF_Account_Number__c)
                              AND (Order_Status__c =:OPEN OR Order_Status__c =:CLOSED )
                                       Order By CreatedDate DESC];
            }catch(Exception e){                
                throw new AuraHandledException('Error: '+e.getMessage());                
            }

                return reportOrdersList;
            }
        // IF record is Opportunity
        else if(sobjectType == OPPRTUNITYOBJ){            
            List<Opportunity> oppData = [select AccountId,product_1__r.Name,product_2__r.Name,
                                          product_3__r.Name,product_4__r.Name,product_5__r.Name 
                                          From Opportunity Where Id=:recordId Limit 1];
               if(oppData.size() > 0){
                   try{
                    reportOrdersList = [Select id, Name, 
                          Order_No__c, PO_No_Line_Item__c, Invoice_Number__c, 
                          Reference__c, Account__c,
                          Account__r.Name, Reporting_uB_Office__c, 
                          Order_Status__c, Product_ID__c,Product__c, 
                          Frame_Order__c, Order_Date__c, 
                          Request_Date__c, Delivery_Date__c, 
                          Qty_Ordered__c, Qty_Invoiced__c, 
                          Price_per_unit__c, Total_Value__c, 
                          End_Customer_Account__c,End_Customer_Account__r.Name, Project_Owner_Account__c,Project_Owner_Account__r.Name,
                          End_Customer_Account_SF_Number__c, Project_Owner_SF_Acc_No__c,
                          End_Customer_Account_ID__c, 
                          Project_Owner_Account_ID__c, Product__r.Name            
                          From Billings__c 
                          Where Delivery_Date__c >= LAST_N_DAYS:730 AND (Order_Status__c =:OPEN OR Order_Status__c =:CLOSED)   
                          AND ( Product__r.Name =: oppData[0].product_1__r.Name
                                OR Product__r.Name =: oppData[0].product_2__r.Name 
                                OR Product__r.Name =: oppData[0].product_3__r.Name
                                OR Product__r.Name =: oppData[0].product_4__r.Name
                                OR Product__r.Name =: oppData[0].product_5__r.Name)
                                AND (Account__c=:oppData[0].AccountId OR End_Customer_Account__c=:oppData[0].AccountId OR Project_Owner_Account__c=:oppData[0].AccountId )
                                       Order By CreatedDate DESC];
                   }catch(Exception e){                       
                       throw new AuraHandledException('Error: '+e.getMessage());
                   }
               }
            return reportOrdersList;
        }
        return reportOrdersList; 
    }
}