force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/AssistNow_Token_Resend__c.field-meta.xml
<CustomField>
    <fullName>AssistNow_Token_Resend__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for Email Alert to resend the token.</description>
    <inlineHelpText>Used for Email Alert to resend the token.</inlineHelpText>
    <label>AssistNow Token Resend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AssistNow_Token_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>AssistNow_Token_To_Delete__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Token to be deactivated is copied to this field and sent to svc-pos-team-GLOBAL@u-blox.com</description>
    <inlineHelpText>Token to be deactivated is copied to this field and sent to svc-pos-team-GLOBAL@u-blox.com</inlineHelpText>
    <label>AssistNow Token To Delete</label>
    <length>22</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/e_LULA_M__c.field-meta.xml
<CustomField>
    <fullName>e_LULA_M__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the email will be sent to the Contact with the URL to e-LULA-M (Limited Use License Agreement for Marvel) form.</description>
    <inlineHelpText>When checked, the email will be sent to the Contact with the URL to e-LULA-M (Limited Use License Agreement for Marvel) form.</inlineHelpText>
    <label>e-LULA-M</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/e_LULA_N__c.field-meta.xml
<CustomField>
    <fullName>e_LULA_N__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the email will be sent to the Contact with the URL to e-LULA-N (Limited Use License Agreement for NXP) form.</description>
    <inlineHelpText>When checked, the email will be sent to the Contact with the URL to e-LULA-N (Limited Use License Agreement for NXP) form.</inlineHelpText>
    <label>e-LULA-N</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/e_NDA__c.field-meta.xml
<CustomField>
    <fullName>e_NDA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the email will be sent to the Contact with the URL to e-NDA form.</description>
    <inlineHelpText>When checked, the email will be sent to the Contact with the URL to e-NDA form.</inlineHelpText>
    <label>e-NDA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MGA__c.field-meta.xml
<CustomField>
    <fullName>MGA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Multi-GNSS AssistNow Service
Checked: The token is active or needs to be generated. If AssistNow Requested Date is empty, press button &quot;AssistNow Request&quot; to generate a new token.
Unchecked: The token will be deactivated and deleted.</inlineHelpText>
    <label>AssistNow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MGA_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>MGA_Requested_Date__c</fullName>
    <inlineHelpText>When the AssistNow Token has been generated</inlineHelpText>
    <label>AssistNow Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MGA_Token__c.field-meta.xml
<CustomField>
    <fullName>MGA_Token__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>AssistNow Token. Generated with button &quot;AssistNow Enable&quot;.</inlineHelpText>
    <label>AssistNow Token</label>
    <length>22</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Analyst (Report)</fullName>
            </value>
            <value>
                <fullName>Auditor</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Investment banker</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Portfolio manager</fullName>
            </value>
            <value>
                <fullName>Sales/Broker</fullName>
            </value>
            <value>
                <fullName>Shareholder engagement</fullName>
            </value>
            <value>
                <fullName>Trader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTestDataFactory.cls
@isTest
public class ContactTestDataFactory extends TestDataFactory {
    
    public ContactTestDataFactory() {
        super('contact');
    }

    public override sObject initializeRecord(){
        Contact c = new Contact();
        c.LastName = 'Test Contact1';
        return c;
    }

    public override sObject createRecord() {
        Contact c = (Contact)initializeRecord();
        Insert c;
        return c;
    }

    public override List<sObject> createBulkRecords() {
        for (Integer i = 0; i < numberOfRecords; i++) {
            Contact cont = new Contact();
            cont.LastName = 'Test Contact'+i;
            recordsList.add(cont);
        }
        Insert recordsList;
        return recordsList;
    }

    public Contact updateRecords(Contact toupdate) {
        toUpdate.MGA_Token__c = 'tokenupdaed';
        update toupdate;
        return toupdate;
    } 

    
    public Database.SaveResult[] COP_Record_Type_Std_Record() {
        String record = '[{"LastName": "Test Contact 1", "Role__c": "Other"}]';
        return createBulkRecordsfromJson(record);
    }

    public Database.SaveResult[] COP_Record_Type_Finance_Record() {
        String record = '[{"LastName": "Test Contact 1", "Role__c": "Shareholder engagement", "RecordTypeId": "01257000000BeCAAA0"}]';
        return createBulkRecordsfromJson(record);
    }

    public Database.SaveResult[] AssistNow_new_token_generation_Record() {
        String record = '[{"LastName": "Test Contact 1", "MGA__c": "true", "MGA_Token__c": "thisistoken32", "Email": "testuser@example.com"}]';
        return createBulkRecordsfromJson(record);
    }

    public Database.SaveResult[] AssistNow_token_to_deactivate_Record() {
        String record = '[{"LastName": "Test Contact 1", "MGA__c": "false", "Email": "testuser@example.com", "MGA_Requested_Date__c": "2016-10-30T15:27:02.000Z", "AssistNow_Token_To_Delete__c": "delete"}]';
        return createBulkRecordsfromJson(record);
    }

    public Database.SaveResult[] AssistNow_token_to_resend_Record() {
        String record = '[{"LastName": "Test Contact 1", "Email": "testuser@example.com", "AssistNow_Token_Resend__c": "true"}]';
        return createBulkRecordsfromJson(record);
    }

    public Database.SaveResult[] Send_e_LULA_M_link_to_Contact_Record() {
        String record = '[{"LastName": "Test Contact 1", "Email": "testuser@example.com", "e_LULA_M__c": "false"}]';
        return createBulkRecordsfromJson(record);
    }

    public Database.SaveResult[] Send_e_LULA_N_link_to_Contact_Record() {
        String record = '[{"LastName": "Test Contact 1", "Email": "testuser@example.com", "e_LULA_N__c": "false"}]';
        return createBulkRecordsfromJson(record);
    }

    public Database.SaveResult[] Send_e_NDA_Americas_link_to_Contact_created_Record() {
        AccountTestDataFactory accountFactory = new AccountTestDataFactory();
        Account a = (Account)accountFactory.initializeRecord();
        a.uB_Office__c = 'Americas';
        a = (Account)accountFactory.createRecord(a);
        String record = '[{"LastName": "Test Contact 1", "Email": "testuser@example.com", "e_NDA__c": "true", "AccountId": "'+a.Id+'"}]';
        return createBulkRecordsfromJson(record);
    }
}