force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <inlineHelpText>On creation, if empty copied from the master Opportunity after Save. Edit as needed.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product_Series__c.field-meta.xml
<CustomField>
    <fullName>Product_Series__c</fullName>
    <formula>TEXT(Product__r.Product_Series__c)</formula>
    <label>Product Series</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Status_Factor__c.field-meta.xml
<CustomField>
    <fullName>Status_Factor__c</fullName>
    <formula>case( text(Status__c),
&quot;Evaluation&quot;, 1,
&quot;Won&quot;, 1,
0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Factor</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <formula>TEXT( Opportunity__r.Account.uB_Office__c )</formula>
    <label>uB Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <description>Annual run rate of product. If</description>
    <inlineHelpText>Annual run rate. For single shot opportunities, use total quantity.
If Opportunity is converted from Lead, this is copied from Lead.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Product_Series__c.field-meta.xml
<CustomField>
    <fullName>Product_Series__c</fullName>
    <description>Product Series to define Formfactor and Platform</description>
    <inlineHelpText>Product Series to define Formfactor and Platform</inlineHelpText>
    <label>Product Series</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Center__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACC</fullName>
            </value>
            <value>
                <fullName>ACCESS-CTRL</fullName>
            </value>
            <value>
                <fullName>ALEX-N3</fullName>
            </value>
            <value>
                <fullName>ALEX-R5</fullName>
            </value>
            <value>
                <fullName>AMY-5</fullName>
            </value>
            <value>
                <fullName>AMY-6</fullName>
            </value>
            <value>
                <fullName>ANNA-B1</fullName>
            </value>
            <value>
                <fullName>ANNA-B4</fullName>
            </value>
            <value>
                <fullName>ANN-MB</fullName>
            </value>
            <value>
                <fullName>ANN-MS</fullName>
            </value>
            <value>
                <fullName>AssistNow-Offline</fullName>
            </value>
            <value>
                <fullName>AssistNow-Online</fullName>
            </value>
            <value>
                <fullName>BMD-2</fullName>
            </value>
            <value>
                <fullName>BMD-3</fullName>
            </value>
            <value>
                <fullName>BMD-40</fullName>
            </value>
            <value>
                <fullName>BMD-44</fullName>
            </value>
            <value>
                <fullName>CAM-7</fullName>
            </value>
            <value>
                <fullName>CAM-M8</fullName>
            </value>
            <value>
                <fullName>CellLocate</fullName>
            </value>
            <value>
                <fullName>CloudLocate</fullName>
            </value>
            <value>
                <fullName>Dataflow-Node</fullName>
            </value>
            <value>
                <fullName>DES-SEC</fullName>
            </value>
            <value>
                <fullName>E2E-SEC</fullName>
            </value>
            <value>
                <fullName>ELLA-W1</fullName>
            </value>
            <value>
                <fullName>EMMY-W1</fullName>
            </value>
            <value>
                <fullName>EMMY-W2</fullName>
            </value>
            <value>
                <fullName>EVA-7</fullName>
            </value>
            <value>
                <fullName>EVA-8</fullName>
            </value>
            <value>
                <fullName>EVA-M8</fullName>
            </value>
            <value>
                <fullName>FW27</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Series__c.field-meta.xml
<CustomField>
    <fullName>Product_Series__c</fullName>
    <description>Product Series to define Formfactor and Platform</description>
    <inlineHelpText>Product Series to define Formfactor and Platform</inlineHelpText>
    <label>Product Series</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Center__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALEX-N3</fullName>
            </value>
            <value>
                <fullName>ALEX-R5</fullName>
            </value>
            <value>
                <fullName>ANNA-B1</fullName>
            </value>
            <value>
                <fullName>ELLA-W1</fullName>
            </value>
            <value>
                <fullName>EMMY-W1</fullName>
            </value>
            <value>
                <fullName>EMMY-W2</fullName>
            </value>
            <value>
                <fullName>JODY-B3</fullName>
            </value>
            <value>
                <fullName>JODY-W1</fullName>
            </value>
            <value>
                <fullName>JODY-W2</fullName>
            </value>
            <value>
                <fullName>JODY-W3</fullName>
            </value>
            <value>
                <fullName>LARA-R2</fullName>
            </value>
            <value>
                <fullName>LARA-R3</fullName>
            </value>
            <value>
                <fullName>LARA-R4</fullName>
            </value>
            <value>
                <fullName>LEON-G1</fullName>
            </value>
            <value>
                <fullName>LILY-W1</fullName>
            </value>
            <value>
                <fullName>LISA-C2</fullName>
            </value>
            <value>
                <fullName>LISA-N1</fullName>
            </value>
            <value>
                <fullName>LISA-U2</fullName>
            </value>
            <value>
                <fullName>NANO-S1</fullName>
            </value>
            <value>
                <fullName>NINA-B1</fullName>
            </value>
            <value>
                <fullName>NINA-B2</fullName>
            </value>
            <value>
                <fullName>NINA-B3</fullName>
            </value>
            <value>
                <fullName>NINA-W1</fullName>
            </value>
            <value>
                <fullName>MPCI-L1</fullName>
            </value>
            <value>
                <fullName>MPCI-L2</fullName>
            </value>
            <value>
                <fullName>MPCI-L4</fullName>
            </value>
            <value>
                <fullName>N7-MAT</fullName>
            </value>
            <value>
                <fullName>OBS</fullName>
            </value>
            <value>
                <fullName>ODIN-W1</fullName>
            </value>
            <value>
                <fullName>ODIN-W2</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/productTriggerHelperTest.cls
@isTest(seealldata=false)
public with sharing class productTriggerHelperTest {
/*
2016.04.07 khir: Added Description of new Opportunity creation for update of updateStatusOnOppProduct.apxt
2016.04.07 khir: Added Account creation to solve the error for Flow "EMEA_Sales_Stage_8" (made by Process Builder)
YYYY.MM.DD skyvva: Commented test lines (see below)
2018.03.27 khir: Commented unused items (prodForRanked6, oppProductRanked6)
*/
    
    static testMethod void productTriggerHelperTest() {
        
        Map<Id, Opp_Product__c> oppProducts = new Map<Id, Opp_Product__c>();

        // 2016.04.07 khir: Added Account creation to solve the error for Flow "EMEA_Sales_Stage_8" (made by Process Builder)
        Account acc = new Account(Name='Test Acc',uB_Office__c='Corporate');
        insert acc;
        
        // 2017.11.27 khir: Added Product creation to solve the error for Flow
        Product2 prodForRanked1 = new Product2(Name='testProd1', Type_No__c='testTypeNum1', Product_Series__c='Legacy');
        insert prodForRanked1;
        Product2 prodForRanked2 = new Product2(Name='testProd2', Type_No__c='testTypeNum2', Product_Series__c='Legacy');
        //insert prodForRanked2; saaz
        Product2 prodForRanked3 = new Product2(Name='testProd3', Type_No__c='testTypeNum3', Product_Series__c='Legacy');
        //insert prodForRanked3; saaz
/*
        Product2 prodForRanked4 = new Product2(Name='testProd4', Type_No__c='testTypeNum4', Product_Series__c='Legacy');
        insert prodForRanked4;
        Product2 prodForRanked5 = new Product2(Name='testProd5', Type_No__c='testTypeNum5', Product_Series__c='Legacy');
        insert prodForRanked5;
*/
//        Product2 prodForRanked6 = new Product2(Name='testProd6', Type_No__c='testTypeNum6', Product_Series__c='Legacy');
//        insert prodForRanked6;
        
        
        // 2016.04.07 khir: Added Description of new Opportunity creation for update of updateStatusOnOppProduct.apxt
        Opportunity opp = new Opportunity(Name='TestOpp', StageName='3 Calling on',CloseDate=Date.today(),Description='test description',AccountId=acc.Id);
        insert opp;

        Opp_Product__c oppProductRanked1 = new Opp_Product__c(Opportunity__c=opp.Id);
        // Revenue = Annual_Quantity__c * Unit_Price__c * Status_Factor__c
        oppProductRanked1.Annual_Quantity__c = 10000;
        oppProductRanked1.Unit_Price__c = 10;
        oppProductRanked1.Status__c = 'Won'; // This will set Status_Factor__c for Revenue_c formula.
        oppProductRanked1.Loss_Reason__c = 'Price'; // khir: Added as it's required by Validation Rule.
        oppProductRanked1.Product__c = prodForRanked1.Id;
        //insert oppProductRanked1; saaz

        Opp_Product__c oppProductRanked2 = new Opp_Product__c(Opportunity__c=opp.Id);
        // Revenue = Annual_Quantity__c * Unit_Price__c * Status_Factor__c
        oppProductRanked2.Annual_Quantity__c = 8000;
        oppProductRanked2.Unit_Price__c = 10;
        oppProductRanked2.Status__c = 'Won'; // This will set Status_Factor__c for Revenue_c formula.
        oppProductRanked2.Loss_Reason__c = 'Price'; // khir: Added as it's required by Validation Rule.
        oppProductRanked2.Product__c = prodForRanked2.Id;
        //insert oppProductRanked2;  saaz

        Opp_Product__c oppProductRanked3 = new Opp_Product__c(Opportunity__c=opp.Id);
        // Revenue = Annual_Quantity__c * Unit_Price__c * Status_Factor__c
        oppProductRanked3.Annual_Quantity__c = 6000;
        oppProductRanked3.Unit_Price__c = 10;
        oppProductRanked3.Status__c = 'Won'; // This will set Status_Factor__c for Revenue_c formula.
        oppProductRanked3.Loss_Reason__c = 'Price'; // khir: Added as it's required by Validation Rule.
        oppProductRanked3.Product__c = prodForRanked3.Id;
       //-- insert oppProductRanked3; saaz
        /*
        delete prodForRanked3;
        Product2[] p = [Select Id, IsDeleted from Product2 where Id=:prodForRanked3.Id];
        
        system.assertEquals(true, p.isEmpty());
*/
        
/*
        Opp_Product__c oppProductRanked4 = new Opp_Product__c(Opportunity__c=opp.Id);
        // Revenue = Annual_Quantity__c * Unit_Price__c * Status_Factor__c
        oppProductRanked4.Annual_Quantity__c = 4000;
        oppProductRanked4.Unit_Price__c = 10;
        oppProductRanked4.Status__c = 'Won'; // This will set Status_Factor__c for Revenue_c formula.
        oppProductRanked4.Loss_Reason__c = 'Price'; // khir: Added as it's required by Validation Rule.
        oppProductRanked4.Product__c = prodForRanked4.Id;
        insert oppProductRanked4;

        Opp_Product__c oppProductRanked5 = new Opp_Product__c(Opportunity__c=opp.Id);
        // Revenue = Annual_Quantity__c * Unit_Price__c * Status_Factor__c
        oppProductRanked5.Annual_Quantity__c = 2000;
        oppProductRanked5.Unit_Price__c = 10;
        oppProductRanked5.Status__c = 'Won'; // This will set Status_Factor__c for Revenue_c formula.
        oppProductRanked5.Loss_Reason__c = 'Price'; // khir: Added as it's required by Validation Rule.
        oppProductRanked5.Product__c = prodForRanked5.Id;
        insert oppProductRanked5;
*/
        
        
//        Opp_Product__c oppProductRanked6 = new Opp_Product__c(Opportunity__c=opp.Id);
//        // Revenue = Annual_Quantity__c * Unit_Price__c * Status_Factor__c
//        oppProductRanked6.Annual_Quantity__c = 1000;
//        oppProductRanked6.Unit_Price__c = 10;
//        oppProductRanked6.Status__c = 'Won'; // This will set Status_Factor__c for Revenue_c formula.
//        oppProductRanked6.Loss_Reason__c = 'Price'; // khir: Added as it's required by Validation Rule.
//        oppProductRanked6.Product__c = prodForRanked6.Id;
//        insert oppProductRanked6;


        //skyvva
        //Comment to avoid error from validtion rule https://eu1.salesforce.com/00ND0000005bHJB?setupid=CustomObjects
        /*
        // Relate Products to Opp Product record.
        oppProductRanked1.Product__c = prodForRanked1.Id;
        update oppProductRanked1;
        oppProductRanked2.Product__c = prodForRanked2.Id;
        update oppProductRanked2;
        oppProductRanked3.Product__c = prodForRanked3.Id;
        update oppProductRanked3;
        oppProductRanked4.Product__c = prodForRanked4.Id;
        update oppProductRanked4;
        oppProductRanked5.Product__c = prodForRanked5.Id;
        update oppProductRanked5;
        oppProductRanked6.Product__c = prodForRanked6.Id;
        update oppProductRanked6;

        Opportunity oppReturned = [SELECT Id, Product_1__c, Product_2__c, Product_3__c, Product_4__c, Product_5__c
                                                    FROM Opportunity
                                                    WHERE Id =:opp.Id LIMIT 1];
        system.assertEquals(prodForRanked1.Id, oppReturned.Product_1__c);
        system.assertEquals(prodForRanked2.Id, oppReturned.Product_2__c);
        system.assertEquals(prodForRanked3.Id, oppReturned.Product_3__c);
        system.assertEquals(prodForRanked4.Id, oppReturned.Product_4__c);
        system.assertEquals(prodForRanked5.Id, oppReturned.Product_5__c);

        prodForRanked1.COGS_1__c = 12;
        update prodForRanked1;
        prodForRanked2.COGS_1__c = 8;
        update prodForRanked2;

        oppReturned = [SELECT Id, Product_1__c, Product_2__c, Product_3__c, Product_4__c, Product_5__c
                                                    FROM Opportunity
                                                    WHERE Id =:opp.Id LIMIT 1];

        system.debug('xxxxx ' + prodForRanked1.Id + '/' + prodForRanked2.Id + '/' + prodForRanked3.Id + '/' + prodForRanked4.Id + '/' + prodForRanked5.Id);
        system.debug('yyyyy ' + oppReturned.Product_1__c + '/' + oppReturned.Product_2__c + '/' + oppReturned.Product_3__c + '/' + oppReturned.Product_4__c + '/' + oppReturned.Product_5__c);
        
        //system.assertEquals(oppReturned.Product_1__c, prodForRanked3.Id);
        //system.assertEquals(oppReturned.Product_2__c, prodForRanked4.Id);
        //system.assertEquals(oppReturned.Product_3__c, prodForRanked5.Id);
        //system.assertEquals(oppReturned.Product_4__c, prodForRanked2.Id);
        //system.assertEquals(oppReturned.Product_5__c, prodForRanked6.Id);

        delete prodforRanked5;

        oppReturned = [SELECT Id, Product_1__c, Product_2__c, Product_3__c, Product_4__c, Product_5__c
                                                    FROM Opportunity
                                                    WHERE Id =:opp.Id LIMIT 1];

        system.debug('xxxxx ' + prodForRanked1.Id + '/' + prodForRanked2.Id + '/' + prodForRanked3.Id + '/' + prodForRanked4.Id + '/' + prodForRanked5.Id);
        system.debug('yyyyy ' + oppReturned.Product_1__c + '/' + oppReturned.Product_2__c + '/' + oppReturned.Product_3__c + '/' + oppReturned.Product_4__c + '/' + oppReturned.Product_5__c);
        
        //system.assertEquals(oppReturned.Product_1__c, prodForRanked3.Id);
        //system.assertEquals(oppReturned.Product_2__c, prodForRanked4.Id);
        //system.assertEquals(oppReturned.Product_3__c, null);
        //system.assertEquals(oppReturned.Product_4__c, prodForRanked2.Id);
        //system.assertEquals(oppReturned.Product_5__c, prodForRanked6.Id);
        */
        
    }
}