force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End Customer Account)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quotation_Account__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is opportunity, than it is blank.</description>
    <label>Quotation Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_quotation__c.field-meta.xml
<CustomField>
    <fullName>Type_of_quotation__c</fullName>
    <description>Is the quotation budgetary or binding?</description>
    <inlineHelpText>Is the quotation budgetary or binding?</inlineHelpText>
    <label>Type of Quotation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quotation</fullName>
                <default>true</default>
                <label>Quotation</label>
            </value>
            <value>
                <fullName>Budgetary Quotation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Quotation.recordType-meta.xml
<RecordType>
    <fullName>Quotation</fullName>
    <active>true</active>
    <businessProcess>Quotation</businessProcess>
    <label>Quotation</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/IPR_Coverage__c.field-meta.xml
<CustomField>
    <fullName>IPR_Coverage__c</fullName>
    <inlineHelpText>IPR coverage of u-blox. Only relevant for wireless products.</inlineHelpText>
    <label>IPR Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Premium coverage</fullName>
            </value>
            <value>
                <fullName>Prime coverage</fullName>
            </value>
            <value>
                <fullName>Premium except Qualcomm</fullName>
            </value>
            <value>
                <fullName>Prime except Qualcomm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Price_Level__c.field-meta.xml
<CustomField>
    <fullName>Price_Level__c</fullName>
    <description>Price level
RSP: Price = RSP
TPD: RSP &gt; Price &gt;= TPD
MSP: TPD &gt; Price &gt;= MSP
PPP: MSP &gt; Price</description>
    <inlineHelpText>Price level
RSP: Price = RSP
TPD: RSP &gt; Price &gt;= TPD
MSP: TPD &gt; Price &gt;= MSP
PPP: MSP &gt; Price</inlineHelpText>
    <label>Price Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RSP (Recommended Sales Price)</fullName>
            </value>
            <value>
                <fullName>TPD (Transfer Price for Distributor)</fullName>
            </value>
            <value>
                <fullName>MSP (Minimum Sales Price)</fullName>
            </value>
            <value>
                <fullName>PPP (Project Price Plan)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tashang</fullName>
            </value>
            <value>
                <fullName>u-blox</fullName>
                <default>true</default>
                <label>u-blox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OpportunityLineItemTriggerHandlerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class OpportunityLineItemTriggerHandlerTest {

    static final Product2 cellularProduct;    
    static final Account quoteAccount;
    static final Opportunity quotation;
    static final PricebookEntry stdPriceBookEntry;
    static final OpportunityLineItem[] quoteProducts = new OpportunityLineItem[]{};
            
    static{        
        quoteAccount = new Account(
            Name = 'KAE Electronics',
            uB_Office__c = 'EMEA'
        );
        database.insert(quoteAccount);

        cellularProduct = new Product2(
            Name='TOBY-L201 quote',
            BusinessUnit__c = 'u-blox', 
            Type_No__c='TOBY-L201-02S-01-q', 
            Product_Center__C='Cellular'
        ); 
        database.insert(cellularProduct);
        
        stdPriceBookEntry = new PricebookEntry(
            Pricebook2Id = test.getStandardPricebookId(),
            Product2Id = cellularProduct.Id,
            UnitPrice = 0.00,
            IsActive = true
        );
        database.insert(stdPriceBookEntry);

        quotation = new Opportunity(
            Name='KAE Electronics', 
            StageName='3 Calling on',
            CloseDate = Date.today().addDays(7),            
            End_Customer_Account__c = quoteAccount.Id,
            Quotation_Account__c = quoteAccount.Id,
            AccountId = quoteAccount.Id,
            Type_of_quotation__c = 'Quotation',
            RecordTypeId = Schema.sObjectType.Opportunity.getRecordTypeInfosByName().get('Quotation').getRecordTypeId()
        );
        database.insert(quotation);
        
        system.assert(cellularProduct.Id != null);
        system.assert(quotation.Id != null);
        
        quoteProducts.add(new OpportunityLineItem(
            OpportunityId = quotation.Id,
            Product2Id = cellularProduct.Id,
            PricebookEntryId = stdPriceBookEntry.Id,
            Quantity = 10,
            UnitPrice = 14,
            Price_Level__c = 'RSP (Recommended Sales Price)',
            IPR_Coverage__c = 'Prime coverage'
        ));
        quoteProducts.add(new OpportunityLineItem(
            OpportunityId = quotation.Id,
            Product2Id = cellularProduct.Id,
            PricebookEntryId = stdPriceBookEntry.Id,            
            Quantity = 10,
            UnitPrice = 15,
            Price_Level__c = 'RSP (Recommended Sales Price)',
            IPR_Coverage__c = 'Premium coverage'
        ));
        database.insert(quoteProducts);
    }
       
    static testMethod void codeCoverageForReadonlyMethods() {
        // TO DO: implement unit test
        OpportunityLineItemTriggerHandler handler = new OpportunityLineItemTriggerHandler();        
        handler.prepareBefore();
        handler.prepareAfter();
        handler.beforeInsert();
        handler.beforeUpdate();
        handler.afterUpdate();
        handler.beforeDelete();
        handler.afterDelete();
    }
}