force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Has_PDF_Attachments__c.field-meta.xml
<CustomField>
    <fullName>Has_PDF_Attachments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated with Apex Trigger &quot;AttachmentTrigger&quot;</description>
    <inlineHelpText>Checked if there is a PDF Attachment. Automatically updated.</inlineHelpText>
    <label>Has PDF Attachments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/AttachmentTriggerTest.cls
/*
 * Title: AttachmentTriggerTest
 * Description: Test class for AttachmentTrigger
 * Author:  ldra
 * Created:  2018-12-06
 */

@isTest
public class AttachmentTriggerTest {

    @isTest 
    static void opportunityOnInsert() {

        Account acc = new Account(Name='Test Acc',uB_Office__c='Corporate');
        insert acc;

        Opportunity opp = new Opportunity(Name='TestOpp', StageName='3 Calling on',CloseDate=Date.today(),Description='test description',AccountId=acc.Id);
        insert opp;
        
        Attachment att=new Attachment();  
        att.ParentId=opp.Id;
        att.Name='Unit Test Attachment';
        att.Body=Blob.valueOf('Unit Test Attachment Body');
        att.ContentType='application/pdf';
        insert att;
        
        Opportunity o = [SELECT Id, Has_PDF_Attachments__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(true, o.Has_PDF_Attachments__c);  

    }

    @isTest 
    static void opportunityOnDelete() {

        Account acc = new Account(Name='Test Acc',uB_Office__c='Corporate');
        insert acc;

        Opportunity opp = new Opportunity(Name='TestOpp', Has_PDF_Attachments__c = true, StageName='3 Calling on',CloseDate=Date.today(),Description='test description',AccountId=acc.Id);
        insert opp;
        
        Attachment att=new Attachment();  
        att.ParentId=opp.Id;
        att.Name='Unit Test Attachment';
        att.Body=Blob.valueOf('Unit Test Attachment Body');
        att.ContentType='application/pdf';
        insert att;
        
        delete att;

        Opportunity o = [SELECT Id, Has_PDF_Attachments__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(false, o.Has_PDF_Attachments__c);  

    }
    
}