force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End Customer Account)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quotation_Account__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is opportunity, than it is blank.</description>
    <label>Quotation Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_quotation__c.field-meta.xml
<CustomField>
    <fullName>Type_of_quotation__c</fullName>
    <description>Is the quotation budgetary or binding?</description>
    <inlineHelpText>Is the quotation budgetary or binding?</inlineHelpText>
    <label>Type of Quotation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quotation</fullName>
                <default>true</default>
                <label>Quotation</label>
            </value>
            <value>
                <fullName>Budgetary Quotation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Quotation.recordType-meta.xml
<RecordType>
    <fullName>Quotation</fullName>
    <active>true</active>
    <businessProcess>Quotation</businessProcess>
    <label>Quotation</label>
</RecordType>

force-app/main/default/objects/Product2/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tashang</fullName>
            </value>
            <value>
                <fullName>u-blox</fullName>
                <default>true</default>
                <label>u-blox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tashang</fullName>
            </value>
            <value>
                <fullName>u-blox</fullName>
                <default>true</default>
                <label>u-blox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Tashang</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quote_Multi_Price_Breaks__c/Quote_Multi_Price_Breaks__c.object-meta.xml
<CustomObject>
    <description>This object is created to add multiple price breaks in quotation for global distributor partners.</description>
    <label>Price Breaks</label>
    <nameField>
        <displayFormat>PB-{0000000}</displayFormat>
        <label>Price breaks Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Breaks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Multi_Price_Breaks__c/fields/Price_Sample_100__c.field-meta.xml
<CustomField>
    <fullName>Price_Sample_100__c</fullName>
    <label>Samples &lt; 100</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Multi_Price_Breaks__c/fields/Price_Sample_100k__c.field-meta.xml
<CustomField>
    <fullName>Price_Sample_100k__c</fullName>
    <label>100K+</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Multi_Price_Breaks__c/fields/Price_Sample_1k__c.field-meta.xml
<CustomField>
    <fullName>Price_Sample_1k__c</fullName>
    <label>1K+</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Multi_Price_Breaks__c/fields/Price_Sample_4k__c.field-meta.xml
<CustomField>
    <fullName>Price_Sample_4k__c</fullName>
    <label>4K+</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Multi_Price_Breaks__c/fields/Price_Sample_50k__c.field-meta.xml
<CustomField>
    <fullName>Price_Sample_50k__c</fullName>
    <label>50K+</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Multi_Price_Breaks__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Price_breaks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Multi_Price_Breaks__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Price Breaks (Automotive Products)</relationshipLabel>
    <relationshipName>Price_breaks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Multi_Price_Breaks__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Price Breaks (Automotive Products)</relationshipLabel>
    <relationshipName>Price_Breaks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Multi_Price_Breaks__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/quoteLineItemPriceBreaksCtrlTest.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/
@isTest
public class quoteLineItemPriceBreaksCtrlTest {
    static final Product2 cellularProduct;    
    static final Account quoteAccount;
    static final opportunity opportunity;
    static final Quote quotation;
    static final list<Quote> quoteList;
    static final PricebookEntry stdPriceBookEntry;
    static final QuoteLineItem[] quoteProducts = new QuoteLineItem[]{};
        
        static{        
            quoteAccount = new Account(
                Name = 'KAE Electronics',
                uB_Office__c = 'EMEA'
            );
            database.insert(quoteAccount);
            
            cellularProduct = new Product2(
                Name='TOBY-L201 quote',
                BusinessUnit__c = 'u-blox', 
                Type_No__c='TOBY-L201-02S-01-q', 
                Product_Center__C='Cellular'
            ); 
            database.insert(cellularProduct);
            
            stdPriceBookEntry = new PricebookEntry(
                Pricebook2Id = test.getStandardPricebookId(),
                Product2Id = cellularProduct.Id,
                UnitPrice = 0.00,
                IsActive = true
            );
            database.insert(stdPriceBookEntry);
            
            Opportunity = new Opportunity(
                Name='KAE Electronics', 
                StageName='3 Calling on',
                CloseDate = Date.today().addDays(7),            
                End_Customer_Account__c = quoteAccount.Id,
                Quotation_Account__c = quoteAccount.Id,
                AccountId = quoteAccount.Id,
                // Type_of_quotation__c = 'Quotation',
                RecordTypeId = Schema.sObjectType.Opportunity.getRecordTypeInfosByName().get('Opportunity').getRecordTypeId()
            );
            database.insert(Opportunity);
            
            quotation = new Quote(
                Name='KAE Electronics',
                opportunityId =Opportunity.Id,
                pricebook2Id =test.getStandardPricebookId(),
                //CloseDate = Date.today().addDays(7),            
                //End_Customer_Account__c = AccountId,
                Quotation_Account__c = quoteAccount.Id
                //AccountId = quoteAccount.Id
                
            );
            quoteList= new list<Quote>();
            quoteList.add(quotation);
            database.insert(quoteList);
            
            system.assert(cellularProduct.Id != null);
            system.assert(quoteList[0].Id != null);
            
            quoteProducts.add(new QuoteLineItem(
                QuoteId = quoteList[0].Id,
                Product2Id = cellularProduct.Id,
                PricebookEntryId = stdPriceBookEntry.Id,
                Quantity = 10,
                UnitPrice = 14,
                Price_Level__c = 'RSP (Recommended Sales Price)',
                IPR_Coverage__c = 'Prime coverage'
            ));
            quoteProducts.add(new QuoteLineItem(
                //  QuoteId = quotation.Id,
                quoteId = quoteList[0].Id,
                Product2Id = cellularProduct.Id,
                PricebookEntryId = stdPriceBookEntry.Id,            
                Quantity = 10,
                UnitPrice = 15,
                Price_Level__c = 'RSP (Recommended Sales Price)',
                IPR_Coverage__c = 'Premium coverage'
            ));
            database.insert(quoteProducts);
            
        }
    
    static testMethod void codeCoverageMultiPriceBreakWithExistingItem() {
        // TO DO: implement unit test
        ApexPages.currentPage().getParameters().put('id',quoteList[0].Id);
        
        ApexPages.StandardSetController sController = new ApexPages.StandardSetController(quoteList);        
        quoteLineItemPriceBreaksCtrl ctrl = new quoteLineItemPriceBreaksCtrl(sController);        
        ctrl.quoteId = quoteList[0].Id;
        Quote_Multi_Price_Breaks__c priceBreak = new Quote_Multi_Price_Breaks__c(
            Quote__c = quoteList[0].Id,
            Quote_Line_Item__c = quoteProducts[1].Id,
            Product__c = quoteProducts[1].Product2Id,
            Year__c = '2023',
            Price_Sample_1k__c = 4.5,
            Price_Sample_100__c = 4.7,
            Price_Sample_4k__c = 5,
            Price_Sample_50k__c = 5.5,
            Price_Sample_100k__c = 6
        ); 
        quoteLineItemPriceBreaksCtrl.priceBreaksWrapper wrapper = new quoteLineItemPriceBreaksCtrl.priceBreaksWrapper();
        wrapper.productName = quoteProducts[1].Product2.Name;
        wrapper.orderingCode = quoteProducts[1].Product2.ProductCode;
        wrapper.priceBreak = priceBreak;
        list<quoteLineItemPriceBreaksCtrl.priceBreaksWrapper> wrapperList = new list<quoteLineItemPriceBreaksCtrl.priceBreaksWrapper>();
        wrapperList.add(wrapper);
        ctrl.multiPriceBreaks.put(quoteProducts[1].Id,wrapperList);  
        ctrl.saveAll();      
    }

    static testMethod void codeCoverageMultiPriceBreak() {
        // TO DO: implement unit test
        ApexPages.currentPage().getParameters().put('id',quoteList[0].Id);
        
        ApexPages.StandardSetController sController = new ApexPages.StandardSetController(quoteList);        
        quoteLineItemPriceBreaksCtrl ctrl = new quoteLineItemPriceBreaksCtrl(sController);
        ctrl.showQuoteLookup = true;
        ctrl.quoteLookupId = quoteProducts[0];
        ctrl.quoteId = quoteList[0].Id;
        ctrl.addPriceBreaksFromExistingQuote();
        ctrl.saveAll();      
    }
}