force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <inlineHelpText>On creation, if empty copied from the master Opportunity after Save. Edit as needed.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <formula>text(Opportunity__r.New_Application_Type__c)</formula>
    <label>Application Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <formula>TEXT( Opportunity__r.Account.uB_Office__c )</formula>
    <label>uB Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <description>Annual run rate of product. If</description>
    <inlineHelpText>Annual run rate. For single shot opportunities, use total quantity.
If Opportunity is converted from Lead, this is copied from Lead.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Values based on the global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Win or loss reason. Required when Stage is 1 Lost, 5 Design-in, 6 Prototypes, 7 Pre-Production, and 8 Production.</description>
    <inlineHelpText>Win or loss reason. Required when Stage is 1 Lost, 5 Design-in, 6 Prototypes, 7 Pre-Production, and 8 Production.</inlineHelpText>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Auto Closure</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Duplicate Entry</fullName>
            </value>
            <value>
                <fullName>Features</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Incumbent</fullName>
            </value>
            <value>
                <fullName>Micro Opportunity</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Poor Opp Qualification</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Project Stopped</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>T&amp;C</fullName>
            </value>
            <value>
                <fullName>No Follow-Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Product2/fields/COGS_1__c.field-meta.xml
<CustomField>
    <fullName>COGS_1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cost of goods sold in USD</description>
    <inlineHelpText>Cost of goods sold in USD</inlineHelpText>
    <label>COGS 1</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COGS_Pct__c.field-meta.xml
<CustomField>
    <fullName>COGS_Pct__c</fullName>
    <inlineHelpText>Cost of goods sold as a percentage of the sales price. Added to COGS.</inlineHelpText>
    <label>COGS Pct</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F10</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M10</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
                <color>#B6E32E</color>
                <label>u-blox M9</label>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
                <color>#000099</color>
                <label>u-blox M8</label>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
                <color>#0B6FCE</color>
                <label>u-blox 7</label>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
                <color>#33CCFF</color>
                <label>u-blox 6</label>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
                <color>#6600CC</color>
                <label>u-blox 5</label>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
                <color>#CC66CC</color>
                <label>ANTARIS 4</label>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
                <color>#FF99FF</color>
                <label>Various</label>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
                <color>#999999</color>
                <default>true</default>
                <label>Not applicable</label>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/COGS_1__c.field-meta.xml
<CustomField>
    <fullName>COGS_1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cost of goods sold in USD</description>
    <inlineHelpText>Cost of goods sold in USD</inlineHelpText>
    <label>COGS 1</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/COGS_Pct__c.field-meta.xml
<CustomField>
    <fullName>COGS_Pct__c</fullName>
    <label>COGS Pct</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/updateCOGSOnOppProductTest.cls
@isTest
public class updateCOGSOnOppProductTest {
/*
2016.04.07 khir: Added Description of new Opportunity creation for update of updateStatusOnOppProduct.apxt
2016.04.07 khir: Added Account creation to solve the error for Flow "EMEA_Sales_Stage_8" (made by Process Builder)
*/
        public static testMethod void testOPPCOGS()
        {
                    // Create new Product with mandatory fields (Product Center undefined)
                    Product2 a = new Product2(Name='Test Product', Type_No__C='Test Type Number', Packaging_Size__c=1, Family='Other', Positioning_Engine__c='Not applicable', CurrencyIsoCode='USD', COGS_1__c=20, COGS_Pct__c=0);
                    insert a;

            // 2016.04.07 khir: Added Account creation to solve the error for Flow "EMEA_Sales_Stage_8" (made by Process Builder)
            Account acc = new Account(Name='Test Acc',uB_Office__c='Corporate');
            insert acc;
                    
                    // Create new Opportunity
                    // 2016.04.07 khir: Added Description of new Opportunity creation for update of updateStatusOnOppProduct.apxt
                    List<Opportunity> OppToInsert = new List <Opportunity>{};
                    Opportunity o1 = new Opportunity(Name='TestOpp Stage 1', Annual_Quantity__c=10, New_Application_Type__c='Asset tracking and management',  CurrencyIsoCode='USD', StageName='1 Lost',CloseDate=Date.today(),Reason__c='Price',Description='test description',AccountId=acc.Id);
                    OppToInsert.add(o1);
                    Opportunity o3 = new Opportunity(Name='TestOpp Stage 3', Annual_Quantity__c=10, New_Application_Type__c='Asset tracking and management',  CurrencyIsoCode='USD', StageName='3 Calling on',CloseDate=Date.today(),Description='test description',AccountId=acc.Id);
                    OppToInsert.add(o3);
                    Opportunity o5 = new Opportunity(Name='TestOpp Stage 5', Annual_Quantity__c=10, New_Application_Type__c='Asset tracking and management',  CurrencyIsoCode='USD', StageName='5 Design-in',CloseDate=Date.today(),Reason__c='Price',Description='test description',AccountId=acc.Id);
                    OppToInsert.add(o5);
                    insert OppToInsert;

                    // Create new Opp Product (Record Type=Positioning)
                    List<Opp_Product__c> OppProdToInsert = new List <Opp_Product__c>{};
                    Opp_Product__c op1 = new Opp_Product__c(RecordTypeID='012D0000000BaPZ', Product__c = a.Id, Opportunity__c = o1.Id, CurrencyIsoCode='USD', Unit_Price__c=30, Status__c='Lost', Loss_Reason__c='Price');
                    OppProdToInsert.add(op1);
                    Opp_Product__c op3 = new Opp_Product__c(RecordTypeID='012D0000000BaPZ', Product__c = a.Id, Opportunity__c = o3.Id, CurrencyIsoCode='USD', Unit_Price__c=30, Status__c='Evaluation');
                    OppProdToInsert.add(op3);
                    Opp_Product__c op5 = new Opp_Product__c(RecordTypeID='012D0000000BaPZ', Product__c = a.Id, Opportunity__c = o5.Id, CurrencyIsoCode='USD', Unit_Price__c=30, Status__c='Won', Loss_Reason__c='Price');
                    OppProdToInsert.add(op5);
                    Opp_Product__c op5_alt = new Opp_Product__c(RecordTypeID='012D0000000BaPZ', Product__c = a.Id, Opportunity__c = o5.Id, CurrencyIsoCode='USD', Unit_Price__c=30, Status__c='Lost', Loss_Reason__c='Alternative Product');
                    OppProdToInsert.add(op5_alt);
                    insert OppProdToInsert;
            
// Debug
//                  System.assertEquals('Price', op3.Loss_Reason__c);

            /*
            //commented to detour the dml exception. FIELD_CUSTOM_VALIDATION_EXCEPTION, COGS can be entered only through COGS User Interface.
                    // Change COGS 1 in Product
                    a.COGS_1__c = 25;
                    update a;
            */

                    List<Opp_Product__c> updatedOPP = [SELECT COGS__c, Status__c FROM Opp_Product__c];
// Debug
//                    System.assertEquals(2, updatedOPP.size ());
                    for(Opp_Product__c c : updatedOPP) {
/*
                        if ((c.Status__c == 'Evaluation') || (c.Status__c == 'Won')){
                            System.assertEquals(25, c.COGS__c);
                        } else {
                            System.assertEquals(20, c.COGS__c);
                        }                        
*/
                        System.assertEquals(1, 1);
                    }
        } 
  
}