force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <description>Annual run rate of product. If</description>
    <inlineHelpText>Annual run rate. For single shot opportunities, use total quantity.
If Opportunity is converted from Lead, this is copied from Lead.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approval_Status_Flag__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status_Flag__c</fullName>
    <label>Approval Status Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_design_house__c.field-meta.xml
<CustomField>
    <fullName>Area_design_house__c</fullName>
    <inlineHelpText>Area in which the design is made.</inlineHelpText>
    <label>uB Office Design House</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_Design_Win__c.field-meta.xml
<CustomField>
    <fullName>Area_Design_Win__c</fullName>
    <inlineHelpText>Area with the highest contribution to the design win. Field used for contribution split.</inlineHelpText>
    <label>uB Office Design-Win</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_manufacturing__c.field-meta.xml
<CustomField>
    <fullName>Area_manufacturing__c</fullName>
    <inlineHelpText>Select one or several areas, in which the product is manufactured.</inlineHelpText>
    <label>uB Office Manufacturing</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_opportunity_owner__c.field-meta.xml
<CustomField>
    <fullName>Area_opportunity_owner__c</fullName>
    <inlineHelpText>Area in which the opportunity owner resides</inlineHelpText>
    <label>uB Office Opp Owner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Values based on the global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is quotation, than it is blank.</description>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Remark_Contribution__c.field-meta.xml
<CustomField>
    <fullName>Remark_Contribution__c</fullName>
    <inlineHelpText>Comment for contribution split</inlineHelpText>
    <label>Remark Contribution</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_mail_with_info__c.field-meta.xml
<CustomField>
    <fullName>Send_mail_with_info__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When you check the box, a mail with the main information will be sent to the account owner. This can be forwarded to a customer or distributor for an update.</inlineHelpText>
    <label>Send mail with opportunity information</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Team_members__c.field-meta.xml
<CustomField>
    <fullName>Team_members__c</fullName>
    <description>Sales persons involved in the opportunity</description>
    <inlineHelpText>Select the sales persons involved in the opportunity. If they are in a different area, grant access by adding them to the account team.</inlineHelpText>
    <label>Team Members</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adam Andres</fullName>
            </value>
            <value>
                <fullName>Adam Strout</fullName>
            </value>
            <value>
                <fullName>Adrian Tan</fullName>
            </value>
            <value>
                <fullName>Amitesh Bajaj</fullName>
            </value>
            <value>
                <fullName>Anthony Protopsaltis</fullName>
            </value>
            <value>
                <fullName>Armin Böshenz</fullName>
            </value>
            <value>
                <fullName>Brad Sherrard</fullName>
            </value>
            <value>
                <fullName>Bruce Wu</fullName>
            </value>
            <value>
                <fullName>Carine Loo</fullName>
            </value>
            <value>
                <fullName>Carlos Dias</fullName>
            </value>
            <value>
                <fullName>Daniel Jungo</fullName>
            </value>
            <value>
                <fullName>David Sel</fullName>
            </value>
            <value>
                <fullName>Derek Wang</fullName>
            </value>
            <value>
                <fullName>Dylan Huang</fullName>
            </value>
            <value>
                <fullName>Ellen Huang</fullName>
            </value>
            <value>
                <fullName>Federico Dal Ferro</fullName>
            </value>
            <value>
                <fullName>Frederic Duhem</fullName>
            </value>
            <value>
                <fullName>Fredrik Borgstrom</fullName>
            </value>
            <value>
                <fullName>Henry You</fullName>
            </value>
            <value>
                <fullName>Hiroshi Yoshimura</fullName>
            </value>
            <value>
                <fullName>Jan Reisen</fullName>
            </value>
            <value>
                <fullName>Jason Meilhon</fullName>
            </value>
            <value>
                <fullName>Jean-Marie Dubois</fullName>
            </value>
            <value>
                <fullName>JeeHoon Kim</fullName>
            </value>
            <value>
                <fullName>Jennifer Nkire</fullName>
            </value>
            <value>
                <fullName>Jim Neff</fullName>
            </value>
            <value>
                <fullName>Jochen Steinhauer</fullName>
            </value>
            <value>
                <fullName>John Demirali</fullName>
            </value>
            <value>
                <fullName>Krystal Li</fullName>
            </value>
            <value>
                <fullName>Leo DeRosa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/OpportunityTestDataFactory.cls
@isTest
public class OpportunityTestDataFactory extends TestDataFactory {
    public OpportunityTestDataFactory() {
        super('Opportunity');
    }

    public override sObject initializeRecord(){
        Opportunity o = new Opportunity();
        o.Name = 'Test Opportunity1';
        o.StageName = '3 Calling on';
        o.CloseDate = Date.today();
        return o;
    }

    public override sObject createRecord() {
        Opportunity o = (Opportunity)initializeRecord();
        Insert o;
        return o;
    }

    public sObject createRecord(sObject record) {
        Insert record;
        return record;
    }

    public sObject updateRecord(Opportunity record) {
        update record;
        return record;
    }

    public override List<sObject> createBulkRecords() {
        for (Integer i = 0; i < numberOfRecords; i++) {
            Opportunity cont = new Opportunity();
            cont.Name = 'Test Opportunity'+i;
            recordsList.add(cont);
        }
        Insert recordsList;
        return recordsList;
    }

    public Database.SaveResult[] Opp_embargo_countries_Record() {
        AccountTestDataFactory accFactory = new AccountTestDataFactory();
        Account a = accFactory.getAccwithBillingAddress();
        String data = '[{"Name": "Test Opportunity1", "StageName": "3 Calling on", "CloseDate": "2021-11-28", "AccountId": "'+a.id+'"}]';
        return createBulkRecordsfromJson(data);
    }

    public Database.SaveResult[] All_Opps_Record() {
        AccountTestDataFactory accFactory = new AccountTestDataFactory();
        Account a = accFactory.getAccwithBillingAddress();
        String data = '[{"Name": "Test Opportunity1", "StageName": "3 Calling on", "CloseDate": "2021-11-28", "AccountId": "'+a.id+'"}]';
        return createBulkRecordsfromJson(data);
    }

    public Database.SaveResult[] Send_Email_to_Future_Americas_Record() {
        AccountTestDataFactory accFactory = new AccountTestDataFactory();
        Account a = accFactory.getAccwithBillingAddress();
        String data = '[{"Name": "Test Opportunity1", "StageName": "3 Calling on", "CloseDate": "2021-11-28", "AccountId": "'+a.id+'", "Approval_Status_Flag__c": "Approved"}]';
        return createBulkRecordsfromJson(data);
    }

    public Database.SaveResult[] Opportunity_send_mail_with_information_Record() {
        AccountTestDataFactory accFactory = new AccountTestDataFactory();
        Account a = accFactory.getAccwithBillingAddress();
        String data = '[{"Name": "Test Opportunity1", "StageName": "3 Calling on", "CloseDate": "2021-11-28", "AccountId": "'+a.id+'", "Approval_Status_Flag__c": "Approved", "Send_mail_with_info__c": "true" }]';
        return createBulkRecordsfromJson(data);
    }
    
    public Opportunity Opp_Reminder_of_Stage_5_to_FAE_Record() {
        Opportunity o = (Opportunity)createRecord();
        AccountTestDataFactory accFactory = new AccountTestDataFactory();
        Account a = (Account)accFactory.createRecord();
        a.uB_Office__c = 'EMEA';
        a = (Account)accFactory.updateRecords(a);
        o.StageName = '5 Design-in';
        return (Opportunity)updateRecord(o);
    }
    
    public Opportunity Opp_Owner_different_from_Account_Owner_Record() {
        Opportunity o = (Opportunity)createRecord();
        AccountTestDataFactory accFactory = new AccountTestDataFactory();
        Account a = (Account)accFactory.createRecord();
        o.AccountId = a.id;
        return (Opportunity)updateRecord(o);
    }
    
    public Opportunity oppForOppProduct(){
    Opportunity OPP = (Opportunity)initializeRecord();
    
    OPP.Opportunity_Account__c = OPP.AccountId;
    Opp.AccountId = OPP.AccountId;
    OPP.Name = OPP.Name + ' - New generation';
    OPP.CurrencyIsoCode = 'EUR';
    OPP.RecordTypeId = '01220000000CqRn'; /*Record ID für Opportunity*/
    OPP.Annual_Quantity__c = 500;
    OPP.New_Application_Type__c = 'Gateways and routers';

    
    OPP.Description = 'This is test opportunity';
    
    OPP.Area_opportunity_owner__c = 'Americas';
    OPP.Area_design_house__c = 'Americas';
    OPP.Area_manufacturing__c = 'Americas';
    OPP.Area_Design_Win__c = 'EMEA';
    OPP.Remark_Contribution__c = 'I worked really hard to develop this';
    OPP.Team_members__c = 'Adrian Tan';

    insert OPP;
    return OPP;
    }
    
}