force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <formula>Product__r.Packaging_Size__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Packaging Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lead_Source_Webform__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Webform__c</fullName>
    <description>Converted from Lead</description>
    <inlineHelpText>Converted from Lead</inlineHelpText>
    <label>Lead Source Webform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source_Webform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flow_Notification_Settings__c/Flow_Notification_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings to enable/disable email notification flow for each object</description>
    <label>Flow Notification Settings</label>
</CustomObject>

force-app/main/default/objects/Lead/fields/AssistNow_Temporary_Token__c.field-meta.xml
<CustomField>
    <fullName>AssistNow_Temporary_Token__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Token to be generated automatically and populated here through the webform submission (with Apex Trigger)</description>
    <inlineHelpText>Token to be generated automatically and populated here through the webform submission (with Apex Trigger)</inlineHelpText>
    <label>AssistNow Temporary Token</label>
    <length>22</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Products_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Products_Of_Interest__c</fullName>
    <inlineHelpText>From Project Information Form (if Lead is generated through that form). Copied to Opportunity.</inlineHelpText>
    <label>Products Of Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Source_Webform__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Webform__c</fullName>
    <description>Webform from that the Lead has been generated</description>
    <inlineHelpText>Webform from that the Lead has been generated</inlineHelpText>
    <label>Lead Source Webform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source_Webform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Product2/fields/COGS_1__c.field-meta.xml
<CustomField>
    <fullName>COGS_1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cost of goods sold in USD</description>
    <inlineHelpText>Cost of goods sold in USD</inlineHelpText>
    <label>COGS 1</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COGS_Pct__c.field-meta.xml
<CustomField>
    <fullName>COGS_Pct__c</fullName>
    <inlineHelpText>Cost of goods sold as a percentage of the sales price. Added to COGS.</inlineHelpText>
    <label>COGS Pct</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F10</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M10</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
                <color>#B6E32E</color>
                <label>u-blox M9</label>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
                <color>#000099</color>
                <label>u-blox M8</label>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
                <color>#0B6FCE</color>
                <label>u-blox 7</label>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
                <color>#33CCFF</color>
                <label>u-blox 6</label>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
                <color>#6600CC</color>
                <label>u-blox 5</label>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
                <color>#CC66CC</color>
                <label>ANTARIS 4</label>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
                <color>#FF99FF</color>
                <label>Various</label>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
                <color>#999999</color>
                <default>true</default>
                <label>Not applicable</label>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LeadTestDataFactory.cls
@isTest
public class LeadTestDataFactory extends TestDataFactory {
    
    public Account addAccount(){
        
        Account acc = new Account();
        acc.Name='Test Acc';   
        insert acc;
        return acc;
    }
    public static Opportunity addOpportunity(){
        Opportunity oppObj = new Opportunity();
        oppObj.Name = 'Opportunity - M11 Scout';
        oppObj.StageName='6 Prototypes';
        oppObj.CloseDate= system.today();
        insert oppObj;
        return oppObj;        
    }
    
    public static Lead initiliazeLead(){
        Lead LeadObj = new Lead();
        LeadObj.LastName = 'test Lead';
        LeadObj.Company= 'test company';
        LeadObj.Country = 'GB';
        return LeadObj;        
    }
    
    
    public override sObject initializeRecord(){
        Contact c = new Contact();
        c.LastName = 'Test Contact1';
        return c;
    }
    public static Account initializeAccount(String Name ){
        // Insert
        Account accObj = new Account();
        accObj.Name='test';
        return accObj;
    }
    
    public static void createCustomSettings(){
        Flow_Notification_Settings__c	 setting = new Flow_Notification_Settings__c	();
        setting.Lead__c =true;
        insert setting;
    }
    
    @isTest
    public static void LeadScenariosTesting() {
        
        createCustomSettings();
        List<Lead> leadList = new List<Lead>();
        //Opportunity oppObj = addOpportunity();
        //Account tempAccount = TestUtils.createAccount();
        
        //Lead / online shop: send email alert (APAC)
        Lead leadObj = initiliazeLead();
        leadObj.LeadSource = 'u-shop order';
        leadObj.uB_Office__c = 'China';


//Lead / PCN subscription: send email alert (Americas)
        Lead leadObj2 = initiliazeLead();
        leadObj2.LeadSource = 'PCN subscription';
        leadObj2.uB_Office__c = 'Americas';
        leadObj2.Lead_Source_Webform__c='PCN Subscription Form';



//Lead: inform about web2lead action, PCN (APAC)
        Lead leadObjAPAC = initiliazeLead();
        leadObjAPAC.LeadSource = 'PCN subscription';
        leadObjAPAC.uB_Office__c = 'EMEA';
        leadObjAPAC.Lead_Source_Webform__c='PCN Subscription Form';
        
        
        //Lead: inform about web2lead action, PCN (APAC)
        Lead leadObjAmericas = initiliazeLead();
        leadObjAmericas.LeadSource = 'Web';
        leadObjAmericas.uB_Office__c = 'Americas';
        leadObjAmericas.Lead_Source_Webform__c='Service Registration Form';



 //Lead: inform about web2lead action, PCN (APAC)
        Lead leadObjAus = initiliazeLead();
        leadObjAus.LeadSource = 'Web';
        leadObjAus.uB_Office__c = 'Australia';


 //Lead / project form: send email alert (China)
        Lead leadObjChina = initiliazeLead();
        leadObjChina.LeadSource = 'Web';
        leadObjChina.uB_Office__c = 'China';
        
        
         //Lead / project form: send email alert (EMEA)
        Lead leadObjEMEA = initiliazeLead();
        leadObjEMEA.uB_Office__c = 'Corporate';
        leadObjEMEA.LeadSource = 'Project Form - Customer';
        leadObjEMEA.Lead_Source_Webform__c = 'Event registration (aloom)';
        
        
        
          //project form: send email alert (India)
        Lead leadObjIndia = initiliazeLead();
        leadObjIndia.uB_Office__c = 'India';
        leadObjIndia.LeadSource = 'Project Form - Customer';
        
        
        
       
        
          // Lead / project form: send email alert (Japan) 
        Lead leadObjJapan = initiliazeLead();
        leadObjJapan.uB_Office__c = 'Japan';
        leadObjJapan.LeadSource = 'Project Form - Customer';
        
        
        
        // Lead / project form: send email alert (Korea)
        Lead leadObjKorea = initiliazeLead();
        leadObjKorea.uB_Office__c = 'Korea';
        leadObjKorea.LeadSource = 'Project Form - Customer';
        
        
        
        
         // Lead / project form: send email alert (RoA)
        Lead leadObjRoA = initiliazeLead();
        leadObjRoA.uB_Office__c = 'Rest of APAC';
        leadObjRoA.LeadSource = 'Project Form - Customer';
        
        //starts from here
        //
        
         //Lead / project form: send email alert (Taiwan)
        Lead leadObjTaiwan = initiliazeLead();
        leadObjTaiwan.uB_Office__c = 'Taiwan';
        leadObjTaiwan.LeadSource = 'Project Form - Customer';
        
        
       /*
        
        //Lead: Auto response for webforms (AssistNow Temporary) 
        Lead leadObjAssistNow = initiliazeLead();
        leadObjAssistNow.LeadSource = 'Webform';
        leadObjAssistNow.Lead_Source_Webform__c = 'AssistNow Temporary';
        //leadObjAssistNow.AssistNow_Temporary_Token__c=true;
        */
        
        //Lead: Auto response for webforms (for new website with Drupal, AssistNow)
        Lead leadObjWebform = initiliazeLead();
        leadObjWebform.LeadSource = 'Webform';
        leadObjWebform.Lead_Source_Webform__c = 'Service Registration Form';
        
        
        
        
        //Lead: Auto response for webforms (for new website with Drupal, generic)
        Lead leadObjWebformDrupal = initiliazeLead();
        
        leadObjWebformDrupal.LeadSource = 'Project Form - Distributor';
        leadObjWebformDrupal.Lead_Source_Webform__c = 'Project Form - Distributor';
        
        //Lead: Notify gsol about new leads
        Lead leadObjgsol = initiliazeLead();
        leadObjgsol.Products_Of_Interest__c = 'IoT-Security-as-a-Service';
        leadObjgsol.LeadSource = 'Project Form - Customer';
        
        
        //Lead: send email alert to info@u-blox.com (EMEA) 
        
        Lead leadObjInfoEMEA = initiliazeLead();
        leadObjInfoEMEA.uB_Office__c = 'Corporate';
        leadObjInfoEMEA.LeadSource = 'Project Form - Customer';
        
        
        
        //Lead: Set Company and Record Types 
        
         Lead leadObjRecordType = initiliazeLead();
        
        leadObjRecordType.LeadSource = 'Webform';
        leadObjRecordType.Lead_Source_Webform__c = 'News Subscription';
        
        
        
        //Lead: ub Office as EMEACondition
        
         Lead leadObjEMEACondition = initiliazeLead();
        
        leadObjEMEACondition.uB_Office__c = 'EMEA';
        leadObjEMEACondition.Lead_Source_Webform__c = 'NB-IoT Project Form';

        
        
        
        
        
       // insert leadObj;

        
        
        
        
       
        leadList.add(leadObj);
        leadList.add(leadObj2);
        leadList.add(leadObjAPAC);
        
        leadList.add(leadObjAmericas);
        leadList.add(leadObjAus);
        leadList.add(leadObjChina);

        leadList.add(leadObjEMEA);
        
        leadList.add(leadObjIndia);
        
        leadList.add(leadObjJapan);
        leadList.add(leadObjKorea);
        
        
        
        
        leadList.add(leadObjTaiwan);
      
        leadList.add(leadObjWebform);
      leadList.add(leadObjWebformDrupal);  
        
        leadList.add(leadObjgsol);
        
        
        leadList.add(leadObjInfoEMEA);
        
        leadList.add(leadObjRecordType);
        
        
        leadList.add(leadObjEMEACondition);
        //leadList.add();
        //leadList.add();
        //leadList.add();
        //leadList.add();
        //leadList.add();
         //leadList.add(leadObjRecordType);
        
        insert leadList;
        system.debug('accList--->>>'+leadList);
    
    }
    
    public override sObject createRecord() {
        
        Account accObj = TestUtils.createAccount();
        Product2 prodObj= createProduct ('Test Prod', 'Test Prod 001');
        insert prodObj;
        
        return prodObj;
    }
    
    public static Product2 createProduct (String Name, String Type)
    {
        return new Product2(
            Name=Name,
            Type_No__C=Type,
            Packaging_Size__c=1,
            Family='Other',
            Positioning_Engine__c='Not applicable',
            CurrencyIsoCode='USD',
            COGS_1__c=20,
            COGS_Pct__c=0);
    }
    
    public override List<sObject> createBulkRecords() {
        
        for (Integer i = 0; i < numberofRecords; i++) {
            recordsList.add((Billings__c)initializeRecord());
        }
        Insert recordsList;
        return recordsList;
    }
    
}