force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product_Series__c.field-meta.xml
<CustomField>
    <fullName>Product_Series__c</fullName>
    <formula>TEXT(Product__r.Product_Series__c)</formula>
    <label>Product Series</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <formula>TEXT( Opportunity__r.Account.uB_Office__c )</formula>
    <label>uB Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Product_Series__c.field-meta.xml
<CustomField>
    <fullName>Product_Series__c</fullName>
    <description>Product Series to define Formfactor and Platform</description>
    <inlineHelpText>Product Series to define Formfactor and Platform</inlineHelpText>
    <label>Product Series</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Center__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACC</fullName>
            </value>
            <value>
                <fullName>ACCESS-CTRL</fullName>
            </value>
            <value>
                <fullName>ALEX-N3</fullName>
            </value>
            <value>
                <fullName>ALEX-R5</fullName>
            </value>
            <value>
                <fullName>AMY-5</fullName>
            </value>
            <value>
                <fullName>AMY-6</fullName>
            </value>
            <value>
                <fullName>ANNA-B1</fullName>
            </value>
            <value>
                <fullName>ANNA-B4</fullName>
            </value>
            <value>
                <fullName>ANN-MB</fullName>
            </value>
            <value>
                <fullName>ANN-MS</fullName>
            </value>
            <value>
                <fullName>AssistNow-Offline</fullName>
            </value>
            <value>
                <fullName>AssistNow-Online</fullName>
            </value>
            <value>
                <fullName>BMD-2</fullName>
            </value>
            <value>
                <fullName>BMD-3</fullName>
            </value>
            <value>
                <fullName>BMD-40</fullName>
            </value>
            <value>
                <fullName>BMD-44</fullName>
            </value>
            <value>
                <fullName>CAM-7</fullName>
            </value>
            <value>
                <fullName>CAM-M8</fullName>
            </value>
            <value>
                <fullName>CellLocate</fullName>
            </value>
            <value>
                <fullName>CloudLocate</fullName>
            </value>
            <value>
                <fullName>Dataflow-Node</fullName>
            </value>
            <value>
                <fullName>DES-SEC</fullName>
            </value>
            <value>
                <fullName>E2E-SEC</fullName>
            </value>
            <value>
                <fullName>ELLA-W1</fullName>
            </value>
            <value>
                <fullName>EMMY-W1</fullName>
            </value>
            <value>
                <fullName>EMMY-W2</fullName>
            </value>
            <value>
                <fullName>EVA-7</fullName>
            </value>
            <value>
                <fullName>EVA-8</fullName>
            </value>
            <value>
                <fullName>EVA-M8</fullName>
            </value>
            <value>
                <fullName>FW27</fullName>
            </value>
            <value>
                <fullName>VERA-P1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Series__c.field-meta.xml
<CustomField>
    <fullName>Product_Series__c</fullName>
    <description>Product Series to define Formfactor and Platform</description>
    <inlineHelpText>Product Series to define Formfactor and Platform</inlineHelpText>
    <label>Product Series</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Center__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALEX-N3</fullName>
            </value>
            <value>
                <fullName>ALEX-R5</fullName>
            </value>
            <value>
                <fullName>ANNA-B1</fullName>
            </value>
            <value>
                <fullName>ELLA-W1</fullName>
            </value>
            <value>
                <fullName>EMMY-W1</fullName>
            </value>
            <value>
                <fullName>EMMY-W2</fullName>
            </value>
            <value>
                <fullName>JODY-B3</fullName>
            </value>
            <value>
                <fullName>JODY-W1</fullName>
            </value>
            <value>
                <fullName>JODY-W2</fullName>
            </value>
            <value>
                <fullName>JODY-W3</fullName>
            </value>
            <value>
                <fullName>LARA-R2</fullName>
            </value>
            <value>
                <fullName>LARA-R3</fullName>
            </value>
            <value>
                <fullName>LARA-R4</fullName>
            </value>
            <value>
                <fullName>LEON-G1</fullName>
            </value>
            <value>
                <fullName>LILY-W1</fullName>
            </value>
            <value>
                <fullName>LISA-C2</fullName>
            </value>
            <value>
                <fullName>LISA-N1</fullName>
            </value>
            <value>
                <fullName>LISA-U2</fullName>
            </value>
            <value>
                <fullName>NANO-S1</fullName>
            </value>
            <value>
                <fullName>NINA-B1</fullName>
            </value>
            <value>
                <fullName>NINA-B2</fullName>
            </value>
            <value>
                <fullName>NINA-B3</fullName>
            </value>
            <value>
                <fullName>NINA-W1</fullName>
            </value>
            <value>
                <fullName>MPCI-L1</fullName>
            </value>
            <value>
                <fullName>MPCI-L2</fullName>
            </value>
            <value>
                <fullName>MPCI-L4</fullName>
            </value>
            <value>
                <fullName>N7-MAT</fullName>
            </value>
            <value>
                <fullName>OBS</fullName>
            </value>
            <value>
                <fullName>ODIN-W1</fullName>
            </value>
            <value>
                <fullName>ODIN-W2</fullName>
            </value>
            <value>
                <fullName>VERA-P1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/NewCompetitorPriceCtrlTest.cls
@IsTest
private class NewCompetitorPriceCtrlTest {     
    public static TestMethod void test(){
      // 2017.11.27 khir: Added Account creation to solve the error for Flow "EMEA_Sales_Stage_8" (made by Process Builder)
      Account acc = new Account(Name='Test Acc',uB_Office__c='Corporate');
      insert acc;
        
        
     Opportunity oppObj =new Opportunity();
     oppObj.Name='test'; 
     oppObj.StageName='prospecting'; 
     oppObj.CloseDate=System.today();     
      oppObj.AccountId=acc.Id; // 2017.11.27 khir
     insert oppObj; 
     Product2 proObj=new Product2();
     proObj.Name='test';
     proObj.Type_No__c='test';
     proObj.Product_Series__c='VERA-P1';
     insert proObj;
     Opp_Product__c oppProObj=new Opp_Product__c();
     oppProObj.Opportunity__c=oppObj.id;
     oppProObj.Product__c=proObj.id;
     insert oppProObj;  
     list<Opp_Product__c>  oppProObjLst=new list<Opp_Product__c>();   
      
     ApexPages.currentPage().getParameters().put('id', oppProObj.id);
     ApexPages.StandardSetController stdController= new ApexPages.StandardSetController(oppProObjLst);   
     NewCompetitorPriceCtrl con= new NewCompetitorPriceCtrl(stdController); 
               
     }
}