force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of all countries and mapping to sales people. Used to automatically assign Accounts when created by OnDemand Service (ISA).</description>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <label>ISO Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <label>uB Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateAccount.cls
/**
** This class is used for:
** 1- Update Account Owner based on the acc's Country and/or State in the Country__c
** 2- Update Accocunt UB Office based on respective UB Office in the Country__c
** 3- Replaced Account_Manager__c with OwnerId of Country object Ticket # IN_SF_MTC-1364 

** ----------- last modified: 09-03-2009 -----------
*/

public class UpdateAccount {
    
    //this class for befor insert account    
        static Map<String,String> mapCtyWithStates=new Map<String,String>();
        
        static {
            mapCtyWithStates.put('US','US');
            mapCtyWithStates.put('CA','CA');
            mapCtyWithStates.put('CN','CN');
        }
    
    //create on trigger on Account, before insert, which set properly the owner of the account
    //owner is choosen based on the country : country code/state code or full state  
    public static void beforUpdateAccount(List<Account> accounts){
        
        Set<String> setCountryCode=new Set<String>();
        Set<String> setStateCode=new Set<String>();
        Set<String> setAccManager=new Set<String>();
        
        Map<String,User> mapUser=new Map<String,User>();
        Map<String,User> mapUser2=new Map<String,User>();
        
        List<String[]> lstAliasCountry=new List<String[]>();//
        List<String[]> lstAliasCountry2=new List<String[]>();//
        
        Map<String,String> mapCountryUbOffice=new Map<String,String>();//key is Country or ISO code and value is UB office       
        
        Map<String,String> mapCountryState=new Map<String,String>();    
            
        for(Account acct : accounts){
            
            if(acct.ShippingCountry!=null){
                setCountryCode.add(acct.ShippingCountry);           
            }       
            if(acct.ShippingState!=null)
                setStateCode.add(acct.ShippingState);//State Code    
        }
            
        for(Account acct : accounts){
            
            //for US CA and CN
            if(mapCtyWithStates.get(acct.ShippingCountry)!=null){                               
                String state=(acct.ShippingState!=null?acct.ShippingState:'');            
                
                if(state!='')
                    mapCountryState.put(acct.ShippingCountry+'#'+state,acct.ShippingCountry+'#'+state);
                else{
                    String city=(acct.ShippingCity!=null?acct.ShippingCity:'');
                    mapCountryState.put(acct.ShippingCountry+'#'+city,acct.ShippingCountry+'#'+city);
                }
            }
            else{
                mapCountryState.put(acct.ShippingCountry,acct.ShippingCountry);
            }
        
        }
                
        for(Country__c c : [select uB_Office__c,OwnerId,ISO_Code__c,State_Code__c,State__c from Country__C where ISO_Code__c IN : setCountryCode OR State_Code__c IN : setStateCode]){
            
            //Dealing with Ub Office            
            mapCountryUbOffice.put(c.ISO_Code__c,c.uB_Office__c);
                    
            if(c.ISO_Code__c!=null){                    
                String state=(c.State_Code__c!=null?c.State_Code__c:''); //State Code
                String state2=(c.State__c!=null?c.State__c:''); //full State
                String s=(mapCtyWithStates.get(c.ISO_Code__c)!=null?mapCountryState.get(c.ISO_Code__c+'#'+state):mapCountryState.get(c.ISO_Code__c));
                           
                //System.debug('>>>country and state code: '+c.ISO_Code__c + ', '+state + ', ' + state2);
                //System.debug('>>>s: '+s);
                
                if(s==null) {
                    String s2=(mapCtyWithStates.get(c.ISO_Code__c)!=null?mapCountryState.get(c.ISO_Code__c+'#'+state2):mapCountryState.get(c.ISO_Code__c));            
                    
                    if(s2==null){                     
                        continue;
                    }
                }
                
                lstAliasCountry.add(new String[]{c.OwnerId,c.ISO_Code__c+'#'+state});//replaced Account_Manager__c with OwnerId of Country object, Country Code#State Code 
                lstAliasCountry2.add(new String[]{c.OwnerId,c.ISO_Code__c+'#'+state2});//replaced Account_Manager__c with OwnerId of Country object, Country Code#State full
                setAccManager.add(c.OwnerId);//replaced Account_Manager__c with OwnerId of Country object                             
                
            }
        
        }   
                   
        
        Map<String,String> mapAlias=new Map<String,String>();
        for(User u : [select id,Alias from User where Id IN :setAccManager]){ //replaced Alias with OwnerId of Country object                
        
            for(String[] s:lstAliasCountry){        
                if(u.Id == s.get(0)) { 
                    mapUser.put(s.get(1),u); //for country code#state code
                }    
            }
            for(String[] s:lstAliasCountry2){        
                if(u.Id == s.get(0)) {
                    mapUser2.put(s.get(1),u); //for country code#full state
                }    
            }
        }       
        
    
        for(Account acc : accounts){
            System.debug('>>>Account obj'+acc);     
            String state=(acc.ShippingState!=null?acc.ShippingState:''); 
            
            if(state=='') state=(acc.ShippingCity!=null?acc.ShippingCity:''); //see city instead of state      
            
            User us=(mapCtyWithStates.get(acc.ShippingCountry)!=null?mapUser.get(acc.ShippingCountry+'#'+state):mapUser.get(acc.ShippingCountry+'#'));
            //System.debug('>>> USER obj step 1'+us);     
            
            if(us==null){
                us=(mapCtyWithStates.get(acc.ShippingCountry)!=null?mapUser2.get(acc.ShippingCountry+'#'+state):mapUser2.get(acc.ShippingCountry+'#'));        
            }
    
            if(us!=null){
                acc.OwnerId=us.Id;//user
                System.debug('>>>USER obj final step'+us);         
            }
            
            //dealing with Ub office
            String ubOff=mapCountryUbOffice.get(acc.ShippingCountry);
            System.debug('>>> ubOff ' + ubOff);
            
            if(ubOff!=null){
                acc.uB_Office__c=ubOff; 
            }
            
                    
        }
    
    
    }//end method
    
    
    
    }