force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <inlineHelpText>On creation, if empty copied from the master Opportunity after Save. Edit as needed.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <formula>text(Product__r.Product_Center__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>When multiple products are in evaluation, set the most probable one as “Evaluation”, all others as “Alternative product”. These will not count as revenue or contribution.</description>
    <inlineHelpText>When multiple products are in evaluation, set the most probable one as “Evaluation”, all others as “Alternative product”. These will not count as revenue or contribution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alternative Product</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
                <default>true</default>
                <label>Evaluation</label>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <formula>TEXT( Opportunity__r.Account.uB_Office__c )</formula>
    <label>uB Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <description>Annual run rate of product. If</description>
    <inlineHelpText>Annual run rate. For single shot opportunities, use total quantity.
If Opportunity is converted from Lead, this is copied from Lead.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End Customer Account)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quotation_Account__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is opportunity, than it is blank.</description>
    <label>Quotation Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_quotation__c.field-meta.xml
<CustomField>
    <fullName>Type_of_quotation__c</fullName>
    <description>Is the quotation budgetary or binding?</description>
    <inlineHelpText>Is the quotation budgetary or binding?</inlineHelpText>
    <label>Type of Quotation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quotation</fullName>
                <default>true</default>
                <label>Quotation</label>
            </value>
            <value>
                <fullName>Budgetary Quotation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Quotation.recordType-meta.xml
<RecordType>
    <fullName>Quotation</fullName>
    <active>true</active>
    <businessProcess>Quotation</businessProcess>
    <label>Quotation</label>
</RecordType>

force-app/main/default/objects/Product2/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tashang</fullName>
            </value>
            <value>
                <fullName>u-blox</fullName>
                <default>true</default>
                <label>u-blox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tashang</fullName>
            </value>
            <value>
                <fullName>u-blox</fullName>
                <default>true</default>
                <label>u-blox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Tashang</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QuoteTriggerHandlerTest.cls
@isTest
public class QuoteTriggerHandlerTest {
    @testSetup
    static void setup(){
        
        AccountTestDataFactory AccountTestDataFactoryobj = new AccountTestDataFactory();
        Account quoteAccount= (Account)AccountTestDataFactoryobj.initializeRecord();
        quoteAccount.Name = 'KAE Electronics';
        quoteAccount.uB_Office__c = 'EMEA';
        insert quoteAccount;
        
        Product2TestDataFactory productTestFactoryObj = new Product2TestDataFactory();
        Product2 cellularProduct = (Product2)productTestFactoryObj.initializeRecord();
        cellularProduct.Name = 'TOBY-L201 quote';
        cellularProduct.Type_No__C='TOBY-L201-02S-01-q';
        cellularProduct.Product_Center__C='Cellular';
        cellularProduct.BusinessUnit__c = 'u-blox';
        insert cellularProduct;
        
        OpportunityTestDataFactory OpportunityTestDataFactoryObj = new OpportunityTestDataFactory();
        Opportunity oppObj= (Opportunity)OpportunityTestDataFactoryObj.initializeRecord();
        oppObj.accountId = quoteAccount.Id;
        oppObj.Name='KAE Electronics';
        oppObj.StageName='3 Calling on';
        oppObj.CloseDate = Date.today().addDays(7);      
        oppObj.End_Customer_Account__c = quoteAccount.Id;
        oppObj.Quotation_Account__c = quoteAccount.Id;
        oppObj.AccountId = quoteAccount.Id;
        oppObj.Type_of_quotation__c = 'Quotation';
        oppObj.RecordTypeId = Schema.sObjectType.Opportunity.getRecordTypeInfosByName().get('Opportunity').getRecordTypeId();
        insert oppObj;
        
        Opp_Product__c oppProductObj = new Opp_Product__c();
        oppProductObj.Opportunity__c = oppObj.Id;
        oppProductObj.Product__c = cellularProduct.Id;
        oppProductObj.Unit_Price__c = 12;
        oppProductObj.Annual_Quantity__c = 12;
        oppProductObj.Status__c = 'Evaluation';
        insert oppProductObj;
        
        pricebook2 priceBookObj = new pricebook2();
        priceBookObj.Name = 'Standard Price Book';
        priceBookObj.CurrencyIsoCode = 'USD';
        insert priceBookObj;
        
        List<pricebookEntry> pricebookEntryList = new List<pricebookEntry>();
        pricebookEntry PBEObj2 = new pricebookEntry();
        PBEObj2.Product2Id = cellularProduct.Id;
        PBEObj2.UnitPrice = 12;
        PBEObj2.Pricebook2Id = Test.getStandardPricebookId();
        PBEObj2.IsActive = true;
        pricebookEntryList.add(PBEObj2);
        pricebookEntry PBEObj = new pricebookEntry();
        PBEObj.Product2Id = cellularProduct.Id;
        PBEObj.UnitPrice = 12;
        PBEObj.Pricebook2Id = priceBookObj.Id;
        PBEObj.IsActive = true;
        pricebookEntryList.add(PBEObj);
        insert pricebookEntryList;
        
    }
    @isTest
    public static void afterInsertTest(){
        Opportunity oppObj = [SELECT Id,AccountId FROM opportunity WHERE Name = 'KAE Electronics'];
         pricebookEntry PBEObj = [SELECT Id FROM pricebookEntry WHERE UnitPrice = 12 LIMIT 1 ];
        pricebook2 priceBookObj = [SELECT Id FROM pricebook2 WHERE name = 'Standard Price Book' LIMIT 1];
        
        Quote quoteObj = new Quote();
        quoteObj.OpportunityId = oppObj.Id;
        quoteObj.Name = 'test quote';
        quoteObj.pricebook2Id = priceBookObj.Id;
        quoteObj.Quotation_Account__c = oppObj.AccountId;

        insert quoteObj;
        
    }
        @isTest
    public static void afterUpdateTest(){
        Opportunity oppObj = [SELECT Id,AccountId FROM opportunity WHERE Name = 'KAE Electronics'];
         pricebookEntry PBEObj = [SELECT Id FROM pricebookEntry WHERE UnitPrice = 12 LIMIT 1 ];
        pricebook2 priceBookObj = [SELECT Id FROM pricebook2 WHERE name = 'Standard Price Book' LIMIT 1];
        
        Quote quoteObj = new Quote();
        quoteObj.OpportunityId = oppObj.Id;
        quoteObj.Name = 'test quote Update';
        quoteObj.pricebook2Id = priceBookObj.Id;
        quoteObj.Quotation_Account__c = oppObj.AccountId;
        insert quoteObj;
        
        quoteObj.Name = 'test quote update';
        update quoteObj;
    }
}