force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of all countries and mapping to sales people. Used to automatically assign Accounts when created by OnDemand Service (ISA).</description>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <label>ISO Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <label>uB Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateAccountTest.cls
@isTest
public with sharing class UpdateAccountTest {
    public UpdateAccountTest() {

    }

    public static testMethod void beforInsertAccount(){
    
        System.debug('>>>Start Test');
        
        //fixed INACTIVE ACCOUNT OWNER USER,
        List<Profile> profList = [select id,Name from Profile where Name ='System Administrator'];
        string profId = profList[0].id; 
        User u=[select id,alias from user where profileId = : profId AND isActive=true limit 1];
        List<Country__c> lc=[select uB_Office__c,OwnerId,ISO_Code__c,State_Code__c,State__c from Country__C where ISO_Code__c IN :new Set<String>{'US','DM','CN','CA','CD'}];
        for(Country__c c : lc){
            c.OwnerId=u.Id;
        }
        update lc;    
        
        List<Account> listAccount=new List<Account>();
        listAccount.add(new Account(Name='Jerry',ShippingCountry='US',ShippingState='AK'));
        listAccount.add(new Account(Name='Tom',ShippingCountry='US',ShippingState='AK'));
        listAccount.add(new Account(Name='Tom 2',ShippingCountry='US',ShippingState='CA'));
        listAccount.add(new Account(Name='Tom 3',ShippingCountry='US'));
        listAccount.add(new Account(Name='Account 1',ShippingCountry='DM'));
        listAccount.add(new Account(Name='Tom 4',ShippingCountry='US',ShippingState='AR'));
        listAccount.add(new Account(Name='Tom 5',ShippingCountry='CN',ShippingCity='JS'));
        listAccount.add(new Account(Name='Tom 6',ShippingCountry='CA',ShippingCity='YT'));
        listAccount.add(new Account(Name='Tom 7',ShippingCountry='CD'));
        
        insert listAccount;
        System.debug('>>> Insert List of Account');
        Account acc;
    
        Account acc1=[Select a.uB_Office__c, a.ShippingCountry, a.ShippingCity, a.Owner.Alias From Account a where a.Name='Jerry' limit 1];
        System.debug('>>>AccountManager:'+acc1.Owner.Alias);//RS
        System.debug('>>>UbOffice:'+acc1.uB_Office__c);//Americas
    
        Account acc2=[Select a.uB_Office__c, a.ShippingCountry, a.ShippingCity, a.Owner.Alias From Account a where a.Name='Tom' limit 1];
        System.debug('>>>AccountManager:'+acc2.Owner.Alias);//RS
        System.debug('>>>UbOffice:'+acc2.uB_Office__c);//Americas
        
        Account acc22=[Select a.uB_Office__c, a.ShippingCountry, a.ShippingCity, a.Owner.Alias From Account a where a.Name='Tom 2' limit 1];
        System.debug('>>>AccountManager:'+acc22.Owner.Alias);//MM
        System.debug('>>>UbOffice:'+acc22.uB_Office__c);//Americas
        
        Account acc23=[Select a.uB_Office__c,a.ShippingCountry, a.ShippingCity, a.Owner.Alias From Account a where a.Name='Tom 3' limit 1];
        System.debug('>>>AccountManager:'+acc23.Owner.Alias);//BS
        System.debug('>>>UbOffice:'+acc23.uB_Office__c);//Americas
        
        Account acc24=[Select a.uB_Office__c,a.ShippingCountry, a.ShippingCity, a.Owner.Alias From Account a where a.Name='Tom 4' limit 1];
        System.debug('>>>AccountManager:'+acc24.Owner.Alias);//AS //ascha
        System.debug('>>>UbOffice:'+acc24.uB_Office__c);//Americas
        
        Account acc25=[Select a.uB_Office__c,a.ShippingCountry, a.ShippingCity, a.Owner.Alias From Account a where a.Name='Tom 5' limit 1];
        System.debug('>>>AccountManager:'+acc25.Owner.Alias);//BW
        System.debug('>>>UbOffice:'+acc25.uB_Office__c);//China
    
        Account acc26=[Select a.uB_Office__c,a.ShippingCountry, a.ShippingCity, a.Owner.Alias From Account a where a.Name='Tom 6' limit 1];
        System.debug('>>>AccountManager:'+acc26.Owner.Alias);//BS
        System.debug('>>>UbOffice:'+acc26.uB_Office__c);//Americas
        
        Account acc27=[Select a.uB_Office__c,a.ShippingCountry, a.ShippingCity, a.Owner.Alias From Account a where a.Name='Tom 7' limit 1];
        System.debug('>>>AccountManager:'+acc27.Owner.Alias);//HR
        System.debug('>>>UbOffice:'+acc27.uB_Office__c);//EMEA
    
        Account acc3=[Select a.uB_Office__c,a.ShippingCountry, a.ShippingCity, a.Owner.Alias From Account a where a.Name='Account 1' limit 1];
        System.debug('>>>AccountManager:'+acc3.Owner.Alias);//NP
        System.debug('>>>UbOffice:'+acc3.uB_Office__c);//Americas
        
        
        
        
    }
}