force-app/main/default/objects/Account/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <inlineHelpText>u-blox office that takes care of this account</inlineHelpText>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <color>#0B6FCE</color>
                <label>Americas</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#78C953</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>China</fullName>
                <color>#E27001</color>
                <label>China</label>
            </value>
            <value>
                <fullName>Hongkong</fullName>
                <color>#A845DC</color>
                <label>Hongkong</label>
            </value>
            <value>
                <fullName>Taiwan</fullName>
                <color>#F3D904</color>
                <label>Taiwan</label>
            </value>
            <value>
                <fullName>Korea</fullName>
                <color>#A53711</color>
                <label>Korea</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <color>#66E9BD</color>
                <label>Japan</label>
            </value>
            <value>
                <fullName>India</fullName>
                <color>#006600</color>
                <label>India</label>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
                <color>#0B24BE</color>
                <label>Rest of APAC</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#999999</color>
                <label>Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of all countries and mapping to sales people. Used to automatically assign Accounts when created by OnDemand Service (ISA).</description>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <label>ISO Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <label>uB Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/uB_Office__c.field-meta.xml
<CustomField>
    <fullName>uB_Office__c</fullName>
    <label>uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
                <color>#B6E32E</color>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateLeadTest.cls
@isTest
public with sharing class UpdateLeadTest {
    public UpdateLeadTest() {

    }

    static testMethod void changeOwnerOnLeadBeforInsert(){
    
        System.debug('>>>Start Test');
        //fixed INACTIVE ACCOUNT OWNER USER,
        User u=[select id,alias from user where isActive=true limit 1];
        List<Country__c> lc=[select uB_Office__c,OwnerId,ISO_Code__c,State_Code__c,State__c from Country__C where ISO_Code__c IN :new Set<String>{'SM','US','CN','CA'}];
        for(Country__c c : lc){
            c.OwnerId = u.Id;
        }
        update lc;
    //Finland
        List<Lead> listLead=new List<Lead>();
        listLead.add(new Lead(FirstName='Jerry',LastName='Mouse',Country='SM',City='San Marino',Company='JerryMouse Co,Ltd'));
        listLead.add(new Lead(FirstName='Tom',LastName='Cat',Country='US',City='AA',Company='TomCat Co,Ltd'));
        listLead.add(new Lead(FirstName='Micky',LastName='Mouse',Country='CN',City='Gansu',Company='MickyMouse Co,Ltd'));
        
        insert listLead;
        System.debug('>>> inserted List of Lead');
        Lead lead;
    
        lead=[Select uB_Office__c,a.Country, a.City, a.Owner.Alias From Lead a where a.FirstName='Jerry' limit 1];
        System.debug('>>>AccountManager expected JMD :'+lead.Owner.Alias);//JMD
        //System.assertEquals('JMD',lead.Owner.Alias);
        //System.assertEquals('EMEA',lead.uB_Office__c);
    
        lead=[Select uB_Office__c,a.Country, a.City, a.Owner.Alias From Lead a where a.FirstName='Tom' limit 1];
        System.debug('>>>AccountManager expected RS :'+lead.Owner.Alias);//RS
        //System.assertEquals('RS',lead.Owner.Alias);
        //System.assertEquals('Americas',lead.uB_Office__c);
        
        lead=[Select uB_Office__c,a.Country, a.City, a.Owner.Alias From Lead a where a.FirstName='Micky' limit 1];
        System.debug('>>>AccountManager expected WL :'+lead.Owner.Alias);//WL
        //System.assertEquals('WL',lead.Owner.Alias);
        //System.assertEquals('China',lead.uB_Office__c);
        
        
        //Modified: 20-08-09
        List<Lead> listLead2=new List<Lead>();
        listLead2.add(new Lead(FirstName='Jerry2',LastName='Mouse2',Country='US',State='WI',Company='Company')); //RS; Americas
        listLead2.add(new Lead(FirstName='Tom2',LastName='Cat2',Country='US',State='AA',Company='Company'));            //RS; Americas  
        //listLead2.add(new Lead(FirstName='Tom2 2',LastName='Cat2 2',Country='US',State='CA',Company='Company'));      //MM; Americas
        listLead2.add(new Lead(FirstName='Tom 5',LastName='Cat 5', Country='CN',City='JS',Company='Company')); //BW; China
        listLead2.add(new Lead(FirstName='Tom 6',LastName='Cat 6',Country='CA',City='YT',Company='Company'));        //BS; Americas
        insert listLead2;
        
        Set<Id> ids = new Set<Id>();
        for(Lead l : listLead2) ids.add(l.Id);
        
        Map<String, String> mapOwnerExpected = new Map<String, String>();
        Map<String, String> mapUbOfficeExpected = new Map<String, String>();
        
        mapOwnerExpected.put('Jerry2','RS');
        mapOwnerExpected.put('Tom2','RS');
        //mapOwnerExpected.put('Tom2 2','MM');
        mapOwnerExpected.put('Tom 5','BW');
        mapOwnerExpected.put('Tom 6','BS');
        
        mapUbOfficeExpected.put('Jerry2','Americas');
        mapUbOfficeExpected.put('Tom2','Americas');
        //mapUbOfficeExpected.put('Tom2 2','Americas');
        mapUbOfficeExpected.put('Tom 5','China');
        mapUbOfficeExpected.put('Tom 6','Americas');
        
            
        List<Lead> result = [Select a.FirstName, a.LastName, a.uB_Office__c, a.Country, a.City, a.Owner.Alias From Lead a where id in : ids 
                order by a.FirstName];
        for(Lead l : result){
            System.debug('>>>Lead FirstName:'+l.FirstName);
            System.debug('>>>Actual AccountManager:'+l.Owner.Alias + '; Expected AccountManager: ' + mapOwnerExpected.get(l.FirstName));
            System.debug('>>>Actual UbOffice:'+l.uB_Office__c + '; Expected UbOffice: ' + mapUbOfficeExpected.get(l.FirstName));
        }    
        
        
    }
}