force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Salesforce Account. Conneced via field &quot;Customer No&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Calculate_Contribution_Split__c.field-meta.xml
<CustomField>
    <fullName>Calculate_Contribution_Split__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checkbox is set, (re-)calculate the split of the contribution to uB Offices</inlineHelpText>
    <label>Calculate Contribution Split</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Calculate_Total_COGS_CHF__c.field-meta.xml
<CustomField>
    <fullName>Calculate_Total_COGS_CHF__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Set the flag to (re-)calculate the COGS and split of the contribution.</inlineHelpText>
    <label>Calculate Total COGS CHF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Contribution_Share__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Share__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contribution share that defines the split of the contribution for this order</inlineHelpText>
    <label>Contribution Share</label>
    <referenceTo>Contribution_Share__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/End_Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The end customer is the company buying from the Account that buys from us. Typically this is the customer of our distributor or direct CM.</inlineHelpText>
    <label>End Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (End Customer Account)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/End_Customer_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account_ID__c</fullName>
    <description>Field used in &quot;Show Orders&quot; report under Account.</description>
    <formula>End_Customer_Account__r.Id</formula>
    <label>End Customer Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <formula>IF ( Product_ID__c = &quot;VIA-CB-C&quot;, &quot;Ignore&quot;,
IF( (Qty_Invoiced__c=0)  &amp;&amp; (Total_Value_CHF__c=0) &amp;&amp; ( Qty_Ordered__c = 0), &quot;Ignore&quot;,
IF(Position_Replaced__c=false,
                    IF( ISNULL(Invoice_Date__c)  ||   Qty_Invoiced__c =0 || ISNULL( Invoice_Number__c ) || Invoice_Number__c =&quot;0&quot;, &quot;Open&quot;, &quot;Closed&quot;),
                    &quot;Position Replaced&quot; )
))</formula>
    <inlineHelpText>Values:
- Billing
- Open Order
- Position Replaced
- Ignore</inlineHelpText>
    <label>Order Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated with Billing</description>
    <inlineHelpText>Product associated with Billing</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Used to match Contribution Share</description>
    <formula>Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used to match Contribution Share</inlineHelpText>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Link to Account in Salesforce</inlineHelpText>
    <label>Project Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Project Owner Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_Account_ID__c</fullName>
    <formula>Project_Owner_Account__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Owner Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_uB_Office__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_uB_Office__c</fullName>
    <formula>IF(LEN( Project_Owner_Account__r.BillingCountry)&lt;&gt;2,
TEXT(Project_Owner_Account__r.uB_Office__c),

IF(Contains(&quot;AN:AR:BR:CA:CL:CO:EC:GT:MX:PA:PE:PR:SV:US:UY:VE&quot;, Project_Owner_Account__r.BillingCountry),&quot;Americas&quot;,
IF(Contains(&quot;AE:AM:AT:BA:BE:BG:BY:CH:CY:CZ:DE:DK:EE:EG:ES:FI:FR:GB:GE:GR:HR:HU:IE:IQ:IL:IS:IT:JO:KE:KZ:LB:LI:LT:LU:LV:MA:MD:MT:NG:NL:NO:PL:PT:RO:RS:RU:SE:SA:SI:SK:SM:TJ:TR:UA:UK:ZA&quot;, Project_Owner_Account__r.BillingCountry),&quot;EMEA&quot;,
IF(Contains(&quot;ID:MY:PH:PK:SG:TH:VN&quot;,Project_Owner_Account__r.BillingCountry),&quot;Rest of APAC&quot;,

Case(Project_Owner_Account__r.BillingCountry,
&quot;IN&quot;,&quot;India&quot;,
&quot;JP&quot;,&quot;Japan&quot;,
&quot;KR&quot;,&quot;Korea&quot;,
&quot;TW&quot;,&quot;Taiwan&quot;,
&quot;CN&quot;,&quot;China&quot;,
&quot;HK&quot;,&quot;China&quot;,
&quot;AU&quot;,&quot;Australia&quot;,
&quot;NZ&quot;,&quot;Australia&quot;,
TEXT(Project_Owner_Account__r.uB_Office__c))
)))
)</formula>
    <inlineHelpText>uB Office in which the project owner resides.</inlineHelpText>
    <label>Project Owner uB Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Reporting_uB_Office__c.field-meta.xml
<CustomField>
    <fullName>Reporting_uB_Office__c</fullName>
    <formula>Case (Reporting_Area__c,
&quot;AU&quot;,&quot;Australia&quot;,
&quot;IN&quot;,&quot;India&quot;,
&quot;MY&quot;,&quot;Rest of APAC&quot;,
&quot;NZ&quot;,&quot;Australia&quot;,
&quot;PH&quot;,&quot;Rest of APAC&quot;,
&quot;SG&quot;,&quot;Rest of APAC&quot;,
&quot;TH&quot;,&quot;Rest of APAC&quot;,
&quot;VN&quot;,&quot;Rest of APAC&quot;,
&quot;JP&quot;,&quot;Japan&quot;,
&quot;CN&quot;,&quot;China&quot;,
&quot;HK&quot;,&quot;China&quot;,
&quot;TW&quot;,&quot;Taiwan&quot;,
&quot;KR&quot;,&quot;Korea&quot;,
&quot;Rest of APAC&quot;,&quot;Rest of APAC&quot;,

    Case(Reporting_Region__c ,
    &quot;EMEA&quot;,&quot;EMEA&quot;,
    &quot;AMERICAS&quot;, &quot;Americas&quot;,
    &quot;UBX Corporate&quot;)
)</formula>
    <inlineHelpText>uB Office for reporting, derived from Reporting Area.</inlineHelpText>
    <label>Reporting uB Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Update_CS__c.field-meta.xml
<CustomField>
    <fullName>Update_CS__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When ticked, the Contribution Share for this order is looked up.</inlineHelpText>
    <label>Update CS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/Contribution_Share__c.object-meta.xml
<CustomObject>
    <description>Object that defines the share of contribution that is assigned for a certain Project Owner in an order.</description>
    <label>Contribution Share</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Contribution Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Shares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contribution_Share__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Buying Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contribution Share</relationshipLabel>
    <relationshipName>Contribution_Share</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/End_Customer_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account_ID__c</fullName>
    <description>Used for matching with Order (in the Apex Class)</description>
    <formula>End_Customer__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used for matching with Order (in the Apex Class)</inlineHelpText>
    <label>End Customer Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product to be used for matching Orders</description>
    <inlineHelpText>Product to be used for matching Orders</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contribution Shares</relationshipLabel>
    <relationshipName>Contribution_Shares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Project_Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Account for which this contribution share applies</inlineHelpText>
    <label>Project Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contribution Shares (Project Owner Account)</relationshipLabel>
    <relationshipName>Contribution_Shares</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Project_Owner_uB_Office__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_uB_Office__c</fullName>
    <formula>text( Project_Owner_Account__r.uB_Office__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Owner uB Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Reporting_uB_Office__c.field-meta.xml
<CustomField>
    <fullName>Reporting_uB_Office__c</fullName>
    <label>Reporting uB Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Rest of APAC</fullName>
            </value>
            <value>
                <fullName>HQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BillingsTrigger.cls
/*
    Created by Ben Mansfield - 23/02/2010
    Changed by Werner Grätzer - 12/12/2012 / Request Herber Blaser 11/12/2012
    - replaced "Reporting_uB_Office__c" by "Project_Owner_uB_Office__c"
    Changed by Werner Grätzer - 19/04/2013 / Request Herbert Blaser 18/04/2013 / PRN-070542
    - replaced "Project_Owner_uB_Office__c" by "Project_Owner_Account_ID__c"
    
    Matches 'Project_Owner_Account_ID__c' field on Billings__c to the 'Project_Owner_Account_ID__c' field on
    a Contribution_Share__c record related to the same Account.

    2018.04.12 :khir: - End Customer, Product Name and Approval Status added for matching. Test cases also added.

*/
public with sharing class BillingsTrigger {
    
    public static void updateContributionShareOnBillings(List<Billings__c> updatedOrders, Map<Id, Billings__c> oldRecords)
    {
        List<Billings__c> ordersRequiringCSUpdate = new List<Billings__c>();
        Set<Id> accounts = new Set<Id>();
     
        // Loop through orders
        for (Billings__c order : updatedOrders)
        {
            // If order requires update
            if ((order.Order_Status__c == 'Closed' && (oldRecords == null || oldRecords.get(order.Id).Order_Status__c != order.Order_Status__c)) || order.Update_CS__c || order.Calculate_Total_COGS_CHF__c)
            {
                // Add orders to list
                ordersRequiringCSUpdate.add(order);
                // Add related account id to set
                accounts.add(order.Account__c);
                
                // Reset update CS flag
                order.Update_CS__c = false;
                // Set flag to calculate contribution split
                //order.Calculate_Contribution_Split__c = true;
            }
        }
        
        if (ordersRequiringCSUpdate.size() > 0) updateCS(ordersRequiringCSUpdate, accounts);
    }
    
    private static void updateCS(List<Billings__c> ordersToUpdate, Set<Id> targetAccounts)
    {
        // Get all accounts related to the orders including all of the contribution share related records 
        Map<Id, Account> accountDetails = new Map<Id, Account>([Select Id, 
                                        (Select Id, Project_Owner_Account_ID__c, End_Customer_Account_ID__c, Product_Name__c, Status__c From Contribution_Share__r)
                                        From Account Where Id in :targetAccounts]);

        System.debug('accountDetails:'+accountDetails);
        
        // Loop through orders
        for (Billings__c order : ordersToUpdate)
        {
            // Set Contribution Share field to null
            order.Contribution_Share__c = null;
            // If there is an account related to this order
            if (accountDetails.containsKey(order.Account__c))
            {
                // Get account
                Account target = accountDetails.get(order.Account__c);
                // Match order fields to contribution share
                Contribution_Share__c match = matchReportinguBOffice(order, target);
                // If there was a match, add record id to lookup field
                if (match != null) order.Contribution_Share__c = match.Id;
            }
        }
    }
    
    private static Contribution_Share__c matchReportinguBOffice(Billings__c order, Account relatedAccount)
    {
        // If the order record has no matchable fields - return null
        if (order.Project_Owner_Account_ID__c == null || order.Project_Owner_Account_ID__c == '') return null;
        // Loop through all contribution share records for this account
        for (Contribution_Share__c cs : relatedAccount.Contribution_Share__r)
        {
            // If this contribution share has no matchable fields, go to next record
            if (cs.Project_Owner_Account_ID__c == null || cs.Project_Owner_Account_ID__c == '' || cs.End_Customer_Account_ID__c == '' || cs.End_Customer_Account_ID__c == null) continue;

            // Try to match the contribution share field with the order field of the same name
            // 2018.04.12 :khir: End Customer, Product Name and Approval Status added for matching
            if (cs.Project_Owner_Account_ID__c == order.Project_Owner_Account_ID__c && cs.End_Customer_Account_ID__c == order.End_Customer_Account_ID__c && cs.Product_Name__c == order.Product_Name__c && cs.Status__c == 'Activated') return cs;
        }
        
        // No matches found here
        return null;
    }
    


//     @IsTest
//     private static void basictest()
//     {

// // 		List<Account> iAccounts = new list<Account>();
// // 		List<Product2> iProducts = new list<Product2>();

// //         Account acc = new Account();
// //         acc.Name = 'Test Account';
// // 		iAccounts.add(acc);
        
// //         Account ac2 = new Account();
// //         ac2.Name = 'Project Owner Test';
// //         iAccounts.add(ac2);

// // // :khir: 2018.03.19 added

// //         Account acc001 = new Account();
// //         acc001.Name = 'Test ACC 001';
// // 		iAccounts.add(acc001);

// //         Account acc002 = new Account();
// //         acc002.Name = 'Test ACC 002';
// // 		iAccounts.add(acc002);

// //         Account eca001 = new Account();
// //         eca001.Name = 'Test ECA 001';
// // 		iAccounts.add(eca001);

// //         Account eca002 = new Account();
// //         eca002.Name = 'Test ECA 002';
// // 		iAccounts.add(eca002);

// //         Account poa001 = new Account();
// //         poa001.Name = 'Test POA 001';
// // 		iAccounts.add(poa001);

// // 		insert iAccounts ;


// //         Product2 prod011 = new Product2();
// //         prod011.Name = 'TEST-P001';
// //         prod011.ProductCode = 'TEST-P001-0';
// //         prod011.Type_No__c = 'TEST-P001-0-01';
// // 		iProducts.add(prod011);

// //         Product2 prod012 = new Product2();
// //         prod012.Name = 'TEST-P001';
// //         prod012.ProductCode = 'TEST-P001-0';
// //         prod012.Type_No__c = 'TEST-P001-0-02';
// // 		iProducts.add(prod012);

// //         Product2 prod021 = new Product2();
// //         prod021.Name = 'TEST-P002';
// //         prod021.ProductCode = 'TEST-P002-0';
// //         prod021.Type_No__c = 'TEST-P002-0-01';
// // 		iProducts.add(prod021);

// //         Product2 prod022 = new Product2();
// //         prod022.Name = 'TEST-P002';
// //         prod022.ProductCode = 'TEST-P002-0';
// //         prod022.Type_No__c = 'TEST-P002-0-02';
// // 		iProducts.add(prod022);

// //         Product2 prod031 = new Product2();
// //         prod031.Name = 'TEST-P003';
// //         prod031.ProductCode = 'TEST-P003-0';
// //         prod031.Type_No__c = 'TEST-P003-0-01';
// // 		iProducts.add(prod031);

// // 		insert iProducts;


// //         Contribution_Share__c cs = new Contribution_Share__c();
// //         cs.Account__c = acc.Id;
// //         cs.Project_Owner_Account__c = ac2.Id;
// //         insert cs;


// //         Billings__c order_acc001 = new Billings__c();
// //         order_acc001.Account__c = acc001.Id;
// //         order_acc001.End_Customer_Account__c = eca001.Id;
// //         order_acc001.Project_Owner_Account__c = poa001.Id;
// //         order_acc001.Product__c = prod011.Id;
// //         insert order_acc001;

// // // :khir: 2018.03.19 added END
        
// //         Billings__c order = new Billings__c();
// //         order.Account__c = acc.Id;
// //         order.Reporting_Area__c = 'TW';
// //         order.Project_Owner_Account__c = ac2.Id;
// //         order.Update_CS__c = true;
// // 		insert order;

        
// // // :khir: 2018.03.19 commented
// // //        order = [Select Id, Project_Owner_uB_Office__c, Project_Owner_Account__c, Contribution_Share__c From Billings__c Where Id = :order.Id Limit 1][0];
// // //        
// // //        System.assertEquals(cs.Project_Owner_Account__c, order.Project_Owner_Account__c);
// // //        System.assertEquals(cs.Id, order.Contribution_Share__c);
// // // :khir: 2018.03.19 commented END


// // // :khir: 2018.03.19 added
        
// // // Test 1.01
// //         order_acc001.Update_CS__c = true;
// //         update order_acc001;

// //         Billings__c DUT_order = [SELECT Id, Project_Owner_uB_Office__c, Project_Owner_Account__c, Contribution_Share__c From Billings__c Where Id = :order_acc001.Id Limit 1];
// //         System.assertEquals(null, DUT_order.Contribution_Share__c);

// // // Test 1.04 - All the fields match and there is not approved CS
// //         Contribution_Share__c cs001 = new Contribution_Share__c();
// //         cs001.Account__c = acc001.Id;
// //         cs001.End_Customer__c = eca001.Id;
// //         cs001.Project_Owner_Account__c = poa001.Id;
// //         cs001.Product__c = prod011.Id;
// // //        cs001.Status__c = 'Activated';
// //         insert cs001;

// //         order_acc001.Update_CS__c = true;
// //         update order_acc001;
// //         DUT_order = [SELECT Id, Project_Owner_uB_Office__c, Project_Owner_Account__c, Contribution_Share__c From Billings__c Where Id = :order_acc001.Id Limit 1];
// //         System.assertEquals(null, DUT_order.Contribution_Share__c);

// // // Test 1.02
// //         cs001.Status__c = 'Activated';
// //         Update cs001;

// //         order_acc001.Update_CS__c = true;
// //         update order_acc001;

// //         DUT_order = [SELECT Id, Project_Owner_uB_Office__c, Project_Owner_Account__c, Contribution_Share__c From Billings__c Where Id = :order_acc001.Id Limit 1];
// //         System.assertEquals(cs001.Id, DUT_order.Contribution_Share__c);

// // // Test 1.03
// //         order_acc001.Product__c = prod012.Id;
// //         order_acc001.Update_CS__c = true;
// //         update order_acc001;

// //         DUT_order = [SELECT Id, Project_Owner_uB_Office__c, Project_Owner_Account__c, Contribution_Share__c From Billings__c Where Id = :order_acc001.Id Limit 1];
// //         System.assertEquals(cs001.Id, DUT_order.Contribution_Share__c);

// // // Test 1.05 - All the fields except Product match.
// //         order_acc001.Product__c = prod031.Id;
// //         order_acc001.Update_CS__c = true;
// //         update order_acc001;

// //         DUT_order = [SELECT Id, Project_Owner_uB_Office__c, Project_Owner_Account__c, Contribution_Share__c From Billings__c Where Id = :order_acc001.Id Limit 1];
// //         System.assertEquals(null, DUT_order.Contribution_Share__c);

// // // Test 1.06 - All the fields except End Customer match.
// //         order_acc001.Product__c = prod011.Id;
// //         order_acc001.End_Customer_Account__c = eca002.Id;
// //         order_acc001.Update_CS__c = true;
// //         update order_acc001;

// //         DUT_order = [SELECT Id, Project_Owner_uB_Office__c, Project_Owner_Account__c, Contribution_Share__c From Billings__c Where Id = :order_acc001.Id Limit 1];
// //         System.assertEquals(null, DUT_order.Contribution_Share__c);

// // // Test 1.07 - All the fields except Account match.
// //         cs001.Account__c = acc002.Id;
// //         Update cs001;

// //         order_acc001.End_Customer_Account__c = eca001.Id;
// //         order_acc001.Update_CS__c = true;
// //         update order_acc001;

// //         DUT_order = [SELECT Id, Project_Owner_uB_Office__c, Project_Owner_Account__c, Contribution_Share__c From Billings__c Where Id = :order_acc001.Id Limit 1];
// //         System.assertEquals(null, DUT_order.Contribution_Share__c);

// // // Test 1.08 - All the fields except Project Owner Account match.
// //         cs001.Account__c = acc001.Id;
// //         Update cs001;

// //         order_acc001.Project_Owner_Account__c = eca002.Id;
// //         order_acc001.Update_CS__c = true;
// //         update order_acc001;

// //         DUT_order = [SELECT Id, Project_Owner_uB_Office__c, Project_Owner_Account__c, Contribution_Share__c From Billings__c Where Id = :order_acc001.Id Limit 1];
// //         System.assertEquals(null, DUT_order.Contribution_Share__c);

// // :khir: 2018.03.19 added END

//         	System.assertEquals(true, true);
//     }
}