force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Salesforce Account. Conneced via field &quot;Customer No&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Contribution_Share__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Share__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contribution share that defines the split of the contribution for this order</inlineHelpText>
    <label>Contribution Share</label>
    <referenceTo>Contribution_Share__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Customer_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Part_Number__c</fullName>
    <description>This field will populate from the object Customer_Part_Number__c with the value of its field Customer_Part_Number__c. Whenever a new Customer_Part_Number__c generated in the object Customer_Part_Number__c.</description>
    <label>Customer Part Number String</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Customer_Part_Number_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Part_Number_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for Customer Part Number record.</description>
    <inlineHelpText>Lookup field for Customer Part Number record.</inlineHelpText>
    <label>Customer Part Number ID</label>
    <referenceTo>Customer_Part_Number__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/End_Customer_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account_ID__c</fullName>
    <description>Field used in &quot;Show Orders&quot; report under Account.</description>
    <formula>End_Customer_Account__r.Id</formula>
    <label>End Customer Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated with Billing</description>
    <inlineHelpText>Product associated with Billing</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Used to match Contribution Share</description>
    <formula>Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used to match Contribution Share</inlineHelpText>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_Account_ID__c</fullName>
    <formula>Project_Owner_Account__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Owner Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/Contribution_Share__c.object-meta.xml
<CustomObject>
    <description>Object that defines the share of contribution that is assigned for a certain Project Owner in an order.</description>
    <label>Contribution Share</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Contribution Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Shares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contribution_Share__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Buying Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contribution Share</relationshipLabel>
    <relationshipName>Contribution_Share</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/End_Customer_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account_ID__c</fullName>
    <description>Used for matching with Order (in the Apex Class)</description>
    <formula>End_Customer__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used for matching with Order (in the Apex Class)</inlineHelpText>
    <label>End Customer Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product to be used for matching Orders</description>
    <inlineHelpText>Product to be used for matching Orders</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contribution Shares</relationshipLabel>
    <relationshipName>Contribution_Shares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Product_Filter_Field__c.field-meta.xml
<CustomField>
    <fullName>Product_Filter_Field__c</fullName>
    <inlineHelpText>Product field which is used in the matching logic of the Contribution Share process.</inlineHelpText>
    <label>Product Filter Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Family</fullName>
                <label>Product Family</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Product_Filter_Value__c.field-meta.xml
<CustomField>
    <fullName>Product_Filter_Value__c</fullName>
    <inlineHelpText>Product field value which is used in the matching logic of the Contribution Share process. Product Filter Field must be selected.</inlineHelpText>
    <label>Product Filter Value</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contribution_Share__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Part_Number__c/Customer_Part_Number__c.object-meta.xml
<CustomObject>
    <description>makes a link between u-blox part number, Account Name and the Customer&apos;s Part Number</description>
    <label>Customer Part Number</label>
    <nameField>
        <label>Customer Part Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Part Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Part_Number__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Linked to Account based on Abacus Customer Number</description>
    <inlineHelpText>(From Abacus) Related Account based on Abacus Customer Number</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Part Numbers</relationshipLabel>
    <relationshipName>Customer_Part_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Part_Number__c/fields/Customer_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Part_Number__c</fullName>
    <description>This is the P/N in the customers system</description>
    <inlineHelpText>(From Abacus) This is the P/N in the customers system</inlineHelpText>
    <label>Customer Part Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Part_Number__c/fields/Type_No_c__c.field-meta.xml
<CustomField>
    <fullName>Type_No_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked to Product based on Type Number</description>
    <inlineHelpText>(From Abacus) Related Product based on Type Number</inlineHelpText>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Customer Part Numbers</relationshipLabel>
    <relationshipName>Customer_Part_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/orderObjectHelper.cls
public class orderObjectHelper {
    private static final string OBJECT_NAME = 'Contribution_Share__c';
    private static final String FIELD_NAME = 'Product_Filter_Field__c';
      
    public static void updateCS(list<Billings__c> ordersToUpdate, set<Id> targetAccounts){
        map<string,string> productFilterFieldMap = new map<string,string>();
        map<Id,Product2> productsMap = new Map<Id,Product2>();
        list<Product2> prodList = new list<Product2>(); 
        set<Id> productIds = new set<Id>();

        // Get all accounts related to the orders including all of the contribution share related records 
        Map<Id, Account> accountDetails = new Map<Id, Account>([Select Id, 
                                        (Select Id, 
                                            Project_Owner_Account_ID__c, 
                                            End_Customer_Account_ID__c, 
                                            Product_Name__c, Status__c, 
                                            Product_Filter_Value__c,
                                            Product_Filter_Field__c 
                                            From Contribution_Share__r ORDER BY product__c ASC NULLS LAST)
                                        From Account Where Id in :targetAccounts]);
              
        // product field label
        productFilterFieldMap = utility.getFieldValues(OBJECT_NAME,FIELD_NAME);
        
        for(Billings__c order : ordersToUpdate){
            productIds.add(order.Product__c);
        }

        string prodFields = string.join(productFilterFieldMap.values(), ',');      
        string dynamicQuery = 'SELECT Id ,'+prodFields+ ' FROM product2 where id IN :productIds';
        
        try{
            for(product2 prod : database.query(dynamicQuery)){
                productsMap.put(prod.Id, prod);
            }
        }catch(QueryException e){
            system.debug('An error has occurred. '+ e.getMessage());
        }
        
        // Loop through orders
        for(Billings__c order : ordersToUpdate) {

            // Set Contribution Share field to null
            order.Contribution_Share__c = null;
            // If there is an account related to this order
            if (accountDetails.containsKey(order.Account__c)) {
                // Get account
                Account target = accountDetails.get(order.Account__c);
                // Match order fields to contribution share
                Contribution_Share__c match = matchReportinguBOffice(order, target, productsMap, productFilterFieldMap);                
                // If there was a match, add record id to lookup field                
                if (match != null) order.Contribution_Share__c = match.Id;
            }
        }        
    }
    
    private static Contribution_Share__c matchReportinguBOffice(Billings__c order, Account relatedAccount,map<Id,Product2> productsMap ,map<String,String> productFilterFieldMap ){
        // If the order record has no matchable fields - return null
        if (order.Project_Owner_Account_ID__c == null || order.Project_Owner_Account_ID__c == '') return null;
        // Loop through all contribution share records for this account
        for (Contribution_Share__c cs : relatedAccount.Contribution_Share__r) {

            String CSproductFieldName = productFilterFieldMap.get(cs.Product_Filter_Field__c);
            String OrderproductFieldValue;
            if(CSproductFieldName != NULL){
                product2 pordObj = productsMap.get(order.Product__c);
                OrderproductFieldValue = (String) pordObj.get(CSproductFieldName);
            }
                        
            // If this contribution share has no matchable fields, go to next record
            if (cs.Project_Owner_Account_ID__c == null 
                || cs.Project_Owner_Account_ID__c == '' 
                || cs.End_Customer_Account_ID__c == '' 
                || cs.End_Customer_Account_ID__c == null) continue;
            
            // Try to match the contribution share field with the order field of the same name
            // 2018.04.12 :khir: End Customer, Product Name and Approval Status added for matching
            //add product family to relax the CS unique Id
            if (cs.Project_Owner_Account_ID__c == order.Project_Owner_Account_ID__c 
                && cs.End_Customer_Account_ID__c == order.End_Customer_Account_ID__c 
                && cs.Product_Name__c == order.Product_Name__c 
                && cs.Status__c == 'Activated'){

                return cs;
                // comparing product family
            }else if(productFilterFieldMap.containsKey(CS.Product_Filter_Field__c) && productsMap.size() > 0 
                    && (cs.Project_Owner_Account_ID__c == order.Project_Owner_Account_ID__c 
                    && cs.End_Customer_Account_ID__c == order.End_Customer_Account_ID__c 
                    && cs.Product_Filter_Value__c == OrderproductFieldValue
                    && cs.Status__c == 'Activated')){
                return cs;
            }
        }       
        return null;
    }

    /* 
    * disabled by Khurram 3/3/22 moved the CPN assignment to Order Interface Mapping
    *
    public static void setCPN(List<Billings__c> orderList, List<String> accountList, List<String> productList){
        
        Map<String, String> cpnMap = new Map<String, String>();
                 
        if(accountList.size() > 0 && productList.size() > 0){
            
            for(Customer_Part_Number__c cpn : [SELECT Id, 
                                                    Account_Name__c, Type_No_c__c
                                                    FROM Customer_Part_Number__c 
                                                    WHERE Account_Name__c =: accountList 
                                                    AND Type_No_c__c =: productList]){
                cpnMap.put(cpn.Account_Name__c+';'+cpn.Type_No_c__c, cpn.Id);
            }
            
            for(Billings__c  tempOrder :orderList){
                String cpnKey = tempOrder.Account__c+';'+tempOrder.Product__c;               
                if(cpnMap.containsKey(cpnKey)){
                    tempOrder.Customer_Part_Number_ID__c = cpnMap.get(cpnKey);                    
                }else tempOrder.Customer_Part_Number_ID__c = null;
            }
        }
    }*/
}