force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Calculate_Total_COGS_CHF__c.field-meta.xml
<CustomField>
    <fullName>Calculate_Total_COGS_CHF__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Set the flag to (re-)calculate the COGS and split of the contribution.</inlineHelpText>
    <label>Calculate Total COGS CHF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/CM_Pct__c.field-meta.xml
<CustomField>
    <fullName>CM_Pct__c</fullName>
    <formula>if ( Total_Value_CHF__c &gt; 0, Total_Contribution_CHF__c / Total_Value_CHF__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Contribution margin of this order in percent.</inlineHelpText>
    <label>CM [%]</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <formula>IF ( Product_ID__c = &quot;VIA-CB-C&quot;, &quot;Ignore&quot;,
IF( (Qty_Invoiced__c=0)  &amp;&amp; (Total_Value_CHF__c=0) &amp;&amp; ( Qty_Ordered__c = 0), &quot;Ignore&quot;,
IF(Position_Replaced__c=false,
                    IF( ISNULL(Invoice_Date__c)  ||   Qty_Invoiced__c =0 || ISNULL( Invoice_Number__c ) || Invoice_Number__c =&quot;0&quot;, &quot;Open&quot;, &quot;Closed&quot;),
                    &quot;Position Replaced&quot; )
))</formula>
    <inlineHelpText>Values:
- Billing
- Open Order
- Position Replaced
- Ignore</inlineHelpText>
    <label>Order Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Update_CS__c.field-meta.xml
<CustomField>
    <fullName>Update_CS__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When ticked, the Contribution Share for this order is looked up.</inlineHelpText>
    <label>Update CS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OrdersWithFullContribution.cls
public class OrdersWithFullContribution implements Database.Batchable<SObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([SELECT Id, 
                                                Calculate_Total_COGS_CHF__c,
                                                Update_CS__c, 
                                                CM_Pct__c 
                                                FROM Billings__c 
                                                WHERE CM_Pct__c = 100
                                                AND Order_Status__c = 'Closed']);
    }

    public void execute(Database.BatchableContext bc, list<Billings__c> Orders){
        list<Billings__c> updateOrders = new list<Billings__c>();
        for(Billings__c order : Orders){
            updateOrders.add(new Billings__c(
                Id = order.Id,
                Calculate_Total_COGS_CHF__c = true
            ));
        }
        if(updateOrders.size() > 0){
            Database.update(updateOrders, false);
        }
    }
    public void finish(Database.BatchableContext bc){}
}