force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/a4a_needs_Update__c.field-meta.xml
<CustomField>
    <fullName>a4a_needs_Update__c</fullName>
    <formula>a4a_Measure_Filter__c &lt;&gt;  a4a_Measure_Filter_Formula__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>a4a needs Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/App4ForecastOrderSynchBatchable.cls
public inherited sharing class App4ForecastOrderSynchBatchable implements Database.Batchable<sObject>
{
    public String query;
  
    public  App4ForecastOrderSynchBatchable()
        
    {
        query = '';
        query = 'Select Id From Billings__c Where a4a_needs_Update__c = True';
    }
    
    public Database.QueryLocator start(
        Database.BatchableContext  BC){

        return  Database.getQueryLocator(query);
            
    }
    
    public void execute(Database.BatchableContext info, List<sObject> scope) 
    {
        Database.SaveResult[] updateResult = Database.update(scope,false);
        
    }   
    
    public void finish(Database.BatchableContext info) {
        
    }
}