force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Salesforce Account. Conneced via field &quot;Customer No&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/End_Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The end customer is the company buying from the Account that buys from us. Typically this is the customer of our distributor or direct CM.</inlineHelpText>
    <label>End Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (End Customer Account)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>Date of invoice (valuta). Relevant for reporting</description>
    <inlineHelpText>(From Abacus) Date of invoice (valuta). Relevant for reporting</inlineHelpText>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <description>This field is used to determine that a shipment has actually been made. In cases of pre-payment, the invoice quantity and invoice date might be set in order to print a pro-forma invoice, but the shipment awaits the payment.</description>
    <inlineHelpText>(From Abacus) Identification number of the invoice sent to customer.</inlineHelpText>
    <label>Invoice Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <formula>Product__r.Packaging_Size__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Packaging Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated with Billing</description>
    <inlineHelpText>Product associated with Billing</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <formula>text(Product__r.Product_Center__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Product Center: copied from product property</inlineHelpText>
    <label>Product Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Link to Account in Salesforce</inlineHelpText>
    <label>Project Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Project Owner Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Qty_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Qty_Invoiced__c</fullName>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Qty Invoiced</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Total_COGS_CHF__c.field-meta.xml
<CustomField>
    <fullName>Total_COGS_CHF__c</fullName>
    <description>In CHF to make sure the cost is captured with the actual exchange rate.</description>
    <inlineHelpText>Calculated based on the product information at the date of invoice. Combination of cost per product and cost as a percentage of the ASP. IPR cost is included.</inlineHelpText>
    <label>Total COGS CHF</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Total_Value_CHF__c.field-meta.xml
<CustomField>
    <fullName>Total_Value_CHF__c</fullName>
    <inlineHelpText>(From Abacus) Billing value in CHF. Imported from Abacus with correct exchange rate</inlineHelpText>
    <label>Total Value CHF</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/USDtoCHF__c.field-meta.xml
<CustomField>
    <fullName>USDtoCHF__c</fullName>
    <inlineHelpText>Exchange rate USD to CHF at the date of invoicing</inlineHelpText>
    <label>USDtoCHF</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F10</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M10</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
                <color>#B6E32E</color>
                <label>u-blox M9</label>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
                <color>#000099</color>
                <label>u-blox M8</label>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
                <color>#0B6FCE</color>
                <label>u-blox 7</label>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
                <color>#33CCFF</color>
                <label>u-blox 6</label>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
                <color>#6600CC</color>
                <label>u-blox 5</label>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
                <color>#CC66CC</color>
                <label>ANTARIS 4</label>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
                <color>#FF99FF</color>
                <label>Various</label>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
                <color>#999999</color>
                <default>true</default>
                <label>Not applicable</label>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Center__c.field-meta.xml
<CustomField>
    <fullName>Product_Center__c</fullName>
    <label>Product Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Short Range</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Tashang</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BillingsTestDataFactory.cls
@isTest
public class BillingsTestDataFactory extends TestDataFactory {
   
    public BillingsTestDataFactory() {
        super('Billings');
    }

    public override sObject initializeRecord(){
        AccountTestDataFactory acc = new AccountTestDataFactory();
        SObject account = acc.createRecord();		
        Product2 product2 = new Product2(Name = 'NEO-M8P', Type_No__c= 'NEO-M8P-2-11', ProductCode= 'NEO-M8P-2', Family = 'ALEX', Positioning_Engine__c = 'Not applicable', Product_Center__c = 'Positioning', Packaging_Size__c = 1000);
        insert product2;
        
        Billings__c billings = new Billings__c();
        billings.Name = 'Test Billings';
        billings.USDtoCHF__c = 5;
        billings.Qty_Invoiced__c = 10;
        billings.Invoice_Number__c = 'abc0123';
        billings.Total_Value_CHF__c = 10;
        billings.Total_COGS_CHF__c = 2;
        billings.Invoice_Date__c = Date.newInstance(2022, 11, 11);
        billings.Product__c = product2.id;
        billings.Account__c = account.id;
        billings.End_Customer_Account__c= account.id;
        billings.Project_Owner_Account__c = account.id;
		
       	return billings;
    }

    public override sObject createRecord() {
        Billings__c a = (Billings__c)initializeRecord();
        Insert a;
        return a;
    }

    public sObject createRecord(sObject record) {
        Insert record;
        return record;
    }

    public override List<sObject> createBulkRecords() {
        for (Integer i = 0; i < numberOfRecords; i++) {
            Billings__c cont = new Billings__c();
            cont.Name = 'Test Billings'+i;
            recordsList.add(cont);
        }
        Insert recordsList;
        return recordsList;
    }

    public Billings__c updateRecords(Billings__c toupdate) {
        update toupdate;
        return toupdate;
    }   
    
}