force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/a4a_Country__c.field-meta.xml
<CustomField>
    <fullName>a4a_Country__c</fullName>
    <formula>BLANKVALUE(a4a_Country_To_Consolidate__c ,BLANKVALUE(UPPER(Project_Owner_Account__r.BillingCountry),&quot;Other&quot;))

/* previous version until 22.4.2021
BLANKVALUE(UPPER(Project_Owner_Account__r.BillingCountry),&quot;Other&quot;)
*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>a4a Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/a4a_Date__c.field-meta.xml
<CustomField>
    <fullName>a4a_Date__c</fullName>
    <formula>IF(Order_Status__c &lt;&gt; &quot;Position Replaced&quot;,
BLANKVALUE(Invoice_Date__c,Delivery_Date__c),
NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>a4a Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/a4a_Product__c.field-meta.xml
<CustomField>
    <fullName>a4a_Product__c</fullName>
    <formula>BLANKVALUE(Product__r.ProductCode,&quot;Other&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>a4a Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/a4a_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>a4a_Product_Category__c</fullName>
    <formula>Product__r.a4x_Product_Category__c


/* previous Version until 14.6.2021

BLANKVALUE(TEXT(Product__r.Reporting_Category__c),&quot;Other&quot;)
*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>a4a Product Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/a4a_Project_Owner__c.field-meta.xml
<CustomField>
    <fullName>a4a_Project_Owner__c</fullName>
    <formula>BLANKVALUE( a4a_Account_To_Consolidate__c , Project_Owner_Account__r.SF_Account_Number__c) 


/* previous version until 28/01/2021
Project_Owner_Account__r.SF_Account_Number__c
*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>a4a Project Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/a4a_Region__c.field-meta.xml
<CustomField>
    <fullName>a4a_Region__c</fullName>
    <formula>BLANKVALUE( a4a_Region_To_Consolidate__c ,BLANKVALUE(TEXT(Project_Owner_Account__r.uB_Office__c),&quot;Other&quot;))

/* previous version until 22.5.2021
BLANKVALUE(TEXT(Project_Owner_Account__r.uB_Office__c),&quot;Other&quot;)
*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>a4a Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderHelper.cls
/**
* @description Helper class for order processing
*/
public inherited sharing class OrderHelper {
    
    /**
    * @description returns the concatenated dimensions String for one Billings Record.
    * @param Billings__c - o
    * @return String - dimensions
    */
    public static String getDimensions(Billings__c o) {
        
        String dimensions = '';
        if(o.a4a_Region__c != null) dimensions += o.a4a_Region__c;
        if(o.a4a_Product_Category__c != null) dimensions += o.a4a_Product_Category__c;
        if(o.a4a_Country__c != null) dimensions += o.a4a_Country__c;
        if(o.a4a_Product__c != null) dimensions += o.a4a_Product__c;
        if(o.a4a_Project_Owner__c != null) dimensions += o.a4a_Project_Owner__c;
        if(o.a4a_Date__c != null) {
            dimensions += o.a4a_Date__c.year();
            dimensions += o.a4a_Date__c.month();
        }
        
        return dimensions;
    } 

}