force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Salesforce Account. Conneced via field &quot;Customer No&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Cost_CHF_Abacus__c.field-meta.xml
<CustomField>
    <fullName>Cost_CHF_Abacus__c</fullName>
    <inlineHelpText>(From Abacus) Cost in CHF</inlineHelpText>
    <label>Cost CHF Abacus</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <inlineHelpText>(From Abacus) Date of delivery. Used to calculate delivery reliability</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/End_Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The end customer is the company buying from the Account that buys from us. Typically this is the customer of our distributor or direct CM.</inlineHelpText>
    <label>End Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (End Customer Account)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>Date of invoice (valuta). Relevant for reporting</description>
    <inlineHelpText>(From Abacus) Date of invoice (valuta). Relevant for reporting</inlineHelpText>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <description>This field is used to determine that a shipment has actually been made. In cases of pre-payment, the invoice quantity and invoice date might be set in order to print a pro-forma invoice, but the shipment awaits the payment.</description>
    <inlineHelpText>(From Abacus) Identification number of the invoice sent to customer.</inlineHelpText>
    <label>Invoice Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <formula>IF ( Product_ID__c = &quot;VIA-CB-C&quot;, &quot;Ignore&quot;,
IF( (Qty_Invoiced__c=0)  &amp;&amp; (Total_Value_CHF__c=0) &amp;&amp; ( Qty_Ordered__c = 0), &quot;Ignore&quot;,
IF(Position_Replaced__c=false,
                    IF( ISNULL(Invoice_Date__c)  ||   Qty_Invoiced__c =0 || ISNULL( Invoice_Number__c ) || Invoice_Number__c =&quot;0&quot;, &quot;Open&quot;, &quot;Closed&quot;),
                    &quot;Position Replaced&quot; )
))</formula>
    <inlineHelpText>Values:
- Billing
- Open Order
- Position Replaced
- Ignore</inlineHelpText>
    <label>Order Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated with Billing</description>
    <inlineHelpText>Product associated with Billing</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Project_Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Link to Account in Salesforce</inlineHelpText>
    <label>Project Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Project Owner Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Qty_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Qty_Invoiced__c</fullName>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Qty Invoiced</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Qty_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Qty_Ordered__c</fullName>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Qty Ordered</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Total_Gross_Value_CHF__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Value_CHF__c</fullName>
    <inlineHelpText>(From Abacus) Total Gross Value in CHF Currency</inlineHelpText>
    <label>Total Gross Value CHF</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Total_Value_CHF__c.field-meta.xml
<CustomField>
    <fullName>Total_Value_CHF__c</fullName>
    <inlineHelpText>(From Abacus) Billing value in CHF. Imported from Abacus with correct exchange rate</inlineHelpText>
    <label>Total Value CHF</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Use_Abacus_Cost__c.field-meta.xml
<CustomField>
    <fullName>Use_Abacus_Cost__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checked, use the cost from Abacus to calculate the contribution.</inlineHelpText>
    <label>Use Abacus Cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/fields/Use_Abacus_Cost__c.field-meta.xml
<CustomField>
    <fullName>Use_Abacus_Cost__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checked, use the cost from Abacus to calculate the contribution.</inlineHelpText>
    <label>Use Abacus Cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OrdersWithFullContributionTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@IsTest
private class OrdersWithFullContributionTest {
    static final string CRON_EXP = '0 0 1 * * ?';
    static final integer BATCH_SIZE = 100;
    static testMethod void TestFullContributionOrders() {
        a4x__app4forecast__c orgDefaults = a4x__app4forecast__c.getOrgDefaults();
        orgDefaults.a4x__Measure_Events_Active__c = True;
        orgDefaults.a4x__Forecast_Periods__c = 21;
        
        Account mainAccount = new Account(
            Name = 'Test main Acount'
        );        
        insert mainAccount;
              
        Account endCustomerAccount = new Account(
            Name = 'Test End Customer Account'
        );       
        insert endCustomerAccount;
                       
        Account projectOwnerAccount = new Account(
            Name = 'Test Project Owner Account'
        );       
        insert projectOwnerAccount;
                        
        Product2 prod011 = new Product2();
        prod011.Name = 'TEST-P001';
        prod011.ProductCode = 'TEST-P001-0';
        prod011.Type_No__c = 'TEST-P001-0-01';
        prod011.Use_Abacus_Cost__c = true;
        insert prod011;
        
        Product2 prod012 = new Product2();
        prod012.Name = 'TEST-P001';
        prod012.ProductCode = 'TEST-P001-0';
        prod012.Type_No__c = 'TEST-P001-0-02';
        insert prod012;
        
        // Insert
        Billings__c o = new Billings__c();
        o.Account__c = mainAccount.Id;
        o.End_Customer_Account__c = endCustomerAccount.Id;
        o.Project_Owner_Account__c = projectOwnerAccount.Id;
        o.Product__c = prod011.Id;      
        o.Delivery_Date__c = Date.today().addMonths(+2);
        o.Qty_Ordered__c = 100;
        o.Total_Value_CHF__c = 1000;
        o.Total_Gross_Value_CHF__c = 1000;
        
        insert o;
        list<Billings__c> orderStatusOpen = [SELECT Order_Status__c from Billings__c where Id =: o.Id];
        system.assert(orderStatusOpen.size() > 0);
        system.assertEquals('Open', orderStatusOpen[0].Order_Status__c);
        
        o.Qty_Invoiced__c = 100; 
        o.Invoice_Date__c = Date.today().addMonths(+1);
        o.Invoice_Number__c = 'ubx-003';
        o.Cost_CHF_Abacus__c = 5.50;
        update o;
        
        list<Billings__c> orderStatusClosed = [SELECT Order_Status__c from Billings__c where Id =: o.Id];
        system.assert(orderStatusClosed.size() > 0);
        system.assertEquals('Closed', orderStatusClosed[0].Order_Status__c);

        OrdersWithFullContribution fullContributionOrders = new OrdersWithFullContribution(); 
        database.executebatch(fullContributionOrders,BATCH_SIZE);

        CronJobDetail Job;
        try{
            Job = [Select c.Name, c.Id From CronJobDetail c where Name = 'Orders with 100% Contribution' limit 1];         
        }catch(QueryException ex){}
                        
        
        if(Job != null){
            CronTrigger CTrigger  = [SELECT Id FROM CronTrigger WHERE CronJobDetailId = :Job.Id];           
            if(CTrigger != null){
                System.abortJob(CTrigger.Id);   
            }
        }
        
        String jobId = system.schedule('Orders with 100% Contribution', CRON_EXP , new ScheduleOrdersWithFullContribution());
     
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(CRON_EXP, ct.CronExpression);        
    }
}