force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Salesforce Account. Conneced via field &quot;Customer No&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Calculate_Contribution_Split__c.field-meta.xml
<CustomField>
    <fullName>Calculate_Contribution_Split__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checkbox is set, (re-)calculate the split of the contribution to uB Offices</inlineHelpText>
    <label>Calculate Contribution Split</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Calculate_Total_COGS_CHF__c.field-meta.xml
<CustomField>
    <fullName>Calculate_Total_COGS_CHF__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Set the flag to (re-)calculate the COGS and split of the contribution.</inlineHelpText>
    <label>Calculate Total COGS CHF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Customer_Part_Number_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Part_Number_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for Customer Part Number record.</description>
    <inlineHelpText>Lookup field for Customer Part Number record.</inlineHelpText>
    <label>Customer Part Number ID</label>
    <referenceTo>Customer_Part_Number__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <formula>IF ( Product_ID__c = &quot;VIA-CB-C&quot;, &quot;Ignore&quot;,
IF( (Qty_Invoiced__c=0)  &amp;&amp; (Total_Value_CHF__c=0) &amp;&amp; ( Qty_Ordered__c = 0), &quot;Ignore&quot;,
IF(Position_Replaced__c=false,
                    IF( ISNULL(Invoice_Date__c)  ||   Qty_Invoiced__c =0 || ISNULL( Invoice_Number__c ) || Invoice_Number__c =&quot;0&quot;, &quot;Open&quot;, &quot;Closed&quot;),
                    &quot;Position Replaced&quot; )
))</formula>
    <inlineHelpText>Values:
- Billing
- Open Order
- Position Replaced
- Ignore</inlineHelpText>
    <label>Order Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated with Billing</description>
    <inlineHelpText>Product associated with Billing</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Update_CS__c.field-meta.xml
<CustomField>
    <fullName>Update_CS__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When ticked, the Contribution Share for this order is looked up.</inlineHelpText>
    <label>Update CS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderTriggerHandler.cls
/****
Process 1 : update Order with matching Customer Part Number
Process 2 : update Order with matching contribution share

***/
public Class OrderTriggerHandler implements ITrigger
{
    //process 1 data : Update Order with Customer Part Number
    list<String> oProductIds = new list<String>();
    list<String> oAccountIds = new list<String>();
    
    //process 2 data : Update Order with Contribution Share
    Set<Id> accounts = new Set<Id>();
    
    // Prepare the data for catering to--- Before Trigger events
    public void prepareBefore(){
        list<Billings__c> newOrderLst = (list<Billings__c>)Trigger.New;
        map<Id, Billings__c> oldOrders = (map<Id, Billings__c>)Trigger.oldMap;
        if(!Trigger.isDelete){
            for(Billings__c tempOrder : newOrderLst){
                if(Trigger.isUpdate){
                    Billings__c OldOrder = oldOrders.get(tempOrder.Id);
                    
                    //process to update CPN
                    if (tempOrder.Customer_Part_Number_ID__c == null 
                        || OldOrder.Account__c != tempOrder.Account__c 
                        || OldOrder.Product__c != tempOrder.Product__c){
                            
                            oProductIds.add(tempOrder.product__c);
                            oAccountIds.add(tempOrder.account__c);                   
                        }
                    
                    //process to update order with match contribution share
                    
                    if ( (tempOrder.Order_Status__c == 'Closed' 
                        && OldOrder.Order_Status__c != tempOrder.Order_Status__c) 
                            || tempOrder.Update_CS__c 
                            || tempOrder.Calculate_Total_COGS_CHF__c
                           ){
                               // Add related account id to set
                               accounts.add(tempOrder.Account__c);                    
                               // Reset update CS flag
                               //tempOrder.Update_CS__c = false; This check moved to Order : After Record Crete/Update Process Flow
                               // Set flag to calculate contribution split
                               //order.Calculate_Contribution_Split__c = true;
                           }                
                    
                }else if(Trigger.isInsert){
                    oProductIds.add(tempOrder.product__c);
                    oAccountIds.add(tempOrder.account__c);
                    
                    if(tempOrder.Order_Status__c == 'Closed' || tempOrder.Update_CS__c || tempOrder.Calculate_Total_COGS_CHF__c){
                        // Add related account id to set
                        accounts.add(tempOrder.Account__c);                    
                        // Reset update CS flag
                        //tempOrder.Update_CS__c = false; This check moved to Order : After Record Crete/Update Process Flow
                        // Set flag to calculate contribution split
                        //order.Calculate_Contribution_Split__c = true;
                    }
                }    
            }
        }
    }
    
    // Prepare the data for catering to After Trigger events 
    public void prepareAfter(){
    }
    
    // Process logic/functioanlities in other classes for before Insert event  
    public void beforeInsert(){        
        // disabled by Khurram 3/3/22 moved the CPN assignment to Order Interface Mapping
        //orderObjectHelper.setCPN((list<Billings__c>)Trigger.new, oAccountIds, oProductIds);
        // Update Order with Contribution Share by maching the 
        // Order Project Owner Account, End Customer Account and Product
        // with similar fields of Contribution Share 
        // Order Account and Contribution Share Account must be same
        if(accounts.size()>0){
            orderObjectHelper.updateCS((list<Billings__c>)Trigger.new, accounts);
        }
    }
    
    // Process logic/functioanlities in other classes for before Update  event
    public void beforeUpdate(){
        // disabled by Khurram 3/3/22 moved the CPN assignment to Order Interface Mapping
        //orderObjectHelper.setCPN((list<Billings__c>)Trigger.new,oAccountIds, oProductIds);
        if(accounts.size()>0){
            orderObjectHelper.updateCS((list<Billings__c>)Trigger.new, accounts);
        }
    }
    
    // Process logic/functioanlities in other classes for before Delete event
    public void beforeDelete(){}
    
    // Process logic/functioanlities in other classes for after Update  event
    public void afterInsert(){
        //   AccountObjectHelper.updateOwnerEmailFields(Trigger.New,accIdUserIds);        
    }
    
    // Process logic/functioanlities in other classes for after Update  event 
    public void afterUpdate(){}
    
    // Process logic/functioanlities in other classes for after Delete  event
    public void afterDelete(){} 
    
    //Finally do operations to Commit 
    public void finish(){}
}