force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Order information from Abacus. Each record represents an order position.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Salesforce Account. Conneced via field &quot;Customer No&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Customer_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Part_Number__c</fullName>
    <description>This field will populate from the object Customer_Part_Number__c with the value of its field Customer_Part_Number__c. Whenever a new Customer_Part_Number__c generated in the object Customer_Part_Number__c.</description>
    <label>Customer Part Number String</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated with Billing</description>
    <inlineHelpText>Product associated with Billing</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <description>Product identification</description>
    <inlineHelpText>(From Abacus) Product identification. Used to match with field &quot;Type No&quot; in Salesforce products.</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Part_Number__c/Customer_Part_Number__c.object-meta.xml
<CustomObject>
    <description>makes a link between u-blox part number, Account Name and the Customer&apos;s Part Number</description>
    <label>Customer Part Number</label>
    <nameField>
        <label>Customer Part Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Part Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Part_Number__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Linked to Account based on Abacus Customer Number</description>
    <inlineHelpText>(From Abacus) Related Account based on Abacus Customer Number</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Part Numbers</relationshipLabel>
    <relationshipName>Customer_Part_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Part_Number__c/fields/Customer_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Part_Number__c</fullName>
    <description>This is the P/N in the customers system</description>
    <inlineHelpText>(From Abacus) This is the P/N in the customers system</inlineHelpText>
    <label>Customer Part Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Part_Number__c/fields/Type_No_c__c.field-meta.xml
<CustomField>
    <fullName>Type_No_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked to Product based on Type Number</description>
    <inlineHelpText>(From Abacus) Related Product based on Type Number</inlineHelpText>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Customer Part Numbers</relationshipLabel>
    <relationshipName>Customer_Part_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Part_Number__c/fields/Type_Number_field_update__c.field-meta.xml
<CustomField>
    <fullName>Type_Number_field_update__c</fullName>
    <inlineHelpText>(From Abacus)</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/PopCustomerPartNumberOnOrderTest.cls
@isTest
private class PopCustomerPartNumberOnOrderTest {
	
	@isTest static void popCustomerPartNumberOnOrderTest() {

		Map<Id, Billings__c> billingIdsMap = new Map<Id, Billings__c>();

		Account acc = new Account(Name = 'Test Account');
		insert acc;

		Billings__c obillings = new Billings__c(Name = 'Test Order', Account__c = acc.Id, CurrencyIsoCode = 'EUR');
		insert obillings;

		Customer_Part_Number__c cpn = new Customer_Part_Number__c(Name = 'cpn1', Account_Name__c = acc.Id, Customer_Part_Number__c = '12345');
		insert cpn;



		List<Id> billingIds = new List<Id>();
		billingIds.add(obillings.Id);
		
		List<Billings__c> billingIdsToSave = new List<Billings__c>();

		Billings__c bux = billingIdsMap.get(billingIds.get(0));
		//billingIdsToSave.add(bux);

		List<Billings__c> billings = new List<Billings__c>([SELECT Id, Account__c, Product__c, Product_ID__c, Customer_Part_Number__c FROM Billings__c WHERE Id =: billingIds]);
		

		//List<Customer_Part_Number__c> cpns = new List<Customer_Part_Number__c>([SELECT Id, Customer_Part_Number__c FROM Customer_Part_Number__c WHERE Id =: cpn.Id]);

		for(Billings__c b : billings){


			if(b.Product_ID__c == cpn.Type_Number_field_update__c && b.Account__c == cpn.Account_Name__c && b.Product__c == cpn.Type_No_c__c && b.Customer_Part_Number__c==null){
				b.Customer_Part_Number__c = '12345';
				billingIdsToSave.add(b);
			}
		}

		update billingIdsToSave;
		
	}
	
	
	
}