force-app/main/default/objects/CAU_Email_Subscription__c/CAU_Email_Subscription__c.object-meta.xml
<CustomObject>
    <description>This object is specifically created to handle the email subscription of the Community Unregistered Users.
It will keep only the following fields and it may subject to change if we update the subscription options in its parent(Contact) object.

On update there is a trigger that update subscription options in Contact object: 

HasOptedOutOfEmail,
PCN_Modules_Services__c,
Service_Item_3__c,
Event_email__c,
Webinar_email__c,
Press_Releases__c,
Email_uCenter__c,
Email_Blog__c,
Email_Event_Attendance__c,
Email_Magazine__c,</description>
    <label>CAU Email Subscription</label>
    <nameField>
        <label>CAU Email Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CAU Email Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Customer_email__c.field-meta.xml
<CustomField>
    <fullName>Customer_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Blog__c.field-meta.xml
<CustomField>
    <fullName>Email_Blog__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Event_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Email_Event_Attendance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Event Attendance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Magazine__c.field-meta.xml
<CustomField>
    <fullName>Email_Magazine__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Magazine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_uCenter__c.field-meta.xml
<CustomField>
    <fullName>Email_uCenter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>uCenter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Event_email__c.field-meta.xml
<CustomField>
    <fullName>Event_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Event email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Webinar_email__c.field-meta.xml
<CustomField>
    <fullName>Webinar_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Webinar email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Blog__c.field-meta.xml
<CustomField>
    <fullName>Email_Blog__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Blog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Event_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Email_Event_Attendance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Event Attendance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Magazine__c.field-meta.xml
<CustomField>
    <fullName>Email_Magazine__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Magazine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_uCenter__c.field-meta.xml
<CustomField>
    <fullName>Email_uCenter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>uCenter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Event_email__c.field-meta.xml
<CustomField>
    <fullName>Event_email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Receives &quot;Event email&quot; (Email Type in Campaign) by mass mail</inlineHelpText>
    <label>Event email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Service_Item_3__c.field-meta.xml
<CustomField>
    <fullName>Service_Item_3__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Receives &quot;Customer email&quot; (Email Type in Campaign) by mass mail</inlineHelpText>
    <label>Customer email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Webinar_email__c.field-meta.xml
<CustomField>
    <fullName>Webinar_email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Receives &quot;Webinar email&quot; (Email Type in Campaign) by mass mail</inlineHelpText>
    <label>Webinar email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EmailSubscriptionObjectHelper.cls
public class EmailSubscriptionObjectHelper {
    
    //setting the contact subscriptions same as email subscription
    public static List<contact> updateContactSubscriptions( map<String,CAU_Email_Subscription__c> EmailEmailSubcriptionMap ){
        List<contact> contactsToUpdate = new List<Contact>();
        
        if(EmailEmailSubcriptionMap.size() > 0){
            
            Map<String, List<Contact>> EmailcontactMap = new Map<String, List<Contact>>();
            for(Contact tempCont : [SELECT Id ,Email,event_Email__c, HasOptedOutOfEmail FROM Contact WHERE Email = : EmailEmailSubcriptionMap.keySet()]){
                
                if(EmailcontactMap.get(tempCont.email) == null){
                    EmailcontactMap.put(tempCont.email,new list<Contact>{});
                    EmailcontactMap.get(tempCont.email).add(tempCont);
                }else EmailcontactMap.get(tempCont.email).add(tempCont);
                
            }
            
            for(String subscriptionEmailTemp : EmailEmailSubcriptionMap.keySet()){
                
                for(Contact tempContact  : EmailcontactMap.get(subscriptionEmailTemp)){
                    
                    if(EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Customer_email__c 
                        || EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Webinar_email__c
                        || EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Email_uCenter__c 
                        || EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Email_Blog__c
                        || EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Email_Magazine__c 
                        || EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Event_email__c
                        || EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Email_Event_Attendance__c){
                           
                           tempContact.HasOptedOutOfEmail = false;                           
                    }
                    tempContact.Service_Item_3__c =  EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Customer_email__c ;
                    tempContact.Webinar_email__c =  EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Webinar_email__c ;
                    tempContact.Event_email__c =  EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Event_email__c ;
                    tempContact.Email_uCenter__c =  EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Email_uCenter__c ;
                    tempContact.Email_Blog__c =  EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Email_Blog__c ;
                    tempContact.Email_Event_Attendance__c =  EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Email_Event_Attendance__c ;
                    tempContact.Email_Magazine__c =  EmailEmailSubcriptionMap.get(subscriptionEmailTemp).Email_Magazine__c ;
                    
                    contactsToUpdate.add(tempContact);
                }
            }
        }
        return contactsToUpdate;
    }
}