force-app/main/default/objects/CAU_Email_Subscription__c/CAU_Email_Subscription__c.object-meta.xml
<CustomObject>
    <description>This object is specifically created to handle the email subscription of the Community Unregistered Users.
It will keep only the following fields and it may subject to change if we update the subscription options in its parent(Contact) object.

On update there is a trigger that update subscription options in Contact object: 

HasOptedOutOfEmail,
PCN_Modules_Services__c,
Service_Item_3__c,
Event_email__c,
Webinar_email__c,
Press_Releases__c,
Email_uCenter__c,
Email_Blog__c,
Email_Event_Attendance__c,
Email_Magazine__c,</description>
    <label>CAU Email Subscription</label>
    <nameField>
        <label>CAU Email Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CAU Email Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Blog__c.field-meta.xml
<CustomField>
    <fullName>Email_Blog__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Magazine__c.field-meta.xml
<CustomField>
    <fullName>Email_Magazine__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Magazine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Blog__c.field-meta.xml
<CustomField>
    <fullName>Email_Blog__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Blog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Magazine__c.field-meta.xml
<CustomField>
    <fullName>Email_Magazine__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Magazine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EmailSubscriptionTest.cls
/**
 * Created by ldra on 2018-02-26
 */

@IsTest
public class EmailSubscriptionTest {
    
	@testSetup static void setup() {
        Account a = new Account(Name='Test Account Name');
        insert a;
        
        Contact c = new Contact(LastName='TestUserr', Email='test@u-blox.com.dev', AccountId=a.Id);
        insert c; 
        
    }
    
    @isTest static void unsubscriptionTest() {
        // add record to subscription 
        CAU_Email_Subscription__c s = new CAU_Email_Subscription__c(Name='test@u-blox.com.dev', Email__c='test@u-blox.com.dev', Email_Blog__c=true, Email_Magazine__c=true );
        insert s; 
        //System.debug(s.Email__c+s.Email_Blog__c);
        
        Contact c2 =  [Select Id, Email, Email_Blog__c, Email_Magazine__c from Contact where Email='test@u-blox.com.dev' limit 1];
		//System.debug(c2.Email+c2.Email_Blog__c);

        System.assertEquals(s.Email_Blog__c, c2.Email_Blog__c);
    }
}