force-app/main/default/objects/CAU_Email_Subscription__c/CAU_Email_Subscription__c.object-meta.xml
<CustomObject>
    <description>This object is specifically created to handle the email subscription of the Community Unregistered Users.
It will keep only the following fields and it may subject to change if we update the subscription options in its parent(Contact) object.

On update there is a trigger that update subscription options in Contact object: 

HasOptedOutOfEmail,
PCN_Modules_Services__c,
Service_Item_3__c,
Event_email__c,
Webinar_email__c,
Press_Releases__c,
Email_uCenter__c,
Email_Blog__c,
Email_Event_Attendance__c,
Email_Magazine__c,</description>
    <label>CAU Email Subscription</label>
    <nameField>
        <label>CAU Email Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CAU Email Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Customer_email__c.field-meta.xml
<CustomField>
    <fullName>Customer_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Blog__c.field-meta.xml
<CustomField>
    <fullName>Email_Blog__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Event_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Email_Event_Attendance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Event Attendance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Magazine__c.field-meta.xml
<CustomField>
    <fullName>Email_Magazine__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Magazine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_uCenter__c.field-meta.xml
<CustomField>
    <fullName>Email_uCenter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>uCenter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Event_email__c.field-meta.xml
<CustomField>
    <fullName>Event_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Event email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Webinar_email__c.field-meta.xml
<CustomField>
    <fullName>Webinar_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Webinar email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Blog__c.field-meta.xml
<CustomField>
    <fullName>Email_Blog__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Blog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Event_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Email_Event_Attendance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Event Attendance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Magazine__c.field-meta.xml
<CustomField>
    <fullName>Email_Magazine__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Magazine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_uCenter__c.field-meta.xml
<CustomField>
    <fullName>Email_uCenter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>uCenter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Event_email__c.field-meta.xml
<CustomField>
    <fullName>Event_email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Receives &quot;Event email&quot; (Email Type in Campaign) by mass mail</inlineHelpText>
    <label>Event email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Service_Item_3__c.field-meta.xml
<CustomField>
    <fullName>Service_Item_3__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Receives &quot;Customer email&quot; (Email Type in Campaign) by mass mail</inlineHelpText>
    <label>Customer email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Webinar_email__c.field-meta.xml
<CustomField>
    <fullName>Webinar_email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Receives &quot;Webinar email&quot; (Email Type in Campaign) by mass mail</inlineHelpText>
    <label>Webinar email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EmailSubscription.cls
public class EmailSubscription{ 
    
    public static void updateContactSubscriptions(List<CAU_Email_Subscription__c> subscriptions)
    {

        for (CAU_Email_Subscription__c s : subscriptions)
        {
            System.debug(s);
                List<Contact> listToUpdate = new List<Contact>();
            
                for(Contact c : [select Id, Email, HasOptedOutOfEmail From Contact where Email =: s.Email__c]) {
    
                    if(
                        s.Customer_email__c==true || 
                        s.Webinar_email__c==true || 
                        s.Event_email__c==true || 
                        s.Email_uCenter__c==true || 
                        s.Email_Blog__c==true || 
                        s.Email_Event_Attendance__c==true || 
                        s.Email_Magazine__c==true
                    ) {
                        c.HasOptedOutOfEmail = false; 
                    }
                    
                    c.Service_Item_3__c = s.Customer_email__c;
                    c.Webinar_email__c = s.Webinar_email__c;
                    c.Event_email__c = s.Event_email__c;
                    c.Email_uCenter__c = s.Email_uCenter__c;
                    c.Email_Blog__c = s.Email_Blog__c;
                    c.Email_Event_Attendance__c = s.Email_Event_Attendance__c;
                    c.Email_Magazine__c = s.Email_Magazine__c;
                    
                    listToUpdate.add(c);
               }
               if(!listToUpdate.isEmpty()) update listToUpdate;
        }
    }
    
    public static void removeSubscriptions(List<CAU_Email_Subscription__c> subscriptions)
    {
               if(!subscriptions.isEmpty()) delete subscriptions;
    }
}