force-app/main/default/objects/CAU_Email_Subscription__c/CAU_Email_Subscription__c.object-meta.xml
<CustomObject>
    <description>This object is specifically created to handle the email subscription of the Community Unregistered Users.
It will keep only the following fields and it may subject to change if we update the subscription options in its parent(Contact) object.

On update there is a trigger that update subscription options in Contact object: 

HasOptedOutOfEmail,
PCN_Modules_Services__c,
Service_Item_3__c,
Event_email__c,
Webinar_email__c,
Press_Releases__c,
Email_uCenter__c,
Email_Blog__c,
Email_Event_Attendance__c,
Email_Magazine__c,</description>
    <label>CAU Email Subscription</label>
    <nameField>
        <label>CAU Email Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CAU Email Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Customer_email__c.field-meta.xml
<CustomField>
    <fullName>Customer_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Blog__c.field-meta.xml
<CustomField>
    <fullName>Email_Blog__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Event_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Email_Event_Attendance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Event Attendance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Magazine__c.field-meta.xml
<CustomField>
    <fullName>Email_Magazine__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Magazine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_uCenter__c.field-meta.xml
<CustomField>
    <fullName>Email_uCenter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>uCenter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Event_email__c.field-meta.xml
<CustomField>
    <fullName>Event_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Event email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Webinar_email__c.field-meta.xml
<CustomField>
    <fullName>Webinar_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Webinar email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Blog__c.field-meta.xml
<CustomField>
    <fullName>Email_Blog__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Blog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Event_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Email_Event_Attendance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Event Attendance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Magazine__c.field-meta.xml
<CustomField>
    <fullName>Email_Magazine__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Magazine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_uCenter__c.field-meta.xml
<CustomField>
    <fullName>Email_uCenter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>uCenter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Event_email__c.field-meta.xml
<CustomField>
    <fullName>Event_email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Receives &quot;Event email&quot; (Email Type in Campaign) by mass mail</inlineHelpText>
    <label>Event email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Webinar_email__c.field-meta.xml
<CustomField>
    <fullName>Webinar_email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Receives &quot;Webinar email&quot; (Email Type in Campaign) by mass mail</inlineHelpText>
    <label>Webinar email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EmailSubscriptionTriggerHandler.cls
/*
* Title: EmailSubscriptionTriggerHandler
* Description: Class that updates 
*/

public without sharing class EmailSubscriptionTriggerHandler implements ITrigger {
    
    //process 1
    
    map<String,CAU_Email_Subscription__c> EmailEmailSubcriptionMap = new Map<String,CAU_Email_Subscription__c>();
    List<Contact> contList = new List<contact>();
    
    // Prepare the data for catering to Before Trigger events
    public void prepareBefore(){
        //Process 1
    }
    // Prepare the data for catering to After Trigger events 
    public void prepareAfter(){
        List<CAU_Email_Subscription__c> EmailSubscriptionList = (list<CAU_Email_Subscription__c>)Trigger.New;
        //Process 1
        if(Trigger.isInsert || Trigger.isUpdate){
            for(CAU_Email_Subscription__c tempEmailSubscription: EmailSubscriptionList){
                if(Trigger.isUpdate){
                   CAU_Email_Subscription__c EmailSubscriptionOld = (CAU_Email_Subscription__c)Trigger.oldMap.get(tempEmailSubscription.Id);
                   
                    if(EmailSubscriptionOld.Email__c != tempEmailSubscription.Email__c 
                        || EmailSubscriptionOld.Customer_email__c != tempEmailSubscription.Customer_email__c
                        || EmailSubscriptionOld.Webinar_email__c != tempEmailSubscription.Webinar_email__c 
                        || EmailSubscriptionOld.Event_email__c != tempEmailSubscription.Event_email__c
                        || EmailSubscriptionOld.Email_Blog__c != tempEmailSubscription.Email_Blog__c 
                        || EmailSubscriptionOld.Email_uCenter__c != tempEmailSubscription.Email_uCenter__c
                        || EmailSubscriptionOld.Email_Magazine__c != tempEmailSubscription.Email_Magazine__c 
                        || EmailSubscriptionOld.Email_Event_Attendance__c != tempEmailSubscription.Email_Event_Attendance__c){
                          
                        EmailEmailSubcriptionMap.put(tempEmailSubscription.Email__c,tempEmailSubscription);
                    }
                }else{
                    EmailEmailSubcriptionMap.put(tempEmailSubscription.Email__c,tempEmailSubscription);
                }
            }
        }
    }
    // Process logic/functioanlities in other classes for before Insert event  
    public void beforeInsert(){
    }
    // Process logic/functioanlities in other classes for before Update  event
    public void beforeUpdate(){
    }
    // Process logic/functioanlities in other classes for before Delete event
    public void beforeDelete(){
    }
    // Process logic/functioanlities in other classes for after Update  event
    public void afterInsert(){
        //Process 1 Logic : calling Helper to
        contList = EmailSubscriptionObjectHelper.updateContactSubscriptions(EmailEmailSubcriptionMap);
    }
    // Process logic/functioanlities in other classes for after Update  event 
    public void afterUpdate(){
        contList = EmailSubscriptionObjectHelper.updateContactSubscriptions(EmailEmailSubcriptionMap);
    }
    // Process logic/functioanlities in other classes for after Delete  event
    public void afterDelete(){
        //Process 2 Logic : calling Helper to get opps having Has_PDF_Attachments__c as false
    } 
    //Finally do operations to Commit 
    public void finish(){
        //Process 1 Result Commit
        update contList;
    }
}