force-app/main/default/objects/CAU_Email_Subscription__c/CAU_Email_Subscription__c.object-meta.xml
<CustomObject>
    <description>This object is specifically created to handle the email subscription of the Community Unregistered Users.
It will keep only the following fields and it may subject to change if we update the subscription options in its parent(Contact) object.

On update there is a trigger that update subscription options in Contact object: 

HasOptedOutOfEmail,
PCN_Modules_Services__c,
Service_Item_3__c,
Event_email__c,
Webinar_email__c,
Press_Releases__c,
Email_uCenter__c,
Email_Blog__c,
Email_Event_Attendance__c,
Email_Magazine__c,</description>
    <label>CAU Email Subscription</label>
    <nameField>
        <label>CAU Email Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CAU Email Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Customer_email__c.field-meta.xml
<CustomField>
    <fullName>Customer_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Blog__c.field-meta.xml
<CustomField>
    <fullName>Email_Blog__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Event_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Email_Event_Attendance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Event Attendance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_Magazine__c.field-meta.xml
<CustomField>
    <fullName>Email_Magazine__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Magazine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Email_uCenter__c.field-meta.xml
<CustomField>
    <fullName>Email_uCenter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>uCenter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Event_email__c.field-meta.xml
<CustomField>
    <fullName>Event_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Event email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAU_Email_Subscription__c/fields/Webinar_email__c.field-meta.xml
<CustomField>
    <fullName>Webinar_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Webinar email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Blog__c.field-meta.xml
<CustomField>
    <fullName>Email_Blog__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Blog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Event_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Email_Event_Attendance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Event Attendance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Magazine__c.field-meta.xml
<CustomField>
    <fullName>Email_Magazine__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>Magazine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_uCenter__c.field-meta.xml
<CustomField>
    <fullName>Email_uCenter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated through u-blox Portal</description>
    <inlineHelpText>Updated through u-blox Portal</inlineHelpText>
    <label>uCenter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Event_email__c.field-meta.xml
<CustomField>
    <fullName>Event_email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Receives &quot;Event email&quot; (Email Type in Campaign) by mass mail</inlineHelpText>
    <label>Event email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Webinar_email__c.field-meta.xml
<CustomField>
    <fullName>Webinar_email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Receives &quot;Webinar email&quot; (Email Type in Campaign) by mass mail</inlineHelpText>
    <label>Webinar email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SubscriptionManagementUnregistered.cls
/*
 * Title: Subscription Unregistered
 * Author:  wsha, ldra
 * Created:  2018-10
 * 
 * Class for "Subscription Unregistered" page in the Community portal. It redirects registered user to the login page. If contact exists in SF it shows unsubscription form.
 * After updating subscription options script stores data in CAU_Email_Subscription__c. Then trigger (EmailSubscription) updates fields in Contact object instantly.
 */

public with sharing class SubscriptionManagementUnregistered {
    
    @AuraEnabled
    public static Contact getContactSubscriptions(String email, String last, String id){
        Contact c = new Contact();
        if(UserInfo.getUserType() == 'Guest') {
            // check if user exists
            // User[] u = [SELECT Id, ContactId, Email FROM User WHERE Email =: email AND FirstName =: first AND LastName =: last LIMIT 1];
            //
            User[] u = [SELECT Id, ContactId, Email FROM User WHERE Email =: email AND IsActive = true AND Profile.Name != 'Community Registered User' LIMIT 1];
            if(u.size()==0) {
                // check if contact exists
                Map<String, Object> params = new Map<String, Object>();
                params.put('contactEmail', email);
                params.put('contactLast', last);
                params.put('contactId', id);
                Flow.Interview.Read_Contact_Subscriptions ReadContactSubscriptions = new Flow.Interview.Read_Contact_Subscriptions(params);
                ReadContactSubscriptions.start();
                Object flowResult = ReadContactSubscriptions.getVariableValue('getContactSubscriptions');
                c = (Contact)flowResult;
            }
            
        }

        return c;
    }
    
    @AuraEnabled
    public static Boolean setUserSubscriptions(String subscriptions ){
        Boolean isUpdated = false;

        String[] params = new List<String>();
        if(String.isNotBlank(subscriptions)) {
            for(String eachStr : subscriptions.split(',')) {
                params.add(eachStr);
            }
        }
        return isUpdated;
    }


    @AuraEnabled
    public static Boolean setContactSubscriptions(String email, Boolean ServiceItem, Boolean EventEmail, Boolean Webinar, Boolean uCenter, Boolean Blog, Boolean EventAttendance, Boolean Magazine){
        CAU_Email_Subscription__c c = new CAU_Email_Subscription__c();
        c.Name = email;
        c.Email__c = email;
        c.Customer_email__c = ServiceItem;
        c.Event_email__c = EventEmail;
        c.Webinar_email__c = Webinar;
        
        c.Email_uCenter__c = uCenter;
        c.Email_Blog__c = Blog;
        c.Email_Event_Attendance__c = EventAttendance;
        c.Email_Magazine__c = Magazine;
        
        insert c;
        return true;        
    }
    
}