force-app/main/default/objects/Special_Price_Request__c/Special_Price_Request__c.object-meta.xml
<CustomObject>
    <description>Request for TPD, MSP, PPP that needs approvals</description>
    <label>Special Price Request</label>
    <nameField>
        <displayFormat>SPR-{000000}</displayFormat>
        <label>Special Price Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Price_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Opportunity Account if there is Opportunity</description>
    <inlineHelpText>Opportunity Account if there is Opportunity</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Special Price Requests</relationshipLabel>
    <relationshipName>Project_Price_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Approved_By_Regional_Head__c.field-meta.xml
<CustomField>
    <fullName>Approved_By_Regional_Head__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved By Regional Head</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Approved_By_Team_Leader__c.field-meta.xml
<CustomField>
    <fullName>Approved_By_Team_Leader__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved By Team Leader</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Approved_By_Team_Manager__c.field-meta.xml
<CustomField>
    <fullName>Approved_By_Team_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved By Team Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Comment_by_Requestor__c.field-meta.xml
<CustomField>
    <fullName>Comment_by_Requestor__c</fullName>
    <label>Comment by Requestor</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Price_Level__c.field-meta.xml
<CustomField>
    <fullName>Price_Level__c</fullName>
    <description>Price level
RSP: Price = RSP
TPD: RSP &gt; Price &gt;= TPD
MSP: TPD &gt; Price &gt;= MSP
PPP: MSP &gt; Price</description>
    <inlineHelpText>Price level
RSP: Price = RSP
TPD: RSP &gt; Price &gt;= TPD
MSP: TPD &gt; Price &gt;= MSP
PPP: MSP &gt; Price
NOTE: No Approval Process required for TPD</inlineHelpText>
    <label>Price Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PPP (Project Price Plan)</fullName>
            </value>
            <value>
                <fullName>MSP (Minimum Sales Price)</fullName>
            </value>
            <value>
                <fullName>TPD (Transfer Price for Distributor)</fullName>
            </value>
            <value>
                <fullName>RSP (Recommended Sales Price)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Approved: Only when the final approval has been made.
Rejected: Any time the request has been rejected.</description>
    <inlineHelpText>Approved: Only when the final approval has been made.
Rejected: Any time the request has been rejected.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPRTestDataFactory.cls
@IsTest
public class SPRTestDataFactory extends TestDataFactory{

	public override sObject initializeRecord(){
        
		AccountTestDataFactory accountFactory = new AccountTestDataFactory();
        Account acc = (Account)accountFactory.createRecord();
        
        Special_Price_Request__c sprObj = new Special_Price_Request__c();
        sprObj.Account__c = acc.Id;
        sprObj.Status__c = 'Approved';
        sprObj.Price_Level__c = 'PPP (Project Price Plan)';
        sprObj.Approved_By_Team_Leader__c = false;
        sprObj.Approved_By_Team_Manager__c = false;
        sprObj.Approved_By_Regional_Head__c = true;
        sprObj.Comment_by_Requestor__c = 'Comment by Requestor...';
        
        return sprObj;
        
    }
    public override sObject createRecord() {
		Special_Price_Request__c sprObj = (Special_Price_Request__c)initializeRecord();
        insert sprObj;
        return sprObj;
        
    }
    public override List<sObject> createBulkRecords() {
        for (Integer i = 0; i < numberofRecords; i++) {
            recordsList.add((Special_Price_Request__c)initializeRecord());
        }
        Insert recordsList;
        return recordsList;
        
    }

}