force-app/main/default/objects/Special_Price_Request__c/Special_Price_Request__c.object-meta.xml
<CustomObject>
    <description>Request for TPD, MSP, PPP that needs approvals</description>
    <label>Special Price Request</label>
    <nameField>
        <displayFormat>SPR-{000000}</displayFormat>
        <label>Special Price Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Price_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Opportunity Account if there is Opportunity</description>
    <inlineHelpText>Opportunity Account if there is Opportunity</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Special Price Requests</relationshipLabel>
    <relationshipName>Project_Price_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request_Product__c/Special_Price_Request_Product__c.object-meta.xml
<CustomObject>
    <description>Product price plans for Special Price Request</description>
    <label>Special Price Request Product</label>
    <nameField>
        <displayFormat>SPRP-{000000}</displayFormat>
        <label>Special Price Request Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Price_Request_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Special_Price_Request__r.Account__r.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request_Product__c/fields/Special_Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Special_Price_Request__c</fullName>
    <label>Special Price Request</label>
    <referenceTo>Special_Price_Request__c</referenceTo>
    <relationshipLabel>Special Price Request Products</relationshipLabel>
    <relationshipName>Special_Price_Request_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CloneSPRTest.cls
@isTest
private class CloneSPRTest {
    public static TestMethod void Test(){
        Account accObj=new Account();
        accObj.Name='sumit';
        insert accObj;
        Special_Price_Request__c SPRObj= new Special_Price_Request__c();
        SPRObj.Account__c=accObj.id;
        SPRObj.CurrencyIsoCode='USD';
        insert SPRObj;
        Special_Price_Request_Product__c SPRProObj =new Special_Price_Request_Product__c(); 
        SPRProObj.Special_Price_Request__c=SPRObj.id;
        SPRProObj.CurrencyIsoCode='USD';
        insert  SPRProObj;      
        CloneSPR.cloneSPRConform(SPRObj.id);
    }
}