force-app/main/default/objects/Special_Price_Request__c/Special_Price_Request__c.object-meta.xml
<CustomObject>
    <description>Request for TPD, MSP, PPP that needs approvals</description>
    <label>Special Price Request</label>
    <nameField>
        <displayFormat>SPR-{000000}</displayFormat>
        <label>Special Price Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Price_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Opportunity Account if there is Opportunity</description>
    <inlineHelpText>Opportunity Account if there is Opportunity</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Special Price Requests</relationshipLabel>
    <relationshipName>Project_Price_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NewSPRProductCtrlTest.cls
@IsTest
private class NewSPRProductCtrlTest {     
    public static TestMethod void test(){
     Account accObj= new Account();
     accObj.Name='Test';
     insert accObj;
     Special_Price_Request__c sprObj=new Special_Price_Request__c();
     sprObj.Account__c=accObj.id;  
     insert sprObj;
     List<Special_Price_Request__c> sprObjLst=new List<Special_Price_Request__c>();      
     ApexPages.currentPage().getParameters().put('id', sprObj.id);
     ApexPages.StandardSetController stdController= new ApexPages.StandardSetController(sprObjLst);   
     NewSPRProductCtrl con= new NewSPRProductCtrl(stdController); 
               
     }
}