force-app/main/default/objects/Special_Price_Request__c/Special_Price_Request__c.object-meta.xml
<CustomObject>
    <description>Request for TPD, MSP, PPP that needs approvals</description>
    <label>Special Price Request</label>
    <nameField>
        <displayFormat>SPR-{000000}</displayFormat>
        <label>Special Price Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Price_Request__c/fields/Approved_By_Regional_Head__c.field-meta.xml
<CustomField>
    <fullName>Approved_By_Regional_Head__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved By Regional Head</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Approved_By_Team_Leader__c.field-meta.xml
<CustomField>
    <fullName>Approved_By_Team_Leader__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved By Team Leader</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Approved_By_Team_Manager__c.field-meta.xml
<CustomField>
    <fullName>Approved_By_Team_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved By Team Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Date_Approved_By_Regional_Head__c.field-meta.xml
<CustomField>
    <fullName>Date_Approved_By_Regional_Head__c</fullName>
    <description>Date when the last approval by Regional Head has been made</description>
    <inlineHelpText>Date when the last approval by Regional Head has been made</inlineHelpText>
    <label>Date Approved By Regional Head</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Date_Approved_By_Team_Manager__c.field-meta.xml
<CustomField>
    <fullName>Date_Approved_By_Team_Manager__c</fullName>
    <description>Date when the last approval by Team Manager has been made</description>
    <inlineHelpText>Date when the last approval by Team Manager has been made</inlineHelpText>
    <label>Date Approved By Team Manager</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Email_PS_CEL__c.field-meta.xml
<CustomField>
    <fullName>Email_PS_CEL__c</fullName>
    <description>Added for PPP final approval notification. Updated with Workflow using Roll-up Summary.</description>
    <label>Email PS CEL</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Email_PS_POS__c.field-meta.xml
<CustomField>
    <fullName>Email_PS_POS__c</fullName>
    <description>Added for PPP final approval notification. Updated with Workflow using Roll-up Summary.</description>
    <label>Email PS POS</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Email_PS_SHO__c.field-meta.xml
<CustomField>
    <fullName>Email_PS_SHO__c</fullName>
    <description>Added for PPP final approval notification. Updated with Workflow using Roll-up Summary.</description>
    <label>Email PS SHO</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Price_Level__c.field-meta.xml
<CustomField>
    <fullName>Price_Level__c</fullName>
    <description>Price level
RSP: Price = RSP
TPD: RSP &gt; Price &gt;= TPD
MSP: TPD &gt; Price &gt;= MSP
PPP: MSP &gt; Price</description>
    <inlineHelpText>Price level
RSP: Price = RSP
TPD: RSP &gt; Price &gt;= TPD
MSP: TPD &gt; Price &gt;= MSP
PPP: MSP &gt; Price
NOTE: No Approval Process required for TPD</inlineHelpText>
    <label>Price Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PPP (Project Price Plan)</fullName>
            </value>
            <value>
                <fullName>MSP (Minimum Sales Price)</fullName>
            </value>
            <value>
                <fullName>TPD (Transfer Price for Distributor)</fullName>
            </value>
            <value>
                <fullName>RSP (Recommended Sales Price)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Prices_Valid_Until__c.field-meta.xml
<CustomField>
    <fullName>Prices_Valid_Until__c</fullName>
    <description>If it is empty, it will be Date Approved By CEO + 120 days</description>
    <inlineHelpText>If it is empty, it will be Date Approved By CEO + 120 days</inlineHelpText>
    <label>Prices Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Prices_Valid_Until_Previous__c.field-meta.xml
<CustomField>
    <fullName>Prices_Valid_Until_Previous__c</fullName>
    <description>Date previously filled, to be used if Prices Valid Until is added</description>
    <inlineHelpText>Date previously filled, to be used if Prices Valid Until is added</inlineHelpText>
    <label>Prices Valid Until Previous</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Approved: Only when the final approval has been made.
Rejected: Any time the request has been rejected.</description>
    <inlineHelpText>Approved: Only when the final approval has been made.
Rejected: Any time the request has been rejected.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <formula>Total_Quantity_P1__c+Total_Quantity_P2__c+Total_Quantity_P3__c+Total_Quantity_P4__c+Total_Quantity_P5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Sum of Total Quantity P1+P2+P3+P4+P5</inlineHelpText>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Total_Quantity_CEL__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity_CEL__c</fullName>
    <description>Made to add Email PS CEL</description>
    <label>Total Quantity CEL</label>
    <summarizedField>Special_Price_Request_Product__c.Quantity_Total__c</summarizedField>
    <summaryFilterItems>
        <field>Special_Price_Request_Product__c.Product_Center_picklist__c</field>
        <operation>equals</operation>
        <value>Cellular</value>
    </summaryFilterItems>
    <summaryForeignKey>Special_Price_Request_Product__c.Special_Price_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Total_Quantity_P1__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity_P1__c</fullName>
    <inlineHelpText>Sum of Quantity P1 of all added Special Price Request Products</inlineHelpText>
    <label>Total Quantity P1</label>
    <summarizedField>Special_Price_Request_Product__c.Quantity_P1__c</summarizedField>
    <summaryForeignKey>Special_Price_Request_Product__c.Special_Price_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Total_Quantity_P2__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity_P2__c</fullName>
    <inlineHelpText>Sum of Quantity P2 of all added Special Price Request Products</inlineHelpText>
    <label>Total Quantity P2</label>
    <summarizedField>Special_Price_Request_Product__c.Quantity_P2__c</summarizedField>
    <summaryForeignKey>Special_Price_Request_Product__c.Special_Price_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Total_Quantity_P3__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity_P3__c</fullName>
    <inlineHelpText>Sum of Quantity P3 of all added Special Price Request Products</inlineHelpText>
    <label>Total Quantity P3</label>
    <summarizedField>Special_Price_Request_Product__c.Quantity_P3__c</summarizedField>
    <summaryForeignKey>Special_Price_Request_Product__c.Special_Price_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Total_Quantity_P4__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity_P4__c</fullName>
    <inlineHelpText>Sum of Quantity P4 of all added Special Price Request Products</inlineHelpText>
    <label>Total Quantity P4</label>
    <summarizedField>Special_Price_Request_Product__c.Quantity_P4__c</summarizedField>
    <summaryForeignKey>Special_Price_Request_Product__c.Special_Price_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Total_Quantity_P5__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity_P5__c</fullName>
    <inlineHelpText>Sum of Quantity P5 of all added Special Price Request Products</inlineHelpText>
    <label>Total Quantity P5</label>
    <summarizedField>Special_Price_Request_Product__c.Quantity_P5__c</summarizedField>
    <summaryForeignKey>Special_Price_Request_Product__c.Special_Price_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Total_Quantity_POS__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity_POS__c</fullName>
    <description>Made to add Email PS POS</description>
    <label>Total Quantity POS</label>
    <summarizedField>Special_Price_Request_Product__c.Quantity_Total__c</summarizedField>
    <summaryFilterItems>
        <field>Special_Price_Request_Product__c.Product_Center_picklist__c</field>
        <operation>equals</operation>
        <value>Positioning</value>
    </summaryFilterItems>
    <summaryForeignKey>Special_Price_Request_Product__c.Special_Price_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Special_Price_Request__c/fields/Total_Quantity_SHO__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity_SHO__c</fullName>
    <description>Made to add Email PS SHO</description>
    <label>Total Quantity SHO</label>
    <summarizedField>Special_Price_Request_Product__c.Quantity_Total__c</summarizedField>
    <summaryFilterItems>
        <field>Special_Price_Request_Product__c.Product_Center_picklist__c</field>
        <operation>equals</operation>
        <value>Short Range</value>
    </summaryFilterItems>
    <summaryForeignKey>Special_Price_Request_Product__c.Special_Price_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/SPRFlowTest.cls
@IsTest
public class SPRFlowTest {
/*
Flow Name: SPR: Before Insert/Update
*/    
    
    @isTest
	static void TestClearApprovalMSPRegionalHead(){
        
		SPRTestDataFactory inst = new SPRTestDataFactory();
        UserTestDataFactory testuser = new UserTestDataFactory();
        User u_atan = (User)testuser.createRecord();
        
        test.startTest();
        
        System.runAs(u_atan) {
        	sObject sprrecord = inst.createRecord();
			Special_Price_Request__c spr = [SELECT Price_Level__c, 
                                            Status__c, 
                                            Approved_By_Team_Leader__c, 
                                            Approved_By_Team_Manager__c, 
                                            Approved_By_Regional_Head__c 
                                            FROM Special_Price_Request__c Where Id=:sprrecord.id];             
            spr.Price_Level__c= 'PPP (Project Price Plan)';
			spr.Status__c = 'Approved';
            spr.Approved_By_Team_Leader__c = false;
            spr.Approved_By_Team_Manager__c = false;
            spr.Approved_By_Regional_Head__c = true;
            update spr;   
    }
        test.stopTest();
    }
    @isTest
    static void TestFillPricesValidUntilPrevious(){

		SPRTestDataFactory inst = new SPRTestDataFactory();
		sObject sprrecord = inst.createRecord();
        test.startTest();
        if(sprrecord.id !=null ){
			Special_Price_Request__c spr = [SELECT Prices_Valid_Until__c, 
                                            Prices_Valid_Until_Previous__c
                                            FROM Special_Price_Request__c Where Id=:sprrecord.id];
			spr.Prices_Valid_Until_Previous__c = spr.Prices_Valid_Until__c;
            update spr;   
        }
        test.stopTest();
        
    }
	@isTest
	static void TestApproveMSPasCM(){
   		SPRTestDataFactory inst = new SPRTestDataFactory();

        Special_Price_Request__c sprrecord = (Special_Price_Request__c)inst.initializeRecord();        
        sprrecord.Price_Level__c = 'MSP (Minimum Sales Price)';
        insert sprrecord;
                 
        UserTestDataFactory testuser = new UserTestDataFactory();
		User u_tnak = (User)testuser.initializeRecord();
        //User u_tnak = inst.initializeuser();
        u_tnak.Alias = 'tnak';
        u_tnak.Username = 'u_tnak@testorg.com';
        insert u_tnak;
        
        test.startTest();
        System.runAs(u_tnak) {
            Special_Price_Request__c spr = [SELECT Price_Level__c, 
                                            Approved_By_Team_Manager__c,
                                            Date_Approved_By_Team_Manager__c,
                                            Status__c
                                            FROM Special_Price_Request__c Where Id=:sprrecord.id];
            
            
            if(spr.Price_Level__c == 'MSP (Minimum Sales Price)'){
				spr.Approved_By_Team_Manager__c = true;
                spr.Date_Approved_By_Team_Manager__c = spr.Date_Approved_By_Team_Manager__c;
                spr.Status__c = 'Approved';
                update spr;
            }
        }
        test.stopTest();
    }
    @isTest
    static void TestApproveMSPasRegionalHead(){
        SPRTestDataFactory inst = new SPRTestDataFactory();
        
		UserTestDataFactory testuser = new UserTestDataFactory();
        User u_atan = (User)testuser.createRecord();
        //User u_atan = inst.createUser();
        
        Special_Price_Request__c sprrecord = (Special_Price_Request__c)inst.initializeRecord();        
        sprrecord.Price_Level__c = 'MSP (Minimum Sales Price)';
        insert sprrecord;
        
        test.startTest();
       	System.runAs(u_atan) {
        Special_Price_Request__c spr = [SELECT Price_Level__c, 
                                            Date_Approved_By_Regional_Head__c,
                                        	Date_Approved_By_Team_Manager__c,
                                        	Approved_By_Regional_Head__c,
                                            Status__c
                                            FROM Special_Price_Request__c Where Id=:sprrecord.id];
            
      	if(spr.Price_Level__c == 'MSP (Minimum Sales Price)'){
			spr.Approved_By_Regional_Head__c = true;
            spr.Date_Approved_By_Regional_Head__c = spr.Date_Approved_By_Team_Manager__c;
            spr.Status__c = 'Approved';
            update spr;
            }
        }
        test.stopTest();
        
    }
    
    
/*
Flow Name: SPR: After insert/update
*/
    
    @isTest
    static void TestAddEmailPSAll(){
    	SPRTestDataFactory inst = new SPRTestDataFactory();
		Special_Price_Request__c spr = (Special_Price_Request__c)inst.initializeRecord();
		insert spr;
		//spr.CreatedDate = '2020/12/12';   // Not writeable field 
		// Total_Quantity__c is sum of Total Quantity P1+P2+P3+P4+P5
        //spr.Total_Quantity_P1__c = 0;
        //spr.Total_Quantity_P2__c = 0;
        //spr.Total_Quantity_P3__c = 0;
        //spr.Total_Quantity_P4__c = 0;
        //spr.Total_Quantity_P5__c = 0;
		
        test.startTest();
        	if(spr.Price_Level__c == 'PPP (Project Price Plan)' && spr.Total_Quantity__c == 0 && spr.CreatedDate != spr.LastModifiedDate){
            	spr.Email_PS_CEL__c = 'stefano.moioli@u-blox.com';
                spr.Email_PS_POS__c = 'Peter.Fairhurst@u-blox.com';
                spr.Email_PS_SHO__c = 'hakan.svegerud@u-blox.com';
                update spr;
        	}
        test.stopTest();
    }
    @isTest
    static void TestAddEmailPSCELdecision(){
        SPRTestDataFactory inst = new SPRTestDataFactory();
		Special_Price_Request__c spr = (Special_Price_Request__c)inst.initializeRecord();
		insert spr;
        
        test.startTest();
        if(spr.Price_Level__c == 'PPP (Project Price Plan)' && spr.Total_Quantity__c>0){
            spr.Email_PS_CEL__c = 'stefano.moioli@u-blox.com';          
        }
        test.stopTest();
    }
    @isTest
    static void TestAddEmailPSPOS(){
        SPRTestDataFactory inst = new SPRTestDataFactory();
		Special_Price_Request__c spr = (Special_Price_Request__c)inst.initializeRecord();
		insert spr;
        
        test.startTest();
        if(spr.Price_Level__c == 'PPP (Project Price Plan)' && spr.Total_Quantity_POS__c > 0 ){
        	spr.Email_PS_POS__c = 'Peter.Fairhurst@u-blox.com';
        }
        test.stopTest();
    }
    @isTest
    static void TestAddEmailPSSHO(){
        SPRTestDataFactory inst = new SPRTestDataFactory();
		Special_Price_Request__c spr = (Special_Price_Request__c)inst.initializeRecord();
		insert spr;
        
        test.startTest();
        if(spr.Price_Level__c == 'PPP (Project Price Plan)' && spr.Total_Quantity_SHO__c > 0 ){
            spr.Email_PS_SHO__c = 'hakan.svegerud@u-blox.com';
        }
        test.stopTest();
    }
    @isTest
    static void TestRemoveEmailPSCEL(){
        SPRTestDataFactory inst = new SPRTestDataFactory();
		Special_Price_Request__c spr = (Special_Price_Request__c)inst.initializeRecord();
		insert spr;
        
        Test.startTest();
        if(spr.Price_Level__c == 'PPP (Project Price Plan)' && spr.Total_Quantity_CEL__c == 0 &&  spr.Total_Quantity__c > 0){
            spr.Email_PS_CEL__c = '';
        }
        test.stopTest();
    }
    @isTest
    static void TestRemoveEmailPSPOS(){
        SPRTestDataFactory inst = new SPRTestDataFactory();
		Special_Price_Request__c spr = (Special_Price_Request__c)inst.initializeRecord();
		insert spr;
        
        Test.startTest();
        if(spr.Price_Level__c == 'PPP (Project Price Plan)' && spr.Total_Quantity_POS__c == 0 &&  spr.Total_Quantity__c > 0){
            spr.Email_PS_POS__c = '';
        }
        test.stopTest();
    }
    @isTest
    static void TestRemoveEmailPSSHO(){
        SPRTestDataFactory inst = new SPRTestDataFactory();
		Special_Price_Request__c spr = (Special_Price_Request__c)inst.initializeRecord();
		insert spr;
     
        Test.startTest();
        if(spr.Price_Level__c == 'PPP (Project Price Plan)' &&  spr.Total_Quantity_SHO__c == 0 && spr.Total_Quantity__c > 0){
            spr.Email_PS_SHO__c = '';
        }
        test.stopTest();
    }
    
}