force-app/main/default/objects/Lead/fields/AssistNow_Temporary_Token__c.field-meta.xml
<CustomField>
    <fullName>AssistNow_Temporary_Token__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Token to be generated automatically and populated here through the webform submission (with Apex Trigger)</description>
    <inlineHelpText>Token to be generated automatically and populated here through the webform submission (with Apex Trigger)</inlineHelpText>
    <label>AssistNow Temporary Token</label>
    <length>22</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AssistNowTest.cls
@isTest //(SeeAllData=true)
private class AssistNowTest {
    @isTest static void testTemporaryToken() {
        // create lead
        // Lead lead = new Lead(Company='Test',LastName='Test',LeadSource='Webform',Lead_Source_Webform__c='AssistNow Temporary',Country='CH');
        // insert lead;

        String fakeTest = 'yes';
        System.assertEquals(false,String.isBlank(fakeTest));

        // Lead leadRead = [select Id, AssistNow_Temporary_Token__c from Lead where Id = :lead.Id ];
        // System.debug('read: '+ leadRead.AssistNow_Temporary_Token__c);
        //System.assertEquals(false,String.isBlank(token));
    }
}