force-app/main/default/objects/Lead/fields/Date_Production__c.field-meta.xml
<CustomField>
    <fullName>Date_Production__c</fullName>
    <inlineHelpText>Planned start of mass production. Copied to Opportunity.</inlineHelpText>
    <label>Date Production</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this lead.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Based on the values of global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>Imported from Project Information Form field Project Name, will be used for the Opportunity Name after conversion (Name on Convert window will be overwritten).</description>
    <inlineHelpText>Imported from Project Information Form field Project Name, will be used for the Opportunity Name after conversion (Name on Convert window will be overwritten).</inlineHelpText>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market_Classification__c/Market_Classification__c.object-meta.xml
<CustomObject>
    <description>Market Classification object is created to store market and market segments for different objects like Account, Lead, and Opportunities. It&apos;s an improvement on an existing way of storing the application and application type on account, lead and opportunities.</description>
    <label>Market Classification</label>
    <nameField>
        <label>Market Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Classification__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Classification__c/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <inlineHelpText>Select market by quality grade.</inlineHelpText>
    <label>Market (OLD)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this opportunity.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Values based on the global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/CreateCompletedTaskForNoOppLeadTest.cls
@isTest
private class CreateCompletedTaskForNoOppLeadTest {
	
	  public static testMethod void testCreateCompletedTaskForNoOppLead()
        {
            Market_Classification__c classification = new Market_Classification__c(
                    IsActive__c = true,
                    Market__c = 'Automotive',
                    Market_Segment__c = 'Autonomous driving');
            Database.insert(classification);
        	
            Lead l = new Lead(LastName='testname', Company='testcompany', Project_Name__c = 'Test Project', IsConverted = false, Country='CH',Market_Classification__c = classification.id,New_Application_Type__c = 'Autonomous driving');
            insert l;
            
          
            Database.LeadConvert lc = new Database.LeadConvert();
            lc.setLeadId(l.id);
            LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
            lc.setConvertedStatus(convertStatus.MasterLabel);
            lc.setDoNotCreateOpportunity(false);
            Database.LeadConvertResult lcr = Database.convertLead(lc);
            System.assert(lcr.isSuccess());

           // Datetime productionDate = l.Date_Production__c;
           // String productionDateFormat = productionDate.format('MMMM d,  yyyy');


           if(l.Project_Name__c != null){

           	Task t = new Task(Subject='Lead conversion (no Opportunity generated)',ActivityDate=date.today(),Status='Completed',Type='Other',WhoId=l.ConvertedContactId,WhatId=l.ConvertedAccountId,

           	Description = l.Project_Name__c!=null?'Project Name: '+l.Project_Name__c+'\r\n':'');
           	
           }
           
            
           
            Lead convertedLead = [SELECT Id, ConvertedContactId FROM Lead WHERE id = :l.id];
            
            
            

            	
            
            


            
        
        } 
	
}