force-app/main/default/objects/Process_Settings__c/fields/Account_Allowed_Profiles_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>Account_Allowed_Profiles_To_Delete__c</fullName>
    <description>Profiles able to delete accounts in any criteria.</description>
    <inlineHelpText>Profiles able to delete accounts in any criteria.</inlineHelpText>
    <label>Account: Allowed Profiles To Delete</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Process_Settings__c/fields/Account_Allowed_Profiles_To_Merge__c.field-meta.xml
<CustomField>
    <fullName>Account_Allowed_Profiles_To_Merge__c</fullName>
    <description>Profiles which are allowed to merge accounts in different regions.</description>
    <inlineHelpText>Profiles which are allowed to merge accounts in different regions.</inlineHelpText>
    <label>Account: Allowed Profiles To Merge</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Process_Settings__c/fields/Restricted_Profiles_For_Contract__c.field-meta.xml
<CustomField>
    <fullName>Restricted_Profiles_For_Contract__c</fullName>
    <description>Restricted Profiles for users which cannot be Owner of Contracts</description>
    <label>Restricted Profiles For Contract</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CommonUtils.cls
Global Class CommonUtils
{
    Public final static string ACTIVATED = 'Activated';
    public final static string NDA_CATEGORY = 'NDA';

    
    public static List<String> getRestrictedProfilesForContract()
    {
        List<String> res = new List<String>();
        
        Process_Settings__c pSetting = Process_Settings__c.getInstance();
        string fText = pSetting.Restricted_Profiles_For_Contract__c;
        
        if(!String.isEmpty(fText))
            res = fText.split(';');
        
        return res;
    }
    
    public static Boolean isAllowedProfileForMerge (String profile)
    {
        Boolean res = false;
        
        Process_Settings__c pSetting = Process_Settings__c.getInstance();
        string fText = pSetting.Account_Allowed_Profiles_To_Merge__c;
        
        if(fText.contains(profile))
            res = true;
        
        return res;
    }
    
    public static Boolean isAllowedProfileForDelete (String profile)
    {
        Boolean res = false;
        
        Process_Settings__c pSetting = Process_Settings__c.getInstance();
        string fText = pSetting.Account_Allowed_Profiles_To_Delete__c;
        
        if(fText.contains(profile))
            res = true;
        
        return res;
    }


    public static List<Schema.FieldSetMember> getFieldSetFields(String fieldSetName, String ObjectName)
    {
        List<Schema.FieldSetMember> fieldSetMemList = new List<Schema.FieldSetMember>();
        Map<String, Schema.SObjectType> gDescribeMap = Schema.getGlobalDescribe(); 
        Schema.SObjectType objectType = gDescribeMap.get(ObjectName);
        if(objectType!=null)
        {
            Schema.DescribeSObjectResult descObjectResult = objectType.getDescribe();   
            Schema.FieldSet fieldSetObj = descObjectResult.FieldSets.getMap().get(fieldSetName);        
            if(fieldSetObj!=null)
                fieldSetMemList = fieldSetObj.getFields(); 
        }
        
        return fieldSetMemList;
    }

}