force-app/main/default/objects/Opportunity/fields/OppAutoNumber__c.field-meta.xml
<CustomField>
    <fullName>OppAutoNumber__c</fullName>
    <description>To be used for Quotation_Reference_Number__c</description>
    <displayFormat>{YY}{000000}</displayFormat>
    <label>OppAutoNumber</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create related list that only shows quotation or opportunity. If the record type is quotation, than it is blank.</description>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Partner_Role__c/Partner_Role__c.object-meta.xml
<CustomObject>
    <description>Link between two Accounts for a specific Opportunity</description>
    <label>Partner Role</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>P-Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partner Roles</relationshipLabel>
    <relationshipName>R00N20000000pWzkEAE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Role__c/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Roles (As Opportunity Account)</relationshipLabel>
    <relationshipName>R00N200000018BaOEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Role__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Roles (As Partner Account)</relationshipLabel>
    <relationshipName>R00N20000000pWzvEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Role__c/fields/Partner_Role__c.field-meta.xml
<CustomField>
    <fullName>Partner_Role__c</fullName>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 Partner Referral (commissions required)</fullName>
            </value>
            <value>
                <fullName>0 Partner Referral (no commissions)</fullName>
            </value>
            <value>
                <fullName>1 Opportunity owner</fullName>
            </value>
            <value>
                <fullName>2 Ref. design / platform dev.</fullName>
            </value>
            <value>
                <fullName>3 Design house</fullName>
            </value>
            <value>
                <fullName>3 ODM (Design and Manufacturing)</fullName>
            </value>
            <value>
                <fullName>3 Local Module Maker</fullName>
            </value>
            <value>
                <fullName>4 Consultant/Advisor</fullName>
            </value>
            <value>
                <fullName>4 Certification partner</fullName>
            </value>
            <value>
                <fullName>4 Technology partner</fullName>
            </value>
            <value>
                <fullName>4 MNO / MVNO</fullName>
            </value>
            <value>
                <fullName>5 Former contract manufacturer</fullName>
            </value>
            <value>
                <fullName>5 Actual contract manufacturer</fullName>
            </value>
            <value>
                <fullName>5 Potential contract manufacturer</fullName>
            </value>
            <value>
                <fullName>6 Sourcing / Negotiation entity</fullName>
            </value>
            <value>
                <fullName>6 Purchasing entity</fullName>
            </value>
            <value>
                <fullName>7 Distributor</fullName>
            </value>
            <value>
                <fullName>8 Sales representative</fullName>
            </value>
            <value>
                <fullName>8 Agent</fullName>
            </value>
            <value>
                <fullName>9 Customer of opp. owner</fullName>
            </value>
            <value>
                <fullName>9 Car brand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variable__c/Variable__c.object-meta.xml
<CustomObject>
    <label>Variable</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Variable__c/fields/LastOppID__c.field-meta.xml
<CustomField>
    <fullName>LastOppID__c</fullName>
    <label>LastOppID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Variable__c/fields/LastPartnerRoleID__c.field-meta.xml
<CustomField>
    <fullName>LastPartnerRoleID__c</fullName>
    <label>LastPartnerRoleID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NewPartnerRoleCtrl.cls
/*
* Apex Controller for New Partner Role button in Opportunity object in Lightning
* Author: ldra
* Date: 07/10/2019
* */


public class NewPartnerRoleCtrl {
    @AuraEnabled
    public static Opportunity getRecord(String recordId){
        Opportunity o =[SELECT Id, Opportunity_Account__c, CurrencyIsoCode FROM Opportunity WHERE Id = :recordId];   
        return o;
    }
    public Opportunity currentRecord {get;set;}//Current Opporutnity
    public Partner_Role__c partnerRole {get;set;}// Initialzing partner role
    
    public NewPartnerRoleCtrl(apexPages.StandardController sc)
    {
        //Fetch current record's information
        Id currentRecordId = sc.getRecord().Id;
        
        currentRecord = [SELECT Id, Opportunity_Account__c, Name,OppAutoNumber__c ,CurrencyIsoCode, AccountId FROM Opportunity
                         WHERE Id =:currentRecordId];

        
        //Initialize the parther role from current Opportunity
        partnerRole = new Partner_Role__c(
            CurrencyIsoCode          = currentRecord.CurrencyIsoCode,
            Opportunity_Account__c = currentRecord.Opportunity_Account__c,
            Opportunity__c = currentRecord.Id
        );
    }
    //Return to opportunity
    public pageReference doCancel()
    {
        pageReference pageRef = new pageReference('/' + currentRecord.Id);
        pageRef.SetRedirect(true);
        return pageRef;
    }
    //Save and return
    public pageReference doSave()
    {
        Id partnerObjId;
		partnerObjId = save(partnerRole);
       
            pageReference pageRef = new pageReference('/' + (partnerObjId != null ? partnerObjId : currentRecord.Id));
            pageRef.SetRedirect(true);
            return pageRef;
    }
    
    @AuraEnabled
    public static Id save(Partner_Role__c pr) {
        
        Id oppID = pr.Opportunity__c;
        String LastOppID;
        String VariableID;
        String UserID= UserInfo.getUserId();
        list<Variable__c> varLst= [SELECT Id, Name, LastOppID__c, LastPartnerRoleID__c FROM Variable__c WHERE Name =:UserID];            
        if (!varLst.isEmpty())
        {
            LastOppID = varLst[0].LastOppID__c;
            VariableID = varLst[0].Id;
            String LastPartnerRoleID = varLst[0].LastPartnerRoleID__c;
            
            if (LastPartnerRoleID!= null)
            {
                list<Partner_Role__c> proleLst=[SELECT Id, IsDeleted, Partner_Account__c FROM Partner_Role__c WHERE Id = :LastPartnerRoleID];
                
                if (!proleLst.isEmpty())
                {

                    if (proleLst[0].Partner_Account__c == null)
                    {            
                        Partner_Role__c PAR=new Partner_Role__c();
                        PAR.id=LastPartnerRoleID;
                        delete PAR;
                        
                    }
                }
            }
        }
        else
        {
            Variable__c VAR=new Variable__c();              
            VAR.Name = UserID;
            insert VAR;
            VariableID = VAR.id;
        }
        
        // insert partner role
        insert pr;
        
        Variable__c VAR=new Variable__c();      
        VAR.Id = VariableID;
        VAR.LastPartnerRoleID__c = pr.id;
        VAR.LastOppID__c = OppID;
        update VAR;
        
        return pr.Id;
    }
}