force-app/main/default/objects/Contact/fields/AssistNow_Token_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>AssistNow_Token_To_Delete__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Token to be deactivated is copied to this field and sent to svc-pos-team-GLOBAL@u-blox.com</description>
    <inlineHelpText>Token to be deactivated is copied to this field and sent to svc-pos-team-GLOBAL@u-blox.com</inlineHelpText>
    <label>AssistNow Token To Delete</label>
    <length>22</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/MGA__c.field-meta.xml
<CustomField>
    <fullName>MGA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Multi-GNSS AssistNow Service
Checked: The token is active or needs to be generated. If AssistNow Requested Date is empty, press button &quot;AssistNow Request&quot; to generate a new token.
Unchecked: The token will be deactivated and deleted.</inlineHelpText>
    <label>AssistNow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MGA_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>MGA_Requested_Date__c</fullName>
    <inlineHelpText>When the AssistNow Token has been generated</inlineHelpText>
    <label>AssistNow Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MGA_Token__c.field-meta.xml
<CustomField>
    <fullName>MGA_Token__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>AssistNow Token. Generated with button &quot;AssistNow Enable&quot;.</inlineHelpText>
    <label>AssistNow Token</label>
    <length>22</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AssistNowDeleteCtrl.cls
public class AssistNowDeleteCtrl {
    @AuraEnabled
    public static Boolean checkToken(String recordId){
        String ContactId;
        if(!string.isEmpty(recordId)){ 
            ContactId=recordId;
            Contact conc= new Contact();
            conc=[Select id,MGA__c,MGA_Token__c,MGA_Requested_Date__c from Contact Where id=:ContactId];           
            if (conc.MGA__c == true && conc.MGA_Token__c != ''){
                return true;
            }                              
        }
        return false;
    }
    
    @AuraEnabled
     public static String deleteToken(String recordId){
         Contact c=[Select id,MGA__c,MGA_Token__c,MGA_Requested_Date__c from Contact Where id=:recordId];    
         c.MGA__c = false;
         c.MGA_Token__c = null;
         c.AssistNow_Token_To_Delete__c = c.MGA_Token__c;
         update c;                                 
         return c.id;
     }
    
}