force-app/main/default/objects/Contact/fields/AssistNow_Token_Resend__c.field-meta.xml
<CustomField>
    <fullName>AssistNow_Token_Resend__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for Email Alert to resend the token.</description>
    <inlineHelpText>Used for Email Alert to resend the token.</inlineHelpText>
    <label>AssistNow Token Resend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MGA__c.field-meta.xml
<CustomField>
    <fullName>MGA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Multi-GNSS AssistNow Service
Checked: The token is active or needs to be generated. If AssistNow Requested Date is empty, press button &quot;AssistNow Request&quot; to generate a new token.
Unchecked: The token will be deactivated and deleted.</inlineHelpText>
    <label>AssistNow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MGA_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>MGA_Requested_Date__c</fullName>
    <inlineHelpText>When the AssistNow Token has been generated</inlineHelpText>
    <label>AssistNow Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MGA_Token__c.field-meta.xml
<CustomField>
    <fullName>MGA_Token__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>AssistNow Token. Generated with button &quot;AssistNow Enable&quot;.</inlineHelpText>
    <label>AssistNow Token</label>
    <length>22</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AssitNowEnableCtrl.cls
public class AssitNowEnableCtrl {
	 @AuraEnabled
     public static Boolean assitNowEnableToken(String recordId){
       String ContactId;
       
       if(!string.isEmpty(recordId)){ 
        ContactId=recordId;
        Contact conc= new Contact();
        conc=[Select id,MGA__c,MGA_Token__c,MGA_Requested_Date__c from Contact Where id=:ContactId];           
         //System.debug('aaaaaaaaaa'+conc);
        if (String.isEmpty(conc.MGA_Token__c)){
            
           return true;
        }else if(conc.MGA__c == true && !String.isEmpty(conc.MGA_Token__c)){
          return false;  
        }                              
       }
       return false;
     }
     
    @AuraEnabled
     public static String assitNowEnableTokenConform(String recordId){
        String ContactId=recordId;
        Contact conc= new Contact();
        conc=[Select id,MGA__c,MGA_Token__c,MGA_Requested_Date__c from Contact Where id=:ContactId];
         // generate MGA Token
         // Make sure the URL http://token-live1.services.u-blox.com is added in
         // Your name | Administration Setup | Security Control | Remote Site Settings
         if(!Test.isRunningTest()){ 
             HttpRequest req = new HttpRequest();req.setEndpoint('http://token-live1.services.u-blox.com/GetToken.ashx?key=84cba94b-24fd-48db-a370-d5b81805db52');
             req.setMethod('GET');Http h = new Http(); HttpResponse res = h.send(req);conc.MGA_Token__c = res.getBody();
         }    
         conc.MGA__c = True;
         upsert conc;    
         
       return conc.id;
         
     }
    
    @AuraEnabled
     public static String assitNowEnableTokenReSend(String recordId){
        String ContactId=recordId;
        Contact conc= new Contact();
        conc=[Select id,MGA__c,MGA_Token__c,MGA_Requested_Date__c,AssistNow_Token_Resend__c from Contact Where id=:ContactId];
        conc.AssistNow_Token_Resend__c = True;
        upsert conc;                                 
       return conc.id;
     }
    
}