force-app/main/default/objects/Contact/fields/AssistNow_Token_Resend__c.field-meta.xml
<CustomField>
    <fullName>AssistNow_Token_Resend__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for Email Alert to resend the token.</description>
    <inlineHelpText>Used for Email Alert to resend the token.</inlineHelpText>
    <label>AssistNow Token Resend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MGA__c.field-meta.xml
<CustomField>
    <fullName>MGA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Multi-GNSS AssistNow Service
Checked: The token is active or needs to be generated. If AssistNow Requested Date is empty, press button &quot;AssistNow Request&quot; to generate a new token.
Unchecked: The token will be deactivated and deleted.</inlineHelpText>
    <label>AssistNow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MGA_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>MGA_Requested_Date__c</fullName>
    <inlineHelpText>When the AssistNow Token has been generated</inlineHelpText>
    <label>AssistNow Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MGA_Token__c.field-meta.xml
<CustomField>
    <fullName>MGA_Token__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>AssistNow Token. Generated with button &quot;AssistNow Enable&quot;.</inlineHelpText>
    <label>AssistNow Token</label>
    <length>22</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AssistNowEnableCtrl.cls
public class AssistNowEnableCtrl {
     @AuraEnabled
     public static Boolean checkToken(String recordId){
         if(!string.isEmpty(recordId)){ 
             Contact c=[Select id,MGA__c,MGA_Token__c,MGA_Requested_Date__c from Contact Where id=:recordId];           
             //System.debug('aaaaaaaaaa'+conc);
             if (String.isEmpty(c.MGA_Token__c)){
                 return true;
             }else if(c.MGA__c == true && !String.isEmpty(c.MGA_Token__c)){
                 return false;  
             }                              
         }
         return false;
     }
     
    @AuraEnabled
     public static String enableToken(String recordId){
        Contact c = [Select id,MGA__c,MGA_Token__c,MGA_Requested_Date__c from Contact Where id=:recordId];
         // generate MGA Token
         // Make sure the URL http://token-live1.services.u-blox.com is added in
         // Your name | Administration Setup | Security Control | Remote Site Settings

         
         String url = 'https://token-live1.services.u-blox.com/GetToken.ashx?key=test-key';
         if(!Test.isRunningTest()){ 
             //String url = 'https://token-live1.services.u-blox.com/GetToken.ashx?key=28549d2b-be1a-4137-894d-e1d0ee93c1b6';
             url = 'https://token-live1.services.u-blox.com/GetToken.ashx?key=84cba94b-24fd-48db-a370-d5b81805db52';
         }
         HttpRequest req = new HttpRequest();
         req.setEndpoint(url);
         req.setMethod('GET');
         Http h = new Http();
         if(!Test.isRunningTest()){
         	HttpResponse res = h.send(req);
            c.MGA_Token__c = res.getBody();
         }

         c.MGA__c = True;
         update c;    
         
         return c.id;
         
     }
    
    @AuraEnabled
     public static String resendToken(String recordId) {
        Contact c = [Select id,MGA__c,MGA_Token__c,MGA_Requested_Date__c,AssistNow_Token_Resend__c from Contact Where id=:recordId];
        c.AssistNow_Token_Resend__c = True;
        update c;                                 
        return c.id;
     }
    
}