force-app/main/default/objects/Contact/fields/Exhibition__c.field-meta.xml
<CustomField>
    <fullName>Exhibition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition</label>
    <referenceTo>Exhibition__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of all countries and mapping to sales people. Used to automatically assign Accounts when created by OnDemand Service (ISA).</description>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition__c/Exhibition__c.object-meta.xml
<CustomObject>
    <label>Exhibition</label>
    <nameField>
        <label>Exhibition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country in 2-character ISO Code (e.g. CH for Switzerland)</description>
    <inlineHelpText>Country in 2-character ISO Code (e.g. CH for Switzerland)</inlineHelpText>
    <label>Country</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Exhibition__c.field-meta.xml
<CustomField>
    <fullName>Exhibition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Add if Lead Source is Trade Show</description>
    <inlineHelpText>Add if Lead Source is Trade Show</inlineHelpText>
    <label>Exhibition</label>
    <referenceTo>Exhibition__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Market_Classification__c.field-meta.xml
<CustomField>
    <fullName>Market_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Market Segment is successor of Application Type field. To select right value, search for keywords and choose the value which best fits this lead.</inlineHelpText>
    <label>Market Segment Selection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market_Classification__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select &quot;All Fields&quot; checkbox bellow the Search field to see all possible Market Segments!</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market_Classification__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/New_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Application_Type__c</fullName>
    <description>Based on the values of global picklist, New Application Type.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Classification__c/Market_Classification__c.object-meta.xml
<CustomObject>
    <description>Market Classification object is created to store market and market segments for different objects like Account, Lead, and Opportunities. It&apos;s an improvement on an existing way of storing the application and application type on account, lead and opportunities.</description>
    <label>Market Classification</label>
    <nameField>
        <label>Market Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Classification__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Classification__c/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/createCompletedTaskForExhibitionTest.cls
@isTest
public class createCompletedTaskForExhibitionTest {
        public static testMethod void testCompletedTaskForExhibition()
        {
//      System.debug(Logginglevel.INFO, '+ alignOppAccOnPartnerRoleTest.alignOppAccOnPartnerRole'); 
                Market_Classification__c classification = new Market_Classification__c(
                        IsActive__c = true,
                        Market__c = 'Automotive',
                        Market_Segment__c = 'Autonomous driving');
                Database.insert(classification);
            // Create Exhibition and Lead records to be used for test
            Exhibition__c e = new Exhibition__c(Name='test exhibition', Country__c='CH');
            insert e;
            Lead l = new Lead(LastName='testname', Company='testcompany', Exhibition__c=e.Id, Country='CH',Market_Classification__c = classification.id, New_Application_Type__c = 'Autonomous driving');
            insert l;
            
            // Lead conversion and check if the conversion is successful
            Database.LeadConvert lc = new Database.LeadConvert();
            lc.setLeadId(l.id);
            LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
            lc.setConvertedStatus(convertStatus.MasterLabel);
            Database.LeadConvertResult lcr = Database.convertLead(lc);
            System.assert(lcr.isSuccess());
            
            // Retrieve field values of the converted Lead and created Task
            Lead convertedLead = [SELECT Id, ConvertedContactId FROM Lead WHERE id = :l.id];
            Contact createdContact = [SELECT Id FROM Contact WHERE id = :lcr.getContactId()];
            list<Task> createdTask = [SELECT WhoId, Exhibition__r.Id FROM Task WHERE WhoId = :lcr.getContactId()];

            // Check if the created Task has correct Contact and Exhibition (expected, actual)
            //System.assertEquals(0, createdTask.size());
        
            // If the trigger needs to be deactivated, comment all the above and include only below.
//                    System.assertEquals(1, 1);

//      System.debug(Logginglevel.INFO, '- alignOppAccOnPartnerRoleTest.alignOppAccOnPartnerRole'); 
        } 
}