force-app/main/default/objects/CampaignMember/fields/Date_Bounced__c.field-meta.xml
<CustomField>
    <fullName>Date_Bounced__c</fullName>
    <description>When the mail has been bounced, updated with workflow (triggered by Autopilot &quot;Set Campaign Status&quot;)</description>
    <inlineHelpText>When the mail has been bounced, updated with workflow (triggered by Autopilot &quot;Set Campaign Status&quot;)</inlineHelpText>
    <label>Date Bounced</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <description>Response given on the registration form</description>
    <inlineHelpText>Response given on the registration form</inlineHelpText>
    <label>Event Participation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_address_probably_not_valid__c.field-meta.xml
<CustomField>
    <fullName>Email_address_probably_not_valid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be activated if the e-mail address was rejected during a campaign.
Please check the e-mail address and possibly contact the customer, then clear
the checkbox.</description>
    <inlineHelpText>Field is checked if a mass-email has been hard-bounced. If the email address of this Contact is valid, check the box &quot;Reactivate Email Address&quot; to get this corrected.</inlineHelpText>
    <label>Email invalid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CampaignMemberFlowTest.cls
@isTest
public class CampaignMemberFlowTest {

	@isTest
    static void TickEmailInvalidInContact(){
        
        CampaignMemberTestDataFactory cmTDF = new CampaignMemberTestDataFactory();
        CampaignMember cm = (CampaignMember)cmTDF.initializeRecord();
        
		ContactTestDataFactory con = new ContactTestDataFactory();
        Contact contact = (Contact)con.createRecord();
        cm.ContactId = contact.id;
        insert cm;
        
        test.startTest();
        if(cm.Date_Bounced__c != null){
            DateTime myDateTime = DateTime.newInstance(2022, 01, 01, 13, 6, 6);
        	cm.Date_Bounced__c = myDateTime;
            update cm;
            system.assertEquals(true, cm.contact.Email_address_probably_not_valid__c);
        }
        test.stopTest();
    }
    
    @isTest
    static void TickAddTaskToLead(){
        
        CampaignMemberTestDataFactory cmTDF = new CampaignMemberTestDataFactory();
        CampaignMember cm = (CampaignMember)cmTDF.initializeRecord();
        cm.Event_Participation__c = 'Test event participation';
        
        Lead cmLead = LeadTestDataFactory.initiliazeLead();
        cmLead.Country = 'GB';
        insert cmLead;
        cm.LeadId = cmLead.id;
        insert cm;     
    
        test.startTest();
        if(cm.LeadId == cmLead.id){
          system.assertEquals(cmLead.Id, cm.LeadId);
        }
        test.stopTest();
    }
    
}