force-app/main/default/objects/Forecast_Unit__c/Forecast_Unit__c.object-meta.xml
<CustomObject>
    <description>Forecast entity: Account-Product-End Customer for which a forecast is made</description>
    <label>Forecast Unit</label>
    <nameField>
        <label>Forecast Unit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecast Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Unit_Period__c/Forecast_Unit_Period__c.object-meta.xml
<CustomObject>
    <description>Forecast period (month) of a forecast unit.</description>
    <label>Forecast Unit Period</label>
    <nameField>
        <label>Forecast Unit Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecast Unit Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Unit_Period__c/fields/FCUPReference_ext_ID__c.field-meta.xml
<CustomField>
    <fullName>FCUPReference_ext_ID__c</fullName>
    <externalId>true</externalId>
    <label>FCUPReference ext ID</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forecast_Unit_Period__c/fields/Forecast_Unit__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Unit__c</fullName>
    <label>Forecast Unit</label>
    <referenceTo>Forecast_Unit__c</referenceTo>
    <relationshipLabel>Forecast Unit Periods</relationshipLabel>
    <relationshipName>Forecast_Unit_Periods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/alignCurrencyOnForecastUnitPeriodTest.cls
@isTest
public class alignCurrencyOnForecastUnitPeriodTest {
        public static testMethod void testFUPCurrency()
        {
                    // Create new Forecast Unit
                    Forecast_Unit__c a = new Forecast_Unit__c(Name='Test FU', CurrencyIsoCode='USD');
                    insert a;
                    
                    // Create new Forecast Period
                    Forecast_Unit_Period__c testFUP = new Forecast_Unit_Period__c(Name = 'Test FUP', Forecast_Unit__c = a.Id, CurrencyIsoCode = 'USD', FCUPReference_ext_ID__c = 'Test FUP');
                    insert testFUP;
                  
                    // Change Currency in Forecast Unit
                    a.CurrencyIsoCode = 'EUR';
                    update a;
                                                      
                    // Verify that the inserted FUP has the same Currency as the related FU                    
                    Forecast_Unit_Period__c updatedFUP = [SELECT CurrencyIsoCode FROM Forecast_Unit_Period__c WHERE Forecast_Unit__c = :a.Id];
                    System.assertEquals(a.CurrencyIsoCode, updatedFUP.CurrencyIsoCode);                                                

        } 
  
}