force-app/main/default/objects/IPR_Cost__c/IPR_Cost__c.object-meta.xml
<CustomObject>
    <description>IPR costs that should replace the current ones in each Product</description>
    <label>IPR Cost</label>
    <nameField>
        <label>IPR Cost Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPR Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPR_Cost__c/fields/Consumer_Pct__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Pct__c</fullName>
    <description>Used only for 2G</description>
    <inlineHelpText>Used only for 2G</inlineHelpText>
    <label>Consumer Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Consumer_USD__c.field-meta.xml
<CustomField>
    <fullName>Consumer_USD__c</fullName>
    <description>Used only for 2G</description>
    <inlineHelpText>Used only for 2G</inlineHelpText>
    <label>Consumer USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Handset_Pct__c.field-meta.xml
<CustomField>
    <fullName>Handset_Pct__c</fullName>
    <label>Handset Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Handset_USD__c.field-meta.xml
<CustomField>
    <fullName>Handset_USD__c</fullName>
    <label>Handset USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Laptop_Pct__c.field-meta.xml
<CustomField>
    <fullName>Laptop_Pct__c</fullName>
    <label>Laptop Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Laptop_USD__c.field-meta.xml
<CustomField>
    <fullName>Laptop_USD__c</fullName>
    <label>Laptop USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/M2M_Pct__c.field-meta.xml
<CustomField>
    <fullName>M2M_Pct__c</fullName>
    <label>M2M Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/M2M_USD__c.field-meta.xml
<CustomField>
    <fullName>M2M_USD__c</fullName>
    <label>M2M USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Other_Pct__c.field-meta.xml
<CustomField>
    <fullName>Other_Pct__c</fullName>
    <label>Other Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Other_USD__c.field-meta.xml
<CustomField>
    <fullName>Other_USD__c</fullName>
    <label>Other USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Prime_Pct__c.field-meta.xml
<CustomField>
    <fullName>Prime_Pct__c</fullName>
    <description>IPR rate in Precent for Prime</description>
    <inlineHelpText>IPR rate in Precent for Prime</inlineHelpText>
    <label>Prime Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Prime_USD__c.field-meta.xml
<CustomField>
    <fullName>Prime_USD__c</fullName>
    <label>Prime USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Telematics_Pct__c.field-meta.xml
<CustomField>
    <fullName>Telematics_Pct__c</fullName>
    <label>Telematics Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Telematics_USD__c.field-meta.xml
<CustomField>
    <fullName>Telematics_USD__c</fullName>
    <label>Telematics USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COGS_1__c.field-meta.xml
<CustomField>
    <fullName>COGS_1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cost of goods sold in USD</description>
    <inlineHelpText>Cost of goods sold in USD</inlineHelpText>
    <label>COGS 1</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COGS_Pct__c.field-meta.xml
<CustomField>
    <fullName>COGS_Pct__c</fullName>
    <inlineHelpText>Cost of goods sold as a percentage of the sales price. Added to COGS.</inlineHelpText>
    <label>COGS Pct</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Cost__c.field-meta.xml
<CustomField>
    <fullName>IPR_Cost__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>IPR cost in detail, used to update IPR USD xxx and IPR Pct xxx fields. Populated when IPR Technology picklist field is changed (using Process and Workflow)</description>
    <inlineHelpText>IPR cost in detail, used to update IPR USD xxx and IPR Pct xxx fields. Populated when IPR Technology picklist field is changed</inlineHelpText>
    <label>IPR Cost</label>
    <referenceTo>IPR_Cost__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_Consumer__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_Consumer__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Value copied from IPR Cost</description>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR Pct Consumer</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_Handset__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_Handset__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR Pct Handset</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_Laptop__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_Laptop__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR Pct Laptop</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_M2M__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_M2M__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR Pct M2M</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_Other__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_Other__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR Pct Other</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_Prime__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_Prime__c</fullName>
    <label>IPR Pct Prime</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_Telematics__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_Telematics__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR Pct Telematics</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_Consumer__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_Consumer__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR USD Consumer</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_Handset__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_Handset__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR USD Handset</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_Laptop__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_Laptop__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR USD Laptop</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_M2M__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_M2M__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR USD M2M</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_Other__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_Other__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR USD Other</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_Prime__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_Prime__c</fullName>
    <label>IPR USD Prime</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_Telematics__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_Telematics__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR USD Telematics</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Packaging_Size__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Size__c</fullName>
    <description>Prev. help text
Equals the Minimum Order Quantity MOQ.
In case there are several trays in a pack, use the total volume.</description>
    <inlineHelpText>(From Abacus) Packaging size</inlineHelpText>
    <label>Packaging Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Positioning_Engine__c.field-meta.xml
<CustomField>
    <fullName>Positioning_Engine__c</fullName>
    <label>Positioning Engine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>u-blox A9</fullName>
            </value>
            <value>
                <fullName>u-blox D9</fullName>
            </value>
            <value>
                <fullName>u-blox F10</fullName>
            </value>
            <value>
                <fullName>u-blox F9</fullName>
            </value>
            <value>
                <fullName>u-blox M10</fullName>
            </value>
            <value>
                <fullName>u-blox M9</fullName>
                <color>#B6E32E</color>
                <label>u-blox M9</label>
            </value>
            <value>
                <fullName>u-blox M8</fullName>
                <color>#000099</color>
                <label>u-blox M8</label>
            </value>
            <value>
                <fullName>u-blox 8</fullName>
            </value>
            <value>
                <fullName>u-blox 7</fullName>
                <color>#0B6FCE</color>
                <label>u-blox 7</label>
            </value>
            <value>
                <fullName>u-blox 6</fullName>
                <color>#33CCFF</color>
                <label>u-blox 6</label>
            </value>
            <value>
                <fullName>u-blox 5</fullName>
                <color>#6600CC</color>
                <label>u-blox 5</label>
            </value>
            <value>
                <fullName>ANTARIS 4</fullName>
                <color>#CC66CC</color>
                <label>ANTARIS 4</label>
            </value>
            <value>
                <fullName>SiRF3</fullName>
            </value>
            <value>
                <fullName>SiRF4</fullName>
            </value>
            <value>
                <fullName>MTK3318</fullName>
            </value>
            <value>
                <fullName>MTK3329</fullName>
            </value>
            <value>
                <fullName>MTK3333</fullName>
            </value>
            <value>
                <fullName>MTK3339</fullName>
            </value>
            <value>
                <fullName>ST Teseo 2</fullName>
            </value>
            <value>
                <fullName>Atheros</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
                <color>#FF99FF</color>
                <label>Various</label>
            </value>
            <value>
                <fullName>C&amp;P</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
                <color>#999999</color>
                <default>true</default>
                <label>Not applicable</label>
            </value>
            <value>
                <fullName>HED8020</fullName>
            </value>
            <value>
                <fullName>MTK3337</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_No__c.field-meta.xml
<CustomField>
    <fullName>Type_No__c</fullName>
    <description>Unique product type number.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique product type number. Not used for quotations</inlineHelpText>
    <label>Type Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IPRCostTriggerHandlerTest.cls
@IsTest
public class IPRCostTriggerHandlerTest {
	
    Public static testMethod void afterInsertTest (){


/*
		IPR_Cost__c i = new IPR_Cost__c();
        i.Name = 'test';
        //i.Type_No__c = 'NEO-M8U-06B-00';
        i.Consumer_USD__c = 1;
        i.M2M_USD__c = 2;
        i.Telematics_USD__c = 3;
        i.Handset_USD__c  = 4;
        i.Laptop_USD__c = 5;
        i.Other_USD__c = 6;
        i.Consumer_Pct__c = 7;
        i.M2M_Pct__c = 8;
        i.Telematics_Pct__c = 9;
        i.Handset_Pct__c = 10;
        i.Laptop_Pct__c = 11;
        i.Other_Pct__c = 12;
		i.Prime_Pct__c = 13;      
        i.Prime_USD__c = 14;

		insert i;      
        
		Product2 p2 = new Product2();
        p2.Name = 'test';
        p2.Type_No__c = 'NEO-M8U-06B-00';
        p2.IPR_USD_Consumer__c = i.Consumer_USD__c;
		p2.IPR_USD_M2M__c = 2;
		p2.IPR_USD_Telematics__c = 3;
        p2.IPR_USD_Handset__c = 4;
        p2.IPR_USD_Laptop__c = 5;
        p2.IPR_USD_Other__c = 6;
        p2.IPR_Pct_Consumer__c = 7;
        p2.IPR_Pct_M2M__c = 8;
        p2.IPR_Pct_Telematics__c = 9;
        p2.IPR_Pct_Handset__c = 10;
        p2.IPR_Pct_Laptop__c = 11;
        p2.IPR_Pct_Laptop__c = 12;
        p2.IPR_Pct_Other__c = 13;
        p2.IPR_Pct_Prime__c = 14;
        p2.IPR_USD_Prime__c = 15;
        
		insert p2;  
        
        List<Product2> prodList1 = new List<Product2>();
        List<Product2> prodList2 = new List<Product2>();
        
       		prodList2 = [SELECT IPR_USD_Consumer__c,IPR_USD_M2M__c,IPR_USD_Telematics__c,IPR_USD_Handset__c,
                           	IPR_USD_Laptop__c,IPR_USD_Other__c, IPR_Pct_Consumer__c,IPR_Pct_M2M__c,IPR_Pct_Telematics__c,
							IPR_Pct_Handset__c,IPR_Pct_Laptop__c,IPR_Pct_Other__c, IPR_Pct_Prime__c, IPR_USD_Prime__c, 
							IPR_Cost__r.Consumer_USD__c,IPR_Cost__r.M2M_USD__c,IPR_Cost__r.Telematics_USD__c,
                           	IPR_Cost__r.Handset_USD__c,IPR_Cost__r.Laptop_USD__c,IPR_Cost__r.Other_USD__c,
                			IPR_Cost__r.Consumer_Pct__c,IPR_Cost__r.M2M_Pct__c,IPR_Cost__r.Telematics_Pct__c,
                           	IPR_Cost__r.Handset_Pct__c,	IPR_Cost__r.Laptop_Pct__c,IPR_Cost__r.Other_Pct__c,
                			IPR_Cost__r.Prime_Pct__c, IPR_Cost__r.Prime_USD__c
        					FROM Product2];
        
        if(!prodList2.isempty()){
            for(Product2 list1: prodList2){
            //list1.prodList1 = prodList2;
        }
    }
     
*/
        
                // Create new Product with mandatory fields (Product Center undefined)
        Product2 prod = new Product2(Name='Test Product', Type_No__C='Test Type Number', Packaging_Size__c=1, Family='Other', Positioning_Engine__c='Not applicable', CurrencyIsoCode='USD', COGS_1__c=20, COGS_Pct__c=0);
        insert prod;

        // Create new IPR Cost
        IPR_Cost__c iprc = new IPR_Cost__c(Name='Test IPR Cost', Consumer_USD__c=1,M2M_USD__c=2,Telematics_USD__c=3,Handset_USD__c=4,Laptop_USD__c=5,Other_USD__c=6,Consumer_Pct__c=1,M2M_Pct__c=2,Telematics_Pct__c=3,Handset_Pct__c=4,Laptop_Pct__c=5,Other_Pct__c=6);
        insert iprc;
        
        prod.IPR_Cost__c = iprc.Id;
        update prod;
        
		
        List<Product2> updatedProd = [
            SELECT IPR_USD_Consumer__c,IPR_USD_M2M__c,IPR_USD_Telematics__c,IPR_USD_Handset__c,IPR_USD_Laptop__c,IPR_USD_Other__c,
                IPR_Pct_Consumer__c,IPR_Pct_M2M__c,IPR_Pct_Telematics__c,IPR_Pct_Handset__c,IPR_Pct_Laptop__c,IPR_Pct_Other__c,
                IPR_Cost__r.Consumer_USD__c,IPR_Cost__r.M2M_USD__c,IPR_Cost__r.Telematics_USD__c,IPR_Cost__r.Handset_USD__c,IPR_Cost__r.Laptop_USD__c,IPR_Cost__r.Other_USD__c,
                IPR_Cost__r.Consumer_Pct__c,IPR_Cost__r.M2M_Pct__c,IPR_Cost__r.Telematics_Pct__c,IPR_Cost__r.Handset_Pct__c,IPR_Cost__r.Laptop_Pct__c,IPR_Cost__r.Other_Pct__c
            FROM Product2
            WHERE IPR_Cost__c = :prod.Id];
        
        for(Product2 a : updatedProd){

            System.assertEquals(a.IPR_Cost__r.Consumer_USD__c, a.IPR_USD_Consumer__c);
            System.assertEquals(a.IPR_Cost__r.M2M_USD__c, a.IPR_USD_M2M__c);
            System.assertEquals(a.IPR_Cost__r.Telematics_USD__c, a.IPR_USD_Telematics__c);
            System.assertEquals(a.IPR_Cost__r.Handset_USD__c, a.IPR_USD_Handset__c);
            System.assertEquals(a.IPR_Cost__r.Laptop_USD__c, a.IPR_USD_Laptop__c);
            System.assertEquals(a.IPR_Cost__r.Other_USD__c, a.IPR_USD_Other__c);
            System.assertEquals(a.IPR_Cost__r.Consumer_Pct__c, a.IPR_Pct_Consumer__c);
            System.assertEquals(a.IPR_Cost__r.M2M_Pct__c, a.IPR_Pct_M2M__c);
            System.assertEquals(a.IPR_Cost__r.Telematics_Pct__c, a.IPR_Pct_Telematics__c);
            System.assertEquals(a.IPR_Cost__r.Handset_Pct__c, a.IPR_Pct_Handset__c);
            System.assertEquals(a.IPR_Cost__r.Laptop_Pct__c, a.IPR_Pct_Laptop__c);
            System.assertEquals(a.IPR_Cost__r.Other_Pct__c, a.IPR_Pct_Other__c);

//            System.assertEquals(1, 1);
        }        

        
        
    }


}