force-app/main/default/objects/IPR_Cost__c/IPR_Cost__c.object-meta.xml
<CustomObject>
    <description>IPR costs that should replace the current ones in each Product</description>
    <label>IPR Cost</label>
    <nameField>
        <label>IPR Cost Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPR Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPR_Cost__c/fields/Consumer_Pct__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Pct__c</fullName>
    <description>Used only for 2G</description>
    <inlineHelpText>Used only for 2G</inlineHelpText>
    <label>Consumer Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Consumer_USD__c.field-meta.xml
<CustomField>
    <fullName>Consumer_USD__c</fullName>
    <description>Used only for 2G</description>
    <inlineHelpText>Used only for 2G</inlineHelpText>
    <label>Consumer USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Handset_Pct__c.field-meta.xml
<CustomField>
    <fullName>Handset_Pct__c</fullName>
    <label>Handset Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Handset_USD__c.field-meta.xml
<CustomField>
    <fullName>Handset_USD__c</fullName>
    <label>Handset USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Laptop_Pct__c.field-meta.xml
<CustomField>
    <fullName>Laptop_Pct__c</fullName>
    <label>Laptop Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Laptop_USD__c.field-meta.xml
<CustomField>
    <fullName>Laptop_USD__c</fullName>
    <label>Laptop USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/M2M_Pct__c.field-meta.xml
<CustomField>
    <fullName>M2M_Pct__c</fullName>
    <label>M2M Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/M2M_USD__c.field-meta.xml
<CustomField>
    <fullName>M2M_USD__c</fullName>
    <label>M2M USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Other_Pct__c.field-meta.xml
<CustomField>
    <fullName>Other_Pct__c</fullName>
    <label>Other Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Other_USD__c.field-meta.xml
<CustomField>
    <fullName>Other_USD__c</fullName>
    <label>Other USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Prime_Pct__c.field-meta.xml
<CustomField>
    <fullName>Prime_Pct__c</fullName>
    <description>IPR rate in Precent for Prime</description>
    <inlineHelpText>IPR rate in Precent for Prime</inlineHelpText>
    <label>Prime Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Prime_USD__c.field-meta.xml
<CustomField>
    <fullName>Prime_USD__c</fullName>
    <label>Prime USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Telematics_Pct__c.field-meta.xml
<CustomField>
    <fullName>Telematics_Pct__c</fullName>
    <label>Telematics Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IPR_Cost__c/fields/Telematics_USD__c.field-meta.xml
<CustomField>
    <fullName>Telematics_USD__c</fullName>
    <label>Telematics USD</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Cost__c.field-meta.xml
<CustomField>
    <fullName>IPR_Cost__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>IPR cost in detail, used to update IPR USD xxx and IPR Pct xxx fields. Populated when IPR Technology picklist field is changed (using Process and Workflow)</description>
    <inlineHelpText>IPR cost in detail, used to update IPR USD xxx and IPR Pct xxx fields. Populated when IPR Technology picklist field is changed</inlineHelpText>
    <label>IPR Cost</label>
    <referenceTo>IPR_Cost__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_Consumer__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_Consumer__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Value copied from IPR Cost</description>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR Pct Consumer</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_Handset__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_Handset__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR Pct Handset</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_Laptop__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_Laptop__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR Pct Laptop</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_M2M__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_M2M__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR Pct M2M</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_Other__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_Other__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR Pct Other</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_Prime__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_Prime__c</fullName>
    <label>IPR Pct Prime</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_Pct_Telematics__c.field-meta.xml
<CustomField>
    <fullName>IPR_Pct_Telematics__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR Pct Telematics</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_Consumer__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_Consumer__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR USD Consumer</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_Handset__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_Handset__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR USD Handset</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_Laptop__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_Laptop__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR USD Laptop</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_M2M__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_M2M__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR USD M2M</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_Other__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_Other__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR USD Other</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_Prime__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_Prime__c</fullName>
    <label>IPR USD Prime</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IPR_USD_Telematics__c.field-meta.xml
<CustomField>
    <fullName>IPR_USD_Telematics__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Value copied from IPR Cost</inlineHelpText>
    <label>IPR USD Telematics</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IPRCostHelper.cls
public class IPRCostHelper {
    public list<Product2> getProductsUpdate(set<Id> iprCostIds) {
        list<Product2> productsToCheck = [SELECT IPR_USD_Consumer__c,
                                                IPR_USD_M2M__c,
                                                IPR_USD_Telematics__c,
                                                IPR_USD_Handset__c,
                                                IPR_USD_Laptop__c,
                                                IPR_USD_Other__c,
                                                IPR_Pct_Consumer__c,
                                                IPR_Pct_M2M__c,
                                                IPR_Pct_Telematics__c,
                                                IPR_Pct_Handset__c,
                                                IPR_Pct_Laptop__c,
                                                IPR_Pct_Other__c, 
                                                IPR_Pct_Prime__c, 
                                                IPR_USD_Prime__c,
                                                IPR_Cost__r.Consumer_USD__c,
                                                IPR_Cost__r.M2M_USD__c,
                                                IPR_Cost__r.Telematics_USD__c,
                                                IPR_Cost__r.Handset_USD__c,
                                                IPR_Cost__r.Laptop_USD__c,
                                                IPR_Cost__r.Other_USD__c,
                                                IPR_Cost__r.Consumer_Pct__c,
                                                IPR_Cost__r.M2M_Pct__c,
                                                IPR_Cost__r.Telematics_Pct__c,
                                                IPR_Cost__r.Handset_Pct__c,
                                                IPR_Cost__r.Laptop_Pct__c,
                                                IPR_Cost__r.Other_Pct__c,
                                                IPR_Cost__r.Prime_Pct__c, 
                                                IPR_Cost__r.Prime_USD__c
                                            FROM Product2
                                            WHERE IPR_Cost__c IN :iprCostIds];

        list<Product2> productsToUpdate = new list<Product2>();
        
        for(Product2 a: productsToCheck){
            Integer updateflag = 0;

            if(a.IPR_USD_Consumer__c <> a.IPR_Cost__r.Consumer_USD__c){
                a.IPR_USD_Consumer__c = a.IPR_Cost__r.Consumer_USD__c;
                updateflag++;  
            }
            if(a.IPR_USD_M2M__c <> a.IPR_Cost__r.M2M_USD__c){
                a.IPR_USD_M2M__c = a.IPR_Cost__r.M2M_USD__c;
                updateflag++;
            }
            if(a.IPR_USD_Telematics__c <> a.IPR_Cost__r.Telematics_USD__c){
                a.IPR_USD_Telematics__c = a.IPR_Cost__r.Telematics_USD__c;
                updateflag++;
            }
            if(a.IPR_USD_Handset__c <> a.IPR_Cost__r.Handset_USD__c){
                a.IPR_USD_Handset__c = a.IPR_Cost__r.Handset_USD__c;
                updateflag++;
            }
            if(a.IPR_USD_Laptop__c <> a.IPR_Cost__r.Laptop_USD__c){
                a.IPR_USD_Laptop__c = a.IPR_Cost__r.Laptop_USD__c;
                updateflag++;
            }
            if(a.IPR_USD_Other__c <> a.IPR_Cost__r.Other_USD__c){
                a.IPR_USD_Other__c = a.IPR_Cost__r.Other_USD__c;
                updateflag++;
            }
            if(a.IPR_USD_Prime__c <> a.IPR_Cost__r.Prime_USD__c){
                a.IPR_USD_Prime__c = a.IPR_Cost__r.Prime_USD__c;
                updateflag++;
            }
            if(a.IPR_Pct_Consumer__c <> a.IPR_Cost__r.Consumer_Pct__c){
                a.IPR_Pct_Consumer__c = a.IPR_Cost__r.Consumer_Pct__c;
                updateflag++;  
            }
            if(a.IPR_Pct_M2M__c <> a.IPR_Cost__r.M2M_Pct__c){
                a.IPR_Pct_M2M__c = a.IPR_Cost__r.M2M_Pct__c;
                updateflag++;
            }
            if(a.IPR_Pct_Telematics__c <> a.IPR_Cost__r.Telematics_Pct__c){
                a.IPR_Pct_Telematics__c = a.IPR_Cost__r.Telematics_Pct__c;
                updateflag++;
            }
            if(a.IPR_Pct_Handset__c <> a.IPR_Cost__r.Handset_Pct__c){
                a.IPR_Pct_Handset__c = a.IPR_Cost__r.Handset_Pct__c;
                updateflag++;
            }
            if(a.IPR_Pct_Laptop__c <> a.IPR_Cost__r.Laptop_Pct__c){
                a.IPR_Pct_Laptop__c = a.IPR_Cost__r.Laptop_Pct__c;
                updateflag++;
            }
            if(a.IPR_Pct_Other__c <> a.IPR_Cost__r.Other_Pct__c){
                a.IPR_Pct_Other__c = a.IPR_Cost__r.Other_Pct__c;
                updateflag++;
            }
            if(a.IPR_Pct_Prime__c <> a.IPR_Cost__r.Prime_Pct__c){
                a.IPR_Pct_Prime__c = a.IPR_Cost__r.Prime_Pct__c;
                updateflag++;
            }
            
            if(updateflag > 0){
                productsToUpdate.add(a);
            }
        }
        return productsToUpdate;
    }
}