force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Object to capture general data about competitors</description>
    <label>Competitor</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Product__c/Competitor_Product__c.object-meta.xml
<CustomObject>
    <description>Competitor product that competes with our existing or potential future products. Maintained by marketing.</description>
    <label>Competitor Product</label>
    <nameField>
        <label>Competitor Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Product__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <description>Competitor name that produces this Competitor Product</description>
    <inlineHelpText>Competitor name that produces this Competitor Product</inlineHelpText>
    <label>Competitor</label>
    <referenceTo>Competitor__c</referenceTo>
    <relationshipLabel>Competitor Products</relationshipLabel>
    <relationshipName>Competitor_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CompetitorProductTestDataFactory.cls
@IsTest
public class CompetitorProductTestDataFactory extends TestDataFactory {
 
    public CompetitorProductTestDataFactory() {
        super('Competitor_Product__c');
    }

    public override sObject initializeRecord(){
        Competitor_Product__c initcp = new Competitor_Product__c();
        initcp.Name = 'Test Competitor Product';
        
        CompetitorTestDataFactory comp= New CompetitorTestDataFactory();
        Competitor__c c = (Competitor__c)comp.createRecord();
        initcp.Competitor__c = c.id;
        return initcp;
    }

    public override sObject createRecord() {
        Competitor_Product__c createcp = (Competitor_Product__c)initializeRecord();
        Insert createcp;
        return createcp;
    }

    public sObject createRecord(sObject record) {

        Insert record;
        return record;
    }

    public override List<sObject> createBulkRecords() {
        for (Integer i = 0; i < numberOfRecords; i++) {
            Competitor_Product__c cp = new Competitor_Product__c();
            cp.Name = 'Test Competitor Product'+i;
            recordsList.add(cp);
        }
        Insert recordsList;
        return recordsList;
    }

    public Competitor_Product__c updateRecords(Competitor_Product__c toupdate) {
        update toupdate;
        return toupdate;
    }

}