force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Object to capture general data about competitors</description>
    <label>Competitor</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Product__c/Competitor_Product__c.object-meta.xml
<CustomObject>
    <description>Competitor product that competes with our existing or potential future products. Maintained by marketing.</description>
    <label>Competitor Product</label>
    <nameField>
        <label>Competitor Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Product__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <description>Competitor name that produces this Competitor Product</description>
    <inlineHelpText>Competitor name that produces this Competitor Product</inlineHelpText>
    <label>Competitor</label>
    <referenceTo>Competitor__c</referenceTo>
    <relationshipLabel>Competitor Products</relationshipLabel>
    <relationshipName>Competitor_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Competitor_Product_Price__c/Competitor_Product_Price__c.object-meta.xml
<CustomObject>
    <label>Competitor Product Price</label>
    <nameField>
        <displayFormat>CPP-{000000}</displayFormat>
        <label>Competitor Product Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Product Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Product_Price__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Additional information on competitor product prices</description>
    <inlineHelpText>Additional information on competitor product prices</inlineHelpText>
    <label>Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Competitor_Product_Price__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor</label>
    <referenceTo>Competitor__c</referenceTo>
    <relationshipLabel>Competitor Product Prices</relationshipLabel>
    <relationshipName>Competitor_Product_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Product_Price__c/fields/Competitor_Product__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Competitor_Product__c.Competitor__c</field>
            <operation>equals</operation>
            <valueField>$Source.Competitor__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Competitor_Product__c</referenceTo>
    <relationshipLabel>Competitor Product Prices</relationshipLabel>
    <relationshipName>Competitor_Product_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Product_Price__c/fields/Opp_Product__c.field-meta.xml
<CustomField>
    <fullName>Opp_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Filled automatically when created from Opp Product</description>
    <inlineHelpText>Filled automatically when created from Opp Product</inlineHelpText>
    <label>Opp Product</label>
    <referenceTo>Opp_Product__c</referenceTo>
    <relationshipLabel>Competitor Product Prices</relationshipLabel>
    <relationshipName>Competitor_Product_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Product_Price__c/fields/Price_Information_Date__c.field-meta.xml
<CustomField>
    <fullName>Price_Information_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Populated automatically with modified date if left empty when Save.</description>
    <inlineHelpText>Populated automatically with modified date if left empty when Save.</inlineHelpText>
    <label>Price Information Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/CompetitorProductPriceTestDataFactory.cls
@IsTest
public class CompetitorProductPriceTestDataFactory extends TestDataFactory {

    public CompetitorProductPriceTestDataFactory() {
        super('Competitor_Product_Price__c');
    }

    public override sObject initializeRecord(){
        Competitor_Product_Price__c cpp = new Competitor_Product_Price__c();
        
        CompetitorTestDataFactory comp= New CompetitorTestDataFactory();
        Competitor__c c = (Competitor__c)comp.initializeRecord();
        cpp.Competitor__c = c.id;
        
        CompetitorProductTestDataFactory cprod = New CompetitorProductTestDataFactory();
        Competitor_Product__c cp = (Competitor_Product__c)cprod.initializeRecord();
        cpp.Competitor_Product__c = cp.id;
		
		OppProductTestDataFactory oppProd = new OppProductTestDataFactory();
        Opp_Product__c oppProdObj = (Opp_Product__c)oppProd.initializeRecord();
		
		//AccountTestDataFactory accTDF = new AccountTestDataFactory();
        //Account acc = (Account)accTDF.initializeRecord();
        
        OpportunityTestDataFactory opportunity = new OpportunityTestDataFactory();
        Opportunity opp = (Opportunity)opportunity.initializeRecord();
        //opp.AccountId = acc.id;
        
        oppProdObj.Opportunity__c = opp.id;
        
		cpp.Opp_Product__c = oppProdObj.id;
        cpp.Comment__c = 'test comment';
        cpp.Price_Information_Date__c = date.today();
        return cpp;
    }

    public override sObject createRecord() {
        Competitor_Product_Price__c cpp = (Competitor_Product_Price__c)initializeRecord();
        Insert cpp;
        return cpp;
    }

    public sObject createRecord(sObject record) {

        Insert record;
        return record;
    }

    public override List<sObject> createBulkRecords() {
        for (Integer i = 0; i < numberOfRecords; i++) {
            Competitor_Product_Price__c cpp = new Competitor_Product_Price__c();
            //cpp.Name = 'Test Competitor Product Price'+i;
            recordsList.add(cpp);
        }
        Insert recordsList;
        return recordsList;
    }

    public Competitor_Product_Price__c updateRecords(Competitor_Product_Price__c toupdate) {
        update toupdate;
        return toupdate;
    }

}