force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Object to capture general data about competitors</description>
    <label>Competitor</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Product__c/Competitor_Product__c.object-meta.xml
<CustomObject>
    <description>Competitor product that competes with our existing or potential future products. Maintained by marketing.</description>
    <label>Competitor Product</label>
    <nameField>
        <label>Competitor Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Product__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <description>Competitor name that produces this Competitor Product</description>
    <inlineHelpText>Competitor name that produces this Competitor Product</inlineHelpText>
    <label>Competitor</label>
    <referenceTo>Competitor__c</referenceTo>
    <relationshipLabel>Competitor Products</relationshipLabel>
    <relationshipName>Competitor_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NewPriceCtrl.cls
public with sharing class NewPriceCtrl {
    public Competitor_Product__c compProduct{get;set;} 
    public Id ids{get;set;}
    public NewPriceCtrl(ApexPages.StandardSetController stdSetController) {
        ids=ApexPages.currentPage().getParameters().get('id');
        if(ids!=null){
            compProduct=[Select id,Competitor__c,Competitor__r.Name,Name from Competitor_Product__c where id=:ids];
         }   
    }

}