force-app/main/default/objects/Contact/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/Opp_Product__c/Opp_Product__c.object-meta.xml
<CustomObject>
    <description>Products to be added in Opportunities, substitutes former GPS and Wireless Products.</description>
    <label>Opp Product</label>
    <nameField>
        <displayFormat>OppProd-{000000}</displayFormat>
        <label>Opp Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product__c/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <inlineHelpText>On creation, if empty copied from the master Opportunity after Save. Edit as needed.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/IPR_Coverage__c.field-meta.xml
<CustomField>
    <fullName>IPR_Coverage__c</fullName>
    <label>IPR Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Premium coverage</fullName>
            </value>
            <value>
                <fullName>Prime coverage</fullName>
            </value>
            <value>
                <fullName>Premium except Qualcomm</fullName>
            </value>
            <value>
                <fullName>Prime except Qualcomm</fullName>
            </value>
            <value>
                <fullName>No coverage</fullName>
            </value>
            <value>
                <fullName>Full coverage</fullName>
            </value>
            <value>
                <fullName>All except Qualcomm</fullName>
            </value>
            <value>
                <fullName>All except Interdigital</fullName>
            </value>
            <value>
                <fullName>All except QCOM and IDC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (9 AND 10)) AND 7) OR 8</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Cellular</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Cellular, Services</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Positioning</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Positioning</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Short Range</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Status__c</field>
            <operation>notEqual</operation>
            <value>End of Life, Obsolete</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API Admin, Automatic process, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opp Product Tashang, Opp Product Services</value>
        </filterItems>
        <filterItems>
            <field>Product2.Product_Center__c</field>
            <operation>equals</operation>
            <value>Services, Tashang</value>
        </filterItems>
        <infoMessage>If you cannot find a product you want to add, choose other Record Type.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (Opp Products)</relationshipLabel>
    <relationshipName>Opp_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>When multiple products are in evaluation, set the most probable one as “Evaluation”, all others as “Alternative product”. These will not count as revenue or contribution.</description>
    <inlineHelpText>When multiple products are in evaluation, set the most probable one as “Evaluation”, all others as “Alternative product”. These will not count as revenue or contribution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alternative Product</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
                <default>true</default>
                <label>Evaluation</label>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opp_Product__c/fields/Use_Restriction__c.field-meta.xml
<CustomField>
    <fullName>Use_Restriction__c</fullName>
    <label>Use Restriction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2G Consumer</fullName>
            </value>
            <value>
                <fullName>2G M2M</fullName>
            </value>
            <value>
                <fullName>2G Telematics</fullName>
            </value>
            <value>
                <fullName>2G Handset</fullName>
            </value>
            <value>
                <fullName>2G Laptop</fullName>
            </value>
            <value>
                <fullName>2G Other</fullName>
            </value>
            <value>
                <fullName>3G M2M</fullName>
            </value>
            <value>
                <fullName>3G Telematics</fullName>
            </value>
            <value>
                <fullName>3G Handset</fullName>
            </value>
            <value>
                <fullName>3G Laptop</fullName>
            </value>
            <value>
                <fullName>3G Other</fullName>
            </value>
            <value>
                <fullName>4G M2M</fullName>
            </value>
            <value>
                <fullName>4G Telematics</fullName>
            </value>
            <value>
                <fullName>4G Handset</fullName>
            </value>
            <value>
                <fullName>4G Laptop</fullName>
            </value>
            <value>
                <fullName>4G Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Annual_Quantity__c</fullName>
    <description>Annual run rate of product. If</description>
    <inlineHelpText>Annual run rate. For single shot opportunities, use total quantity.
If Opportunity is converted from Lead, this is copied from Lead.</inlineHelpText>
    <label>Annual Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OppAutoNumber__c.field-meta.xml
<CustomField>
    <fullName>OppAutoNumber__c</fullName>
    <description>To be used for Quotation_Reference_Number__c</description>
    <displayFormat>{YY}{000000}</displayFormat>
    <label>OppAutoNumber</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Quotation.recordType-meta.xml
<RecordType>
    <fullName>Quotation</fullName>
    <active>true</active>
    <businessProcess>Quotation</businessProcess>
    <label>Quotation</label>
</RecordType>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/QuoteObjectTriggerHandler.cls
public class QuoteObjectTriggerHandler {
    public static void addContactDetails(list<Quote> quoteObj){
        set<Id> opportunityIds = new set<Id>();
        map<Id,OpportunityContactRole> opportunityContacts = new map<Id, OpportunityContactRole>();
        map<Id,Opportunity> quoteOpportunity = new map<Id, Opportunity>();
        for(Quote Q : quoteObj){
            opportunityIds.add(Q.OpportunityId);
        }
        for(Opportunity opp : [Select Id, Name, OwnerId, AccountId, OppAutoNumber__c from Opportunity where Id IN : opportunityIds]){
            quoteOpportunity.put(opp.Id,Opp);
        }

        for(OpportunityContactRole ocr : [SELECT ContactId,
                                                    OpportunityId,
                                                    Contact.Phone, 
                                                    Contact.Fax, 
                                                    Contact.Email, 
                                                    IsPrimary 
                                                FROM OpportunityContactRole 
                                                WHERE OpportunityId IN : opportunityIds
                                                AND Role = 'Contact Quotation'
                                                AND IsPrimary = true]){
            opportunityContacts.put(ocr.OpportunityId, ocr);
        }
        for(Quote Q : quoteObj){
            if(!quoteOpportunity.isEmpty() && quoteOpportunity.get(Q.OpportunityId) != null){
                //Q.Name = quoteOpportunity.get(Q.OpportunityId).Name + '-u-blox-';
                Q.OwnerId = quoteOpportunity.get(Q.OpportunityId).OwnerId;            
            }
            
            if(Q.ContactId == NULL && !opportunityContacts.isEmpty() && opportunityContacts.get(Q.OpportunityId) != NULL){
                Q.ContactId = opportunityContacts.get(Q.OpportunityId).ContactId;
                Q.Email = opportunityContacts.get(Q.OpportunityId).Contact.Email;
                Q.Phone = opportunityContacts.get(Q.OpportunityId).Contact.Phone;
                Q.Fax = opportunityContacts.get(Q.OpportunityId).Contact.Fax;
            }
        }
    }

    public static void addPriceBook(list<Quote> quoteObj){
        List<pricebook2> priceBookList = new List<pricebook2>();
        priceBookList = [SELECT Id from pricebook2 WHERE name = 'Standard Price Book' Limit 1];
        if(priceBookList.size() > 0){
            for(Quote Q : quoteObj){               
                Q.pricebook2Id = priceBookList[0].Id;
            }
        }
    }

    public static List<QuoteLineItem> createQuoteLienItem(List<Quote> quoteObj){
        List<String> productIds = new List<String>();
        List<quoteLineItem> quoteLineItemList = new List<quoteLineItem>();
        map<String,String> quoteOppIds = new map<String, String>();
        map<String,String> prodPBEMap = new map<String,String>();
        map<String,List<opp_product__c>> oppIdProdMap = new map<String, List<opp_product__c>>();
        
        for(quote tempQuote : quoteObj){
            quoteOppIds.put(tempQuote.Id,tempQuote.opportunityId);
        }
        
        for(opp_product__c tempProd : [SELECT Id,
                                                Opportunity__c, 
                                                product__c,
                                                Annual_Quantity__c, 
                                                Unit_Price__c,
                                                Use_Restriction__c, 
                                                IPR_Coverage__c 
                                                FROM opp_product__c 
                                                WHERE opportunity__c IN :quoteOppIds.values()
                                                AND Status__c != 'Lost']){
            if(oppIdProdMap.get(tempProd.Opportunity__c) == null){
                oppIdProdMap.put(tempProd.Opportunity__c,new List<opp_product__c>() );
            }
            oppIdProdMap.get(tempProd.Opportunity__c).add(tempProd);
            productIds.add(tempProd.product__c);
        }
        
        for(PricebookEntry pe :[SELECT Id,CurrencyIsoCode , Product2Id
                                FROM PricebookEntry
                                WHERE Product2Id IN:productIds
                                AND IsActive = true])
        {
            String PBEKey = pe.Product2Id + pe.CurrencyIsoCode;
            prodPBEMap.put(PBEKey,pe.Id);
        }
                
        for(quote tempQuote :quoteObj){
            if(oppIdProdMap.size() > 0 && oppIdProdMap.get(tempQuote.OpportunityId) != null){
                for(Opp_Product__c tempOppProd : oppIdProdMap.get(tempQuote.OpportunityId)  ){
                    String PBEKey = tempOppProd.Product__c + tempQuote.CurrencyIsoCode;
                    quoteLineItem quoteLineItemObj = new quoteLineItem();
                    quoteLineItemObj.QuoteId = tempQuote.Id;
                    quoteLineItemObj.Quantity = tempOppProd.Annual_Quantity__c;
                    quoteLineItemObj.UnitPrice = tempOppProd.Unit_Price__c;
                    quoteLineItemObj.Use_Restriction__c = tempOppProd.Use_Restriction__c;
                    quoteLineItemObj.IPR_Coverage__c = tempOppProd.IPR_Coverage__c;
                    quoteLineItemObj.PriceBookEntryId = prodPBEMap.get(PBEKey);
                    quoteLineItemList.add(quoteLineItemObj);
                }
            }
        }
        return quoteLineItemList;
    }   
}