force-app/main/default/objects/SalesToolFiles__c/SalesToolFiles__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Setting used to have information regarding Salestool files</description>
    <label>SalesToolFiles</label>
</CustomObject>

force-app/main/default/objects/SalesToolFiles__c/fields/Library_Folder_Name__c.field-meta.xml
<CustomField>
    <fullName>Library_Folder_Name__c</fullName>
    <defaultValue>&quot;SalesToolFiles&quot;</defaultValue>
    <description>Name of the folder used to store SalestoolFile in Library. Will be used in AttachmentToFileConverterHelper Class</description>
    <label>Library Folder Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesToolFolder__c/SalesToolFolder__c.object-meta.xml
<CustomObject>
    <label>SalesTool Folder</label>
    <nameField>
        <label>SalesToolFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesTool Folder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AttachmentToFileConverterHelperTest.cls
@IsTest
private class AttachmentToFileConverterHelperTest{
    
    @testSetup
    private static void createTestData() {
        ContentWorkspace testWorkspace = new ContentWorkspace(Name='SalesToolFiles1', DeveloperName='SalesToolFiles1');
        insert testWorkspace;
    }
    
    private static SalesToolFolder__c createSalesToolFolder(){
        SalesToolFolder__c stFolder = new SalesToolFolder__c(Name = 'Default');
        insert stFolder;
        return stFolder;
    }
    
    private static Attachment createAttachment(String parentId){
        Attachment attach=new Attachment();       
        attach.Name='Attach1.txt';
        Blob bodyBlob=Blob.valueOf('Test Attachment');
        attach.body=bodyBlob;
        attach.parentId=parentId;
        insert attach;
        return attach;
    }
    
    static testMethod void createAttachmentToSalesToolFolder()
    {
        SalesToolFiles__c salesToolSetting = SalesToolFiles__c.getInstance();
        salesToolSetting.Library_Folder_Name__c = 'SalesToolFiles1';
        upsert salesToolSetting;
        
        SalesToolFolder__c stFolder = createSalesToolFolder();
        Attachment attStFolder = createAttachment(stFolder.Id);        
    }
    
    static testMethod void createAttachmentToFolderNotPresent()
    {
        SalesToolFiles__c salesToolSetting = SalesToolFiles__c.getInstance();
        salesToolSetting.Library_Folder_Name__c = 'SalesToolFiles2';
        upsert salesToolSetting;
        try{
            SalesToolFolder__c stFolder = createSalesToolFolder();
            Attachment attStFolder = createAttachment(stFolder.Id); 
        }catch(Exception ex){     
        }       
    }
    
    static testMethod void createAttachmentToFolderWithSameName()
    {
        SalesToolFiles__c salesToolSetting = SalesToolFiles__c.getInstance();
        salesToolSetting.Library_Folder_Name__c = 'SalesToolFiles1';
        upsert salesToolSetting;
        
        SalesToolFolder__c stFolder = createSalesToolFolder();
        Attachment attStFolder = createAttachment(stFolder.Id);
        Attachment attStFolder1 = createAttachment(stFolder.Id);        
    }
    
    
}