force-app/main/default/objects/ProductPrices__c/ProductPrices__c.object-meta.xml
<CustomObject>
    <label>Product Prices</label>
    <nameField>
        <label>Product Prices Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductPrices__c/fields/Ordering_Number__c.field-meta.xml
<CustomField>
    <fullName>Ordering_Number__c</fullName>
    <externalId>true</externalId>
    <label>Ordering Number</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductPrices__c/fields/Price_USD_Sample_Size_1000__c.field-meta.xml
<CustomField>
    <fullName>Price_USD_Sample_Size_1000__c</fullName>
    <label>1000+ Price USD</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductPrices__c/fields/Price_USD_Sample_Size_100__c.field-meta.xml
<CustomField>
    <fullName>Price_USD_Sample_Size_100__c</fullName>
    <label>100+ Price USD</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductPrices__c/fields/Price_USD_Sample_Size_10__c.field-meta.xml
<CustomField>
    <fullName>Price_USD_Sample_Size_10__c</fullName>
    <label>10+ Price USD</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductPrices__c/fields/Price_USD_Sample_Size_1__c.field-meta.xml
<CustomField>
    <fullName>Price_USD_Sample_Size_1__c</fullName>
    <label>1+ Price USD</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductPrices__c/fields/Price_USD_Sample_Size_250__c.field-meta.xml
<CustomField>
    <fullName>Price_USD_Sample_Size_250__c</fullName>
    <label>250+ Price USD</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductPrices__c/fields/Price_USD_Sample_Size_500__c.field-meta.xml
<CustomField>
    <fullName>Price_USD_Sample_Size_500__c</fullName>
    <label>500+ Price USD</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductPrices__c/fields/Price_USD_Sample_Size_50__c.field-meta.xml
<CustomField>
    <fullName>Price_USD_Sample_Size_50__c</fullName>
    <label>50+ Price USD</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductPrices__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Valid From</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ProductPricesPerProductController.cls
public class ProductPricesPerProductController{
    
    public List<ProductPrices__c> productPrices{get; set;}
    public ProductPricesPerProductController()
    {
        String product_code  = '%';
        String test_output = ApexPages.currentPage().getParameters().get('id');
        if(ApexPages.currentPage().getParameters().get('id') != null)
        {
            Product2 product = [SELECT Id, Name, ProductCode FROM Product2
                       WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
            
            product_code = product.ProductCode;
        }
        
        productPrices = new List<ProductPrices__c>();
          
        for (ProductPrices__c p : [Select id, Name,Product_Name__c, Ordering_Number__c, Price_USD_Sample_Size_1__c, Price_USD_Sample_Size_10__c ,Price_USD_Sample_Size_50__c, Price_USD_Sample_Size_100__c, Price_USD_Sample_Size_250__c, Price_USD_Sample_Size_500__c, Price_USD_Sample_Size_1000__c, Valid_From__c from ProductPrices__c where Ordering_Number__c LIKE :product_code ORDER BY Valid_From__c])
        {          
                  
           productPrices.add(p);

        }
    }
    
}